### ISSUE TITLE
HTTP/2 support in Web transports

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#1000]
Crossbar.io should already support HTTP/2 for Web transports by the virtue of recent Twisted supporting HTTP/2.

* Test that this is indeed the case.
* Document that

> Note that we don't need actual unit tests or such here, as this is Twisted business.

**Comment by oberstet** [comment]
Twisted Web claims support for HTTP/2 since 16.3 (https://twistedmatrix.com/trac/ticket/7460).

Support for HTTP/2 is enable automatically when H2 is installed (from `from twisted.web.http2 import H2Connection`):

```
>>> from twisted.web import http
>>> http.H2_ENABLED
False
>>> 
```

So everything that is needed for HTTP/2 support would be adding a new dependency (`pip install h2`).

**Comment by oberstet** [comment]
Here is more info also about testing this stuff https://pawelmhm.github.io/python/twisted/http2/python3/2016/07/30/twisted-http2.html

**Comment by meejah** [comment]
Hmm, this might not be quite ready for prime-time? With the changes from above branch, I get this when a connection is timed-out:

```
Timing out client: IPv4Address(TCP, '127.0.0.1', 37605)
2017-04-26T18:30:19-0600 [Router      21355] Unhandled Error
Traceback (most recent call last):
  File "/home/mike/work-tavendo/src/crossbar/crossbar/worker/process.py", line 287, in <module>
    run()
  File "/home/mike/work-tavendo/src/crossbar/crossbar/worker/process.py", line 275, in run
    reactor.run()
  File "/home/mike/work-tavendo/venv/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1243, in run
    self.mainLoop()
  File "/home/mike/work-tavendo/venv/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1252, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/home/mike/work-tavendo/venv/local/lib/python2.7/site-packages/twisted/internet/base.py", line 878, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/home/mike/work-tavendo/venv/local/lib/python2.7/site-packages/twisted/protocols/policies.py", line 735, in __timedOut
    self.timeoutConnection()
  File "/home/mike/work-tavendo/venv/local/lib/python2.7/site-packages/twisted/web/http.py", line 2009, in timeoutConnection
    self.loseConnection()
  File "/home/mike/work-tavendo/venv/local/lib/python2.7/site-packages/twisted/web/http.py", line 2109, in loseConnection
    self._networkProducer.unregisterProducer()
  File "/home/mike/work-tavendo/venv/local/lib/python2.7/site-packages/twisted/protocols/tls.py", line 610, in unregisterProducer
    if isinstance(self._producer._producer, _PullToPush):
exceptions.AttributeError: 'NoneType' object has no attribute '_producer'
```

**Comment by oberstet** [comment]
Support landed via https://github.com/crossbario/crossbar/pull/1052, but there is a follow up #https://github.com/crossbario/crossbar/issues/1063
