### ISSUE TITLE
cd hello - doesnt start

### ISSUE THREAD

**Issue by snape6666** [crossbario/crossbar#1002]
crossbar start
2017-03-26T16:05:53-0700 [Controller 110591]      __  __  __  __  __  __      __     __
2017-03-26T16:05:53-0700 [Controller 110591]     /  `|__)/  \/__`/__`|__) /\ |__)  |/  \
2017-03-26T16:05:53-0700 [Controller 110591]     \__,|  \\__/.__/.__/|__)/~~\|  \. |\__/
2017-03-26T16:05:53-0700 [Controller 110591]                                         
2017-03-26T16:05:53-0700 [Controller 110591] Version:     Crossbar.io COMMUNITY 17.2.1
2017-03-26T16:05:53-0700 [Controller 110591] Public Key:  87ee86aaa3b7667c727d71470fc423d683a0f651825daca79fbffd04cff0427f
2017-03-26T16:05:53-0700 [Controller 110591] 
2017-03-26T16:05:53-0700 [Controller 110591] Node created with personality "community" [crossbar.controller.node.Node]
2017-03-26T16:05:53-0700 [Controller 110591] Running from node directory "/home/snape6666/hello/.crossbar"
2017-03-26T16:05:53-0700 [Controller 110591] Node configuration loaded from "/home/snape6666/hello/.crossbar/config.json"
2017-03-26T16:05:53-0700 [Controller 110591] Controller process starting (CPython-EPollReactor) ..
2017-03-26T16:05:53-0700 [Controller 110591] No extra node router roles
2017-03-26T16:05:53-0700 [Controller 110591] Router service session attached [crossbar.router.service.RouterServiceSession]
2017-03-26T16:05:53-0700 [Controller 110591] Joined realm 'crossbar' on node management router
2017-03-26T16:05:53-0700 [Controller 110591] While firing onJoin: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1447, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1301, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python2.7/dist-packages/crossbar/controller/process.py", line 188, in onJoin
    yield NativeProcessSession.onJoin(self, details)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1447, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1301, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python2.7/dist-packages/crossbar/common/process.py", line 245, in onJoin
    dl.append(self.register(getattr(self, proc), uri, options=RegisterOptions(details_arg='details')))
  File "/usr/local/lib/python2.7/dist-packages/autobahn/wamp/protocol.py", line 1373, in register
    assert(procedure is None or type(procedure) == six.text_type)
exceptions.AssertionError: 

2017-03-26T16:05:53-0700 [Controller 110591] Node controller attached [crossbar.controller.process.NodeControllerSession]
2017-03-26T16:05:53-0700 [Controller 110591] Using default node shutdown triggers [u'shutdown_on_worker_exit']
2017-03-26T16:05:53-0700 [Controller 110591] Configuring node from local configuration ...
2017-03-26T16:05:53-0700 [Controller 110591] Starting 2 workers ...
2017-03-26T16:05:53-0700 [Controller 110591] Could not startup node: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1301, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python2.7/dist-packages/crossbar/controller/node.py", line 504, in start
    yield self._startup()
  File "/usr/local/lib/python2.7/dist-packages/crossbar/controller/node.py", line 529, in _startup
    return self._configure_node_from_config(self._config)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1447, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1301, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python2.7/dist-packages/crossbar/controller/node.py", line 590, in _configure_node_from_config
    yield self._controller.start_router(worker_id, worker_options, details=call_details)
  File "/usr/local/lib/python2.7/dist-packages/crossbar/controller/process.py", line 333, in start_router
    return self._start_native_worker('router', id, options, details=details)
  File "/usr/local/lib/python2.7/dist-packages/crossbar/controller/process.py", line 617, in _start_native_worker
    self.publish(starting_topic, starting_info, options=PublishOptions(exclude=details.caller))
  File "/usr/local/lib/python2.7/dist-packages/autobahn/wamp/protocol.py", line 1144, in publish
    assert(type(topic) == six.text_type)
exceptions.AssertionError:

**Comment by jrh418** [comment]
Same issue here. Downgrading autobahn from 0.18.0 to 0.17.2 fixed it for me.

**Comment by xgdgsc** [comment]
Same here. Please fix.

**Comment by oberstet** [comment]
This is fixed on master (release is coming)
