### ISSUE TITLE
Assertion failure on Debian/ARM

### ISSUE THREAD

**Issue by ecorm** [crossbario/crossbar#1004]
When starting the latest Crossbar on Debian/ARM, it aborts with an assertion failure.

OS: Debian 8.3 armhf
Crossbar version: 17.2.1
Python version: 2.7.9
Installed via pip install using CPython in virtualenv

Output:
```
2017-03-28T00:53:15+0000 [Controller   1982]      __  __  __  __  __  __      __     __
2017-03-28T00:53:15+0000 [Controller   1982]     /  `|__)/  \/__`/__`|__) /\ |__)  |/  \
2017-03-28T00:53:15+0000 [Controller   1982]     \__,|  \\__/.__/.__/|__)/~~\|  \. |\__/
2017-03-28T00:53:15+0000 [Controller   1982]                                         
2017-03-28T00:53:15+0000 [Controller   1982] Version:     Crossbar.io COMMUNITY 17.2.1
2017-03-28T00:53:15+0000 [Controller   1982] Public Key:  XXXXXXXXXXX
2017-03-28T00:53:15+0000 [Controller   1982] 
2017-03-28T00:53:15+0000 [Controller   1982] Node created with personality "community" [crossbar.controller.node.Node]
2017-03-28T00:53:15+0000 [Controller   1982] Running from node directory "/home/debian/emc/crossbar/.crossbar"
2017-03-28T00:53:15+0000 [Controller   1982] Node configuration loaded from "/home/debian/emc/crossbar/.crossbar/config.json"
2017-03-28T00:53:15+0000 [Controller   1982] Controller process starting (CPython-EPollReactor) ..
2017-03-28T00:53:15+0000 [Controller   1982] No extra node router roles
2017-03-28T00:53:15+0000 [Controller   1982] Router service session attached [crossbar.router.service.RouterServiceSession]
2017-03-28T00:53:15+0000 [Controller   1982] Joined realm 'crossbar' on node management router
2017-03-28T00:53:15+0000 [Controller   1982] While firing onJoin: Traceback (most recent call last):
  File "/opt/crossbar/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1447, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
  File "/opt/crossbar/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1301, in _inlineCallbacks
    result = g.send(result)
  File "/opt/crossbar/local/lib/python2.7/site-packages/crossbar/controller/process.py", line 188, in onJoin
    yield NativeProcessSession.onJoin(self, details)
  File "/opt/crossbar/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1447, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/opt/crossbar/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1301, in _inlineCallbacks
    result = g.send(result)
  File "/opt/crossbar/local/lib/python2.7/site-packages/crossbar/common/process.py", line 245, in onJoin
    dl.append(self.register(getattr(self, proc), uri, options=RegisterOptions(details_arg='details')))
  File "/opt/crossbar/local/lib/python2.7/site-packages/autobahn/wamp/protocol.py", line 1373, in register
    assert(procedure is None or type(procedure) == six.text_type)
exceptions.AssertionError: 

2017-03-28T00:53:15+0000 [Controller   1982] Node controller attached [crossbar.controller.process.NodeControllerSession]
2017-03-28T00:53:15+0000 [Controller   1982] Using default node shutdown triggers [u'shutdown_on_worker_exit']
2017-03-28T00:53:15+0000 [Controller   1982] Configuring node from local configuration ...
2017-03-28T00:53:15+0000 [Controller   1982] Starting 1 workers ...
2017-03-28T00:53:15+0000 [Controller   1982] Could not startup node: Traceback (most recent call last):
  File "/opt/crossbar/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1301, in _inlineCallbacks
    result = g.send(result)
  File "/opt/crossbar/local/lib/python2.7/site-packages/crossbar/controller/node.py", line 504, in start
    yield self._startup()
  File "/opt/crossbar/local/lib/python2.7/site-packages/crossbar/controller/node.py", line 529, in _startup
    return self._configure_node_from_config(self._config)
  File "/opt/crossbar/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1447, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/opt/crossbar/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1301, in _inlineCallbacks
    result = g.send(result)
  File "/opt/crossbar/local/lib/python2.7/site-packages/crossbar/controller/node.py", line 590, in _configure_node_from_config
    yield self._controller.start_router(worker_id, worker_options, details=call_details)
  File "/opt/crossbar/local/lib/python2.7/site-packages/crossbar/controller/process.py", line 333, in start_router
    return self._start_native_worker('router', id, options, details=details)
  File "/opt/crossbar/local/lib/python2.7/site-packages/crossbar/controller/process.py", line 617, in _start_native_worker
    self.publish(starting_topic, starting_info, options=PublishOptions(exclude=details.caller))
  File "/opt/crossbar/local/lib/python2.7/site-packages/autobahn/wamp/protocol.py", line 1144, in publish
    assert(type(topic) == six.text_type)
exceptions.AssertionError: 
```

**Comment by ecorm** [comment]
I just realized that I messed up the update of my ARM device. That could be the cause of my problem. I'll start over with a fresh Debian image and will report back.

**Comment by oberstet** [comment]
@ecorm this might be my fault: the latest AB Py releases (0.18.0 and 0.18.1) have now fully strict type checking (rather than type coercion) on URIs. But a CB release is necessary ..

**Comment by ecorm** [comment]
@oberstet That bit of info was invaluable, thanks!

I did `pip install 'autobahn==0.17.2' before doing `pip install crossbar`, and that ensured that AB Py 0.17.2 was used instead of the latest bleeding edge.

With AB Py 0.17.2, I'm now able to start Crossbar on my ARM device. :-)

The `python-pip` and `python-virtualenv` Debian packages seem to be too old to install some of the needed Python packages. So I've had better luck installing Crossbar by first using `get-pip.py` to install the latest `pip` and `virtualenv`:

```
sudo apt install build-essential libssl-dev libffi-dev python-dev
wget https://bootstrap.pypa.io/get-pip.py
sudo python get-pip.py
sudo pip install virtualenv
```

The only problem with this approach is that it takes around 30 minutes to install Crossbar, because some of the dependencies seem to be compiled from scratch. However, once the dependencies are installed, removing and installing the `crossbar` package is pretty quick.

Let me know if there's a better way of doing this on Debian/ARM.

**Comment by markope** [comment]
When I go back to `autobahn==0.17.2` however, I get this issue back #992. So which combination of versions of autobahn-js, autobahn-python and crossbar would work together right now?

**Comment by ecorm** [comment]
Perhaps testing on an ARM device should be part of the release checklist? Especially considering that Crossbar is touted as an IoT technology.

**Comment by meejah** [comment]
@ecorm regarding Debian: I use the packaged virtualenv, but always run "pip install --upgrade pip setuptools" in new virtual-envs.

The reason for the slow install is probably because most projects ship "wheel" files, but probably not for ARM platform -- and then pip falls back to making its own. If you have a modern pip, it will cache the result so a second install (or upgrade) should be fast(er). If you're deploying a lot, you could arrange for the pip cache to be available.

Unfortunately, the "real" answer here would be "have more ARM wheels" but that's up to individual projects, etc. You *could* run your own "devpi" instance and cache arm-wheels. This is perhaps something crossbar.io could do (i.e. have a repository containing wheels for all crossbar dependencies,for ARM + amd64).

**Comment by oberstet** [comment]
This issue is fixed on master. 

@ecorm rgd armhf, the way that we'd like to improve support is via Docker https://github.com/crossbario/crossbar-docker#crossbar-on-armhf

**Comment by ecorm** [comment]
@oberstet , a Docker image for ARM might be fine and convenient for development, but the image is too large for deployment on an embedded end product. It's larger than the entire Debian installation on our device.
