### ISSUE TITLE
File upload: can't mix strings and bytes in path components

### ISSUE THREAD

**Issue by Yamakaky** [crossbario/crossbar#1007]
```
Traceback (most recent call last):
  File "/home/yamakaky/dev/radiokawa/crossbar/lib/python3.6/site-packages/twisted/web/http.py", line 1447, in dataReceived
    finishCallback(data[contentLength:])
  File "/home/yamakaky/dev/radiokawa/crossbar/lib/python3.6/site-packages/twisted/web/http.py", line 1827, in _finishRequestBody
    self.allContentReceived()
  File "/home/yamakaky/dev/radiokawa/crossbar/lib/python3.6/site-packages/twisted/web/http.py", line 1906, in allContentReceived
    req.requestReceived(command, path, version)
  File "/home/yamakaky/dev/radiokawa/crossbar/lib/python3.6/site-packages/twisted/web/http.py", line 771, in requestReceived
    self.process()
--- <exception caught here> ---
  File "/home/yamakaky/dev/radiokawa/crossbar/lib/python3.6/site-packages/twisted/web/server.py", line 190, in process
    self.render(resrc)
  File "/home/yamakaky/dev/radiokawa/crossbar/lib/python3.6/site-packages/twisted/web/server.py", line 241, in render
    body = resrc.render(self)
  File "/home/yamakaky/dev/radiokawa/crossbar/lib/python3.6/site-packages/twisted/web/resource.py", line 250, in render
    return m(request)
  File "/home/yamakaky/dev/radiokawa/crossbar/lib/python3.6/site-packages/crossbar/twisted/fileupload.py", line 243, in render_POST
    fileTempDir = os.path.join(self._tempDirRoot, fileId)
  File "/usr/lib/python3.6/posixpath.py", line 92, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.6/genericpath.py", line 151, in _check_arg_types
    raise TypeError("Can't mix strings and bytes in path components") from None
builtins.TypeError: Can't mix strings and bytes in path components
```
`_uploadRoot` and `_tempDirRoot` are `bytes`. Temporary fix at https://github.com/crossbario/crossbar/blob/master/crossbar/twisted/fileupload.py#L72-L73:
```python
        self._uploadRoot = upload_directory.decode('utf8')
        self._tempDirRoot = temp_directory.decode('utf8')
```

**Comment by Yamakaky** [comment]
Hum, in fact the path is encoded in ascii (bye non-ascii paths btw) at https://github.com/crossbario/crossbar/blob/master/crossbar/worker/router.py#L1189, apparently because of https://stackoverflow.com/questions/20433559/twisted-web-file-directory-listing-issues/20433918#20433918.

**Comment by oberstet** [comment]
As mentioned elsewhere, the File Upload service needs a full code review .. I suspect there are multiple issue hidden.

**Comment by Paradoxeuh** [comment]
Running the version 17.12.1 and it is still not working (trying with the crossbario example).

**Comment by oberstet** [comment]
I am inclined to remove this altogether .. there are multiple issues with this code. or at least mark it as "experimental" or "partially broken". we don't have the resources right now to clean it up

**Comment by Yamakaky** [comment]
script removed
