### ISSUE TITLE
Cookie store type=file broken on Py 2

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#1021]
When a cookie gets loaded from persistent cookie store (`type == "file"`):

```console
2017-04-03T06:59:56+0000 [Router      22045] internal error: 
Traceback (most recent call last):
  File "/home/ubuntu/crossbar-pypy2-1/site-packages/autobahn/wamp/websocket.py", line 95, in onMessage
    self._session.onMessage(msg)
  File "/home/ubuntu/crossbar-pypy2-1/site-packages/crossbar/router/session.py", line 414, in onMessage
    d = txaio.as_future(self.onHello, msg.realm, details)
  File "/home/ubuntu/crossbar-pypy2-1/site-packages/txaio/tx.py", line 408, in as_future
    return maybeDeferred(fun, *args, **kwargs)
  File "/home/ubuntu/crossbar-pypy2-1/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
--- <exception caught here> ---
  File "/home/ubuntu/crossbar-pypy2-1/site-packages/crossbar/router/session.py", line 664, in onHello
    authextra=None)
  File "/home/ubuntu/crossbar-pypy2-1/site-packages/autobahn/wamp/types.py", line 157, in __init__
    assert(authid is None or type(authid) == six.text_type)
exceptions.AssertionError: 
```

**Comment by oberstet** [comment]
readd later to demo config:

```json
                            "cookie": {
                                "name": "cbdemo",
                                "length": 24,
                                "max_age": 86400,
                                "store": {
                                    "type": "memory"
                                }
                            },
```
