### ISSUE TITLE
'WampWebSocketServerProtocol' object has no attribute '_transport_info'

### ISSUE THREAD

**Issue by koxu1996** [crossbario/crossbar#1031]
After installing latest version I am getting error:
```
2017-04-06T23:59:46+0200 [Router      23375] Traceback (most recent call last):
2017-04-06T23:59:46+0200 [Router      23375]   File "/usr/local/lib/python2.7/dist-packages/crossbar/router/protocol.py", line 240, in onConnect
2017-04-06T23:59:46+0200 [Router      23375]     self._authid, self._authrole, self._authmethod, self._authrealm, authextra = self.factory._cookiestore.getAuth(self._cbtid)
2017-04-06T23:59:46+0200 [Router      23375]   File "/usr/local/lib/python2.7/dist-packages/crossbar/router/cookiestore.py", line 153, in getAuth
2017-04-06T23:59:46+0200 [Router      23375]     cookie_auth_info = c['authid'], c['authrole'], c['authmethod'], c['authrealm'], c['authextra']
2017-04-06T23:59:46+0200 [Router      23375] KeyError: 'authrealm'
2017-04-06T23:59:46+0200 [Router      23375] Unhandled error in Deferred:
2017-04-06T23:59:46+0200 [Router      23375] 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/autobahn/websocket/protocol.py", line 1203, in consumeData
    self.processHandshake()
  File "/usr/local/lib/python2.7/dist-packages/autobahn/websocket/protocol.py", line 2797, in processHandshake
    txaio.add_callbacks(f, self.succeedHandshake, forward_error)
  File "/usr/local/lib/python2.7/dist-packages/txaio/tx.py", line 490, in add_callbacks
    future.addCallbacks(callback, errback)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 310, in addCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/autobahn/websocket/protocol.py", line 2990, in succeedHandshake
    self._onOpen()
  File "/usr/local/lib/python2.7/dist-packages/autobahn/twisted/websocket.py", line 141, in _onOpen
    self.onOpen()
  File "/usr/local/lib/python2.7/dist-packages/crossbar/router/protocol.py", line 302, in onOpen
    self._transport_info[u'websocket_extensions_in_use'] = [e.__json__() for e in self.websocket_extensions_in_use]
exceptions.AttributeError: 'WampWebSocketServerProtocol' object has no attribute '_transport_info'
```

**Comment by koxu1996** [comment]
I discovered the problem. Now cookie-based authentication store another fields. There are two solutions:
- deleting old cookie file
- adding `authrealm` and `authextra` fields for every entry

I wonder why there is no UPDATE.md which show incompabilities between versions?
