### ISSUE TITLE
Pub/sub broken in 17.5.1

### ISSUE THREAD

**Issue by agronholm** [crossbario/crossbar#1094]
We started getting these exceptions in Crossbar (pypy3-17.5.1) logs after a few days of running it:
```
Jun 05 08:13:44 tietoib crossbar[1199]: 2017-06-05T08:13:44+0000 [Router         11] Unhandled Error
Jun 05 08:13:44 tietoib crossbar[1199]: Traceback (most recent call last):
Jun 05 08:13:44 tietoib crossbar[1199]:   File "/usr/local/site-packages/crossbar/worker/process.py", line 287, in <module>
Jun 05 08:13:44 tietoib crossbar[1199]:     run()
Jun 05 08:13:44 tietoib crossbar[1199]:   File "/usr/local/site-packages/crossbar/worker/process.py", line 275, in run
Jun 05 08:13:44 tietoib crossbar[1199]:     reactor.run()
Jun 05 08:13:44 tietoib crossbar[1199]:   File "/usr/local/site-packages/twisted/internet/base.py", line 1243, in run
Jun 05 08:13:44 tietoib crossbar[1199]:     self.mainLoop()
Jun 05 08:13:44 tietoib crossbar[1199]:   File "/usr/local/site-packages/twisted/internet/base.py", line 1252, in mainLoop
Jun 05 08:13:44 tietoib crossbar[1199]:     self.runUntilCurrent()
Jun 05 08:13:44 tietoib crossbar[1199]: --- <exception caught here> ---
Jun 05 08:13:44 tietoib crossbar[1199]:   File "/usr/local/site-packages/twisted/internet/base.py", line 878, in runUntilCurrent
Jun 05 08:13:44 tietoib crossbar[1199]:     call.func(*call.args, **call.kw)
Jun 05 08:13:44 tietoib crossbar[1199]:   File "/usr/local/site-packages/crossbar/router/broker.py", line 467, in _notify_some
Jun 05 08:13:44 tietoib crossbar[1199]:     txaio.resolve(all_d, None)
Jun 05 08:13:44 tietoib crossbar[1199]:   File "/usr/local/site-packages/txaio/tx.py", line 456, in resolve
Jun 05 08:13:44 tietoib crossbar[1199]:     future.callback(result)
Jun 05 08:13:44 tietoib crossbar[1199]:   File "/usr/local/site-packages/twisted/internet/defer.py", line 459, in callback
Jun 05 08:13:44 tietoib crossbar[1199]:     self._startRunCallbacks(result)
Jun 05 08:13:44 tietoib crossbar[1199]:   File "/usr/local/site-packages/twisted/internet/defer.py", line 560, in _startRunCallbacks
Jun 05 08:13:44 tietoib crossbar[1199]:     raise AlreadyCalledError
Jun 05 08:13:44 tietoib crossbar[1199]: twisted.internet.defer.AlreadyCalledError:

```
On the client side, we're seeing errors similar to these with both autobahn-python and autobahn-js:
```
INFO:asphalt.wamp.client:Joined realm 'myoffice'
CRITICAL:root:Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/autobahn/wamp/websocket.py", line 95, in onMessage
    self._session.onMessage(msg)
  File "/usr/local/lib/python3.6/site-packages/autobahn/wamp/protocol.py", line 651, in onMessage
    raise ProtocolError("EVENT received for non-subscribed subscription ID {0}".format(msg.subscription))
autobahn.wamp.exception.ProtocolError: EVENT received for non-subscribed subscription ID 1642824748581814
```
This breaks our production install so we had to revert to 17.2.1. We also had issues with 17.3.1 which we had to revert back to 17.2.1.

**Comment by agronholm** [comment]
This is what we get on the client side (with autobahn-js 0.12)
![client-problems](https://cloud.githubusercontent.com/assets/130003/26776303/4f743980-49e1-11e7-8bcc-384897ba48f5.png)

**Comment by oberstet** [comment]
cannot reproduce. we are running this on our demo instances
