### ISSUE TITLE
Crossbar crash with KeyError: 6L in crossbar.controller.processtypes.RouterWorkerProcess

### ISSUE THREAD

**Issue by marcvdijk** [crossbario/crossbar#1171]
It happens to me frequently that upon relaunch of Crossbar I get the following error:

08/21/2017 11:14:51 - [critical: crossbar.controller.processtypes.RouterWorkerProcess] - Traceback (most recent call last):
  File "/Users/mvdijk/Documents/WorkProjects/liestudio-master/liestudio/.venv/lib/python2.7/site-packages/autobahn/wamp/websocket.py", line 95, in onMessage
    self._session.onMessage(msg)
  File "/Users/mvdijk/Documents/WorkProjects/liestudio-master/liestudio/.venv/lib/python2.7/site-packages/crossbar/router/session.py", line 536, in onMessage
    self._router.process(self, msg)
  File "/Users/mvdijk/Documents/WorkProjects/liestudio-master/liestudio/.venv/lib/python2.7/site-packages/crossbar/router/router.py", line 240, in process
    self._dealer.processYield(session, msg)
  File "/Users/mvdijk/Documents/WorkProjects/liestudio-master/liestudio/.venv/lib/python2.7/site-packages/crossbar/router/dealer.py", line 811, in processYield
    self._remove_invoke_request(invocation_request)
  File "/Users/mvdijk/Documents/WorkProjects/liestudio-master/liestudio/.venv/lib/python2.7/site-packages/crossbar/router/dealer.py", line 740, in _remove_invoke_request
    del self._invocations_by_call[invocation_request.call.request]
KeyError: 6L

Usually, after trying a few times, crossbar will launch and run normally.
At the moment I do not know where to start looking for solving this issue.
I hope anyone can help pointing me in the right direction

My system:
- OSX 10.11.6
- Crossbar 17.6.1.post3
- Autobahn 17.7.1

Tanks,

Marc

**Comment by meejah** [comment]
I believe this is fixed by https://github.com/crossbario/crossbar/pull/1142 -- can you confirm by running crossbar from master?

**Comment by marcvdijk** [comment]
Hey meejah,

Thanks for the pointer. I can confirm its fixed in the master and the recent pip version (17.8.1.post1)

**Comment by meejah** [comment]
Great! Thanks for following up
