### ISSUE TITLE
'guest' type missing in  _configure_node_from_config

### ISSUE THREAD

**Issue by Emantor** [crossbario/crossbar#1179]
Since #1175 the guest type is missing from the assertion in https://github.com/crossbario/crossbar/blob/2f1f0ae8d8bcd6f56d78e4291a1b2e0bbeedc298/crossbar/controller/node.py#L656
# Crossbar version
Output of `crossbar version`:
```
     __  __  __  __  __  __      __     __
    /  `|__)/  \/__`/__`|__) /\ |__)  |/  \
    \__,|  \\__/.__/.__/|__)/~~\|  \. |\__/

 Crossbar.io        : 17.9.1 (Crossbar.io COMMUNITY)
   Autobahn         : 17.9.1 (with JSON, MessagePack, CBOR, UBJSON)
   Twisted          : 17.5.0-EPollReactor
   LMDB             : 0.93/lmdb-0.9.18
   Python           : 3.6.2/CPython
 OS                 : Linux-4.12.8-2-ARCH-x86_64-with-arch
 Machine            : x86_64
 Release key        : RWRj+Sb8UH/pwLCycZ+3OroR5UV9aaLUDVbKxNcj+gYoOOZv0LrzMH1a
```
# Error
Starting the labgrid-project/labgrid coordinator fails with
```
2017-09-05T14:52:34+0200 [Controller  15960] Starting 2 workers ...
2017-09-05T14:52:34+0200 [Controller  15960] Router worker "worker-001" starting ..
2017-09-05T14:52:34+0200 [Router      15969] Started Router worker "worker-001" [crossbar.worker.router.RouterWorkerSession / CPython-EPollReactor]
2017-09-05T14:52:34+0200 [Router      15969] Router worker "worker-001" session 3303279962187294 initializing ..
2017-09-05T14:52:34+0200 [Router      15969] Registered 35 procedures
2017-09-05T14:52:34+0200 [Router      15969] Router worker "worker-001" session ready
2017-09-05T14:52:34+0200 [Controller  15960] Router worker "worker-001" process 15969 started
2017-09-05T14:52:34+0200 [Router      15969] RouterServiceSession ready [configured on_ready fired]
2017-09-05T14:52:34+0200 [Router      15969] Realm 'realm1' started
2017-09-05T14:52:34+0200 [Controller  15960] Router 'worker-001': realm 'realm-001' (named 'realm1') started
2017-09-05T14:52:34+0200 [Router      15969] role role-001 on realm realm-001 started
2017-09-05T14:52:34+0200 [Controller  15960] Router 'worker-001': role 'role-001' (named 'authenticator') started on realm 'realm-001'
2017-09-05T14:52:34+0200 [Router      15969] role role-002 on realm realm-001 started
2017-09-05T14:52:34+0200 [Controller  15960] Router 'worker-001': role 'role-002' (named 'public') started on realm 'realm-001'
2017-09-05T14:52:34+0200 [Router      15969] started component: labgrid.remote.authenticator.AuthenticatorSession id=1175882440106437
2017-09-05T14:52:34+0200 [Controller  15960] Router 'worker-001': component 'component-001' started
2017-09-05T14:52:34+0200 [Router      15969] Site starting on 20408
2017-09-05T14:52:34+0200 [Controller  15960] Router 'worker-001': transport 'transport-001' started
2017-09-05T14:52:34+0200 [Controller  15960] Could not startup node: Traceback (most recent call last):
  File "/home/phoenix/.virtualenvs/labgrid/lib/python3.6/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/phoenix/.virtualenvs/labgrid/lib/python3.6/site-packages/twisted/internet/defer.py", line 1442, in gotResult
    _inlineCallbacks(r, g, deferred)
  File "/home/phoenix/.virtualenvs/labgrid/lib/python3.6/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/phoenix/.virtualenvs/labgrid/lib/python3.6/site-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
--- <exception caught here> ---
  File "/home/phoenix/.virtualenvs/labgrid/lib/python3.6/site-packages/crossbar/controller/node.py", line 597, in start
    yield self._startup()
  File "/home/phoenix/.virtualenvs/labgrid/lib/python3.6/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "/home/phoenix/.virtualenvs/labgrid/lib/python3.6/site-packages/crossbar/controller/node.py", line 656, in _configure_node_from_config
    assert worker_type in self._native_workers
builtins.AssertionError:
```
Crossbar configuration is available here: [Labgrid crossbar config](https://github.com/labgrid-project/labgrid/blob/master/.crossbar/config.yaml)
Full `crossbar start` output: [Paste](https://paste.stratum0.org/?161daf1fd021d21f#IR15mPt9BhT86riC23nkkZ1D5V7p0GRyGN+6bRV+J2s=)

# Reproduction steps
1. Download labgrid from git
2. Install with coordinator support `pip install .[coordinator]`
3. Start with `crossbar start`

**Comment by oberstet** [comment]
The offending assert should be removed (as the config was already checked, and the worker_type at this line of code can legitimately be "guest").

**Comment by oberstet** [comment]
@Emantor thanks for reporting! if you can, could you test master branch on your side? I just merged a patch that fixes the issue.

**Comment by Emantor** [comment]
Thanks for the quick fix, it is working as intended now 🎉 👍

**Comment by oberstet** [comment]
Thanks for reporting back! We will do a follow up release 17.9.2 very soon that will include this fix.

**Comment by oberstet** [comment]
long fixed and released (as above)
