### ISSUE TITLE
Remove half-baked realm auto-activation code

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#1186]
This leads to confusing "internal error" client disconnect, though the actual reason is a non-existing realm the client wants to join:

```console
2017-09-06T16:48:19+0000 [Router         18] Internal error (2): realm auto-activation (realm 'oberstet') not yet implemented
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/autobahn/wamp/protocol.py", line 792, in onMessage
    txaio.resolve(on_reply, msg.args[0])
  File "/usr/local/lib/python3.6/site-packages/txaio/tx.py", line 456, in resolve
    future.callback(result)
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 459, in callback
    self._startRunCallbacks(result)
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 567, in _startRunCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/python3.6/site-packages/crossbar/router/auth/cryptosign.py", line 181, in on_authenticate_ok
    error = self._assign_principal(principal)
  File "/usr/local/lib/python3.6/site-packages/crossbar/router/auth/pending.py", line 151, in _assign_principal
    self._router_factory.auto_start_realm(self._realm)
  File "/usr/local/lib/python3.6/site-packages/crossbar/router/router.py", line 540, in auto_start_realm
    raise Exception("realm auto-activation (realm '{}') not yet implemented".format(realm))
builtins.Exception: realm auto-activation (realm 'oberstet') not yet implemented
```

**Comment by koliyo** [comment]
Almost same problem when connecting to an existing realm, but with wrong authentication method, eg connecting anonymously to a protected realm. Very confusing error message

```
crossbar_1  |     raise Exception("role auto-activation (role '{}') not yet implemented".format(role))
crossbar_1  | builtins.Exception: role auto-activation (role 'internal') not yet implemented
```

**Comment by haizaar** [comment]
This produces about 20+ lines of logs for every attempt of misconfigured client. There also seems to be no option to disable this behavior.

**Comment by oberstet** [comment]
fixed long ago https://github.com/crossbario/crossbar/blob/ecc8b4e0d9f8fa3efa7d59755cb2e16151055870/crossbar/router/router.py#L510
