### ISSUE TITLE
'Register' object has no attribute 'correlation'

### ISSUE THREAD

**Issue by felipeZ** [crossbario/crossbar#1188]
I have install `crossbar` inside an anaconda virtual environment using:
`pip install crossbar`

The initialization output is:
```
user@server0:~$ crossbar init
Initializing application template 'default' in directory '/home/user'
Using template from '/home/user/miniconda3/envs/wamp/lib/python3.6/site-packages/crossbar/templates/default'
Creating directory /home/user/.crossbar
Creating directory /home/user/web
File /home/user/README.md already exists - SKIPPING
Creating file /home/user/.crossbar/config.json
Creating directory /home/user/web/js
Creating file /home/user/web/frontend.html
Creating file /home/user/web/backend.html
Creating file /home/user/web/index.html
Creating file /home/user/web/js/autobahn.js
Creating file /home/user/web/js/CHECKSUM.SHA256
Creating file /home/user/web/js/CHECKSUM.MD5
Creating file /home/user/web/js/autobahn.min.js
Creating file /home/user/web/js/autobahn.min.jgz
Creating file /home/user/web/js/CHECKSUM.SHA1
Creating file /home/user/web/js/LICENSE
Application template initialized

To start your node, run 'crossbar start --cbdir /home/user/.crossbar'
```

Then, I have tried to reproduce the examples of the documentation and run into the following error:
```
user@server0:~$ crossbar start --cbdir /home/user/.crossbar
2017-09-13T17:06:31+0200 [Controller  25371]      __  __  __  __  __  __      __     __
2017-09-13T17:06:31+0200 [Controller  25371]     /  `|__)/  \/__`/__`|__) /\ |__)  |/  \
2017-09-13T17:06:31+0200 [Controller  25371]     \__,|  \\__/.__/.__/|__)/~~\|  \. |\__/
2017-09-13T17:06:31+0200 [Controller  25371]                                         
2017-09-13T17:06:31+0200 [Controller  25371] Version:     Crossbar.io COMMUNITY 17.9.1
2017-09-13T17:06:31+0200 [Controller  25371] Public Key:  218879d67298ad2cfecc5233ffb8969cf210f101b0f5883787c8acb38a7554da
2017-09-13T17:06:31+0200 [Controller  25371] 
2017-09-13T17:06:31+0200 [Controller  25371] Node starting with personality "community" [crossbar.controller.node.Node]
2017-09-13T17:06:31+0200 [Controller  25371] Running from node directory "/home/user/.crossbar"
2017-09-13T17:06:31+0200 [Controller  25371] Node configuration loaded from "/home/user/.crossbar/config.json"
2017-09-13T17:06:31+0200 [Controller  25371] Controller process starting [CPython-EPollReactor] ..
2017-09-13T17:06:31+0200 [Controller  25371] No extra node router roles
2017-09-13T17:06:31+0200 [Controller  25371] Unhandled error in Deferred:
2017-09-13T17:06:31+0200 [Controller  25371] Traceback (most recent call last):
  File "/home/user/miniconda3/envs/wamp/lib/python3.6/site-packages/crossbar/router/router.py", line 252, in process
    self._dealer.processRegister(session, msg)
  File "/home/user/miniconda3/envs/wamp/lib/python3.6/site-packages/crossbar/router/dealer.py", line 422, in processRegister
    txaio.add_callbacks(d, on_authorize_success, on_authorize_error)
  File "/home/user/miniconda3/envs/wamp/lib/python3.6/site-packages/txaio/tx.py", line 491, in add_callbacks
    future.addCallbacks(callback, errback)
  File "/home/user/miniconda3/envs/wamp/lib/python3.6/site-packages/twisted/internet/defer.py", line 310, in addCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/home/user/miniconda3/envs/wamp/lib/python3.6/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/user/miniconda3/envs/wamp/lib/python3.6/site-packages/crossbar/router/dealer.py", line 403, in on_authorize_success
    reply.correlation = register.correlation
builtins.AttributeError: 'Register' object has no attribute 'correlation'
```

**Comment by om26er** [comment]
I think you need the latest autobahn-python, can you check if have the latest one installed ?

**Comment by felipeZ** [comment]
I have the following:
```
user@server0:~$ pip search autobahn
autobahn (17.9.2)                  - WebSocket client & server library, WAMP real-time framework
  INSTALLED: 17.9.2 (latest)
```

**Comment by om26er** [comment]
Sorry for the inconvenience, it seems crossbar in pypi is not updated to 17.9.2 while autobahn is.

So as a workaround please install autobahn 17.9.1 and it should work.

```pip install autobahn==17.9.1```

**Comment by felipeZ** [comment]
It Works, Thanks!
Are you going to introduce a constraint in the setup.py? I have the same problem in python 2.7
