### ISSUE TITLE
Crossbar 17.9.2 Twisted Reactor Error on init/start

### ISSUE THREAD

**Issue by rrueth** [crossbario/crossbar#1200]
After pip installing crossbar 17.9.2, running the `crossbar init`, `crossbar start`, or `crossbar version` commands raises the following error:

```
Running on *BSD or MacOSX, but cannot install kqueue Twisted reactor
Running on *BSD or MacOSX, but cannot install kqueue Twisted reactor
Traceback (most recent call last):
  File "/Users/ryan/Projects/server/env_crossbar/lib/python3.5/site-packages/autobahn/twisted/choosereactor.py", line 68, in install_optimal_reactor
    kqreactor.install()
  File "/Users/ryan/Projects/server/env_crossbar/lib/python3.5/site-packages/twisted/internet/kqreactor.py", line 317, in install
    installReactor(p)
  File "/Users/ryan/Projects/server/env_crossbar/lib/python3.5/site-packages/twisted/internet/main.py", line 32, in installReactor
    raise error.ReactorAlreadyInstalledError("reactor already installed")
twisted.internet.error.ReactorAlreadyInstalledError: reactor already installed
```

The output of `crossbar version` is below:
```
     __  __  __  __  __  __      __     __
    /  `|__)/  \/__`/__`|__) /\ |__)  |/  \
    \__,|  \\__/.__/.__/|__)/~~\|  \. |\__/

 Crossbar.io        : 17.9.2 (Crossbar.io COMMUNITY)
   Autobahn         : 17.9.3 (with JSON, MessagePack, CBOR, UBJSON)
   Twisted          : 17.9.0-SelectReactor
   LMDB             : 0.93/lmdb-0.9.18
   Python           : 3.5.3/CPython
 OS                 : Darwin-16.6.0-x86_64-i386-64bit
 Machine            : x86_64
 Release key        : RWRj+Sb8UH/pwLCycZ+3OroR5UV9aaLUDVbKxNcj+gYoOOZv0LrzMH1a
```

**Comment by geohuz** [comment]
I'm having the same issue with the lastest crossbar, on macOS sierra 10.12.6

**Comment by fhriley** [comment]
Same here on 10.12.6.

**Comment by mhtun** [comment]
getting the same issue on 10.12.6. Seems like this is the same issue as #939

**Comment by rrueth** [comment]
I don’t see the issue on Ubuntu 16.04.

**Comment by oberstet** [comment]
@rrueth are you installing crossbar into an own dedicated virtualenv or are you using Docker?

> all other forms of deployment are not supported by us ..

**Comment by rrueth** [comment]
This is with crossbar running in its own virtual env.

**Comment by fhriley** [comment]
Same here, brand new virtualenv. Basically just followed the instructions.

**Comment by petri** [comment]
same thing started happening here, brand new crossbar on Python 3.6.2, OSX high sierra. Ran fine for a while, then at some point when tried to start, started seeing the above error.

**Comment by Veronicacz** [comment]
Same here. And tried to use the methon in #939 (You can do that by "pip install https://github.com/crossbario/crossbar/archive/master.zip"). Still not work.

**Comment by dvhwgumby** [comment]
I submitted a patch for this (though it currently fails CI for reasons unconnected to my patch).  It's a simple change to autobahn-python in `autobahn/twisted/choosereactor.py`:

```
 @@ -65,7 +65,8 @@ def install_optimal_reactor(verbose=False):
          if current_reactor != 'KQueueReactor':
              try:
                  from twisted.internet import kqreactor
 -                kqreactor.install()
 +                if 'twisted.internet.reactor' not in sys.modules:
 +                    kqreactor.install()
              except:
```
I submitted a pull request but it may be ignored due to the Travis issue.

**Comment by meejah** [comment]
That change would certainly stop the symptoms -- but why is a reactor already installed? Which one is getting installed (i.e. if it's the `select` based reactor, it's not going to perform as well a the `kqueue` reactor)

**Comment by dvhwgumby** [comment]
Well true, but there's the package user's and package developer's perspective.  Checking and not installing is consistent with other practice (e.g. pip) and is consistent with Postel's maxim ("Be liberal in what you accept and strict in what you produce").   

The real fix needs to go in twisted, but that's an external package.  Also the bug appears in a deprecated function call.  Probably the correct fix is to overwrite any existing choice, but again, that would have to go into twisted.

FWiW: when I am a package developer I am willing to dig in to figure out the root cause, even if it delays getting a work around to users.  As a user I want a work around ASAP -- let the developer do the proper fix asynchronously.  For crossbar I'm a user not a developer!

**Comment by oberstet** [comment]
exactly. we should not paster over the symptoms, but dig to the root. likely some twisted package we started to use instantiates an implicit reactor. Twisted has this issue excessively, and we maybe a dozen places in our code where we postpone importing the twisted package exactly for that reason. We just need to find and add one more location.however, the deeper real problem is in twisted design (global reactor), but that is practcally unfixable ..Am 25.01.2018 9:09 nachm. schrieb meejah <notifications@github.com>:That change would certainly stop the symptoms -- but why is a reactor already installed? Which one is getting installed (i.e. if it's the select based reactor, it's not going to perform as well a the kqueue reactor)

**Comment by solomn1991** [comment]
maybe twisted is not the best base frame for crossbar,asyncio may be a more fit one

**Comment by oberstet** [comment]
@solomn1991 no, Twisted is great and exactly the right thing for what we do. asyncio lacks the features/maturity we need

**Comment by meejah** [comment]
Maybe for now we can improve the error-message? i.e. catch the exception and log a warning (with the name of the already-installed reactor) instead.

**Comment by alexey-baranov** [comment]
same with 17.8.1.post1 on win7
