### ISSUE TITLE
exit with "No module named worker"

### ISSUE THREAD

**Issue by brammeleman** [crossbario/crossbar#1219]
Error output
----------------
```
...
...
2017-11-07T20:54:23+0100 [Controller  28655] Starting 1 workers ...
2017-11-07T20:54:23+0100 [Controller  28655] Router worker "worker-001" starting ..
2017-11-07T20:54:23+0100 [Router      28664] /usr/bin/python: No module named worker
2017-11-07T20:54:23+0100 [Controller  28655] Native worker connection closed uncleanly: A process has ended with a probable error condition: process ended with exit code 1.
2017-11-07T20:54:23+0100 [Controller  28655] Failed to start native worker: A process has ended with a probable error condition: process ended with exit code 1.
2017-11-07T20:54:23+0100 [Controller  28655] ApplicationError: ApplicationError(error=<crossbar.error.cannot_start>, args=['Failed to start native worker: A process has ended with a probable error condition: process ended with exit code 1.', [u'/usr/bin/python: No module named worker']], kwargs={}, enc_algo=None): Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/endpoints.py", line 384, in processEnded
    return self.protocol.connectionLost(reason)
  File "/usr/local/lib/python2.7/dist-packages/crossbar/controller/native.py", line 82, in connectionLost
    self.factory._on_ready.errback(reason)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 500, in errback
    self._startRunCallbacks(fail)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 567, in _startRunCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/crossbar/controller/process.py", line 506, in on_ready_error
    raise ApplicationError(u"crossbar.error.cannot_start", emsg, worker.getlog())
autobahn.wamp.exception.ApplicationError: ApplicationError(error=<crossbar.error.cannot_start>, args=['Failed to start native worker: A process has ended with a probable error condition: process ended with exit code 1.', [u'/usr/bin/python: No module named worker']], kwargs={}, enc_algo=None)

2017-11-07T20:54:23+0100 [Controller  28655] crossbar.error.cannot_start: Failed to start native worker: A process has ended with a probable error condition: process ended with exit code 1. [u'/usr/bin/python: No module named worker']
```
Steps to reproduce
---------------------
1. checkout any crossbar demo app with a `.crossbar` directory in it
1. at the same level of `.crossbar`, touch a file named `crossbar.py`, so:
1. start crossbar: `crossbar start`

Ie:
```
cd ~/src/crossbar-examples/demos/gauges
touch crossbar.py
crossbar start
```

Above steps create a crossbar.pyc file that will cause crossbar to exit with this cryptic error.
Why is the crossbar.py file included/compiled when starting crossbar?
For now, I'll avoid naming files `crossbar.py` in the top level directory....

Crossbar version
----------
```
     __  __  __  __  __  __      __     __
    /  `|__)/  \/__`/__`|__) /\ |__)  |/  \
    \__,|  \\__/.__/.__/|__)/~~\|  \. |\__/
                                        
 Crossbar.io        : 17.11.1 (Crossbar.io COMMUNITY)
   Autobahn         : 17.10.1 (with JSON, MessagePack, CBOR, UBJSON)
   Twisted          : 17.9.0-EPollReactor
   LMDB             : 0.93/lmdb-0.9.18
   Python           : 2.7.12/CPython
 OS                 : Linux-4.4.0-98-generic-x86_64-with-Ubuntu-16.04-xenial
 Machine            : x86_64
 Release key        : RWT/n6IQ4dKesCP8YwwJiWH30ST8eq5D21ih4EFbJZazzsqEX6CmaT3k
```

**Comment by meejah** [comment]
Python will interpret "crossbar.py" as a module and shadow our own, probably. Tou'll have to name it something else.
