### ISSUE TITLE
Crossbar WSS not working

### ISSUE THREAD

**Issue by sevaho** [crossbario/crossbar#1267]
I want to implement wss, but it is simply not working and I have no more clues how I am supposed to get it working.

What I did

# 1: Setting up SSL certs

So first of all I have an SSL cert from Comodo with 2x intermediate CA, 1 root CA and 1 public cert.
Next I have 1 key that is working for my public cert.

I've read the docs and I am confused on how to set up my ssl cert.

Here https://crossbar.io/docs/TLS-Certificates/ it says that I need to "append any intermediate CA certificates to the server certificate" and "but excluding the highest level (root) CA". Okay so I concatenate 1x server.crt 2x intermediate CA.

But then there is this 1 line mention "ca_certificates when set requires that a connecting client's certificate be issued by one of the listed CAs, otherwise the connection establishment will be denied (optional)" I assume this is only used when using self-signed certs to validate them with custom ca-certs? and you do not use this ever when you have bought an SSL cert. (please correct me if I am wrong).

# 2: config.json

I tried several configs (but I guess they are actually all the same):

NOTE: I am using example.com here, I don't use this as actual code, my cert is a wildcard fyi.

1)

```
{
    "version": 2,
    "controller": {},
    "workers": [
        {
            "type": "router",
            "realms": [
                {
                    "name": "realm1",
                    "roles": [
                        {
                            "name": "anonymous",
                            "permissions": [
                                {
                                    "uri": "com.help",
                                    "match": "prefix",
                                    "allow": {
                                        "call": true,
                                        "register": true,
                                        "publish": true,
                                        "subscribe": true
                                    },
                                    "disclose": {
                                        "caller": false,
                                        "publisher": false
                                    },
                                    "cache": true
                                }
                            ]
                        }
                    ]
                }
            ],
            "transports": [
                {
                    "type": "universal",
                    "endpoint": {
                        "type": "tcp",
                        "port": 8080,
                        "tls": {
                            "key": "private.pem",
                            "certificate": "public.pem",
                            "dhparam":"dhparam.pem",
                            "ciphers": "ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AES:RSA+3DES:!ADH:!AECDH:!MD5:!DSS"
                        }
                    },
                    "websocket": {
                        "ws": {
                            "type":"websocket",
                            "url": "wss://api.example.com:8080"
                        }
                    }
                }
            ]
        }
    ]
}
```

2)

```
{
    "version": 2,
    "controller": {},
    "workers": [
        {
            "type": "router",
            "realms": [
                {
                    "name": "realm1",
                    "roles": [
                        {
                            "name": "anonymous",
                            "permissions": [
                                {
                                    "uri": "com.help",
                                    "match": "prefix",
                                    "allow": {
                                        "call": true,
                                        "register": true,
                                        "publish": true,
                                        "subscribe": true
                                    },
                                    "disclose": {
                                        "caller": false,
                                        "publisher": false
                                    },
                                    "cache": true
                                }
                            ]
                        }
                    ]
                }
            ],
            "transports": [
                {
                    "type": "web",
                    "endpoint": {
                        "type": "tcp",
                        "port": 8080,
                        "tls": {
                            "key": "private.pem",
                            "certificate": "public.pem",
                            "dhparam":"dhparam.pem"
                        }
                    },
                    "paths": {
                        "ws": {
                            "type": "websocket",
                            "url": "wss://api.example.com:8080/ws"
                        }
                    }
                }
            ]
        }
    ]
}
```

3)

```
{
    "version": 2,
    "controller": {},
    "workers": [
        {
            "type": "router",
            "realms": [
                {
                    "name": "realm1",
                    "roles": [
                        {
                            "name": "anonymous",
                            "permissions": [
                                {
                                    "uri": "com.help",
                                    "match": "prefix",
                                    "allow": {
                                        "call": true,
                                        "register": true,
                                        "publish": true,
                                        "subscribe": true
                                    },
                                    "disclose": {
                                        "caller": false,
                                        "publisher": false
                                    },
                                    "cache": true
                                }
                            ]
                        }
                    ]
                }
            ],
            "transports": [
                {
                    "type": "websocket",
                    "endpoint": {
                        "type": "tcp",
                        "port": 8080,
                        "tls": {
                            "key": "private.pem",
                            "certificate": "public.pem",
                            "dhparam":"dhparam.pem"
                        }
                    },
                      "url": "wss://api.example.com:8080/ws" 
     
                }
            ]
        }
    ]
}
```

# 3: autobahnjs connection

```
"use strict"

const autobahn = require('autobahn');
const l = require('./logger');

var conn = new autobahn.Connection({

    url: "wss://api.example.com:8080",
    // url: "wss://api.example.com:8080/ws",
    realm: "realm1"

});

conn.open();

conn.onopen = function (session, details) {

    function onHello (res) {
    
        console.log(res);

    }

    session.subscribe("com.help", onHello);

    function add (args) {

        return args[0] + args[1];

    }

    session.register("com.help.add", add);

}
```

# 4 LOGS

config 1 has no error in logs but nothing works.

When using config 2)

```
...
2018-03-13T10:19:06+0000 [Router         15 crossbar.worker.worker.NativeWorkerSession] RouterWorkerSession.start_router_transport
2018-03-13T10:19:06+0000 [Router         15 crossbar.worker.worker.NativeWorkerSession] Unable to format event {'ttype': 'web', 'log_logger': <Logger 'crossbar.worker.worker.NativeWorkerSession'>, 'log_source': None, 'log_format': 'Starting {type}-transport on router.', 'log_time': 1520936346.4093735}: 'type'
2018-03-13T10:19:06+0000 [Router         15 crossbar.worker.worker.NativeWorkerSession] Loading server TLS key from /node/.crossbar/tls.key
2018-03-13T10:19:06+0000 [Router         15 crossbar.worker.worker.NativeWorkerSession] Loading server TLS certificate from /node/.crossbar/tls.crt
2018-03-13T10:19:06+0000 [Router         15 crossbar.worker.worker.NativeWorkerSession] Using secure default TLS ciphers
2018-03-13T10:19:06+0000 [Router         15 crossbar.worker.worker.NativeWorkerSession] OpenSSL is using elliptic curve prime256v1 (NIST P-256)
2018-03-13T10:19:06+0000 [Router         15 log_legacy] Site (TLS) starting on 8080
2018-03-13T10:19:06+0000 [Router         15 crossbar.worker.worker.NativeWorkerSession] Router transport 'transport-001'' started and listening
2018-03-13T10:19:06+0000 [Controller      1 crossbar.router.router.Router] Validate 'call_result' for 'crossbar.worker.worker-001.start_router_transport'
2018-03-13T10:19:06+0000 [Controller      1 crossbar.controller.node.Node] Router "worker-001": transport 'transport-001' started
2018-03-13T10:19:06+0000 [Controller      1 crossbar.router.router.Router] Validate 'call' for 'crossbar.worker.worker-001.start_web_transport_service'
2018-03-13T10:19:06+0000 [Controller      1 crossbar.router.role.RouterRole] CrossbarRouterTrustedRole.authorize trusted crossbar.worker.worker-001.start_web_transport_service call {}
2018-03-13T10:19:06+0000 [Controller      1 crossbar.router.router.Router] Authorized action 'call' for URI 'crossbar.worker.worker-001.start_web_transport_service' by session 908698830703389 with authid 'None' and authrole 'trusted' -> authorization: {'allow': True, 'cache': False, 'disclose': False}
2018-03-13T10:19:06+0000 [Router         15 crossbar.worker.worker.NativeWorkerSession] RouterWorkerSession.start_web_transport_service(transport_id=transport-001, path=ws, config={'type': 'websocket', 'url': 'wss://api2.wegroup.be:8080/ws'})
2018-03-13T10:19:06+0000 [Controller      1 crossbar.router.router.Router] Validate 'call_result' for 'crossbar.worker.worker-001.start_web_transport_service'
2018-03-13T10:19:06+0000 [Controller      1 crossbar.controller.node.Node] Router "worker-001": web service 'websocket' started on path 'ws' on transport 'transport-001'
2018-03-13T10:19:06+0000 [Controller      1 crossbar.controller.node.Node] Local node configuration applied successfully!
2018-03-13T10:20:05+0000 [Router         15 log_legacy] Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/twisted/web/_http2.py", line 186, in dataReceived
    self._requestEnded(event)
  File "/usr/local/lib/python3.6/site-packages/twisted/web/_http2.py", line 493, in _requestEnded
    stream.requestComplete()
  File "/usr/local/lib/python3.6/site-packages/twisted/web/_http2.py", line 990, in requestComplete
    self._request.requestReceived(self.command, self.path, b'HTTP/2')
  File "/usr/local/lib/python3.6/site-packages/twisted/web/http.py", line 866, in requestReceived
    self.process()
--- <exception caught here> ---
  File "/usr/local/lib/python3.6/site-packages/twisted/web/server.py", line 195, in process
    self.render(resrc)
  File "/usr/local/lib/python3.6/site-packages/twisted/web/server.py", line 255, in render
    body = resrc.render(self)
  File "/usr/local/lib/python3.6/site-packages/autobahn/twisted/resource.py", line 121, in render
    protocol = self._factory.buildProtocol(request.transport.getPeer())
builtins.AttributeError: 'NoneType' object has no attribute 'getPeer'

2018-03-13T10:20:06+0000 [Router         15 log_legacy] Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/twisted/web/_http2.py", line 186, in dataReceived
    self._requestEnded(event)
  File "/usr/local/lib/python3.6/site-packages/twisted/web/_http2.py", line 493, in _requestEnded
    stream.requestComplete()
  File "/usr/local/lib/python3.6/site-packages/twisted/web/_http2.py", line 990, in requestComplete
    self._request.requestReceived(self.command, self.path, b'HTTP/2')
  File "/usr/local/lib/python3.6/site-packages/twisted/web/http.py", line 866, in requestReceived
    self.process()
--- <exception caught here> ---
  File "/usr/local/lib/python3.6/site-packages/twisted/web/server.py", line 195, in process
    self.render(resrc)
  File "/usr/local/lib/python3.6/site-packages/twisted/web/server.py", line 255, in render
    body = resrc.render(self)
  File "/usr/local/lib/python3.6/site-packages/autobahn/twisted/resource.py", line 121, in render
    protocol = self._factory.buildProtocol(request.transport.getPeer())
builtins.AttributeError: 'NoneType' object has no attribute 'getPeer'

2018-03-13T10:21:17+0000 [Router         15 log_legacy] Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/twisted/web/_http2.py", line 186, in dataReceived
    self._requestEnded(event)
  File "/usr/local/lib/python3.6/site-packages/twisted/web/_http2.py", line 493, in _requestEnded
    stream.requestComplete()
  File "/usr/local/lib/python3.6/site-packages/twisted/web/_http2.py", line 990, in requestComplete
    self._request.requestReceived(self.command, self.path, b'HTTP/2')
  File "/usr/local/lib/python3.6/site-packages/twisted/web/http.py", line 866, in requestReceived
    self.process()
--- <exception caught here> ---
  File "/usr/local/lib/python3.6/site-packages/twisted/web/server.py", line 195, in process
    self.render(resrc)
  File "/usr/local/lib/python3.6/site-packages/twisted/web/server.py", line 255, in render
    body = resrc.render(self)
  File "/usr/local/lib/python3.6/site-packages/autobahn/twisted/resource.py", line 121, in render
    protocol = self._factory.buildProtocol(request.transport.getPeer())
builtins.AttributeError: 'NoneType' object has no attribute 'getPeer'
```

When using config 3)

```
2018-03-13T10:24:29+0000 [Router         15 crossbar.worker.worker.NativeWorkerSession] RouterWorkerSession.start_router_transport
2018-03-13T10:24:29+0000 [Router         15 crossbar.worker.worker.NativeWorkerSession] Unable to format event {'ttype': 'websocket', 'log_logger': <Logger 'crossbar.worker.worker.NativeWorkerSession'>, 'log_source': None, 'log_format': 'Starting {type}-transport on router.', 'log_time': 1520936669.2736218}: 'type'
2018-03-13T10:24:29+0000 [Router         15 crossbar.worker.worker.NativeWorkerSession] Loading server TLS key from /node/.crossbar/tls.key
2018-03-13T10:24:29+0000 [Router         15 crossbar.worker.worker.NativeWorkerSession] Loading server TLS certificate from /node/.crossbar/tls.crt
2018-03-13T10:24:29+0000 [Router         15 crossbar.worker.worker.NativeWorkerSession] Using secure default TLS ciphers
2018-03-13T10:24:29+0000 [Router         15 crossbar.worker.worker.NativeWorkerSession] OpenSSL is using elliptic curve prime256v1 (NIST P-256)
2018-03-13T10:24:29+0000 [Router         15 log_legacy] WampWebSocketServerFactory (TLS) starting on 8080
2018-03-13T10:24:29+0000 [Router         15 crossbar.worker.worker.NativeWorkerSession] Router transport 'transport-001'' started and listening
2018-03-13T10:24:29+0000 [Controller      1 crossbar.router.router.Router] Validate 'call_result' for 'crossbar.worker.worker-001.start_router_transport'
2018-03-13T10:24:29+0000 [Controller      1 crossbar.controller.node.Node] Router "worker-001": transport 'transport-001' started
2018-03-13T10:24:29+0000 [Controller      1 crossbar.controller.node.Node] Local node configuration applied successfully!
2018-03-13T10:24:37+0000 [Router         15 crossbar.router.protocol.WampWebSocketServerProtocol] 
[('logOctets', False, 'WampWebSocketServerFactory'),
 ('logFrames', False, 'WampWebSocketServerFactory'),
 ('trackTimings', False, 'WampWebSocketServerFactory'),
 ('utf8validateIncoming', True, 'WampWebSocketServerFactory'),
 ('applyMask', True, 'WampWebSocketServerFactory'),
 ('maxFramePayloadSize', 0, 'WampWebSocketServerFactory'),
 ('maxMessagePayloadSize', 0, 'WampWebSocketServerFactory'),
 ('autoFragmentSize', 0, 'WampWebSocketServerFactory'),
 ('failByDrop', False, 'WampWebSocketServerFactory'),
 ('echoCloseCodeReason', False, 'WampWebSocketServerFactory'),
 ('openHandshakeTimeout', 0.0, 'WampWebSocketServerFactory'),
 ('closeHandshakeTimeout', 0.0, 'WampWebSocketServerFactory'),
 ('tcpNoDelay', True, 'WampWebSocketServerFactory'),
 ('autoPingInterval', 0, 'WampWebSocketServerFactory'),
 ('autoPingTimeout', 0, 'WampWebSocketServerFactory'),
 ('autoPingSize', 4, 'WampWebSocketServerFactory'),
 ('versions', [8, 13], 'WampWebSocketServerFactory'),
 ('webStatus', True, 'WampWebSocketServerFactory'),
 ('requireMaskedClientFrames', True, 'WampWebSocketServerFactory'),
 ('maskServerFrames', False, 'WampWebSocketServerFactory'),
 ('perMessageCompressionAccept',
  <function set_websocket_options.<locals>.<lambda> at 0x7f3c082f60d0>,
  'WampWebSocketServerFactory'),
 ('serveFlashSocketPolicy', False, 'WampWebSocketServerFactory'),
 ('flashSocketPolicy',
  '<cross-domain-policy>\n'
  '     <allow-access-from domain="*" to-ports="*" />\n'
  '</cross-domain-policy>\x00',
  'WampWebSocketServerFactory'),
 ('allowedOrigins', ['*'], 'WampWebSocketServerFactory'),
 ('allowedOriginsPatterns', [re.compile('^.*$')], 'WampWebSocketServerFactory'),
 ('allowNullOrigin', True, 'WampWebSocketServerFactory'),
 ('maxConnections', 0, 'WampWebSocketServerFactory'),
 ('trustXForwardedFor', 0, 'WampWebSocketServerFactory')]
2018-03-13T10:24:37+0000 [Router         15 crossbar.router.protocol.WampWebSocketServerProtocol] connection accepted from peer tcp4:10.44.0.1:32878
2018-03-13T10:24:37+0000 [Router         15 crossbar.router.protocol.WampWebSocketServerProtocol] Connection made to tcp4:10.44.0.1:32878
2018-03-13T10:24:37+0000 [Router         15 crossbar.router.protocol.WampWebSocketServerProtocol] Connection to/from tcp4:10.44.0.1:32878 was lost in a non-clean fashion: Connection to the other side was lost in a non-clean fashion: Connection lost.
2018-03-13T10:24:37+0000 [Router         15 crossbar.router.protocol.WampWebSocketServerProtocol] _connectionLost: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionLost'>: Connection to the other side was lost in a non-clean fashion: Connection lost.
]
2018-03-13T10:24:39+0000 [Router         15 crossbar.router.protocol.WampWebSocketServerProtocol] 
[('logOctets', False, 'WampWebSocketServerFactory'),
 ('logFrames', False, 'WampWebSocketServerFactory'),
 ('trackTimings', False, 'WampWebSocketServerFactory'),
 ('utf8validateIncoming', True, 'WampWebSocketServerFactory'),
 ('applyMask', True, 'WampWebSocketServerFactory'),
 ('maxFramePayloadSize', 0, 'WampWebSocketServerFactory'),
 ('maxMessagePayloadSize', 0, 'WampWebSocketServerFactory'),
 ('autoFragmentSize', 0, 'WampWebSocketServerFactory'),
 ('failByDrop', False, 'WampWebSocketServerFactory'),
 ('echoCloseCodeReason', False, 'WampWebSocketServerFactory'),
 ('openHandshakeTimeout', 0.0, 'WampWebSocketServerFactory'),
 ('closeHandshakeTimeout', 0.0, 'WampWebSocketServerFactory'),
 ('tcpNoDelay', True, 'WampWebSocketServerFactory'),
 ('autoPingInterval', 0, 'WampWebSocketServerFactory'),
 ('autoPingTimeout', 0, 'WampWebSocketServerFactory'),
 ('autoPingSize', 4, 'WampWebSocketServerFactory'),
 ('versions', [8, 13], 'WampWebSocketServerFactory'),
 ('webStatus', True, 'WampWebSocketServerFactory'),
 ('requireMaskedClientFrames', True, 'WampWebSocketServerFactory'),
 ('maskServerFrames', False, 'WampWebSocketServerFactory'),
 ('perMessageCompressionAccept',
  <function set_websocket_options.<locals>.<lambda> at 0x7f3c082f60d0>,
  'WampWebSocketServerFactory'),
 ('serveFlashSocketPolicy', False, 'WampWebSocketServerFactory'),
 ('flashSocketPolicy',
  '<cross-domain-policy>\n'
  '     <allow-access-from domain="*" to-ports="*" />\n'
  '</cross-domain-policy>\x00',
  'WampWebSocketServerFactory'),
 ('allowedOrigins', ['*'], 'WampWebSocketServerFactory'),
 ('allowedOriginsPatterns', [re.compile('^.*$')], 'WampWebSocketServerFactory'),
 ('allowNullOrigin', True, 'WampWebSocketServerFactory'),
 ('maxConnections', 0, 'WampWebSocketServerFactory'),
 ('trustXForwardedFor', 0, 'WampWebSocketServerFactory')]
2018-03-13T10:24:39+0000 [Router         15 crossbar.router.protocol.WampWebSocketServerProtocol] connection accepted from peer tcp4:10.44.0.1:32898
2018-03-13T10:24:39+0000 [Router         15 crossbar.router.protocol.WampWebSocketServerProtocol] Connection made to tcp4:10.44.0.1:32898
2018-03-13T10:24:40+0000 [Router         15 crossbar.router.protocol.WampWebSocketServerProtocol] Connection to/from tcp4:10.44.0.1:32898 was lost in a non-clean fashion: Connection to the other side was lost in a non-clean fashion: Connection lost.
2018-03-13T10:24:40+0000 [Router         15 crossbar.router.protocol.WampWebSocketServerProtocol] _connectionLost: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionLost'>: Connection to the other side was lost in a non-clean fashion: Connection lost.
```

**Comment by sevaho** [comment]
Fixed it by adding:

```
"chain_certificates": [
       "./CA.crt",
],
```

This should be said more clearly in the docs imho.
