### ISSUE TITLE
Windows: 5 failing unit tests (Permission denied on filesystem)

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#1286]
**FAILED (skips=25, expectedFailures=3, errors=5, successes=259)**
---

```console
C:\Users\crossbar\scm\oberstet\crossbar>trial crossbar
crossbar.adapter.mqtt.test.test_events
  ConnectAckTests
    test_round_trip ...                                                    [OK]
  ConnectTests
    test_round_trip ...                                                    [OK]
  PubACKTests
    test_round_trip ...                                                    [OK]
  PublishTests
    test_round_trip ...                                                    [OK]
    test_round_trip_qos1 ...                                               [OK]
  SubACKTests
    test_round_trip ...                                                    [OK]
  SubscribeTests
    test_round_trip ...                                                    [OK]
  UnsubACKTests
    test_round_trip ...                                                    [OK]
  UnsubscribeTests
    test_round_trip ...                                                    [OK]
crossbar.adapter.mqtt.test.test_protocol
  MQTTConformanceTests
    test_connect_not_first ...                                             [OK]
    test_connect_reserved_area ...                                         [OK]
    test_invalid_utf8_continuation ...                                     [OK]
    test_invalid_utf8_null ...                                             [OK]
    test_multiple_connects ...                                             [OK]
    test_reserved_packet_0 ...                                             [OK]
    test_reserved_packet_15 ...                                            [OK]
    test_too_large_header ...                                              [OK]
    test_utf8_zwnbsp ...                                                   [OK]
  ProtocolTests
    test_connect_ping ...                                                  [OK]
    test_connect_subscribe_unsubscribe ...                                 [OK]
    test_correct_connect ...                                               [OK]
    test_malformed_packet ...                                              [OK]
    test_quirks_mode_connect ...                                           [OK]
crossbar.adapter.mqtt.test.test_topic
  MQTTTopicTests
    test_topic_filters_invalid ...                                         [OK]
    test_topic_filters_valid ...                                           [OK]
    test_topic_names_invalid ...                                           [OK]
    test_topic_names_valid ...                                             [OK]
crossbar.adapter.mqtt.test.test_tx
  ConnectHandlingTests
    test_exception_in_connect_drops_connection ...                         [OK]
    test_got_sent_packet ...                                               [OK]
  NonZeroConnACKWithCode1Tests
    test_non_zero_connect_code_must_have_no_present_session ...            [OK]
  NonZeroConnACKWithCode2Tests
    test_non_zero_connect_code_must_have_no_present_session ...            [OK]
  NonZeroConnACKWithCode3Tests
    test_non_zero_connect_code_must_have_no_present_session ...            [OK]
  NonZeroConnACKWithCode4Tests
    test_non_zero_connect_code_must_have_no_present_session ...            [OK]
  NonZeroConnACKWithCode5Tests
    test_non_zero_connect_code_must_have_no_present_session ...            [OK]
  PublishHandlingTests
    test_qos_0_failure_drops_connection ...                                [OK]
    test_qos_0_sends_no_ack ...                                            [OK]
    test_qos_1_failure_drops_connection ...                                [OK]
    test_qos_1_sends_ack ...                                               [OK]
    test_qos_2_failure_drops_connection ...                                [OK]
    test_qos_2_sends_ack ...                                               [OK]
  SendPublishTests
    test_non_allowed_qos_not_queued ...                                    [OK]
    test_qos_0_queues_message ...                                          [OK]
    test_qos_1_queues_message ...                                          [OK]
    test_qos_1_resent_on_disconnect ...                                  [TODO]
    test_qos_2_queues_message ...                                          [OK]
    test_qos_2_resent_on_disconnect_pubcomp ...                          [TODO]
    test_qos_2_resent_on_disconnect_pubrel ...                           [TODO]
  SubscribeHandlingTests
    test_exception_in_subscribe_drops_connection ...                       [OK]
  TwistedProtocolLoggingTests
    test_recv_packet ...                                                   [OK]
    test_send_packet ...                                                   [OK]
  TwistedProtocolTests
    test_keepalive ...                                                     [OK]
    test_keepalive_canceled_on_lost_connection ...                         [OK]
    test_keepalive_full_packet_resets_timeout ...                          [OK]
    test_keepalive_requires_full_packet ...                                [OK]
    test_lose_conn_on_protocol_violation ...                               [OK]
    test_lose_conn_on_reserved_qos3 ...                                    [OK]
    test_lose_conn_on_unimplemented_packet ...                             [OK]
    test_packet_id_is_sixteen_bit ...                                      [OK]
    test_transport_paused_while_processing ...                             [OK]
    test_unknown_connect_code_must_lose_connection ...                     [OK]
  UnsubscribeHandlingTests
    test_exception_in_connect_drops_connection ...                         [OK]
    test_unsubscription_gets_unsuback_with_same_id ...                     [OK]
crossbar.adapter.mqtt.test.test_wamp
  MQTTAdapterTests
    test_tls_auth_denied ...                                               [OK]
crossbar.adapter.rest.test.test_callee
  CalleeTestCase
    test_basic_web ...                                                     [OK]
    test_slightlymorecomplex_web ...                                       [OK]
crossbar.adapter.rest.test.test_caller
  CallerTestCase
    test_add2 ...                                                          [OK]
    test_cb_failure ...                                                    [OK]
    test_failure ...                                                       [OK]
    test_no_body ...                                                       [OK]
    test_no_procedure ...                                                  [OK]
crossbar.adapter.rest.test.test_common
  IPWhitelistingTestCase
    test_allowed_IP ...                                                    [OK]
    test_allowed_IP_range ...                                              [OK]
    test_disallowed_IP_range ...                                           [OK]
  RequestBodyTestCase
    test_ASCII_denied ...                                                  [OK]
    test_JSON_list_body ...                                                [OK]
    test_UTF8_assumption ...                                               [OK]
    test_allow_caps_in_content_type ...                                    [OK]
    test_allow_charset_in_content_type ...                                 [OK]
    test_bad_content_type ...                                              [OK]
    test_bad_method ...                                                    [OK]
    test_broken_contenttype ...                                            [OK]
    test_decodes_UTF8 ...                                                  [OK]
    test_invalid_JSON_body ...                                             [OK]
    test_multiple_content_length ...                                       [OK]
    test_not_matching_bodylength ...                                       [OK]
    test_too_large_body ...                                                [OK]
    test_undecodable_UTF8 ...                                              [OK]
    test_unknown_encoding ...                                              [OK]
  SecureTransportTestCase
    test_not_required_tls_with_tls ...                                     [OK]
    test_required_tls_with_tls ...                                         [OK]
    test_required_tls_without_tls ...                                      [OK]
crossbar.adapter.rest.test.test_publisher
  PublisherTestCase
    test_basic_publish ...                                                 [OK]
    test_publish_cberror ...                                               [OK]
    test_publish_error ...                                                 [OK]
    test_publish_needs_topic ...                                           [OK]
crossbar.adapter.rest.test.test_signature
  SignatureTestCase
    test_good_signature ...                                                [OK]
    test_incorrect_secret ...                                              [OK]
    test_invalid_nonce ...                                                 [OK]
    test_no_key ...                                                        [OK]
    test_no_nonce ...                                                      [OK]
    test_no_seq ...                                                        [OK]
    test_no_signature ...                                                  [OK]
    test_no_timestamp ...                                                  [OK]
    test_outdated_delta ...                                                [OK]
    test_unknown_key ...                                                   [OK]
    test_wrong_seq ...                                                     [OK]
    test_wrong_timestamp ...                                               [OK]
crossbar.adapter.rest.test.test_subscriber
  MessageForwarderTestCase
    test_basic_web ...                                                     [OK]
crossbar.adapter.rest.test.test_webhook
  WebhookTestCase
    test_basic ...                                                         [OK]
crossbar.controller.test.test_cleanup
  CleanupHandler
    test_kill_after_term ...                                               [OK]
crossbar.controller.test.test_cli
  ConvertTests
    test_invalid_json_to_yaml ...                                     [SKIPPED]
    test_invalid_yaml_to_json ...                                     [SKIPPED]
    test_json_to_yaml ...                                             [SKIPPED]
    test_unknown_format ...                                           [SKIPPED]
    test_yaml_to_json ...                                             [SKIPPED]
  StartTests
    test_configValidationFailure ...                                  [SKIPPED]
    test_fileLogging ...                                              [SKIPPED]
    test_stalePID ...                                                 [SKIPPED]
    test_start ...                                                    [SKIPPED]
  VersionTests
    test_basic ...                                                    [SKIPPED]
    test_debug ...                                                    [SKIPPED]
crossbar.router.test.test_authorize
  TestDynamicAuth
    test_authextra_anonymous ...                                           [OK]
    test_authextra_ticket ...                                              [OK]
    test_authextra_tls ...                                                 [OK]
    test_authextra_wampcra ...                                             [OK]
    test_authextra_wampcryptosign ...                                      [OK]
  TestRouterRoleStaticAuth
    test_ruleset_1 ...                                                     [OK]
    test_ruleset_2 ...                                                     [OK]
    test_ruleset_empty ...                                                 [OK]
  TestRouterRoleStaticAuthWild
    test_exact_before_wildcard ...                                         [OK]
    test_prefix ...                                                        [OK]
    test_wildcard_before_prefix ...                                        [OK]
crossbar.router.test.test_broker
  TestBrokerPublish
    test_add ...                                                           [OK]
    test_add_and_subscribe ...                                             [OK]
    test_application_session_internal_error ...                            [OK]
    test_publish_closed_session ...                                        [OK]
    test_publish_traced_events ...                                         [OK]
    test_publish_traced_events_batched ...                                 [OK]
    test_router_session_goodbye_custom_message ...                         [OK]
    test_router_session_goodbye_fire_disconnect_error ...                  [OK]
    test_router_session_goodbye_onLeave_error ...                          [OK]
    test_router_session_internal_error_onAuthenticate ...                  [OK]
    test_router_session_internal_error_onHello ...                         [OK]
    test_router_session_lifecycle ...                                      [OK]
  TestRouterSession
    test_onleave_publish ...                                               [OK]
    test_wamp_session_on_leave ...                                         [OK]
crossbar.router.test.test_cookiestore
  TestCookieStore
    test_purge_on_startup ...                                           [ERROR]
    test_purge_on_startup_default_is_false ...                          [ERROR]
    test_purge_on_startup_delete_expired_cookies ...                    [ERROR]
crossbar.router.test.test_dealer
  TestDealer
    test_call_cancel ...                                                   [OK]
    test_call_cancel_two_sessions ...                                      [OK]
    test_call_cancel_without_callee_support ...                            [OK]
    test_caller_detach_interrupt_cancel_not_supported ...                  [OK]
    test_caller_detach_interrupt_cancel_supported ...                      [OK]
    test_concurrency_with_error ...                                        [OK]
    test_force_reregister_kick ...                                         [OK]
    test_outstanding_invoke ...                                            [OK]
    test_outstanding_invoke_but_caller_gone ...                            [OK]
    test_yield_on_unowned_invocation ...                                   [OK]
crossbar.router.test.test_metering
  TestLmdb
    test_insert ...                                                     [ERROR]
    test_iterate_from ...                                               [ERROR]
crossbar.router.test.test_observation
  TestObservation
    test_create_exact ...                                                  [OK]
    test_create_prefix ...                                                 [OK]
    test_create_wildcard ...                                               [OK]
  TestUriObservationMap
    test_add_observer ...                                                  [OK]
    test_add_observer_is_first_observer ...                                [OK]
    test_add_observer_was_already_observed ...                             [OK]
    test_delete_observer ...                                               [OK]
    test_match_observations_empty ...                                      [OK]
    test_match_observations_match_exact ...                                [OK]
    test_match_observations_match_exact_multi ...                          [OK]
    test_match_observations_match_exact_same ...                           [OK]
    test_match_observations_match_multimode ...                            [OK]
    test_match_observations_match_prefix ...                               [OK]
    test_match_observations_match_wildcard_multi ...                       [OK]
    test_match_observations_match_wildcard_single ...                      [OK]
crossbar.router.test.test_pytrie
  TestPyTrie
    test_contains ...                                                      [OK]
    test_empty_tree ...                                                    [OK]
    test_longest_prefix_1 ...                                              [OK]
    test_longest_prefix_2 ...                                              [OK]
    test_longest_prefix_3 ...                                              [OK]
    test_longest_prefix_4 ...                                         [SKIPPED]
crossbar.router.test.test_router
  TestEmbeddedSessions
    test_add ...                                                           [OK]
    test_add_and_subscribe ...                                             [OK]
    test_application_session_internal_error ...                            [OK]
    test_authorize_exception_call ...                                 [SKIPPED]
    test_authorize_exception_register ...                             [SKIPPED]
    test_router_session_internal_error_onAuthenticate ...                  [OK]
    test_router_session_internal_error_onHello ...                         [OK]
crossbar.router.test.test_testament
  TestamentTests
    test_add_testament_needs_valid_scope ...                               [OK]
    test_destroy_testament_not_sent_when_cleared ...                       [OK]
    test_destroy_testament_sent_on_destroy ...                             [OK]
    test_flush_testament_needs_valid_scope ...                             [OK]
    test_one_scope_does_not_affect_other ...                               [OK]
crossbar.router.test.test_unisocket
  UniSocketTests
    test_invalid_status_line ...                                           [OK]
    test_mqtt_with_factory ...                                             [OK]
    test_mqtt_with_no_factory ...                                          [OK]
    test_rawsocket_with_factory ...                                        [OK]
    test_rawsocket_with_no_factory ...                                     [OK]
    test_web_with_factory ...                                              [OK]
    test_web_with_no_factory ...                                           [OK]
    test_websocket_with_map ...                                            [OK]
    test_websocket_with_no_map ...                                         [OK]
crossbar.router.test.test_wildcard
  TestWildcardMatcher
    test_contains ...                                                      [OK]
    test_delitem ...                                                       [OK]
    test_get ...                                                           [OK]
    test_getitem ...                                                       [OK]
    test_iter_matches ...                                                  [OK]
    test_setitem ...                                                       [OK]
  TestWildcardTrieMatcher
    test_contains ...                                                      [OK]
    test_delitem ...                                                       [OK]
    test_get ...                                                           [OK]
    test_getitem ...                                                       [OK]
    test_iter_matches ...                                                  [OK]
    test_setitem ...                                                       [OK]
crossbar.test.test_checkconfig
  CheckContainerTests
    test_extraKeys ...                                                     [OK]
    test_requiredKeys ...                                                  [OK]
    test_validTemplate_hello ...                                           [OK]
  CheckDictArgsTests
    test_notDict ...                                                       [OK]
    test_sequence_list ...                                                 [OK]
    test_sequence_string ...                                               [OK]
    test_wrongType ...                                                     [OK]
  CheckEndpointTests
    test_twisted_client_error ...                                          [OK]
    test_twisted_client_missing_arg ...                                    [OK]
    test_twisted_server_error ...                                          [OK]
    test_twisted_server_missing_arg ...                                    [OK]
  CheckOnion
    test_port_wrong_type ...                                               [OK]
    test_success ...                                                       [OK]
    test_unknown_attr ...                                                  [OK]
  CheckRealmTests
    test_dynamic_authorizer ...                                            [OK]
    test_static_permissions ...                                            [OK]
    test_static_permissions_and_authorizer ...                             [OK]
    test_static_permissions_invalid_uri ...                                [OK]
    test_static_permissions_isnt_list ...                                  [OK]
    test_static_permissions_lacks_uri ...                                  [OK]
    test_static_permissions_not_dict ...                                   [OK]
    test_static_permissions_uri_not_a_string ...                           [OK]
  CheckWebsocketTests
    test_tiny_timeout_auto_ping ...                                        [OK]
crossbar.test.test_compat
  NativeStringTestCase
    test_bytes_always_native ...                                           [OK]
    test_unicode_not_allowed ...                                           [OK]
crossbar.test.test_logger
  CrossbarLoggerTests
    test_disallow_direct_instantiation ...                                 [OK]
    test_logger_emits ...                                                  [OK]
    test_logger_emits_if_higher ...                                        [OK]
    test_logger_failure ...                                                [OK]
    test_logger_failure_not_called ...                                     [OK]
    test_logger_namespace_classdef ...                                     [OK]
    test_logger_namespace_function ...                                     [OK]
    test_logger_namespace_init ...                                         [OK]
    test_logger_namespace_moduledef ...                                    [OK]
    test_set_level ...                                                     [OK]
  JSONObserverTests
    test_basic ...                                                         [OK]
    test_failure ...                                                       [OK]
    test_not_json_serialisable ...                                         [OK]
    test_raising_during_encoding ...                                       [OK]
    test_repr_formatting ...                                               [OK]
    test_unicode_logs ...                                                  [OK]
  LogCapturerTests
    test_capturer ...                                                      [OK]
  LoggerModuleTests
    test_set_global ...                                                    [OK]
    test_set_global_changes_loggers ...                                    [OK]
    test_set_global_does_not_change_explicit_loggers ...                   [OK]
  StderrObserverTests
    test_basic ...                                                         [OK]
    test_format_failure ...                                                [OK]
    test_format_log_category ...                                           [OK]
    test_output_standard ...                                               [OK]
    test_output_syslogd ...                                                [OK]
  StdoutObserverTests
    test_basic ...                                                         [OK]
    test_format_log_category ...                                           [OK]
    test_output_standard ...                                               [OK]
    test_output_syslogd ...                                                [OK]
crossbar.twisted.test.test_endpoint
  ListeningEndpointTests
    test_twisted_client ...                                                [OK]
    test_twisted_server ...                                                [OK]
    test_unix ...                                                     [SKIPPED]
    test_unix_already_listening ...                                   [SKIPPED]
    test_unix_already_listening_cant_delete ...                       [SKIPPED]
crossbar.twisted.test.test_fileupload
  FileUploadTests
    test_basic ...                                                         [OK]
    test_multichunk ...                                                    [OK]
    test_multichunk_shuffle ...                                            [OK]
    test_remains_cleanup ...                                               [OK]
    test_resumed_upload ...                                                [OK]
crossbar.worker.test.test_loader
  AppSessionLoaderTests
    test_class_importerror ...                                             [OK]
    test_class_non_applicationsession ...                                  [OK]
    test_class_standard ...                                                [OK]
    test_class_syntaxerror ...                                             [OK]
    test_unknown_types ...                                                 [OK]
crossbar.worker.test.test_router
  RouterWorkerSessionTests
    test_basic ...                                                    [SKIPPED]
    test_start_router_component ...                                   [SKIPPED]
    test_start_router_component_fails ...                             [SKIPPED]
    test_start_router_component_invalid_type ...                      [SKIPPED]
    test_start_router_component_wrong_baseclass ...                   [SKIPPED]
  WSGITests
    test_basic ...                                                    [SKIPPED]
    test_basic_subresources ...                                       [SKIPPED]
  WebTests
    test_root_not_required ...                                        [SKIPPED]

===============================================================================
[SKIPPED]
True

crossbar.controller.test.test_cli.ConvertTests.test_invalid_json_to_yaml
crossbar.controller.test.test_cli.ConvertTests.test_invalid_yaml_to_json
crossbar.controller.test.test_cli.ConvertTests.test_json_to_yaml
crossbar.controller.test.test_cli.ConvertTests.test_unknown_format
crossbar.controller.test.test_cli.ConvertTests.test_yaml_to_json
crossbar.controller.test.test_cli.StartTests.test_configValidationFailure
crossbar.controller.test.test_cli.StartTests.test_fileLogging
crossbar.controller.test.test_cli.StartTests.test_stalePID
crossbar.controller.test.test_cli.StartTests.test_start
crossbar.controller.test.test_cli.VersionTests.test_basic
crossbar.controller.test.test_cli.VersionTests.test_debug
crossbar.router.test.test_pytrie.TestPyTrie.test_longest_prefix_4
crossbar.worker.test.test_router.RouterWorkerSessionTests.test_basic
crossbar.worker.test.test_router.RouterWorkerSessionTests.test_start_router_component
crossbar.worker.test.test_router.RouterWorkerSessionTests.test_start_router_component_fails
crossbar.worker.test.test_router.RouterWorkerSessionTests.test_start_router_component_invalid_type
crossbar.worker.test.test_router.RouterWorkerSessionTests.test_start_router_component_wrong_baseclass
crossbar.worker.test.test_router.WSGITests.test_basic
crossbar.worker.test.test_router.WSGITests.test_basic_subresources
crossbar.worker.test.test_router.WebTests.test_root_not_required
===============================================================================
[SKIPPED]
FIXME: the mock may be wrong here ..

crossbar.router.test.test_router.TestEmbeddedSessions.test_authorize_exception_call
crossbar.router.test.test_router.TestEmbeddedSessions.test_authorize_exception_register
===============================================================================
[SKIPPED]
Windows does not have UNIX sockets

crossbar.twisted.test.test_endpoint.ListeningEndpointTests.test_unix
crossbar.twisted.test.test_endpoint.ListeningEndpointTests.test_unix_already_listening
crossbar.twisted.test.test_endpoint.ListeningEndpointTests.test_unix_already_listening_cant_delete
===============================================================================
[TODO]
Reason: 'Needs WAMP-level implementation first, and the WAMP router to resend ACKs/messages'
Traceback (most recent call last):
  File "c:\users\crossbar\scm\oberstet\crossbar\crossbar\adapter\mqtt\test\test_tx.py", line 1163, in test_qos_1_resent_
on_disconnect
    self.assertEqual(len(events), 2)
  File "c:\users\crossbar\appdata\local\programs\python\python36\lib\site-packages\twisted\trial\_synctest.py", line 432
, in assertEqual
    super(_Assertions, self).assertEqual(first, second, msg)
  File "c:\users\crossbar\appdata\local\programs\python\python36\lib\unittest\case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "c:\users\crossbar\appdata\local\programs\python\python36\lib\unittest\case.py", line 822, in _baseAssertEqual
    raise self.failureException(msg)
twisted.trial.unittest.FailTest: 1 != 2

crossbar.adapter.mqtt.test.test_tx.SendPublishTests.test_qos_1_resent_on_disconnect
===============================================================================
[TODO]
Reason: 'Needs WAMP-level implementation first, and the WAMP router to resend ACKs/messages'
Traceback (most recent call last):
  File "c:\users\crossbar\scm\oberstet\crossbar\crossbar\adapter\mqtt\test\test_tx.py", line 1343, in test_qos_2_resent_
on_disconnect_pubcomp
    self.assertEqual(len(events), 2)
  File "c:\users\crossbar\appdata\local\programs\python\python36\lib\site-packages\twisted\trial\_synctest.py", line 432
, in assertEqual
    super(_Assertions, self).assertEqual(first, second, msg)
  File "c:\users\crossbar\appdata\local\programs\python\python36\lib\unittest\case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "c:\users\crossbar\appdata\local\programs\python\python36\lib\unittest\case.py", line 822, in _baseAssertEqual
    raise self.failureException(msg)
twisted.trial.unittest.FailTest: 1 != 2

crossbar.adapter.mqtt.test.test_tx.SendPublishTests.test_qos_2_resent_on_disconnect_pubcomp
===============================================================================
[TODO]
Reason: 'Needs WAMP-level implementation first, and the WAMP router to resend ACKs/messages'
Traceback (most recent call last):
  File "c:\users\crossbar\scm\oberstet\crossbar\crossbar\adapter\mqtt\test\test_tx.py", line 1241, in test_qos_2_resent_
on_disconnect_pubrel
    self.assertEqual(len(events), 2)
  File "c:\users\crossbar\appdata\local\programs\python\python36\lib\site-packages\twisted\trial\_synctest.py", line 432
, in assertEqual
    super(_Assertions, self).assertEqual(first, second, msg)
  File "c:\users\crossbar\appdata\local\programs\python\python36\lib\unittest\case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "c:\users\crossbar\appdata\local\programs\python\python36\lib\unittest\case.py", line 822, in _baseAssertEqual
    raise self.failureException(msg)
twisted.trial.unittest.FailTest: 1 != 2

crossbar.adapter.mqtt.test.test_tx.SendPublishTests.test_qos_2_resent_on_disconnect_pubrel
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "c:\users\crossbar\appdata\local\programs\python\python36\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "c:\users\crossbar\appdata\local\programs\python\python36\lib\unittest\case.py", line 605, in run
    testMethod()
  File "c:\users\crossbar\scm\oberstet\crossbar\crossbar\router\test\test_cookiestore.py", line 94, in test_purge_on_sta
rtup
    CookieStoreFileBacked(fp.name, config)
  File "c:\users\crossbar\scm\oberstet\crossbar\crossbar\router\cookiestore.py", line 240, in __init__
    self._cookie_file = open(self._cookie_file_name, 'a')
builtins.PermissionError: [Errno 13] Permission denied: 'C:\\Users\\crossbar\\AppData\\Local\\Temp\\tmp6_2xnxae'

crossbar.router.test.test_cookiestore.TestCookieStore.test_purge_on_startup
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "c:\users\crossbar\appdata\local\programs\python\python36\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "c:\users\crossbar\appdata\local\programs\python\python36\lib\unittest\case.py", line 605, in run
    testMethod()
  File "c:\users\crossbar\scm\oberstet\crossbar\crossbar\router\test\test_cookiestore.py", line 144, in test_purge_on_st
artup_default_is_false
    CookieStoreFileBacked(fp.name, config)
  File "c:\users\crossbar\scm\oberstet\crossbar\crossbar\router\cookiestore.py", line 240, in __init__
    self._cookie_file = open(self._cookie_file_name, 'a')
builtins.PermissionError: [Errno 13] Permission denied: 'C:\\Users\\crossbar\\AppData\\Local\\Temp\\tmppss8xq7q'

crossbar.router.test.test_cookiestore.TestCookieStore.test_purge_on_startup_default_is_false
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "c:\users\crossbar\appdata\local\programs\python\python36\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "c:\users\crossbar\appdata\local\programs\python\python36\lib\unittest\case.py", line 605, in run
    testMethod()
  File "c:\users\crossbar\scm\oberstet\crossbar\crossbar\router\test\test_cookiestore.py", line 213, in test_purge_on_st
artup_delete_expired_cookies
    CookieStoreFileBacked(fp.name, config)
  File "c:\users\crossbar\scm\oberstet\crossbar\crossbar\router\cookiestore.py", line 240, in __init__
    self._cookie_file = open(self._cookie_file_name, 'a')
builtins.PermissionError: [Errno 13] Permission denied: 'C:\\Users\\crossbar\\AppData\\Local\\Temp\\tmpy99lquok'

crossbar.router.test.test_cookiestore.TestCookieStore.test_purge_on_startup_delete_expired_cookies
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "c:\users\crossbar\appdata\local\programs\python\python36\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "c:\users\crossbar\appdata\local\programs\python\python36\lib\unittest\case.py", line 646, in doCleanups
    function(*args, **kwargs)
  File "c:\users\crossbar\scm\oberstet\crossbar\crossbar\router\test\test_metering.py", line 44, in _scratch
    shutil.rmtree(self.DBFILE)
  File "c:\users\crossbar\appdata\local\programs\python\python36\lib\shutil.py", line 494, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "c:\users\crossbar\appdata\local\programs\python\python36\lib\shutil.py", line 389, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "c:\users\crossbar\appdata\local\programs\python\python36\lib\shutil.py", line 387, in _rmtree_unsafe
    os.unlink(fullname)
builtins.PermissionError: [WinError 32] Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess
 verwendet wird: 'test.dat\\data.mdb'

crossbar.router.test.test_metering.TestLmdb.test_insert
crossbar.router.test.test_metering.TestLmdb.test_iterate_from
-------------------------------------------------------------------------------
Ran 292 tests in 5.047s

FAILED (skips=25, expectedFailures=3, errors=5, successes=259)

C:\Users\crossbar\scm\oberstet\crossbar>
```

**Comment by oberstet** [comment]
windows CI was long removed
