### ISSUE TITLE
Improve examples CI

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#1301]
https://travis-ci.org/crossbario/crossbar/jobs/372635742

```
Running example: ./asyncio/wamp/overview
--------------------------------------------------------------------------------
  starting backend
 backend: Traceback (most recent call last):
 backend:   File "./asyncio/wamp/overview/backend.py", line 28, in <module>
 backend:     runner.run(Component)
 backend: NameError: name 'Component' is not defined
  starting frontend
frontend: Traceback (most recent call last):
frontend:   File "./asyncio/wamp/overview/frontend.py", line 24, in <module>
frontend:     runner.run(Component)
frontend: NameError: name 'Component' is not defined
FAILED: Process exited with code "1".
FAILED: Process exited with code "1".
Killing crossbar
___________________________________ summary ____________________________________
  py36-examples: commands succeeded
  congratulations :)
The command "tox -c tox.ini -e $TOX_ENV" exited with 0.
cache.2
store build cache
0.00s
3.81schange detected (content changed, file is created, or file is deleted):
/home/travis/.cache/pip/http/0/4/e/0/1/04e017851dbfe81db92d092eaaf2526622c3950bcb8f2696e57143da
/home/travis/.cache/pip/http/1/7/5/8/3/17583166344f97bb6a065f46ba672653d1a754d61b31808b9ff525fc
/home/travis/.cache/pip/wheels/d9/53/7e/fbb2a813aaf8b200b663dbc39d03daee9abbbdbabbdc0f3e12/crossbar-18.5.1-py2.py3-none-any.whl
changes detected, packing new archive
uploading archive
after_success
0.41s$ codecov
      _____          _
     / ____|        | |
    | |     ___   __| | ___  ___ _____   __
    | |    / _ \ / _  |/ _ \/ __/ _ \ \ / /
    | |___| (_) | (_| |  __/ (_| (_) \ V /
     \_____\___/ \____|\___|\___\___/ \_/
                                    v2.0.15
==> Detecting CI provider
    Travis Detected
    Fixing merge commit SHA
==> Preparing upload
==> Processing gcov (disable by -X gcov)
    Executing gcov (find /home/travis/build/crossbario/crossbar -not -path './bower_components/**' -not -path './node_modules/**' -not -path './vendor/**' -type f -name '*.gcno'  -exec gcov -pb  {} +)
==> Collecting reports
Error: No coverage report found
Tip: See an example python repo: https://github.com/codecov/example-python
Support channels:
  Email:   hello@codecov.io
  IRC:     #codecov
  Gitter:  https://gitter.im/codecov/support
  Twitter: @codecov
Done. Your build exited with 0.
```

**Comment by oberstet** [comment]
fixed: all Autobahn WAMP examples are run regularily in the CI:

* https://github.com/crossbario/crossbar/blob/ecc8b4e0d9f8fa3efa7d59755cb2e16151055870/.github/workflows/main.yml#L176
* https://github.com/crossbario/crossbar/runs/5732014055?check_suite_focus=true
