### ISSUE TITLE
Install fails on shutil.which (OSX, CPython 2.7)

### ISSUE THREAD

**Issue by MueR** [crossbario/crossbar#1327]
Followed the steps on [this page](https://crossbar.io/docs/Installation-on-Mac-OS-X/#installing-crossbar.io), crossbar won't start.

```
(python-venv) Bass-MacBook-Pro:python-venv bas$ crossbar version
Traceback (most recent call last):
  File "/Users/bas/python-venv/bin/crossbar", line 11, in <module>
    sys.exit(run())
  File "/Users/bas/python-venv/lib/python2.7/site-packages/crossbar/__init__.py", line 164, in run
    from crossbar.node.main import main
  File "/Users/bas/python-venv/lib/python2.7/site-packages/crossbar/node/main.py", line 70, in <module>
    from crossbar.worker import main as worker_main
  File "/Users/bas/python-venv/lib/python2.7/site-packages/crossbar/worker/main.py", line 46, in <module>
    _INSTALLED_PERSONALITIES = crossbar.personalities()
  File "/Users/bas/python-venv/lib/python2.7/site-packages/crossbar/__init__.py", line 174, in personalities
    from crossbar.personality import Personality as StandalonePersonality
  File "/Users/bas/python-venv/lib/python2.7/site-packages/crossbar/personality.py", line 43, in <module>
    from crossbar.node import node
  File "/Users/bas/python-venv/lib/python2.7/site-packages/crossbar/node/node.py", line 52, in <module>
    from crossbar.node.controller import NodeController
  File "/Users/bas/python-venv/lib/python2.7/site-packages/crossbar/node/controller.py", line 38, in <module>
    from shutil import which
ImportError: cannot import name which
```

According to the [2.7 documentation](https://docs.python.org/2/library/shutil.html), `shutil` does not have `which`, that is only available in [Python 3.5+](https://docs.python.org/3.5/library/shutil.html).

**Comment by oberstet** [comment]
we don't support python 2 (any longer): https://github.com/crossbario/crossbar/blob/master/setup.py#L118
