### ISSUE TITLE
Run CI on MacOS - and make it work

### ISSUE THREAD

**Issue by solomn1991** [crossbario/crossbar#1333]
the full stack  just like this below
Could not start node: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/base.py", line 441, in _continueFiring
    callable(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/crossbar/node/main.py", line 744, in start_crossbar
    d = node.start()
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1532, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python3.6/site-packages/crossbar/node/node.py", line 314, in start
    self._router_session_factory.add(self._controller, authrole=u'trusted')
  File "/usr/local/lib/python3.6/site-packages/crossbar/router/session.py", line 855, in add
    self._app_sessions[session] = RouterApplicationSession(session, self._routerFactory, authid, authrole)
  File "/usr/local/lib/python3.6/site-packages/crossbar/router/session.py", line 110, in __init__
    self._session.onConnect()
  File "/usr/local/lib/python3.6/site-packages/crossbar/node/controller.py", line 121, in onConnect
    NativeProcess.onConnect(self, False)
  File "/usr/local/lib/python3.6/site-packages/crossbar/common/process.py", line 214, in onConnect
    self._pinfo = ProcessInfo()
  File "/usr/local/lib/python3.6/site-packages/crossbar/common/processinfo.py", line 181, in __init__
    self._cpus = sorted(self._p.cpu_affinity())
builtins.AttributeError: 'Process' object has no attribute 'cpu_affinity'

can you help me about this problem?

**Comment by meejah** [comment]
Can you tell us how you installed the software and the output of "crossbar version"?

An alternative is to use a Docker image: https://crossbar.io/docs/Using-Docker/

**Comment by solomn1991** [comment]
by pip3

**Comment by solomn1991** [comment]
the version is v18.5.2

**Comment by solomn1991** [comment]
Though docker is a convenient way for deploy,I'm not familar with it ,and it's not convient for modify and developing

**Comment by meejah** [comment]
Did you use a virtualenv? It looks like maybe system-wide? How did you install Python?

What does this do in your environment? `python -c "import psutil, os; print(psutil.Process(os.getpid()).cpu_affinity())"`

**Comment by harpo1224** [comment]
I've gotten this error on several osx machines lately, on previous crossbar installations and fresh machines (installing via pip). According to [this stackoverflow post](https://stackoverflow.com/questions/42658331/python-3-on-macos-how-to-set-process-affinity), which cites apple's thread affinity api:

"OS X does not export interfaces that identify processors or control thread placement—explicit thread to processor binding is not supported."

Commenting the offending line works fine, and doesn't seem to break anything else.

**Comment by meejah** [comment]
From the stack trace, this seems like probably a "psutil" library issue -- in any case, crossbar isn't using this to do cpu-affinity things, but we certainly are using `ProcessInfo` for some functionality. You could try un-installing ``psutil`` for now, as we are switching all such functionality around "is psutil installed or not"...

**Comment by jaimewyant** [comment]
This isn't an issue with psutil.  

The cpu_affinity method simply is not available on the mac version of psutil.  Would it be OK to just detect the availabilty of this and provide reasonable defaults (for Mac there is no cpu affinity -- only thread affinity)?

From the docs:

> Availability: Linux, Windows, FreeBSD

**Comment by meejah** [comment]
Hmmm, okay I see. That's .. too bad since we're not really using this to set cpu-affinity but just to enumerate CPUs. The docs also use this very line of code as an example of how to list CPUs that this process could be on :/

Is there some other way in psutil to do this? I guess we could catch the AttributeError and use cpu_count() or whatever ...?

**Comment by jaimewyant** [comment]
That seems reasonable to me.  I've hacked my local copy to do that.

**Comment by oberstet** [comment]
crossbar supports macos via our docker images. we don't have a CI for macos, so any macos issue will always be guesswork on our side. and I cannot change code that I cannot test .. so any macos hack/workaround puts guesswork on me without gain.

**Comment by liho26** [comment]
Hi. I have the same error. **'Process' object has no attribute 'cpu_affinity'** How to rub crossbar?

**Comment by jaimewyant** [comment]
@liho26 I forked crossbar patching it up so it runs on my mac.  YMMV, but it works for me :)

https://github.com/jaimewyant/crossbar

**Comment by jb137** [comment]
I indeed noticed the cpu info isn't used but unstalling psutil does not provide a solution:
`crossbar/node/worker.py", line 47, in <module>
    from crossbar.common.processinfo import ProcessInfo
ImportError: cannot import name 'ProcessInfo'
`
The worker.py expects ProcessInfo. The switch to see if psutil is installed does not seem to achieve its intended purpose if the application does not start without it (ProcessInfo is only defined when psutil is available).

> crossbar supports macos via our docker images. we don't have a CI for macos, so any macos issue will always be guesswork on our side. and I cannot change code that I cannot test .. so any macos hack/workaround puts guesswork on me without gain.

I am not sure yet that inserting docker in my work flow will improve the development process. But please don't - without a guess (psutil states it only works on Linux/Windows/FreeBSD) - kill off macos compatibility for listing the cpu's when this isn't used anywhere in the application for critical stuff. Please make a switch for non-Linux/Windows/FreeBSD, use cpu_count or none.

**Comment by kneufeld** [comment]
Can confirm that @Alexeyisme suggestion `self._cpus = os.cpu_count()` fixes problem on OSX 10.12.6

**Comment by jb137** [comment]
This isn't really the same. Cpu_affinity is the number of cores a process may use. This is not alway equal to the number of cores installed. However. The number isn't critical for Crossbar as far as I an tell. So please please, replace, remove or implement it conditionally.

And what is needed for the devs to make MacOS an officially supported machine?

**Comment by jb137** [comment]
Cpu_affinity returns a list where os.cpu_count returns a single number. On top of that cpu_affinity is also used in process.py line 294 and 328. Those have been in there since at least 2016... The problem seems a bit more complex.

**Comment by noisyboiler** [comment]
this is a real problem for me. I develop software on Macs against Crossbar. For WAMP and Crossbar to be a success all users need to be considered. I am now forced to stick with older versions whilst this is addressed.

**Comment by oberstet** [comment]
@noisyboiler ok, I get it;) I guess we can make it work with not a lot of effort - the main problem is: we need to be able to test this, and a couple of the core developers (incl. myself) do not use apple products. hence: we need to run the CI on macos : https://docs.travis-ci.com/user/reference/osx

**Comment by jb137** [comment]
Do you need a Mac or someone running CI on a Mac? And is this process fully automated?

**Comment by noisyboiler** [comment]
I'm happy to help on this one. contact me directly if you'd like my help.

**Comment by oberstet** [comment]
ok, I give `multiprocessing.cpu_count()` a  shot, since:

```
oberstet@intel-nuci7:~/scm/crossbario/crossbar$ python
Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.cpu_count()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'cpu_count'
>>> import multiprocessing
>>> multiprocessing.cpu_count()
8
>>> 
```

**Comment by noisyboiler** [comment]
many thanks, @oberstet

**Comment by billtubbs** [comment]
I see this issue is closed but I still get this error.  Was it not solved in latest release?
