### ISSUE TITLE
Cant run crossbar on Windows 10 (home edition) with 32-bit python 2.7.15

### ISSUE THREAD

**Issue by ilovetogetspamed** [crossbario/crossbar#1342]
```
Microsoft Windows [Version 10.0.17134.48]
(c) 2018 Microsoft Corporation. All rights reserved.

(venv) C:\Users\********\Documents\GitHub\flask-twisted-serial>crossbar start
2018-05-31T15:14:59-0400 [Controller   3216] File permissions on node public key fixed!
2018-05-31T15:14:59-0400 [Controller   3216] File permissions on node private key fixed!
2018-05-31T15:14:59-0400 [Controller   3216]      __  __  __  __  __  __      __     __
2018-05-31T15:14:59-0400 [Controller   3216]     /  `|__)/  \/__`/__`|__) /\ |__)  |/  \
2018-05-31T15:14:59-0400 [Controller   3216]     \__,|  \\__/.__/.__/|__)/~~\|  \. |\__/
2018-05-31T15:14:59-0400 [Controller   3216]
2018-05-31T15:14:59-0400 [Controller   3216] Version:     Crossbar.io COMMUNITY 18.4.1
2018-05-31T15:14:59-0400 [Controller   3216] Public Key:  f0501e8d03f7a58d7475222ffd0c7f706a893a37ae9d6ff11045190d6c4881c6
2018-05-31T15:14:59-0400 [Controller   3216]
2018-05-31T15:14:59-0400 [Controller   3216] Node starting with personality "community" [crossbar.controller.node.Node]
2018-05-31T15:14:59-0400 [Controller   3216] Running from node directory "C:\Users\********\Documents\GitHub\flask-twisted-serial\.crossbar"
2018-05-31T15:14:59-0400 [Controller   3216] Node configuration loaded from "C:\Users\********\Documents\GitHub\flask-twisted-serial\.crossbar\config.json"
2018-05-31T15:14:59-0400 [Controller   3216] Controller process starting [CPython-IOCPReactor] ..
2018-05-31T15:14:59-0400 [Controller   3216] No extra node router roles
2018-05-31T15:14:59-0400 [Controller   3216] RouterServiceSession ready [no on_ready configured]
2018-05-31T15:14:59-0400 [Controller   3216] Registered 20 procedures
2018-05-31T15:14:59-0400 [Controller   3216] Using default node shutdown triggers [u'shutdown_on_worker_exit']
2018-05-31T15:14:59-0400 [Controller   3216] Configuring node from local configuration ...
2018-05-31T15:14:59-0400 [Controller   3216] Starting 1 workers ...
2018-05-31T15:14:59-0400 [Controller   3216] Router worker "worker-001" starting ..
2018-05-31T15:15:00-0400 [Router        808] Started Router worker "worker-001" on node "None" [crossbar.worker.router.RouterWorkerSession / CPython-IOCPReactor]
2018-05-31T15:15:00-0400 [Router        808] Router worker "worker-001" session 5633862355716614 initializing ..
2018-05-31T15:15:00-0400 [Router        808] Registered 39 procedures
2018-05-31T15:15:00-0400 [Controller   3216] Router worker "worker-001" process 808 started
2018-05-31T15:15:00-0400 [Router        808] Router worker "worker-001" session ready
2018-05-31T15:15:00-0400 [Router        808] RouterServiceSession ready [configured on_ready fired]
2018-05-31T15:15:00-0400 [Router        808] Realm 'realm1' started
2018-05-31T15:15:00-0400 [Controller   3216] Router "worker-001": realm 'realm-001' (named 'realm1') started
2018-05-31T15:15:00-0400 [Controller   3216] Router "worker-001": role 'role-001' (named 'anonymous') started on realm 'realm-001'
2018-05-31T15:15:00-0400 [Router        808] role role-001 on realm realm-001 started
2018-05-31T15:15:00-0400 [Router        808] Cannot listen on transport endpoint: [Failure instance: Traceback: <class 'twisted.internet.error.CannotListenError'>: Could
n't listen on any:8080: [Errno 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted.
c:\users\********\venv\lib\site-packages\crossbar\worker\router.py:1464:start_router_transport
c:\users\********\venv\lib\site-packages\crossbar\worker\router.py:453:create_transport_from_config
c:\users\********\venv\lib\site-packages\crossbar\twisted\endpoint.py:559:create_listening_port_from_config
c:\users\********\venv\lib\site-packages\twisted\internet\endpoints.py:488:listen
--- <exception caught here> ---
c:\users\********\venv\lib\site-packages\twisted\internet\defer.py:121:execute
c:\users\********\venv\lib\site-packages\twisted\internet\iocpreactor\reactor.py:157:listenTCP
c:\users\********\venv\lib\site-packages\twisted\internet\iocpreactor\tcp.py:457:startListening
]
Traceback (most recent call last):
  File "c:\users\********\venv\lib\site-packages\crossbar\worker\router.py", line 1464, in start_router_transport
    _web_templates=self._templates, add_paths=add_paths
  File "c:\users\********\venv\lib\site-packages\crossbar\worker\router.py", line 453, in create_transport_from_config
    log,
  File "c:\users\********\venv\lib\site-packages\crossbar\twisted\endpoint.py", line 559, in create_listening_port_from_config
    return endpoint.listen(factory)
  File "c:\users\********\venv\lib\site-packages\twisted\internet\endpoints.py", line 488, in listen
    interface=self._interface)
--- <exception caught here> ---
  File "c:\users\********\venv\lib\site-packages\twisted\internet\defer.py", line 121, in execute
    result = callable(*args, **kw)
  File "c:\users\********\venv\lib\site-packages\twisted\internet\iocpreactor\reactor.py", line 157, in listenTCP
    p.startListening()
  File "c:\users\********\venv\lib\site-packages\twisted\internet\iocpreactor\tcp.py", line 457, in startListening
    raise error.CannotListenError(self.interface, self.port, le)
twisted.internet.error.CannotListenError: Couldn't listen on any:8080: [Errno 10048] Only one usage of each socket address (protocol/network address/port) is normally pe
rmitted.

2018-05-31T15:15:00-0400 [Controller   3216] crossbar.error.cannot_listen: Cannot listen on transport endpoint: {log_failure}
2018-05-31T15:15:00-0400 [Router        808] ApplicationError: ApplicationError(error=<crossbar.error.cannot_listen>, args=['Cannot listen on transport endpoint: {log_fa
ilure}'], kwargs={}, enc_algo=None): Traceback (most recent call last):
  File "c:\users\********\venv\lib\site-packages\txaio\tx.py", line 417, in as_future
    return maybeDeferred(fun, *args, **kwargs)
  File "c:\users\********\venv\lib\site-packages\twisted\internet\defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "c:\users\********\venv\lib\site-packages\crossbar\worker\router.py", line 1477, in start_router_transport
    d.addCallbacks(ok, fail)
  File "c:\users\********\venv\lib\site-packages\twisted\internet\defer.py", line 310, in addCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "c:\users\********\venv\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "c:\users\********\venv\lib\site-packages\crossbar\worker\router.py", line 1475, in fail
    raise ApplicationError(u"crossbar.error.cannot_listen", emsg)
autobahn.wamp.exception.ApplicationError: ApplicationError(error=<crossbar.error.cannot_listen>, args=['Cannot listen on transport endpoint: {log_failure}'], kwargs={},
enc_algo=None)

2018-05-31T15:15:00-0400 [Controller   3216] sending TERM to subprocess 808
2018-05-31T15:15:00-0400 [Controller   3216] waiting for 808 to exit...
2018-05-31T15:15:00-0400 [Controller   3216] Native worker connection closed uncleanly: A process has ended with a probable error condition: process ended with exit code
 1.
2018-05-31T15:15:00-0400 [Controller   3216] Node worker worker-001 ended with error ([Failure instance: Traceback (failure with no frames): <class 'twisted.internet.err
or.ProcessTerminated'>: A process has ended with a probable error condition: process ended with exit code 1.
])
2018-05-31T15:15:00-0400 [Controller   3216] Checking for node shutdown: worker_exit_success=False, shutdown_requested=False, node_shutdown_triggers=[u'shutdown_on_worke
r_exit']
2018-05-31T15:15:00-0400 [Controller   3216] Node worker ended, and trigger 'shutdown_on_worker_exit' active
2018-05-31T15:15:00-0400 [Controller   3216] Node shutdown requested ..

(venv) C:\Users\********\Documents\GitHub\flask-twisted-serial>
```
```
Python 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:22:17) [MSC v.1500 32 bit (Intel)] on win32

```

**Comment by oberstet** [comment]
there is already sth running on port 8080
