### ISSUE TITLE
Basic Installation for windows failed

### ISSUE THREAD

**Issue by birneos** [crossbario/crossbar#1356]
Hi,

after Basic Installation for Windows i couldnt startup crossbar. I restart and repeat all steps, completely.
 Following Error...

I typed in ...

> crossbar version

```
Traceback (most recent call last):
  File "C:\Python27\Scripts\crossbar-script.py", line 11, in <module>
    load_entry_point('crossbar', 'console_scripts', 'crossbar')()
  File "c:\users\marco linke\downloads\crossbar\crossbar\crossbar\__init__.py", line 177, in run
    _personalities = personalities()
  File "c:\users\marco linke\downloads\crossbar\crossbar\crossbar\__init__.py", line 215, in personalities
    from crossbar import personality as standalone
  File "c:\users\marco linke\downloads\crossbar\crossbar\crossbar\personality.py", line 40, in <module>
    from crossbar.node import node
  File "c:\users\marco linke\downloads\crossbar\crossbar\crossbar\node\node.py", line 52, in <module>
    from crossbar.node.controller import NodeController
  File "c:\users\marco linke\downloads\crossbar\crossbar\crossbar\node\controller.py", line 38, in <module>
    from shutil import which
ImportError: cannot import name which
```

Thanks!

birneos

**Comment by oberstet** [comment]
we dont support python 2
