### ISSUE TITLE
async is a keyword since py 3.7

### ISSUE THREAD

**Issue by eratulrai** [crossbario/crossbar#1357]
Hi,
  I upgraded my crossbar installation on windows10  , after the installation finished successfully
Whenever I try to run crossbar init or version command , it throws following error:
```
PS D:\crossbar> crossbar init
Traceback (most recent call last):
  File "c:\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python37\Scripts\crossbar.exe\__main__.py", line 9, in <module>
  File "c:\python37\lib\site-packages\crossbar\__init__.py", line 172, in run
    _personalities = personalities()
  File "c:\python37\lib\site-packages\crossbar\__init__.py", line 205, in personalities
    from crossbar import personality as standalone
  File "c:\python37\lib\site-packages\crossbar\personality.py", line 42, in <module>
    from crossbar.worker.router import RouterController
  File "c:\python37\lib\site-packages\crossbar\worker\router.py", line 51, in <module>
    from crossbar.worker.controller import WorkerController
  File "c:\python37\lib\site-packages\crossbar\worker\controller.py", line 214
    def start_profiler(self, profiler=u'vmprof', runtime=10, async=True, details=None):
                                                                 ^
SyntaxError: invalid syntax
PS D:\crossbar> crossbar -version
Traceback (most recent call last):
  File "c:\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python37\Scripts\crossbar.exe\__main__.py", line 9, in <module>
  File "c:\python37\lib\site-packages\crossbar\__init__.py", line 172, in run
    _personalities = personalities()
  File "c:\python37\lib\site-packages\crossbar\__init__.py", line 205, in personalities
    from crossbar import personality as standalone
  File "c:\python37\lib\site-packages\crossbar\personality.py", line 42, in <module>
    from crossbar.worker.router import RouterController
  File "c:\python37\lib\site-packages\crossbar\worker\router.py", line 51, in <module>
    from crossbar.worker.controller import WorkerController
  File "c:\python37\lib\site-packages\crossbar\worker\controller.py", line 214
    def start_profiler(self, profiler=u'vmprof', runtime=10, async=True, details=None):
                                                                 ^
SyntaxError: invalid syntax
```

**Comment by oddjobz** [comment]
Hi, is  it possible python got upgraded to 3.7 at the same time? I think they've made "async" a reserved word in 3.7 which seems to have been causing a little havoc with a number of applications, this  looks like the same problem, I think @meejah has already looked at a similar issue with autobahn;
https://github.com/crossbario/autobahn-python/issues/1022

**Comment by om26er** [comment]
Trying to build crossbar docker image and I am faced with the same issue. Looking into this now.
```
root@ubuntu-s-2vcpu-4gb-nyc3-01:~/crossbar/docker# make build
# enforce auto-generating a new key when using the images
rm -f node/.crossbar/key.*
time docker build --no-cache \
        --build-arg BUILD_DATE= \
        --build-arg CROSSBAR_VCS_REF= \
        --build-arg CROSSBAR_VERSION= \
        -t crossbario/crossbar:latest \
        -t crossbario/crossbar:cpy3 \
        -t crossbario/crossbar:cpy3- \
        -f ./x86_64/Dockerfile.cpy3 .
Sending build context to Docker daemon  35.33kB
Step 1/19 : FROM python:3-alpine
3-alpine: Pulling from library/python
911c6d0c7995: Pull complete 
01a7b783f4b1: Pull complete 
c251983fa222: Pull complete 
722f8b4b13ac: Pull complete 
35f62637a0bf: Pull complete 
Digest: sha256:0a707d5cbdd7156a027cc13b4787618488c0355b248cb4a09e4a737bf681e660
Status: Downloaded newer image for python:3-alpine
 ---> 4c65736f1320
Step 2/19 : MAINTAINER The Crossbar.io Project <support@crossbario.com>
 ---> Running in d9b578c5a272
Removing intermediate container d9b578c5a272
 ---> c2f2c28ef174
Step 3/19 : ARG CROSSBAR_VERSION
 ---> Running in 912901e9873d
Removing intermediate container 912901e9873d
 ---> d46245672ad7
Step 4/19 : ARG BUILD_DATE
 ---> Running in 265ca739d550
Removing intermediate container 265ca739d550
 ---> 6e2254480ff6
Step 5/19 : ARG CROSSBAR_VCS_REF
 ---> Running in d993c9a77fc3
Removing intermediate container d993c9a77fc3
 ---> 22245d95038a
Step 6/19 : LABEL org.label-schema.build-date=$BUILD_DATE       org.label-schema.name="Crossbar.io Starter Template"       org.label-schema.description="Quickstart template for application development with Crossbar.io"       org.label-schema.url="http://crossbar.io"       org.label-schema.vcs-ref=$CROSSBAR_VCS_REF       org.label-schema.vcs-url="https://github.com/crossbario/crossbar"       org.label-schema.vendor="The Crossbar.io Project"       org.label-schema.version=$CROSSBAR_VERSION       org.label-schema.schema-version="1.0"
 ---> Running in 0d3f2e411160
Removing intermediate container 0d3f2e411160
 ---> b305b1475517
Step 7/19 : ENV HOME /node
 ---> Running in b500ec91efa7
Removing intermediate container b500ec91efa7
 ---> 3792118e43bd
Step 8/19 : ENV DEBIAN_FRONTEND noninteractive
 ---> Running in b471a6de8c1c
Removing intermediate container b471a6de8c1c
 ---> 130cf21648c6
Step 9/19 : ENV PYTHONUNBUFFERED 1
 ---> Running in 7633850559b2
Removing intermediate container 7633850559b2
 ---> 8411bda1bc91
Step 10/19 : RUN    apk --update upgrade     && apk add libffi     && apk add --virtual .build-deps                build-base                libffi-dev                openssl-dev                linux-headers     && pip install --no-cache-dir -U pip     && pip install --no-cache-dir crossbar>=${CROSSBAR_VERSION}     && apk del .build-deps
 ---> Running in 5dea2f295e2d
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
OK: 35 MiB in 48 packages
OK: 35 MiB in 48 packages
(1/23) Installing binutils-libs (2.30-r1)
(2/23) Installing binutils (2.30-r1)
(3/23) Installing gmp (6.1.2-r1)
(4/23) Installing isl (0.18-r0)
(5/23) Installing libgomp (6.4.0-r5)
(6/23) Installing libatomic (6.4.0-r5)
(7/23) Installing pkgconf (1.3.10-r0)
(8/23) Installing libgcc (6.4.0-r5)
(9/23) Installing mpfr3 (3.1.5-r1)
(10/23) Installing mpc1 (1.0.3-r1)
(11/23) Installing libstdc++ (6.4.0-r5)
(12/23) Installing gcc (6.4.0-r5)
(13/23) Installing musl-dev (1.1.18-r3)
(14/23) Installing libc-dev (0.7.1-r0)
(15/23) Installing g++ (6.4.0-r5)
(16/23) Installing make (4.2.1-r0)
(17/23) Installing fortify-headers (0.9-r0)
(18/23) Installing build-base (0.5-r0)
(19/23) Installing libffi-dev (3.2.1-r4)
(20/23) Installing zlib-dev (1.2.11-r1)
(21/23) Installing openssl-dev (1.0.2o-r0)
(22/23) Installing linux-headers (4.4.6-r2)
(23/23) Installing .build-deps (0)
Executing busybox-1.27.2-r11.trigger
OK: 214 MiB in 71 packages
Requirement already up-to-date: pip in /usr/local/lib/python3.7/site-packages (10.0.1)
1(1/23) Purging .build-deps (0)
(2/23) Purging build-base (0.5-r0)
(3/23) Purging g++ (6.4.0-r5)
(4/23) Purging gcc (6.4.0-r5)
(5/23) Purging binutils (2.30-r1)
(6/23) Purging libatomic (6.4.0-r5)
(7/23) Purging libgomp (6.4.0-r5)
(8/23) Purging libstdc++ (6.4.0-r5)
(9/23) Purging make (4.2.1-r0)
(10/23) Purging libc-dev (0.7.1-r0)
(11/23) Purging musl-dev (1.1.18-r3)
(12/23) Purging fortify-headers (0.9-r0)
(13/23) Purging libffi-dev (3.2.1-r4)
(14/23) Purging openssl-dev (1.0.2o-r0)
(15/23) Purging zlib-dev (1.2.11-r1)
(16/23) Purging linux-headers (4.4.6-r2)
(17/23) Purging binutils-libs (2.30-r1)
(18/23) Purging mpc1 (1.0.3-r1)
(19/23) Purging mpfr3 (3.1.5-r1)
(20/23) Purging isl (0.18-r0)
(21/23) Purging gmp (6.1.2-r1)
(22/23) Purging pkgconf (1.3.10-r0)
(23/23) Purging libgcc (6.4.0-r5)
Executing busybox-1.27.2-r11.trigger
OK: 35 MiB in 48 packages
Removing intermediate container 5dea2f295e2d
 ---> ceefa9bcbd9c
Step 11/19 : RUN crossbar version
 ---> Running in c068f04885ee
Traceback (most recent call last):
  File "/usr/local/bin/crossbar", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.7/site-packages/crossbar/__init__.py", line 172, in run
    _personalities = personalities()
  File "/usr/local/lib/python3.7/site-packages/crossbar/__init__.py", line 205, in personalities
    from crossbar import personality as standalone
  File "/usr/local/lib/python3.7/site-packages/crossbar/personality.py", line 42, in <module>
    from crossbar.worker.router import RouterController
  File "/usr/local/lib/python3.7/site-packages/crossbar/worker/router.py", line 51, in <module>
    from crossbar.worker.controller import WorkerController
  File "/usr/local/lib/python3.7/site-packages/crossbar/worker/controller.py", line 214
    def start_profiler(self, profiler=u'vmprof', runtime=10, async=True, details=None):
                                                                 ^
SyntaxError: invalid syntax
The command '/bin/sh -c crossbar version' returned a non-zero code: 1
Command exited with non-zero status 1
0.09user 0.02system 2:47.36elapsed 0%CPU (0avgtext+0avgdata 29844maxresident)k
608inputs+0outputs (1major+2475minor)pagefaults 0swaps
Makefile:92: recipe for target 'build_amd64_cpy3' failed
make: *** [build_amd64_cpy3] Error 1
```

**Comment by om26er** [comment]
Unfortunately that won't be a backwards compatible change, if we change the variable name, anyone using it will get caught off guard though fortunately it seems `start_profiler` is part of the management API, which from my understanding is currently meant for CFC (which we control)

**Comment by oberstet** [comment]
@om26er no worries! there is no user API involved here .. so nothing to break .. only need to sync with our cfc side ..
