### ISSUE TITLE
Error after install new Crossbar version on Mac - High Sierra

### ISSUE THREAD

**Issue by rafael-freitas** [crossbario/crossbar#1358]
Any command on crossbar give me this:

```
$ crossbar start
Traceback (most recent call last):
  File "/usr/local/bin/crossbar", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.7/site-packages/crossbar/__init__.py", line 172, in run
    _personalities = personalities()
  File "/usr/local/lib/python3.7/site-packages/crossbar/__init__.py", line 205, in personalities
    from crossbar import personality as standalone
  File "/usr/local/lib/python3.7/site-packages/crossbar/personality.py", line 42, in <module>
    from crossbar.worker.router import RouterController
  File "/usr/local/lib/python3.7/site-packages/crossbar/worker/router.py", line 51, in <module>
    from crossbar.worker.controller import WorkerController
  File "/usr/local/lib/python3.7/site-packages/crossbar/worker/controller.py", line 214
    def start_profiler(self, profiler=u'vmprof', runtime=10, async=True, details=None):
                                                                 ^
SyntaxError: invalid syntax
```

My `config.json`:

```
{
  "version": 2,
  "workers": [
    {
      "type": "router",
      "realms": [
          {
              "name": "realm1",
              "roles": [
                  {
                      "name": "anonymous",
                      "permissions": [
                          {
                              "uri": "",
                              "match": "prefix",
                              "allow": {
                                  "call": true,
                                  "register": true,
                                  "publish": true,
                                  "subscribe": true
                              },
                              "disclose": {
                                  "caller": false,
                                  "publisher": false
                              },
                              "cache": true
                          }
                      ]
                  }
              ]
          }
      ],
      "transports": [
        {
            "type": "websocket",
            "endpoint": {
                "type": "tcp",
                "port": 9001
            }
        }
      ]
    }
  ]
}

```

**Comment by rafael-freitas** [comment]
Even using `virtualenv` and installing via `pip` instead `pip3` I got:

```
$ crossbar version
Traceback (most recent call last):
  File "/Users/rafael/www/erp-base/crossbar/development/my-venv/bin/crossbar", line 11, in <module>
    sys.exit(run())
  File "/Users/rafael/www/erp-base/crossbar/development/my-venv/lib/python2.7/site-packages/crossbar/__init__.py", line 172, in run
    _personalities = personalities()
  File "/Users/rafael/www/erp-base/crossbar/development/my-venv/lib/python2.7/site-packages/crossbar/__init__.py", line 205, in personalities
    from crossbar import personality as standalone
  File "/Users/rafael/www/erp-base/crossbar/development/my-venv/lib/python2.7/site-packages/crossbar/personality.py", line 40, in <module>
    from crossbar.node import node
  File "/Users/rafael/www/erp-base/crossbar/development/my-venv/lib/python2.7/site-packages/crossbar/node/node.py", line 52, in <module>
    from crossbar.node.controller import NodeController
  File "/Users/rafael/www/erp-base/crossbar/development/my-venv/lib/python2.7/site-packages/crossbar/node/controller.py", line 38, in <module>
    from shutil import which
ImportError: cannot import name which
```

**Comment by oddjobz** [comment]
I think this might be the same problem as; https://github.com/crossbario/crossbar/issues/1357, is there any chance you could  downgrade to  python 3.6 and try it again, just to  see?

**Comment by rafael-freitas** [comment]
@oddjobz I solved this issue this way:

1- `pip install crossbar --user`

2- Add Phyton 2.7 bin folder to PATH
```
nano ~/.profile
export PATH=$PATH:~/Library/Python/2.7/bin
source ~/.profile
```
3- Run

```
MacBook-Air-de-macbook:development rafael$ crossbar version
     __  __  __  __  __  __      __     __
    /  `|__)/  \/__`/__`|__) /\ |__)  |/  \
    \__,|  \\__/.__/.__/|__)/~~\|  \. |\__/
                                        
 Crossbar.io        : 18.4.1 (Crossbar.io COMMUNITY)
   Autobahn         : 18.6.1 (with JSON, MessagePack, CBOR, UBJSON)
   Twisted          : 18.4.0-KQueueReactor
   LMDB             : 0.94/lmdb-0.9.22
   Python           : 2.7.10/CPython
 Frozen executable  : no
 Operating system   : Darwin-17.6.0-x86_64-i386-64bit
 Host machine       : x86_64
 Release key        : xxxxxxx
```

**Comment by oddjobz** [comment]
Cool! .. if you don't need P3 I guess this is good stop-gap .. :) .. I'll see if I can find out a little more about the state of 3.7 support ...

**Comment by carlosbbraga** [comment]
Fala Rafael, tudo bem ?

Estou com o mesmo problema que você, mas a solução que serviu pra você não rolou aqui, poderia dar um help ?
