### ISSUE TITLE
Traceback from dynamic authenticator

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#1410]
```
2018-10-10T15:29:42+0200 [Router      17484] Internal error (2): tuple index out of range
Traceback (most recent call last):
  File "/home/oberstet/scm/crossbario/autobahn-python/autobahn/wamp/protocol.py", line 1113, in onMessage
    txaio.reject(on_reply, self._exception_from_message(msg))
  File "/home/oberstet/scm/crossbario/txaio/txaio/tx.py", line 478, in reject
    future.errback(error)
  File "/home/oberstet/cpy370_1/lib/python3.7/site-packages/twisted/internet/defer.py", line 501, in errback
    self._startRunCallbacks(fail)
  File "/home/oberstet/cpy370_1/lib/python3.7/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/home/oberstet/cpy370_1/lib/python3.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/oberstet/scm/crossbario/crossbar/crossbar/router/auth/cryptosign.py", line 191, in on_authenticate_error
    return self._marshal_dynamic_authenticator_error(err)
  File "/home/oberstet/scm/crossbario/crossbar/crossbar/router/auth/pending.py", line 184, in _marshal_dynamic_authenticator_error
    return types.Deny(err.value.error, u'{}'.format(err.value.args[0]))
builtins.IndexError: tuple index out of range
```

**Comment by oberstet** [comment]
long fixed - also see https://github.com/crossbario/crossbar-examples/tree/master/authentication
