### ISSUE TITLE
Traceback in dynamically stopping a router

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#1412]
```
018-10-11T21:57:40+0200 [Router        748] TypeError: argument of type 'RouterWebTransport' is not iterable: Traceback (most recent call last):
  File "/home/oberstet/scm/crossbario/autobahn-python/autobahn/twisted/websocket.py", line 166, in _onMessage
    self.onMessage(payload, isBinary)
  File "/home/oberstet/scm/crossbario/autobahn-python/autobahn/wamp/websocket.py", line 95, in onMessage
    self._session.onMessage(msg)
  File "/home/oberstet/scm/crossbario/autobahn-python/autobahn/wamp/protocol.py", line 936, in onMessage
    on_reply = txaio.as_future(endpoint.fn, *invoke_args, **invoke_kwargs)
  File "/home/oberstet/scm/crossbario/txaio/txaio/tx.py", line 429, in as_future
    return maybeDeferred(fun, *args, **kwargs)
--- <exception caught here> ---
  File "/home/oberstet/cpy370_1/lib/python3.7/site-packages/twisted/internet/defer.py", line 151, in maybeDeferred
    result = f(*args, **kw)
  File "/home/oberstet/scm/crossbario/crossbar/crossbar/worker/router.py", line 887, in stop_web_transport_service
    if path not in transport:
builtins.TypeError: argument of type 'RouterWebTransport' is not iterable

2018-10-11T21:57:40+0200 [Controller    496] ApplicationError: ApplicationError(error=<wamp.error.runtime_error>, args=["argument of type 'RouterWebTransport' is not iterable"], kwargs={}, enc_algo=None): Traceback (most recent call last):
Failure: autobahn.wamp.exception.ApplicationError: ApplicationError(error=<wamp.error.runtime_error>, args=["argument of type 'RouterWebTransport' is not iterable"], kwargs={}, enc_algo=None)
```

**Comment by oberstet** [comment]
long fixed: https://github.com/crossbario/crossbar/blob/ecc8b4e0d9f8fa3efa7d59755cb2e16151055870/crossbar/worker/transport.py#L537
