### ISSUE TITLE
Stack trace during startup on busy Router

### ISSUE THREAD

**Issue by jellisgwn** [crossbario/crossbar#1420]
See the following stack trace on startup as hundreds of clients attempt connect to two realms as soon as the Router is accepting connections:

```
2018-10-22T08:02:17-0500 [Container    7130] could not connect container component to router - transport establishment failed (User timeout caused connection failure.)
2018-10-22T08:02:17-0500 [Container    7130] ApplicationError: ApplicationError(error=<crossbar.error.cannot_connect>, args=[u'could not connect container component to router - transport establishment failed (User timeout caused connection failure.)'], kwargs={}, enc_algo=None): Traceback (most recent call last):
  File "/opt/crossbar/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1128, in connectionFailed
    self.factory.clientConnectionFailed(self, reason)
  File "/opt/crossbar/local/lib/python2.7/site-packages/twisted/internet/endpoints.py", line 263, in clientConnectionFailed
    self._onConnection.errback(reason)
  File "/opt/crossbar/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 500, in errback
    self._startRunCallbacks(fail)
  File "/opt/crossbar/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 567, in _startRunCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/opt/crossbar/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/opt/crossbar/local/lib/python2.7/site-packages/crossbar/worker/container.py", line 359, in on_connect_error
    raise ApplicationError(u'crossbar.error.cannot_connect', emsg)
autobahn.wamp.exception.ApplicationError: ApplicationError(error=<crossbar.error.cannot_connect>, args=[u'could not connect container component to router - transport establishment failed (User timeout caused connection failure.)'], kwargs={}, enc_algo=None)
```

Crossbar then proceeds to shutdown.

**Comment by oberstet** [comment]
Without more information, there are 3 approaches:

* increase the connection timeout in your connecting backend components
* run the backend component connections on a dedicated non-public transport (eg Unix domain socket when on one box (both router and app components) or RawSocket/WebSocket on private IPs with multiple boxes)
* start the (public) listening transport only after the latter has finished

the first 2 are possible with crossbar OSS, the latter is sth possible with CrossbarFX (our enterprise extended crossbar)
