### ISSUE TITLE
Could not start node

### ISSUE THREAD

**Issue by nadavvin** [crossbario/crossbar#1433]
It happen to me only in one server of mine and it work in many other servers.

I even try to reinstall the server, I don't know why it refuse to start here.

```
2018-11-04T12:00:33+0200 [Controller  10236]
2018-11-04T12:00:33+0200 [Controller  10236]     :::::::::::::::::
2018-11-04T12:00:33+0200 [Controller  10236]           :::::          _____                      __
2018-11-04T12:00:33+0200 [Controller  10236]     :::::   :   :::::   / ___/____ ___   ___  ___  / /  ___ _ ____
2018-11-04T12:00:33+0200 [Controller  10236]     :::::::   :::::::  / /__ / __// _ \ (_-< (_-< / _ \/ _ `// __/
2018-11-04T12:00:33+0200 [Controller  10236]     :::::   :   :::::  \___//_/   \___//___//___//_.__/\_,_//_/
2018-11-04T12:00:33+0200 [Controller  10236]           :::::
2018-11-04T12:00:33+0200 [Controller  10236]     :::::::::::::::::   Crossbar v18.7.2
2018-11-04T12:00:33+0200 [Controller  10236]
2018-11-04T12:00:33+0200 [Controller  10236]     Copyright (c) 2013-2018 Crossbar.io Technologies GmbH, licensed under AGPL 3.0.
2018-11-04T12:00:33+0200 [Controller  10236]
2018-11-04T12:00:33+0200 [Controller  10236] Initializing <class 'crossbar.personality.Personality'> node from node directory "c:\myserver\socket\.crossbar"
2018-11-04T12:00:33+0200 [Controller  10236] File permissions on node public key fixed
2018-11-04T12:00:33+0200 [Controller  10236] File permissions on node private key fixed
2018-11-04T12:00:33+0200 [Controller  10236] Node key loaded from "c:\myserver\socket\.crossbar\key.priv"
2018-11-04T12:00:33+0200 [Controller  10236] Node configuration loaded from "c:\myserver\socket\.crossbar\config.json"
2018-11-04T12:00:33+0200 [Controller  10236] Entering event reactor ...
2018-11-04T12:00:33+0200 [Controller  10236] Starting standalone node
2018-11-04T12:00:33+0200 [Controller  10236] Node ID "-volicon" set from hostname
2018-11-04T12:00:33+0200 [Controller  10236] No extra node router roles
2018-11-04T12:00:33+0200 [Controller  10236] RouterServiceAgent ready (realm_name="crossbar", on_ready=None)
2018-11-04T12:00:33+0200 [Controller  10236] Registered 21 procedures
2018-11-04T12:00:33+0200 [Controller  10236] Signal handler installed on process 10236 thread 2088
2018-11-04T12:00:33+0200 [Controller  10236] Using default node shutdown triggers ['shutdown_on_worker_exit']
2018-11-04T12:00:33+0200 [Controller  10236] Booting node
2018-11-04T12:00:33+0200 [Controller  10236] Configuring node from local configuration
2018-11-04T12:00:33+0200 [Controller  10236] Starting 1 workers ...
2018-11-04T12:00:33+0200 [Controller  10236] Starting router worker "worker-001"
2018-11-04T12:00:33+0200 [Controller  10236] Starting new managed worker process for Router worker "worker-001"
2018-11-04T12:00:34+0200 [Router      14076] usage: main.py [-h] [--debug-lifecycle] [--debug-programflow]
2018-11-04T12:00:34+0200 [Router      14076] [--reactor {select,poll,epoll,kqueue,iocp}]
2018-11-04T12:00:34+0200 [Router      14076] [--loglevel {none,error,warn,info,debug,trace}] -c CBDIR -r
2018-11-04T12:00:34+0200 [Router      14076] REALM -p PERSONALITY -k KLASS -n NODE -w WORKER [--title TITLE]
2018-11-04T12:00:34+0200 [Router      14076] [--expose_controller EXPOSE_CONTROLLER]
2018-11-04T12:00:34+0200 [Router      14076] [--expose_shared EXPOSE_SHARED] [--shutdown SHUTDOWN]
2018-11-04T12:00:34+0200 [Router      14076] main.py: error: argument -n/--node: expected one argument
2018-11-04T12:00:34+0200 [Controller  10236] Native worker connection closed uncleanly: A process has ended with a probable error condition: process ended with exit code 2.
2018-11-04T12:00:34+0200 [Controller  10236] Failed to start native worker: A process has ended with a probable error condition: process ended with exit code 2.
2018-11-04T12:00:34+0200 [Controller  10236] ApplicationError: ApplicationError(error=<crossbar.error.cannot_start>, args=['Failed to start native worker: A process has ended with a probable error condition: process ended with exit code 2.', ['usage: main.py [-h] [--debug-lifecycle] [--debug-programflow]', '[--reactor {{select,poll,epoll,kqueue,iocp}}]', '[--loglevel {{none,error,warn,info,debug,trace}}] -c CBDIR -r', 'REALM -p PERSONALITY -k KLASS -n NODE -w WORKER [--title TITLE]', '[--expose_controller EXPOSE_CONTROLLER]', '[--expose_shared EXPOSE_SHARED] [--shutdown SHUTDOWN]', 'main.py: error: argument -n/--node: expected one argument']], kwargs={}, enc_algo=None): Traceback (most recent call last):
  File "c:\program files\python3.6.6\lib\site-packages\twisted\internet\endpoints.py", line 384, in processEnded
    return self.protocol.connectionLost(reason)
  File "c:\program files\python3.6.6\lib\site-packages\crossbar\node\native.py", line 82, in connectionLost
    self.factory._on_ready.errback(reason)
  File "c:\program files\python3.6.6\lib\site-packages\twisted\internet\defer.py", line 502, in errback
    self._startRunCallbacks(fail)
  File "c:\program files\python3.6.6\lib\site-packages\twisted\internet\defer.py", line 569, in _startRunCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "c:\program files\python3.6.6\lib\site-packages\twisted\internet\defer.py", line 656, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "c:\program files\python3.6.6\lib\site-packages\crossbar\node\controller.py", line 557, in on_ready_error
    raise ApplicationError(u"crossbar.error.cannot_start", emsg, worker.getlog())
autobahn.wamp.exception.ApplicationError: ApplicationError(error=<crossbar.error.cannot_start>, args=['Failed to start native worker: A process has ended with a probable error condition: process ended with exit code 2.', ['usage: main.py [-h] [--debug-lifecycle] [--debug-programflow]', '[--reactor {{select,poll,epoll,kqueue,iocp}}]', '[--loglevel {{none,error,warn,info,debug,trace}}] -c CBDIR -r', 'REALM -p PERSONALITY -k KLASS -n NODE -w WORKER [--title TITLE]', '[--expose_controller EXPOSE_CONTROLLER]', '[--expose_shared EXPOSE_SHARED] [--shutdown SHUTDOWN]', 'main.py: error: argument -n/--node: expected one argument']], kwargs={}, enc_algo=None)

2018-11-04T12:00:34+0200 [Controller  10236] Could not start node: Traceback (most recent call last):
--- <exception caught here> ---
  File "c:\program files\python3.6.6\lib\site-packages\crossbar\node\node.py", line 328, in start
    yield self.personality.Node.boot(self)
  File "c:\program files\python3.6.6\lib\site-packages\crossbar\node\node.py", line 403, in boot_from_config
    yield self._controller.call(u'crossbar.start_worker', worker_id, worker_type, worker_options, options=CallOptions())
autobahn.wamp.exception.ApplicationError: ApplicationError(error=<crossbar.error.cannot_start>, args=['Failed to start native worker: A process has ended with a probable error condition: process ended with exit code 2.', ['usage: main.py [-h] [--debug-lifecycle] [--debug-programflow]', '[--reactor {{select,poll,epoll,kqueue,iocp}}]', '[--loglevel {{none,error,warn,info,debug,trace}}] -c CBDIR -r', 'REALM -p PERSONALITY -k KLASS -n NODE -w WORKER [--title TITLE]', '[--expose_controller EXPOSE_CONTROLLER]', '[--expose_shared EXPOSE_SHARED] [--shutdown SHUTDOWN]', 'main.py: error: argument -n/--node: expected one argument']], kwargs={}, enc_algo=None)
```

**Comment by om26er** [comment]
Could you please provide the version of Crossbar you using, also mention if you installed it from pypi or are using the crossbar exe file.

If possible please also share your crossbar config file

**Comment by nadavvin** [comment]
using the crossbar exe file.

 Crossbar v18.7.2
Crossbar.io        : 18.7.2
   Autobahn         : 18.7.1
   Twisted          : 18.7.0-IOCPReactor
   LMDB             : 0.94/lmdb-0.9.22
   Python           : 3.6.6/CPython
 Frozen executable  : no
 Operating system   : Windows-10-10.0.17134-SP0
 Host machine       : AMD64

**Comment by oberstet** [comment]
cannot reproduce (with the current EXE):

```
oberstet@intel-nuci7:~$ mkdir test4
oberstet@intel-nuci7:~$ cd test4
oberstet@intel-nuci7:~/test4$ wget https://download.crossbario.com/crossbarfx/linux-amd64/crossbarfx-linux-amd64-20190108-9553865
--2019-01-12 18:16:49--  https://download.crossbario.com/crossbarfx/linux-amd64/crossbarfx-linux-amd64-20190108-9553865
Auflösen des Hostnamens download.crossbario.com (download.crossbario.com) … 13.32.158.147, 13.32.158.200, 13.32.158.250, ...
Verbindungsaufbau zu download.crossbario.com (download.crossbario.com)|13.32.158.147|:443 … verbunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet … 200 OK
Länge: 41838920 (40M) [binary/octet-stream]
Wird in »crossbarfx-linux-amd64-20190108-9553865« gespeichert.

crossbarfx-linux-amd64-20190108-955 100%[=================================================================>]  39,90M  11,4MB/s    in 3,7s    

2019-01-12 18:16:53 (10,9 MB/s) - »crossbarfx-linux-amd64-20190108-9553865« gespeichert [41838920/41838920]

oberstet@intel-nuci7:~/test4$ chmod +x crossbarfx-linux-amd64-20190108-9553865 
oberstet@intel-nuci7:~/test4$ ./crossbarfx-linux-amd64-20190108-9553865 edge init
Initializing node in directory '/home/oberstet/test4'
Using template from '/tmp/_MEIL4nKkJ/crossbar/node/templates/default'
Creating directory /home/oberstet/test4/web
Creating directory /home/oberstet/test4/.crossbar
Creating file /home/oberstet/test4/README.md
Creating file /home/oberstet/test4/web/README.md
Creating file /home/oberstet/test4/.crossbar/config.json
Application template initialized

To start your node, run 'crossbar start --cbdir /home/oberstet/test4/.crossbar'

oberstet@intel-nuci7:~/test4$ ./crossbarfx-linux-amd64-20190108-9553865 edge version

    :::::::::::::::::
          :::::          _____                 __              _____  __
    :::::   :   :::::   / ___/______  ___ ___ / /  ___ _____  / __/ |/_/
    :::::::   :::::::  / /__/ __/ _ \(_-<(_-</ _ \/ _ `/ __/ / _/_>  <
    :::::   :   :::::  \___/_/  \___/___/___/_.__/\_,_/_/   /_/ /_/|_|
          :::::
    :::::::::::::::::   Crossbar Fabric XBR v18.12.1 [20190108-9553865]

    Copyright (c) 2013-2019 Crossbar.io Technologies GmbH. All rights reserved.

 Crossbar.io        : 18.12.1
   txaio            : 18.8.1
   Autobahn         : 18.12.1
   Twisted          : 18.9.0-EPollReactor
   LMDB             : 0.94/lmdb-0.9.22
   Python           : 3.7.1/CPython
 Crossbar.io FX     : 18.12.1
   XBR              : 18.12.2
   zLMDB            : 18.12.1
 Frozen executable  : yes
 Operating system   : Linux-4.15.0-43-generic-x86_64-with-debian-buster-sid
 Host machine       : x86_64
 Release key        : RWRL2URPgi6MK0CkpI9a4HzKYMTH/wZtSX2tISkJIXE1ctt7+Bf+fWEn

oberstet@intel-nuci7:~/test4$ ./crossbarfx-linux-amd64-20190108-9553865 edge start
2019-01-12T18:17:23+0100 [Controller  31915] 
2019-01-12T18:17:23+0100 [Controller  31915]     :::::::::::::::::
2019-01-12T18:17:23+0100 [Controller  31915]           :::::          _____                 __              _____  __
2019-01-12T18:17:23+0100 [Controller  31915]     :::::   :   :::::   / ___/______  ___ ___ / /  ___ _____  / __/ |/_/
2019-01-12T18:17:23+0100 [Controller  31915]     :::::::   :::::::  / /__/ __/ _ \(_-<(_-</ _ \/ _ `/ __/ / _/_>  <
2019-01-12T18:17:23+0100 [Controller  31915]     :::::   :   :::::  \___/_/  \___/___/___/_.__/\_,_/_/   /_/ /_/|_|
2019-01-12T18:17:23+0100 [Controller  31915]           :::::
2019-01-12T18:17:23+0100 [Controller  31915]     :::::::::::::::::   Crossbar Fabric XBR v18.12.1 [20190108-9553865]
2019-01-12T18:17:23+0100 [Controller  31915] 
2019-01-12T18:17:23+0100 [Controller  31915]     Copyright (c) 2013-2019 Crossbar.io Technologies GmbH. All rights reserved.
2019-01-12T18:17:23+0100 [Controller  31915] 
2019-01-12T18:17:23+0100 [Controller  31915] Initializing <class 'crossbarfx.edge.personality.Personality'> node from node directory /home/oberstet/test4/.crossbar 
2019-01-12T18:17:23+0100 [Controller  31915] New node key pair generated! Public key is 0x03ca3afcb372e40193a2520c7dcd460d55f7277a2dbc3e38ceb127e2a821421f
2019-01-12T18:17:23+0100 [Controller  31915] File permissions on node private key fixed
2019-01-12T18:17:23+0100 [Controller  31915] Node key loaded from /home/oberstet/test4/.crossbar/key.priv
2019-01-12T18:17:23+0100 [Controller  31915] Node configuration loaded from /home/oberstet/test4/.crossbar/config.json
2019-01-12T18:17:23+0100 [Controller  31915] Configuration source 2
2019-01-12T18:17:23+0100 [Controller  31915] Entering event reactor ...
2019-01-12T18:17:23+0100 [Controller  31915] Starting edge node 
2019-01-12T18:17:23+0100 [Controller  31915] Node ID intel-nuci7 set from hostname
2019-01-12T18:17:23+0100 [Controller  31915] RouterServiceAgent ready (realm_name="crossbar", on_ready=None)
2019-01-12T18:17:23+0100 [Controller  31915] Docker daemon integration disabled
2019-01-12T18:17:23+0100 [Controller  31915] Registered 46 procedures
2019-01-12T18:17:23+0100 [Controller  31915] Signal handler installed on process 31915 thread 140656907671360
2019-01-12T18:17:23+0100 [Controller  31915] Using default node shutdown triggers ['shutdown_on_shutdown_requested']
2019-01-12T18:17:23+0100 [Controller  31915] Booting node 
2019-01-12T18:17:23+0100 [Controller  31915] No fabric uplink configured (running unmanaged/single-node)
2019-01-12T18:17:23+0100 [Controller  31915] Booting node from local configuration .. 
2019-01-12T18:17:23+0100 [Controller  31915] Will start 1 worker ..
2019-01-12T18:17:23+0100 [Controller  31915] Order node to start Router worker001
2019-01-12T18:17:23+0100 [Controller  31915] Starting router worker worker001 
2019-01-12T18:17:25+0100 [Router      31927] Starting worker "worker001" for node "intel-nuci7" with personality "edge" 
2019-01-12T18:17:25+0100 [Router      31927] Running as PID 31929 on CPython-EPollReactor
2019-01-12T18:17:25+0100 [Router      31927] Entering event reactor ...
2019-01-12T18:17:25+0100 [Router      31927] Router worker session for "worker001" joined realm "crossbar" on node router 
2019-01-12T18:17:25+0100 [Router      31927] Registered 50 procedures
2019-01-12T18:17:25+0100 [Router      31927] Router worker session for "worker001" ready
2019-01-12T18:17:25+0100 [Controller  31915] Ok, node has started Router worker001
2019-01-12T18:17:25+0100 [Controller  31915] Configuring Router worker001 ..
2019-01-12T18:17:25+0100 [Controller  31915] Order Router worker001 to start Realm realm001
2019-01-12T18:17:25+0100 [Router      31927] Starting router realm "realm001" 
2019-01-12T18:17:25+0100 [Router      31927] Starting router realm realm001 
2019-01-12T18:17:25+0100 [Router      31927] RouterServiceAgent ready (realm_name="realm1", on_ready=<Deferred at 0x7f6708db67f0>)
2019-01-12T18:17:25+0100 [Router      31927] Realm "realm001" (name="realm1") started
2019-01-12T18:17:25+0100 [Controller  31915] Ok, Router worker001 has started Realm realm001
2019-01-12T18:17:25+0100 [Controller  31915] Order Realm realm001 to start Role role001
2019-01-12T18:17:25+0100 [Router      31927] Starting role "role001" on realm "realm001" 
2019-01-12T18:17:25+0100 [Router      31927] role role001 on realm realm001 started
2019-01-12T18:17:25+0100 [Controller  31915] Ok, Realm realm001 has started Role role001
2019-01-12T18:17:25+0100 [Controller  31915] Order Router worker001 to start Transport transport001
2019-01-12T18:17:25+0100 [Router      31927] Starting router transport "transport001" 
2019-01-12T18:17:25+0100 [Router      31927] Creating router transport for "transport001" 
2019-01-12T18:17:25+0100 [Router      31927] Router transport created for "transport001" 
2019-01-12T18:17:25+0100 [Router      31927] Created "static" Web service on root path "/" of Web transport "transport001"
2019-01-12T18:17:25+0100 [Router      31927] UniSocketServerFactory starting on 8080
2019-01-12T18:17:25+0100 [Controller  31915] Ok, Router worker001 has started Transport transport001
2019-01-12T18:17:25+0100 [Controller  31915] Order Transport transport001 to start Web Service webservice001
2019-01-12T18:17:25+0100 [Router      31927] Starting "nodeinfo" Web service on path "info" of transport "transport001" 
2019-01-12T18:17:25+0100 [Controller  31915] Ok, Transport transport001 has started Web Service webservice001
2019-01-12T18:17:25+0100 [Controller  31915] Ok, Router worker001 configured
2019-01-12T18:17:25+0100 [Controller  31915] Ok, local node configuration booted successfully!
^C2019-01-12T18:17:27+0100 [Controller  31915] Controller received SIGINT [signal=2]: shutting down node [shutdown_was_clean=True] ..
2019-01-12T18:17:27+0100 [Controller  31915] Node shutdown requested (restart=False, mode=None, reactor.running=True) ..
2019-01-12T18:17:28+0100 [Controller  31915] sending TERM to subprocess 31927
2019-01-12T18:17:28+0100 [Controller  31915] waiting for 31927 to exit...
2019-01-12T18:17:28+0100 [Router      31927] INVALID JSON: Native worker received SIGTERM - shutting down ..
{"log_time": 1547313448.1906862, "level": "warn", "namespace": "crossbarfx.edge.worker.router.ExtRouterController", "text": "Native worker received SIGTERM - shutting down .."}
2019-01-12T18:17:28+0100 [Router      31927] Shutdown of worker requested!
2019-01-12T18:17:28+0100 [Router      31927] Connection to node controller closed cleanly
2019-01-12T18:17:28+0100 [Router      31927] (TCP Port 8080 Closed)
2019-01-12T18:17:28+0100 [Controller  31915] Native worker connection closed cleanly.
2019-01-12T18:17:28+0100 [Controller  31915] Node worker worker001 ended successfully
2019-01-12T18:17:28+0100 [Controller  31915] Checking for node shutdown: worker_exit_success=True, shutdown_requested=True, node_shutdown_triggers=['shutdown_on_shutdown_requested']
oberstet@intel-nuci7:~/test4$ 
```
