### ISSUE TITLE
Dynamic authorizer stop working after upgrade to 18.11.1

### ISSUE THREAD

**Issue by Dodobibi** [crossbario/crossbar#1437]
Dynamic Authorizer will not work after upgrading to 18.11.1.

The problem is triggered when the router *call* the procedure defined as _authorizer_ in .config.

The error is:
```
raise SerializationError("WampRawSocketProtocol: unable to serialize WAMP application payload ({0})".format(e))

autobahn.wamp.exception.SerializationError: WampRawSocketProtocol: unable to serialize WAMP application payload (cannot serialize unknown object: <autobahn.wamp.types.SessionDetails object at 0x7f2e5fe018b8>)
```
It appears that the initial caller has been passed as a _SessionDetails_ object, **not as Dict** when creating `message.Call` before passing it to the component wich act as authorizer, and SessionDetails cannot be serialized...

Other standard _call_ work well.

Complete error :
```
2018-11-11T20:19:23+0100 [Router       9015] Unhandled error in Deferred:
2018-11-11T20:19:23+0100 [Router       9015] 
Traceback (most recent call last):
  File ".../lib/python3.7/site-packages/crossbar/router/router.py", line 278, in process
    self._dealer.processCall(session, msg)
  File ".../lib/python3.7/site-packages/crossbar/router/dealer.py", line 742, in processCall
    txaio.add_callbacks(d, on_authorize_success, on_authorize_error)
  File ".../lib/python3.7/site-packages/txaio/tx.py", line 506, in add_callbacks
    future.addCallbacks(callback, errback)
  File ".../lib/python3.7/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File ".../lib/python3.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File ".../lib/python3.7/site-packages/crossbar/router/dealer.py", line 721, in on_authorize_success
    self._call(session, call, registration, authorization)
  File ".../lib/python3.7/site-packages/crossbar/router/dealer.py", line 923, in _call
    self._router.send(callee, invocation)
  File ".../lib/python3.7/site-packages/crossbar/router/router.py", line 240, in send
    session._transport.send(msg)
  File ".../lib/python3.7/site-packages/autobahn/twisted/rawsocket.py", line 140, in send
    raise SerializationError("WampRawSocketProtocol: unable to serialize WAMP application payload ({0})".format(e))
autobahn.wamp.exception.SerializationError: WampRawSocketProtocol: unable to serialize WAMP application payload (cannot serialize unknown object: <autobahn.wamp.types.SessionDetails object at 0x7f2e5fe018b8>)
```

**Comment by Dodobibi** [comment]
Issue resolved
