### ISSUE TITLE
Failed to serialize messages

### ISSUE THREAD

**Issue by markope** [crossbario/crossbar#1447]
Using crossbar:pypy-18.11.2 docker image and autobahn 18.11.2 this command fails:

```python
details = yield self.call('wamp.session.get', someint)
```

with 
```console
2018-12-05T10:22:53+0000 [Router         13] {"log_time": 1544005373.7888033, "level": "error", "namespace": "crossbar.router.protocol.WampWebSocketServerProtocol", "text": "WAMP message serialization error: (\"don't know how to cbor serialize object of type %s\", <class 'autobahn.wamp.types.SessionDetails'>)"}{"log_time": 1544005373.7890656, "level": "error", "namespace": "crossbar.router.router.Router", "text": "INTERNAL ERROR in router incoming message processing"}
2018-12-05T10:22:53+0000 [Router         13] {"log_time": 1544005373.7893386, "level": "critical", "namespace": "crossbar.router.router.Router", "text": "\nTraceback (most recent call last):\n  File \"/usr/local/site-packages/twisted/internet/defer.py\", line 311, in addCallbacks\n    self._runCallbacks()\n  File \"/usr/local/site-packages/twisted/internet/defer.py\", line 654, in _runCallbacks\n    current.result = callback(current.result, *args, **kw)\n  File \"/usr/local/site-packages/autobahn/wamp/protocol.py\", line 971, in success\n    self._transport.send(reply)\n  File \"/usr/local/site-packages/crossbar/router/session.py\", line 213, in send\n    self._router.process(self._session, msg)\n--- <exception caught here> ---\n  File \"/usr/local/site-packages/crossbar/router/router.py\", line 284, in process\n    self._dealer.processYield(session, msg)\n  File \"/usr/local/site-packages/crossbar/router/dealer.py\", line 1133, in processYield\n    self._router.send(invocation_request.caller, reply)\n  File \"/usr/local/site-packages/crossbar/router/router.py\", line 240, in send\n    session._transport.send(msg)\n  File \"/usr/local/site-packages/autobahn/wamp/websocket.py\", line 123, in send\n    raise SerializationError(u\"WAMP message serialization error: {{0}}\".format(e))\nautobahn.wamp.exception.SerializationError: WAMP message serialization error: (\"don't know how to cbor serialize object of type %s\", <class 'autobahn.wamp.types.SessionDetails'>)\n"}
```

I also tried with the cbor serializer excluded. Gives a similar error message.

I downgraded to crossbar-18.10.1 again. There it works.

**Comment by jellisgwn** [comment]
The same issue is stopping is upgrading to latest:
```
2018-12-10T00:00:56-0500 [Router      24171]
Traceback (most recent call last):
  File "/opt/crossbar/lib/python3.5/site-packages/crossbar/bridge/rest/common.py", line 557, in on_auth_ok
    d = maybeDeferred(self._process, request, event)
  File "/opt/crossbar/lib/python3.5/site-packages/twisted/internet/defer.py", line 151, in maybeDeferred
    result = f(*args, **kw)
  File "/opt/crossbar/lib/python3.5/site-packages/crossbar/bridge/rest/caller.py", line 92, in _process
    return d.addCallbacks(on_call_ok, on_call_error)
  File "/opt/crossbar/lib/python3.5/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/opt/crossbar/lib/python3.5/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/opt/crossbar/lib/python3.5/site-packages/crossbar/bridge/rest/caller.py", line 79, in on_call_ok
    body = dump_json(res, True).encode('utf8')
  File "/opt/crossbar/lib/python3.5/site-packages/crossbar/_util.py", line 90, in dump_json
    return json.dumps(obj, separators=(',', ':'), ensure_ascii=False)
  File "/usr/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
builtins.TypeError: <autobahn.wamp.types.SessionDetails object at 0x7f5f52047e58> is not JSON serializable
```

**Comment by oberstet** [comment]
fixed via https://github.com/crossbario/crossbar/pull/1461

> note: you need autobahn and crossbar master.
