### ISSUE TITLE
Crossbar on Ubuntu subsystem for Windows 10

### ISSUE THREAD

**Issue by lkjimy** [crossbario/crossbar#1455]
I'm trying to run crossbar on the Ubuntu subsystem for Windows 10 but didn't get any success.

```
  ~$ which python
  /usr/bin/python
  
  ~$ python --version
  Python 2.7.15rc1
  
  ~$ which pip
  /usr/bin/pip
  
  ~$ pip --version
  pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)

  ~$ which crossbar
  /home/lkjimy/.local/bin/crossbar

  ~$ crossbar version
  Traceback (most recent call last):
    File "/home/lkjimy/.local/bin/crossbar", line 11, in <module>
      sys.exit(run())
    File "/home/lkjimy/.local/lib/python2.7/site-packages/crossbar/__init__.py", line 177, in run
      _personalities = personalities()
    File "/home/lkjimy/.local/lib/python2.7/site-packages/crossbar/__init__.py", line 215, in personalities
      from crossbar import personality as standalone
    File "/home/lkjimy/.local/lib/python2.7/site-packages/crossbar/personality.py", line 34, in <module>
      from collections.abc import Mapping
  ImportError: No module named abc
```

**Comment by om26er** [comment]
We dont support Crossbar on Python 2 anymore, please use Python3
