### ISSUE TITLE
stop command in windows not working

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#1506]
```
C:\Windows\system32>crossbar stop --cbdir "C:\Users\crossbar\nzisnode\.crossbar"
Stopping Crossbar.io currently running from node directory C:\Users\crossbar\nzisnode\.crossbar (PID 23356) ...
Traceback (most recent call last):
  File "c:\python35\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python35\Scripts\crossbar.exe\__main__.py", line 9, in <module>
  File "c:\python35\lib\site-packages\crossbar\__init__.py", line 205, in run
    return main(exename, args, reactor, personality_klass)
  File "c:\python35\lib\site-packages\crossbar\node\main.py", line 1165, in main
    options.func(options, reactor=reactor, personality=personality)
  File "c:\python35\lib\site-packages\crossbar\node\main.py", line 524, in _run_command_stop
    p.send_signal(signal.SIGINT)
  File "c:\python35\lib\site-packages\psutil\__init__.py", line 285, in wrapper
    return fun(self, *args, **kwargs)
  File "c:\python35\lib\site-packages\psutil\__init__.py", line 1207, in send_signal
    "only SIGTERM, CTRL_C_EVENT and CTRL_BREAK_EVENT signals "
ValueError: only SIGTERM, CTRL_C_EVENT and CTRL_BREAK_EVENT signals are supported on Windows
```

---

we could check for windows, and right away go to direct kill, instead of sending SIGINT signal first - which isn't supported on windows, and/or choose SIGINT or CTRL_C_EVENT by platform

the respective code to expand is this https://github.com/crossbario/crossbar/blob/master/crossbar/node/main.py#L590

**Comment by oberstet** [comment]
won't fix: can't test / I don't run windows .. pls use docker
