### ISSUE TITLE
Traceback in RouterApplicationSession upon unhandled INTERRUPT message

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#1525]
```
2019-03-18T21:47:28+0100 [Router      24443] Received invocation on uri=com.example.proc1.binary, options=None (caller=6365832353861211, caller_authid=XRHE-E4LA-T7MY-GEU5-PCAP-SLA3, caller_authrole=anonymous, forward_for=None)
2019-03-18T21:47:28+0100 [Router      24443] Received invocation on uri=com.example.proc1.binary, options=None (caller=4226688460328203, caller_authid=WUJW-UYE9-GEUG-P3J9-ST35-R994, caller_authrole=router2router, forward_for=None)
2019-03-18T21:47:28+0100 [Router      24443] Uplink forward-invoked call from local to remote (options=CallOptions(on_progress=None, timeout=None, forward_for=[{'session': 6365832353861211, 'authid': 'anonymous', 'authrole': 'anonymous'}]))
2019-03-18T21:47:28+0100 [Router      24443] Uplink forward-invoked call from local to remote (options=CallOptions(on_progress=None, timeout=None, forward_for=[{'session': 4226688460328203, 'authid': 'router2router', 'authrole': 'router2router'}]))
2019-03-18T21:47:31+0100 [Router      24443] Internal error
Traceback (most recent call last):
  File "/home/oberstet/scm/crossbario/autobahn-python/autobahn/twisted/websocket.py", line 163, in _onMessageEnd
    self.onMessageEnd()
  File "/home/oberstet/scm/crossbario/autobahn-python/autobahn/websocket/protocol.py", line 628, in onMessageEnd
    self._onMessage(payload, self.message_is_binary)
  File "/home/oberstet/scm/crossbario/autobahn-python/autobahn/twisted/websocket.py", line 166, in _onMessage
    self.onMessage(payload, isBinary)
  File "/home/oberstet/scm/crossbario/autobahn-python/autobahn/wamp/websocket.py", line 95, in onMessage
    self._session.onMessage(msg)
--- <exception caught here> ---
  File "/home/oberstet/scm/crossbario/crossbar/crossbar/router/session.py", line 498, in onMessage
    self._router.detach(self)
  File "/home/oberstet/scm/crossbario/crossbar/crossbar/router/router.py", line 202, in detach
    self._detach(session)
  File "/home/oberstet/scm/crossbario/crossbar/crossbar/router/router.py", line 211, in _detach
    self._dealer.detach(session)
  File "/home/oberstet/scm/crossbario/crossbar/crossbar/router/dealer.py", line 220, in detach
    mode=message.Cancel.KILLNOWAIT,
  File "/home/oberstet/scm/crossbario/crossbar/crossbar/router/router.py", line 239, in send
    session._transport.send(msg)
  File "/home/oberstet/scm/crossbario/crossbar/crossbar/router/session.py", line 275, in send
    raise Exception("RouterApplicationSession.send: unhandled message {0}".format(msg))
builtins.Exception: RouterApplicationSession.send: unhandled message Interrupt(request=512, mode=killnowait, reason=None)

2019-03-18T21:48:38+0100 [Router      24443] Received invocation on uri=com.example.proc1.binary, options=None (caller=8202369088916127, caller_authid=YEHM-GTFX-FRFT-VPGV-SFMA-NMGK, caller_authrole=anonymous, forward_for=None)
2019-03-18T21:48:38+0100 [Router      24443] Received invocation on uri=com.example.proc1.binary, options=None (caller=449282664337824, caller_authid=GW4C-X97P-YAES-VG6F-9UJY-V5H5, caller_authrole=router2router, forward_for=None)
2019-03-18T21:48:38+0100 [Router      24443] Received invocation on uri=com.example.proc1.binary, options=None (caller=972845035618571, caller_authid=VJQF-FGNS-SJHJ-H74A-AVXC-GG7Y, caller_authrole=anonymous, forward_for=None)
2019-03-18T21:48:38+0100 [Router      24443] Received invocation on uri=com.example.proc1.binary, options=None (caller=449282664337824, caller_authid=GW4C-X97P-YAES-VG6F-9UJY-V5H5, caller_authrole=router2router, forward_for=None)
2019-03-18T21:48:38+0100 [Router      24443] Uplink forward-invoked call from local to remote (options=CallOptions(on_progress=None, timeout=None, forward_for=[{'session': 972845035618571, 'authid': 'anonymous', 'authrole': 'anonymous'}]))
2019-03-18T21:48:38+0100 [Router      24443] Uplink forward-invoked call from local to remote (options=CallOptions(on_progress=None, timeout=None, forward_for=[{'session': 449282664337824, 'authid': 'router2router', 'authrole': 'router2router'}]))
2019-03-18T21:48:46+0100 [Router      24443] Received invocation on uri=com.example.proc1.binary, options=None (caller=2432802271755385, caller_authid=JJLU-6UMC-GFPG-3WKS-A6YC-UUCG, caller_authrole=router2router, forward_for=None)
```

**Comment by oberstet** [comment]
never seen this one before, and it comes up only now, because the upcoming router-to-router links triggers new constellations ..
