### ISSUE TITLE
Twisted 19.2.1: broken HTTP bridge unit test

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#1557]
Twisted 19.2.1 broke `crossbar.bridge.rest.test.test_common.RequestBodyTestCase.test_not_matching_bodylength`:

```
[ERROR]
Traceback (most recent call last):
  File "/home/travis/build/crossbario/crossbar/crossbar/bridge/rest/test/test_common.py", line 262, in test_not_matching_bodylength
    body=publishBody))
  File "/home/travis/build/crossbario/crossbar/crossbar/bridge/rest/test/__init__.py", line 113, in renderResource
    headers=headers, body=body)
  File "/home/travis/build/crossbario/crossbar/crossbar/bridge/rest/test/_request.py", line 68, in request
    req.requestHeaders = Headers(headers)
  File "/home/travis/build/crossbario/crossbar/.tox/coverage/lib/python3.7/site-packages/twisted/web/http_headers.py", line 79, in __init__
    self.setRawHeaders(name, values)
  File "/home/travis/build/crossbario/crossbar/.tox/coverage/lib/python3.7/site-packages/twisted/web/http_headers.py", line 220, in setRawHeaders
    for v in self._encodeValues(values)]
  File "/home/travis/build/crossbario/crossbar/.tox/coverage/lib/python3.7/site-packages/twisted/web/http_headers.py", line 220, in <listcomp>
    for v in self._encodeValues(values)]
  File "/home/travis/build/crossbario/crossbar/.tox/coverage/lib/python3.7/site-packages/twisted/web/http_headers.py", line 40, in _sanitizeLinearWhitespace
    return b' '.join(headerComponent.splitlines())
builtins.AttributeError: 'int' object has no attribute 'splitlines'
crossbar.bridge.rest.test.test_common.RequestBodyTestCase.test_not_matching_bodylength
```

need to analyze why and what is going wrong here ..

**Comment by oberstet** [comment]
here is a minimal reproducing example of what worked before, and now raises:

```python
from twisted.web.http_headers import Headers

headers = {b"Content-Type": [b"application/json"], b"Content-Length": [1]}
h = Headers(headers)
```

as in:

```
(cpy372_5) oberstet@intel-nuci7:~/scm/crossbario/crossbar$ python
Python 3.7.2 (default, Feb 25 2019, 08:26:41) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from twisted.web.http_headers import Headers
>>> headers = {b"Content-Type": [b"application/json"], b"Content-Length": [1]}
>>> 
>>> h = Headers(headers)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/oberstet/cpy372_5/lib/python3.7/site-packages/twisted/web/http_headers.py", line 79, in __init__
    self.setRawHeaders(name, values)
  File "/home/oberstet/cpy372_5/lib/python3.7/site-packages/twisted/web/http_headers.py", line 220, in setRawHeaders
    for v in self._encodeValues(values)]
  File "/home/oberstet/cpy372_5/lib/python3.7/site-packages/twisted/web/http_headers.py", line 220, in <listcomp>
    for v in self._encodeValues(values)]
  File "/home/oberstet/cpy372_5/lib/python3.7/site-packages/twisted/web/http_headers.py", line 40, in _sanitizeLinearWhitespace
    return b' '.join(headerComponent.splitlines())
AttributeError: 'int' object has no attribute 'splitlines'
```

**Comment by oberstet** [comment]
alright, the commit in twisted that changed the behavior is this https://github.com/twisted/twisted/commit/fd2fbf4bc4889d6d92350c37a0f05aa3ee9ba687#diff-effe5888987605608f990d71470cc65d

**Comment by meejah** [comment]
Is this some bytes/not-bytes python3 thing? ("one thing in a byte-string" is an int in python3 now, IIRC .. as in `type(b'abc'[0])` is `int`).

**Comment by meejah** [comment]
Oh, should that be `b"Content-Length": [b"1"]` instead? (i.e. a byte-string with `1` in it, not the integer `1`..?)

**Comment by oberstet** [comment]
yeah, fixed via https://github.com/crossbario/crossbar/pull/1558

**Comment by meejah** [comment]
I think it's kind-of both: our code is wrong (headers should consist of byte-strings) but Twisted should give a better error-message.
