### ISSUE TITLE
Adjust unit test mocks

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#1567]
We need to cleanup the fallout from a slight change and further tightening to some internal classes (changes from PR https://github.com/crossbario/crossbar/pull/1565) that broke unit test mocks:

```
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/home/oberstet/scm/crossbario/crossbar/crossbar/router/test/test_broker.py", line 218, in test_router_session_goodbye_custom_message
    rap = RouterApplicationSession(session, router_factory)
  File "/home/oberstet/scm/crossbario/crossbar/crossbar/router/session.py", line 91, in __init__
    assert isinstance(session, ApplicationSession), 'session must be of class ApplicationSession, not {}'.format(session.__class__.__name__ if session else type(session))
builtins.AssertionError: session must be of class ApplicationSession, not Mock

crossbar.router.test.test_broker.TestBrokerPublish.test_router_session_goodbye_custom_message
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/home/oberstet/scm/crossbario/crossbar/crossbar/router/test/test_broker.py", line 268, in test_router_session_goodbye_fire_disconnect_error
    rap = RouterApplicationSession(session, router_factory)
  File "/home/oberstet/scm/crossbario/crossbar/crossbar/router/session.py", line 91, in __init__
    assert isinstance(session, ApplicationSession), 'session must be of class ApplicationSession, not {}'.format(session.__class__.__name__ if session else type(session))
builtins.AssertionError: session must be of class ApplicationSession, not Mock

crossbar.router.test.test_broker.TestBrokerPublish.test_router_session_goodbye_fire_disconnect_error
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/home/oberstet/scm/crossbario/crossbar/crossbar/router/test/test_broker.py", line 243, in test_router_session_goodbye_onLeave_error
    rap = RouterApplicationSession(session, router_factory)
  File "/home/oberstet/scm/crossbario/crossbar/crossbar/router/session.py", line 91, in __init__
    assert isinstance(session, ApplicationSession), 'session must be of class ApplicationSession, not {}'.format(session.__class__.__name__ if session else type(session))
builtins.AssertionError: session must be of class ApplicationSession, not Mock

crossbar.router.test.test_broker.TestBrokerPublish.test_router_session_goodbye_onLeave_error
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/home/oberstet/scm/crossbario/crossbar/crossbar/router/test/test_broker.py", line 293, in test_router_session_lifecycle
    rap = RouterApplicationSession(session, router_factory)
  File "/home/oberstet/scm/crossbario/crossbar/crossbar/router/session.py", line 91, in __init__
    assert isinstance(session, ApplicationSession), 'session must be of class ApplicationSession, not {}'.format(session.__class__.__name__ if session else type(session))
builtins.AssertionError: session must be of class ApplicationSession, not Mock

crossbar.router.test.test_broker.TestBrokerPublish.test_router_session_lifecycle
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/home/oberstet/scm/crossbario/crossbar/crossbar/router/test/test_dealer.py", line 345, in test_force_reregister_kick
    rap = RouterApplicationSession(session, self.router_factory)
  File "/home/oberstet/scm/crossbario/crossbar/crossbar/router/session.py", line 91, in __init__
    assert isinstance(session, ApplicationSession), 'session must be of class ApplicationSession, not {}'.format(session.__class__.__name__ if session else type(session))
builtins.AssertionError: session must be of class ApplicationSession, not Mock

crossbar.router.test.test_dealer.TestDealer.test_force_reregister_kick
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/home/oberstet/scm/crossbario/crossbar/.tox/py37-unpinned-trial/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/oberstet/scm/crossbario/crossbar/crossbar/router/test/test_dealer.py", line 103, in test_outstanding_invoke
    rap = RouterApplicationSession(session, self.router_factory)
  File "/home/oberstet/scm/crossbario/crossbar/crossbar/router/session.py", line 91, in __init__
    assert isinstance(session, ApplicationSession), 'session must be of class ApplicationSession, not {}'.format(session.__class__.__name__ if session else type(session))
builtins.AssertionError: session must be of class ApplicationSession, not Mock

crossbar.router.test.test_dealer.TestDealer.test_outstanding_invoke
-------------------------------------------------------------------------------
```

**Comment by oberstet** [comment]
I've deactivated above 5 tests via

```python
raise unittest.SkipTest('FIXME: Adjust unit test mocks #1567')
```
