### ISSUE TITLE
version command fails for EXE

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#1571]
```
buildexe run-test: commands[18] | du -h /home/travis/crossbarfx
42M	/home/travis/crossbarfx
buildexe run-test: commands[19] | /home/travis/crossbarfx master version
Traceback (most recent call last):
  File "site-packages/crossbar/node/main.py", line 109, in _get_version
AttributeError: module 'msgpack' has no attribute '__version__'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "crossbarfx/__init__.py", line 207, in <module>
    run()
  File "crossbarfx/__init__.py", line 200, in run
    sys.exit(main(executable, args, reactor, personality))
  File "site-packages/crossbar/node/main.py", line 1282, in main
  File "site-packages/crossbar/node/main.py", line 456, in _run_command_version
  File "site-packages/crossbar/node/main.py", line 369, in _get_versions
  File "site-packages/crossbar/node/main.py", line 111, in _get_version
  File "site-packages/pkg_resources/__init__.py", line 481, in get_distribution
  File "site-packages/pkg_resources/__init__.py", line 357, in get_provider
  File "site-packages/pkg_resources/__init__.py", line 900, in require
  File "site-packages/pkg_resources/__init__.py", line 786, in resolve
pkg_resources.DistributionNotFound: The 'msgpack' distribution was not found and is required by the application
[7263] Failed to execute script __init__
ERROR: InvocationError for command /home/travis/crossbarfx master version (exited with code 255)
___________________________________ summary ____________________________________
ERROR:   buildexe: commands failed
The command "tox -c tox.ini -e $TOX_ENV" exited with 1.
```

**Comment by oberstet** [comment]
fixed via https://github.com/crossbario/crossbar/pull/1572
