### ISSUE TITLE
flatbuffers version fails on pyinstaller exe

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#1573]
there is another version+pyinstaller related issue:

```
buildexe run-test: commands[16] | file /home/oberstet/crossbarfx
/home/oberstet/crossbarfx: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/l, for GNU/Linux 2.6.32, BuildID[sha1]=28ba79c778f7402713aec6af319ee0fbaf3a8014, stripped
buildexe run-test: commands[17] | ldd /home/oberstet/crossbarfx
	linux-vdso.so.1 (0x00007ffca78aa000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f9268baf000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f9268992000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f92685a1000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f9268db3000)
buildexe run-test: commands[18] | du -h /home/oberstet/crossbarfx
39M	/home/oberstet/crossbarfx
buildexe run-test: commands[19] | /home/oberstet/crossbarfx master version

Traceback (most recent call last):
  File "crossbarfx/__init__.py", line 207, in <module>
    run()
  File "crossbarfx/__init__.py", line 200, in run
    sys.exit(main(executable, args, reactor, personality))
  File "site-packages/crossbar/node/main.py", line 1291, in main
  File "site-packages/crossbar/node/main.py", line 465, in _run_command_version
  File "site-packages/crossbar/node/main.py", line 405, in _get_versions
  File "site-packages/crossbar/node/main.py", line 113, in _get_version
  File "site-packages/pkg_resources/__init__.py", line 481, in get_distribution
  File "site-packages/pkg_resources/__init__.py", line 357, in get_provider
  File "site-packages/pkg_resources/__init__.py", line 900, in require
  File "site-packages/pkg_resources/__init__.py", line 786, in resolve
pkg_resources.DistributionNotFound: The 'flatbuffers' distribution was not found and is required by the application
[4307] Failed to execute script __init__
ERROR: InvocationError for command /home/oberstet/crossbarfx master version (exited with code 255)
_____________________________________________________________________________________________________________________________________ summary _____________________________________________________________________________________________________________________________________
ERROR:   buildexe: commands failed
```

ultimately: https://github.com/google/flatbuffers/issues/5299

**Comment by oberstet** [comment]
workaround (for now) via https://github.com/crossbario/crossbar/pull/1574
