### ISSUE TITLE
Need help on installing/running on Raspberry Pi with Ubuntu 18.04

### ISSUE THREAD

**Issue by 27leaves** [crossbario/crossbar#1589]
Hi!

I tried now for several days to install & run crossbar on a Raspberry Pi with Ubuntu 18.04 without luck. Maybe you can help me with that?

**virtualenv**
When I try to install it with virtualenv on Python 3.6 (also 2.7) the installation works until it hangs on `Running setup.py install for numpy ...`.

**snap**
On snap, it can be installed, but produces the following output:
```
sudo crossbar init
Application directory '/home/ubuntu/code/crossbar' already exists!
Initializing application directory '/home/ubuntu/code/crossbar' ..
Using template from '/snap/crossbar/805/lib/python3.6/site-packages/crossbar/node/templates/default'
Creating directory /home/ubuntu/code/crossbar/.crossbar
Something went wrong while instantiating app template - rolling back changes ..Traceback (most recent call last):
  File "/snap/crossbar/805/bin/crossbar", line 11, in <module>
    load_entry_point('crossbar==19.2.1', 'console_scripts', 'crossbar')()
  File "/snap/crossbar/805/lib/python3.6/site-packages/crossbar/__init__.py", line 205, in run
    return main(exename, args, reactor, personality_klass)
  File "/snap/crossbar/805/lib/python3.6/site-packages/crossbar/node/main.py", line 1240, in main
    options.func(options, reactor=reactor, personality=personality)
  File "/snap/crossbar/805/lib/python3.6/site-packages/crossbar/node/main.py", line 535, in _run_command_init
    get_started_hint = Templates.init(options.appdir, template='default')
--- <exception caught here> ---
  File "/snap/crossbar/805/lib/python3.6/site-packages/crossbar/node/template.py", line 140, in init
    os.mkdir(create_dir_path)
builtins.PermissionError: [Errno 13] Permission denied: '/home/ubuntu/code/crossbar/.crossbar'

Traceback (most recent call last):
  File "/snap/crossbar/805/bin/crossbar", line 11, in <module>
    load_entry_point('crossbar==19.2.1', 'console_scripts', 'crossbar')()
  File "/snap/crossbar/805/lib/python3.6/site-packages/crossbar/__init__.py", line 205, in run
    return main(exename, args, reactor, personality_klass)
  File "/snap/crossbar/805/lib/python3.6/site-packages/crossbar/node/main.py", line 1240, in main
    options.func(options, reactor=reactor, personality=personality)
  File "/snap/crossbar/805/lib/python3.6/site-packages/crossbar/node/main.py", line 535, in _run_command_init
    get_started_hint = Templates.init(options.appdir, template='default')
  File "/snap/crossbar/805/lib/python3.6/site-packages/crossbar/node/template.py", line 140, in init
    os.mkdir(create_dir_path)
PermissionError: [Errno 13] Permission denied: '/home/ubuntu/code/crossbar/.crossbar'
```
`crossbar version` with the snap-installation:
```
 Crossbar.io        : 19.2.1
   txaio            : 18.8.1
   Autobahn         : 19.2.1
   Twisted          : 18.9.0-EPollReactor
   LMDB             : 0.94/lmdb-0.9.22
   Python           : 3.6.7/CPython
 Frozen executable  : no
 Operating system   : Linux-4.15.0-1033-raspi2-aarch64-with-Ubuntu-18.04-bionic
 Host machine       : aarch64
 Release key        : RWR2yD4qEkDnHAOwcTx6qTqaTT55n+J5pWez5jXUFT89fwlfVO77nFaV
```

**docker**
On docker, I can get it to run (without any configuration), but when I try to bind it to a local configuration, it is failing with the following output (The files in .crossbar are chmod 777)
```
crossbar_1  | 2019-05-15T14:01:04+0000 [Controller      1]
crossbar_1  | 2019-05-15T14:01:04+0000 [Controller      1]     :::::::::::::::::
crossbar_1  | 2019-05-15T14:01:04+0000 [Controller      1]           :::::          _____                      __
crossbar_1  | 2019-05-15T14:01:04+0000 [Controller      1]     :::::   :   :::::   / ___/____ ___   ___  ___  / /  ___ _ ____
crossbar_1  | 2019-05-15T14:01:04+0000 [Controller      1]     :::::::   :::::::  / /__ / __// _ \ (_-< (_-< / _ \/ _ `// __/
crossbar_1  | 2019-05-15T14:01:04+0000 [Controller      1]     :::::   :   :::::  \___//_/   \___//___//___//_.__/\_,_//_/
crossbar_1  | 2019-05-15T14:01:04+0000 [Controller      1]           :::::
crossbar_1  | 2019-05-15T14:01:04+0000 [Controller      1]     :::::::::::::::::   Crossbar v19.3.5
crossbar_1  | 2019-05-15T14:01:04+0000 [Controller      1]
crossbar_1  | 2019-05-15T14:01:04+0000 [Controller      1]     Copyright (c) 2013-2019 Crossbar.io Technologies GmbH, licensed under AGPL 3.0.
crossbar_1  | 2019-05-15T14:01:04+0000 [Controller      1]
crossbar_1  | 2019-05-15T14:01:04+0000 [Controller      1] Initializing <crossbar.node.node.Node> as node [realm=crossbar, cbdir=/node/.crossbar]
crossbar_1  | 2019-05-15T14:01:04+0000 [Controller      1] Node key files exist and are valid. Node public key is 0xb4955a7afd730c6cdf26e196abb750b1ba9547e1f01d7cc248699ae89c56856c
crossbar_1  | 2019-05-15T14:01:04+0000 [Controller      1] Traceback (most recent call last):
crossbar_1  | 2019-05-15T14:01:04+0000 [Controller      1]   File "/usr/local/bin/crossbar", line 11, in <module>
crossbar_1  | 2019-05-15T14:01:04+0000 [Controller      1]     sys.exit(run())
crossbar_1  | 2019-05-15T14:01:04+0000 [Controller      1]   File "/usr/local/lib/python3.7/site-packages/crossbar/__init__.py", line 205, in run
crossbar_1  | 2019-05-15T14:01:04+0000 [Controller      1]     return main(exename, args, reactor, personality_klass)
crossbar_1  | 2019-05-15T14:01:04+0000 [Controller      1]   File "/usr/local/lib/python3.7/site-packages/crossbar/node/main.py", line 1282, in main
crossbar_1  | 2019-05-15T14:01:04+0000 [Controller      1]     options.func(options, reactor=reactor, personality=personality)
crossbar_1  | 2019-05-15T14:01:04+0000 [Controller      1]   File "/usr/local/lib/python3.7/site-packages/crossbar/node/main.py", line 800, in _run_command_start
crossbar_1  | 2019-05-15T14:01:04+0000 [Controller      1]     node.load_keys(options.cbdir)
crossbar_1  | 2019-05-15T14:01:04+0000 [Controller      1]   File "/usr/local/lib/python3.7/site-packages/crossbar/node/node.py", line 187, in load_keys
crossbar_1  | 2019-05-15T14:01:04+0000 [Controller      1]     was_new, self._node_key = _maybe_generate_key(cbdir)
crossbar_1  | 2019-05-15T14:01:04+0000 [Controller      1]   File "/usr/local/lib/python3.7/site-packages/crossbar/common/key.py", line 277, in _maybe_generate_key
crossbar_1  | 2019-05-15T14:01:04+0000 [Controller      1]     os.chmod(pubkey_path, 420)
crossbar_1  | 2019-05-15T14:01:04+0000 [Controller      1] PermissionError: [Errno 1] Operation not permitted: '/node/.crossbar/key.pub'
```

Does someone have an idea, how I can get it running on my system?
Thank you!

**Comment by orioncx** [comment]
> Does someone have an idea, how I can get it running on my system?

Probably not actual anymore but  [this](https://dev.to/acro5piano/specifying-user-and-group-in-docker-i2e) will help.

**Comment by oberstet** [comment]
cleaning up orphaned issues
