### ISSUE TITLE
reentrant call inside logger

### ISSUE THREAD

**Issue by etam** [crossbario/crossbar#1639]
This happened here: https://github.com/golemfactory/golem/issues/4768

crossbar version:
```
 Crossbar.io        : 19.6.2
   txaio            : 18.8.1
   Autobahn         : 19.6.2
     UTF8 Validator : autobahn
     XOR Masker     : autobahn
     JSON Codec     : stdlib
     MsgPack Codec  : msgpack-0.6.2
     CBOR Codec     : cbor-1.0.0
     UBJSON Codec   : ubjson-0.11.0
     FlatBuffers    : flatbuffers-1.11
   Twisted          : 19.2.1-EPollReactor
   LMDB             : 0.94/lmdb-0.9.22
   Python           : 3.6.8/CPython
 Frozen executable  : no
 Operating system   : Linux-5.2.14-1-default-x86_64-with-glibc2.29
 Host machine       : x86_64
 Release key        : RWTS7Lf+Zks97Pu2hRHkjaVPjjbDCUVc2tOAHjsd1a1W5cKKciAoSIRE
```

Traceback:
```
INFO     [golem.client                       ] Updating masks
^CWARNING  [twisted                            ] Controller received SIGINT [signal=2]: shutting down node [shutdown_was_clean=True] ..
INFO [actix_server::builder] SIGINT received, exiting
WARNING  [twisted                            ] Controller received SIGINT [signal=2]: shutting down node [shutdown_was_clean=True] ..
--- Logging error ---
INFO [actix_server::builder] SIGINT received, exiting
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/__init__.py", line 998, in emit
    self.flush()
  File "/usr/lib/python3.6/logging/__init__.py", line 978, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='/home/ederenn/.local/share/golem/default/mainnet/logs/golem.error.log'>
Call stack:
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golemapp.py", line 295, in <module>
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golemapp.py", line 243, in main
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/click/core.py", line 764, in __call__
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/click/core.py", line 717, in main
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/click/core.py", line 956, in invoke
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/click/core.py", line 555, in invoke
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golemapp.py", line 204, in start
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golemapp.py", line 200, in _start
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/node.py", line 203, in start
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/internet/asyncioreactor.py", line 267, in run
  File "/usr/lib/python3.6/asyncio/base_events.py", line 427, in run_forever
    raise RuntimeError(
  File "/usr/lib/python3.6/asyncio/base_events.py", line 1404, in _run_once
    logger.log(level, 'poll took %.3f ms: %s events',
  File "/usr/lib/python3.6/selectors.py", line 445, in select
    fd_event_list = self._epoll.poll(timeout, max_ev)
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/crossbar/node/controller.py", line 169, in signal_handler
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/txaio/tx.py", line 190, in _log
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/logger/_logger.py", line 144, in emit
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/logger/_observer.py", line 131, in __call__
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/logger/_legacy.py", line 93, in __call__
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/python/log.py", line 595, in emit
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/logger/_legacy.py", line 154, in publishToNewObserver
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/logger/_stdlib.py", line 116, in __call__
  File "/usr/lib/python3.6/logging/__init__.py", line 1361, in log
    Log 'msg % args' with the integer severity 'level'.
  File "/usr/lib/python3.6/logging/__init__.py", line 1374, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/lib/python3.6/logging/__init__.py", line 1444, in _log
    self.handle(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1454, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1516, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 865, in handle
    self.emit(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1072, in emit
    StreamHandler.emit(self, record)
  File "/usr/lib/python3.6/logging/__init__.py", line 998, in emit
    self.flush()
  File "/usr/lib/python3.6/logging/__init__.py", line 978, in flush
    self.stream.flush()
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/crossbar/node/controller.py", line 169, in signal_handler
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/txaio/tx.py", line 190, in _log
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/logger/_logger.py", line 144, in emit
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/logger/_observer.py", line 131, in __call__
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/logger/_legacy.py", line 93, in __call__
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/python/log.py", line 595, in emit
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/logger/_legacy.py", line 154, in publishToNewObserver
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/logger/_stdlib.py", line 116, in __call__
  File "/usr/lib/python3.6/logging/__init__.py", line 1361, in log
    Log 'msg % args' with the integer severity 'level'.
  File "/usr/lib/python3.6/logging/__init__.py", line 1374, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/lib/python3.6/logging/__init__.py", line 1444, in _log
    self.handle(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1454, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1516, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 865, in handle
    self.emit(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1072, in emit
    StreamHandler.emit(self, record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1000, in emit
    self.handleError(record)
Message: <twisted.logger._stdlib.StringifiableFromEvent object at 0x7fcfd40241d0>
Arguments: ()
INFO     [golem.client                       ] Shutting down ...
INFO     [golem.client                       ] Stopping network ...
```

Steps to reproduce: hit Ctrl+C and have a lot of luck.

This happens because there is a logging call in signal handler.

Related info: https://docs.python.org/3/library/logging.html#thread-safety
> The logging module is intended to be thread-safe without any special work needing to be done by its clients. It achieves this though using threading locks; there is one lock to serialize access to the module’s shared data, and each handler also creates a lock to serialize access to its underlying I/O.
> 
> If you are implementing asynchronous signal handlers using the signal module, you may not be able to use logging from within such handlers. This is because lock implementations in the threading module are not always re-entrant, and so cannot be invoked from such signal handlers.

**Comment by oberstet** [comment]
could you pls post your node config and describe what you are running exactly?

as in: `/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/internet/asyncioreactor.py`

crossbar does not use nor support this reactor ..

**Comment by etam** [comment]
> could you pls post your node config

```
{
   "controller" : {
      "options" : {
         "shutdown" : [
            "shutdown_on_shutdown_requested"
         ]
      }
   },
   "version" : 2,
   "workers" : [
      {
         "components" : [],
         "options" : {
            "title" : "Golem"
         },
         "realms" : [
            {
               "name" : "golem",
               "roles" : [
                  {
                     "name" : "admin",
                     "permissions" : [
                        {
                           "allow" : {
                              "call" : true,
                              "publish" : true,
                              "register" : true,
                              "subscribe" : true
                           },
                           "uri" : "*"
                        }
                     ]
                  },
                  {
                     "name" : "docker",
                     "permissions" : [
                        {
                           "allow" : {
                              "call" : false,
                              "publish" : false,
                              "register" : false,
                              "subscribe" : false
                           },
                           "uri" : "*"
                        },
                        {
                           "allow" : {
                              "call" : true,
                              "publish" : false,
                              "register" : false,
                              "subscribe" : false
                           },
                           "uri" : "docker.*"
                        },
                        {
                           "allow" : {
                              "call" : true,
                              "publish" : false,
                              "register" : false,
                              "subscribe" : false
                           },
                           "uri" : "sys.exposed_procedures"
                        }
                     ]
                  }
               ]
            }
         ],
         "transports" : [
            {
               "auth" : {
                  "wampcra" : {
                     "type" : "static",
                     "users" : {
                        "docker" : {
                           "role" : "docker",
                           "secret" : "[...]"
                        },
                        "electron" : {
                           "role" : "admin",
                           "secret" : "[...]"
                        },
                        "golemapp" : {
                           "role" : "admin",
                           "secret" : "[...]"
                        },
                        "golemcli" : {
                           "role" : "admin",
                           "secret" : "[...]"
                        }
                     }
                  }
               },
               "endpoint" : {
                  "interface" : "localhost",
                  "port" : 61000,
                  "tls" : {
                     "certificate" : "/home/etam/code/github/golemfactory/golem/develop/.datadir/rinkeby/crossbar/rpc_cert.pem",
                     "dhparam" : "",
                     "key" : "/home/etam/code/github/golemfactory/golem/develop/.datadir/rinkeby/crossbar/rpc_key.pem"
                  },
                  "type" : "tcp"
               },
               "options" : {
                  "allowed_origins" : [
                     "http://localhost:*",
                     "https://localhost:*"
                  ],
                  "enable_webstatus" : false
               },
               "serializers" : [
                  "msgpack"
               ],
               "type" : "websocket",
               "url" : "wss://localhost:61000"
            }
         ],
         "type" : "router"
      }
   ]
}
```

> and describe what you are running exactly?

We're running golem (https://github.com/golemfactory/golem), which uses crossbar for RPC communication between main program, cli, gui (and others, without getting into much detail). It works by spawning crossbar router as a subprocess of main golem process.

We have recently enabled asyncio in our codebase and changed twisted reactor to it.

(if my answer is too vague, don't hesitate to ask more questions)

> crossbar does not use nor support this reactor ..

Well, that might be an important issue, that we have overlooked. I'll rise that issue in our team.
(afaik, crossbar has support for using asyncio directly, so maybe we should try using it)

**Comment by oberstet** [comment]
> It works by spawning crossbar router as a subprocess of main golem process.

so you are using Twisted with Twisted asyncio reactor in your main program, and then spawn a subprocess running crossbar?

crossbar, spawned as a regular process, will (on linux) always choose epoll reactor - so this issue is most likely _not_ coming from crossbar.

the problem is more likely either in the specific way you do the spawning, or in Twisted asyncio reactor (signal handling therein, or in interaction with the asyncio loop).

crossbar will itself install signal handlers - and that works with crossbar being spawned by some program (in general). eg we usually run crossbar under systemd and unbuffer

> in general, on linux, crossbar can run on these twisted reactors: 'select', 'poll', 'epoll', but as said, it doesn't matter .. it uses its own reactor .. what you use in your program spawning crossbar as a subprocess is unrelated. also unrelated: yes, _autobahn_ (not crossbar) supports both twisted (all reactors) and pure asyncio too

**Comment by oberstet** [comment]
ah, slightly OT .. but because I noticed you are in crypto - not sure if you are aware of this:

* https://www.linkedin.com/posts/oberstet_automotive-data-markets-activity-6577214409804918784-R7HM
* which is based on https://xbr.network/ .. which builds on top of crossbar/autobahn/wamp

for example, this is how client code looks in JS (AtuobahnJS):

* https://github.com/crossbario/autobahn-js/blob/master/test/xbr/client/nodejs/seller.js
* https://github.com/crossbario/autobahn-js/blob/master/test/xbr/client/nodejs/buyer.js

**Comment by oberstet** [comment]
aah, actually, you are not really starting crossbar as a subprocess, but directly import python classes into your application:

https://github.com/golemfactory/golem/blob/fd680a7cd04098db1f241651bbb50ba74e46a26f/golem/rpc/router.py#L37

this has 2 issues:

* it is technically unsupported (crossbar has not official/supported python level API .. as at the class level)
* it is legally a problem, because golem is GPL, while crossbar is AGPL - to comply, you would need to actually use crossbar as a separate program (start it as a subprocess) _or_ change golem license to AGPL

> pls feel free to contact me via email if you are interested in further infos, or staring a conversation! tobias dot oberstein at crossbario dot com

**Comment by goeddea** [comment]
OK, a closer look at the AGPL v3 reveals that there is a specific exception for combining AGPL and GPL code: This can co-exist in a single application, with the respective licenses applying to the parts (AGPL section 13).

Still, while this is legally OK, we'd suggest you use a cleaner, less brittle approach.

**Comment by etam** [comment]
You're right and I was wrong. I thought we're spawning crossbar router as subprocess, but instead we're spawning a crossbar worker (https://github.com/golemfactory/golem/blob/fd680a7cd04098db1f241651bbb50ba74e46a26f/golemapp.py#L208), which is a different thing.
I'm also glad that we're good with licensing.

Sorry for making noise and thanks for your help. I agree that the case is closed.

**Comment by oberstet** [comment]
yeah, thanks for confirmation!

btw, you might also be interested in this:

* https://download.crossbario.com/crossbarfx/linux-amd64/crossbarfx-latest

as in:

```
oberstet@intel-nuci7:~$ wget https://download.crossbario.com/crossbarfx/linux-amd64/crossbarfx-latest
--2019-09-26 14:46:35--  https://download.crossbario.com/crossbarfx/linux-amd64/crossbarfx-latest
Auflösen des Hostnamens download.crossbario.com (download.crossbario.com) … 99.84.92.76, 99.84.92.100, 99.84.92.42, ...
Verbindungsaufbau zu download.crossbario.com (download.crossbario.com)|99.84.92.76|:443 … verbunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet … 200 OK
Länge: 46490360 (44M) [binary/octet-stream]
Wird in »crossbarfx-latest« gespeichert.

crossbarfx-latest                                                    100%[=====================================================================================================================================================================>]  44,34M  11,1MB/s    in 4,0s    

2019-09-26 14:46:39 (11,0 MB/s) - »crossbarfx-latest« gespeichert [46490360/46490360]

oberstet@intel-nuci7:~$ chmod +x crossbarfx-latest 
oberstet@intel-nuci7:~$ ./crossbarfx-latest version


    :::::::::::::::::
          :::::          _____                 __              _____  _______
    :::::   :   :::::   / ___/______  ___ ___ / /  ___ _____  / __/ |/_/ ___/
    :::::::   :::::::  / /__/ __/ _ \(_-<(_-</ _ \/ _ `/ __/ / _/_>  </ /__
    :::::   :   :::::  \___/_/  \___/___/___/_.__/\_,_/_/   /_/ /_/|_|\___/
          :::::
    :::::::::::::::::   Crossbar.io Fabric XBR Center v19.9.4 [20190921-0c08025]

    Copyright (c) 2013-2019 Crossbar.io Technologies GmbH. All rights reserved.

 Crossbar.io        : 19.10.1
   txaio            : 18.8.1
   Autobahn         : 19.9.3
     UTF8 Validator : autobahn
     XOR Masker     : autobahn
     JSON Codec     : stdlib
     MsgPack Codec  : msgpack-0.6.2
     CBOR Codec     : cbor-1.0.0
     UBJSON Codec   : ubjson-0.14.0
     FlatBuffers    : flatbuffers-?.?.?
   Twisted          : 19.7.0-EPollReactor
   LMDB             : 0.97/lmdb-0.9.22
   Python           : 3.7.1/CPython
 CrossbarFX         : 19.9.4
   NumPy            : 1.15.4
   zLMDB            : 19.9.3
 Frozen executable  : yes
 Operating system   : Linux-4.15.0-64-generic-x86_64-with-debian-buster-sid
 Host machine       : x86_64
 Release key        : RWRlUB1klnmQWao9JKtkTu5GeI74LHoQnhH8q7vvT+oRlbyWRmd74kbw

oberstet@intel-nuci7:~$ 
```

> sidenote, just because I quickly looked at the code location you posted: there are more issues .. for example, removing an already imported reactor (`del sys.modules['twisted.internet.reactor']`) - this is at best a hack that might or might not work in some scenarios. twisted, once a reactor has been imported wants to stick with that. iow: make sure you don't trigger an import before you yourself import and start a manually selected reactor. crossbar is rigorously following this approach (which sometimes can be painful to achieve due to implicit imports).

**Comment by etam** [comment]
> for example, removing an already imported reactor (`del sys.modules['twisted.internet.reactor']`) - this is at best a hack that might or might not work in some scenarios.

I already had problems with this. We know. :)
