### ISSUE TITLE
Docker issue: Getting PermissionError: [Errno 13] Permission denied: '/node/.crossbar/node.pid' on linux

### ISSUE THREAD

**Issue by hqm** [crossbario/crossbar#1672]
I've got a script which is supposed to run the prebuilt crossbar router from crossbar.io, it just contains this command

docker run -it -p 1964:1964 -v `pwd`:/node crossbario/crossbar

It works fine on my Macbook, but when I run it I get this error on our ubuntu linux server:

2019-12-27T05:00:15+0000 [Controller      1] Traceback (most recent call last):

2019-12-27T05:00:15+0000 [Controller      1]   File "/usr/local/bin/crossbar", line 10, in <module>

2019-12-27T05:00:15+0000 [Controller      1]     sys.exit(run())

2019-12-27T05:00:15+0000 [Controller      1]   File "/usr/local/lib/python3.7/site-packages/crossbar/__init__.py", line 205, in run

2019-12-27T05:00:15+0000 [Controller      1]     return main(exename, args, reactor, personality_klass)

2019-12-27T05:00:15+0000 [Controller      1]   File "/usr/local/lib/python3.7/site-packages/crossbar/node/main.py", line 1293, in main

2019-12-27T05:00:15+0000 [Controller      1]     options.func(options, reactor=reactor, personality=personality)

2019-12-27T05:00:15+0000 [Controller      1]   File "/usr/local/lib/python3.7/site-packages/crossbar/node/main.py", line 755, in _run_command_start

2019-12-27T05:00:15+0000 [Controller      1]     with open(fp, 'wb') as fd:

2019-12-27T05:00:15+0000 [Controller      1] PermissionError: [Errno 13] Permission denied: '/node/.crossbar/node.pid'

hqm@leeladev:~/src/jleela/router$ 

Of all things, I don't see how this can be getting an error when running on linux vs osx;  it's inside a docker container so should always run exactly the same in any environment.

I never get this  error running  the container on my macbook, and I don't run it as root or anything.

A co-worker modified the docker container to run the job as root and that made it work, but why should that be needed?

**Comment by oberstet** [comment]
docker;)

the reason is that `'/node/.crossbar/node.pid` actually resides on your host system, as there is a docker volume mounted. crossbar running inside the container wants to write a PID file, and it runs as user U1 inside the container (where U1 is a user inside the container), which maps to U2 on your host (and the mapping is merely by user numeric ID), and hence U2 needs write access to the directory, and `node.pid` in particular.

here https://github.com/crossbario/crossbar/blob/master/docker/x86_64/Dockerfile.cpy3#L51

**Comment by hqm** [comment]
I see. I'm still wondering why it 'just worked' on my mac laptop? 
Maybe there's a coincidental matching of the userid being used in the crossbar container to some userid on the Mac that happens to have write permissions to the .crossbar directory it's looking for?

**Comment by oberstet** [comment]
fwiw, the user id that crossbar wants to use is set here https://github.com/crossbario/crossbar/blob/master/docker/x86_64/Dockerfile.cpy3#L53

> Maybe there's a coincidental matching of the userid being used in the crossbar container to some userid on the Mac that happens to have write permissions to the .crossbar directory it's looking for?

That could happen - and that would be less than ideal of course. In general, the way it is done currently sucks, I would agree;)

Those Dockerfiles have been around a while, also evolved over time. IMO, they lack in eg above, and also rgd the way different CPU architectures are handled. Crossbar's Docker image scripts for ARM predate the (now) promoted / official way .. need to work on that too. 

Closing this one --- sounds like you could get it going
