### ISSUE TITLE
Crossbar can't be used with Python 3.8 on Windows

### ISSUE THREAD

**Issue by zrneely** [crossbario/crossbar#1682]
* crossbar version: 20.1.1
* ZLMDB version: 19.11.1
* Python version: 3.8.0
* Operating System: Windows 10

On Windows, zlmdb uses the method time.clock() (deprecated since Python 3.3) which has been removed in Python 3.8. This means that `crossbar` is unusable with Python 3.8. #268 suggests to me that crossbar intends to support Python 3, despite the published installation instructions mentioning Python 2.7 (which is no longer supported by the PSF as of 1/2020).

I wasn't sure if I should file the issue here, or on crossbario/zlmdb. Hopefully I did the right thing putting it here.

```
C:\users\...\>crossbar version
Traceback (most recent call last):
  File "c:\users\...\appdata\local\programs\python\python38\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\...\appdata\local\programs\python\python38\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\...\AppData\Local\Programs\Python\Python38\Scripts\crossbar.exe\__main__.py", line 7, in <module>
  File "c:\users\...\appdata\local\programs\python\python38\lib\site-packages\crossbar\__init__.py", line 175, in run
    _personalities = personalities()
  File "c:\users\...\appdata\local\programs\python\python38\lib\site-packages\crossbar\__init__.py", line 213, in personalities
    from crossbar import personality as standalone
  File "c:\users\...\appdata\local\programs\python\python38\lib\site-packages\crossbar\personality.py", line 39, in <module>
    from crossbar.node import node
  File "c:\users\...\appdata\local\programs\python\python38\lib\site-packages\crossbar\node\node.py", line 43, in <module>
    from crossbar.router.router import RouterFactory
  File "c:\users\...\appdata\local\programs\python\python38\lib\site-packages\crossbar\router\router.py", line 41, in <module>
    from crossbar.router.dealer import Dealer
  File "c:\users\...\appdata\local\programs\python\python38\lib\site-packages\crossbar\router\dealer.py", line 49, in <module>
    from crossbar.worker import rlink
  File "c:\users\...\appdata\local\programs\python\python38\lib\site-packages\crossbar\worker\rlink.py", line 49, in <module>
    from zlmdb import time_ns
  File "c:\users\...\appdata\local\programs\python\python38\lib\site-packages\zlmdb\__init__.py", line 103, in <module>
    from ._transaction import Transaction, TransactionStats, walltime
  File "c:\users\...\appdata\local\programs\python\python38\lib\site-packages\zlmdb\_transaction.py", line 41, in <module>
    walltime = time.clock
AttributeError: module 'time' has no attribute 'clock'
```

**Comment by oberstet** [comment]
fixed on master via https://github.com/crossbario/crossbar/pull/1685
