### ISSUE TITLE
Log message formatting regression

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#1698]
this commit here totally makes sense, but it triggered some log formatting fallout down the line in container component shutdown

**crossbar/worker/container.py", line 493, in _publish_component_stop**

when stopping a node:

```
2020-02-05T09:26:05+0100 [Controller  13578] FabricServiceNodeManager ready!
^C2020-02-05T09:26:08+0100 [Controller  13578] Controller received SIGINT [signal=2]: shutting down node [shutdown_was_clean=True] ..
2020-02-05T09:26:08+0100 [Controller  13578] Node shutdown requested (restart=False, mode=None, reactor.running=True) ..
2020-02-05T09:26:08+0100 [Controller  13578] FabricNodeControllerSession._shutdown(restart=False, mode=None)
2020-02-05T09:26:08+0100 [Controller  13578] sending TERM to subprocess 13588
2020-02-05T09:26:08+0100 [Controller  13578] waiting for 13588 to exit...
2020-02-05T09:26:08+0100 [Controller  13578] sending TERM to subprocess 13598
2020-02-05T09:26:08+0100 [Controller  13578] waiting for 13598 to exit...
2020-02-05T09:26:08+0100 [Controller  13578] sending TERM to subprocess 13608
2020-02-05T09:26:08+0100 [Controller  13578] waiting for 13608 to exit...
2020-02-05T09:26:08+0100 [Router      13588] Native worker received SIGTERM - shutting down ..
2020-02-05T09:26:08+0100 [Router      13588] Shutdown of worker requested!
2020-02-05T09:26:08+0100 [Container   13598] Native worker received SIGTERM - shutting down ..
2020-02-05T09:26:08+0100 [Container   13598] session closed with reason wamp.close.transport_lost [WAMP transport was lost without closing the session 6642412509418625 before]
2020-02-05T09:26:08+0100 [Container   13608] Native worker received SIGTERM - shutting down ..
2020-02-05T09:26:08+0100 [Container   13608] session closed with reason wamp.close.transport_lost [WAMP transport was lost without closing the session 7848366894658509 before]
2020-02-05T09:26:08+0100 [Container   13608] Closed connection to 'mrealm1'
2020-02-05T09:26:08+0100 [Container   13598] Closed connection to 'component002'
2020-02-05T09:26:08+0100 [Container   13598] Unhandled error in Deferred:
2020-02-05T09:26:08+0100 [Container   13608] Unhandled error in Deferred:
2020-02-05T09:26:08+0100 [Router      13588] Router.detach(session=6642412509418625)
2020-02-05T09:26:08+0100 [Router      13588] Router.detach(session=6642412509418625): detached sessions [6642412509418625] from router realm "com.crossbario.fabric"
2020-02-05T09:26:08+0100 [Container   13608] 
Traceback (most recent call last):
  File "/home/oberstet/cpy381_3/lib/python3.8/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/oberstet/scm/crossbario/autobahn-python/autobahn/wamp/protocol.py", line 1240, in success
    return self.fire('disconnect', self, was_clean=wasClean)
  File "/home/oberstet/scm/crossbario/autobahn-python/autobahn/util.py", line 817, in fire
    future = txaio.as_future(handler, *args, **kwargs)
  File "/home/oberstet/scm/crossbario/txaio/txaio/tx.py", line 366, in as_future
    return maybeDeferred(fun, *args, **kwargs)
--- <exception caught here> ---
  File "/home/oberstet/cpy381_3/lib/python3.8/site-packages/twisted/internet/defer.py", line 151, in maybeDeferred
    result = f(*args, **kw)
  File "/home/oberstet/scm/crossbario/crossbar/crossbar/worker/container.py", line 288, in _closed
    self._publish_component_stop(component)
  File "/home/oberstet/scm/crossbario/crossbar/crossbar/worker/container.py", line 493, in _publish_component_stop
    self.publish(topic, event)
  File "/home/oberstet/scm/crossbario/autobahn-python/autobahn/wamp/protocol.py", line 1440, in publish
    raise e
  File "/home/oberstet/scm/crossbario/autobahn-python/autobahn/wamp/protocol.py", line 1436, in publish
    self._transport.send(msg)
  File "/home/oberstet/scm/crossbario/autobahn-python/autobahn/wamp/websocket.py", line 125, in send
    self.sendMessage(payload, isBinary)
  File "/home/oberstet/scm/crossbario/autobahn-python/autobahn/websocket/protocol.py", line 2190, in sendMessage
    raise Disconnected("Attempt to send on a closed protocol")
autobahn.exception.Disconnected: Attempt to send on a closed protocol

```

**Comment by oberstet** [comment]
oops, actually I mixed up what CB(X) version I was actually running .. invalid
