### ISSUE TITLE
proxy: Attempt to send on a closed protocol

### ISSUE THREAD

**Issue by om26er** [crossbario/crossbar#1725]
That is mostly harmless as the proxy worker continues to run.

```
2020-03-03T22:45:21+0000 [Router      15624] Router.detach(session=8090859270541761)
2020-03-03T22:45:21+0000 [Router      15624] Router.detach(session=8090859270541761): detached sessions [8090859270541761] from router realm "crossbardemo"
2020-03-03T22:45:21+0000 [Proxy       15635] Traceback (most recent call last):
  File "/home/ubuntu/autobahn-python/autobahn/wamp/websocket.py", line 95, in onMessage
    self._session.onMessage(msg)
  File "/home/ubuntu/cfx/venv/lib/python3.6/site-packages/crossbar/worker/proxy.py", line 100, in onMessage
    self._frontend.forward_message(msg)
  File "/home/ubuntu/cfx/venv/lib/python3.6/site-packages/crossbar/worker/proxy.py", line 233, in forward_message
    self.sendMessage(data, is_binary)
  File "/home/ubuntu/autobahn-python/autobahn/websocket/protocol.py", line 2216, in sendMessage
    raise Disconnected("Attempt to send on a closed protocol")
autobahn.exception.Disconnected: Attempt to send on a closed protocol

2020-03-03T22:45:21+0000 [Proxy       15635] failing WebSocket connection (code=1011): "WAMP Internal Error (Attempt to send on a closed protocol)"
2020-03-03T22:45:21+0000 [Proxy       15635] dropping connection to peer unix:b'router.sock' with abort=True: I dropped the WebSocket TCP connection: WAMP Internal Error (Attempt to send on a closed protocol)
2020-03-03T22:45:21+0000 [Proxy       15635] Stopping factory <autobahn.twisted.websocket.WampWebSocketClientFactory object at 0x7ff048dad470>
```

**Comment by om26er** [comment]
That happens when page with active wamp session is refreshed

**Comment by meejah** [comment]
Hmm, can't repeat with: a backend thing sending 1000 publishes per second and a frontend listening (via JS). Then just randomly refreshing the page .. but, try this? https://github.com/crossbario/crossbar/pull/1726

**Comment by oberstet** [comment]
and probably also related https://github.com/crossbario/crossbar/commit/15ba65e0608f8de5bc0c73406494acabbe76374a

closing for now (haven't seen it anymore) ..
