### ISSUE TITLE
Proxy frontend WELCOME info

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#1738]
Seems like it currently lacks `authmethod` ?

here is a test with websocket + rawsocket (over TLS and non-TLS) printing the session details in `onJoin`:

```console
(cpy381_3) oberstet@thinkpad-x1:~/scm/crossbario/<REDACTED>$ CBURL=rss://<REDACTED>1.crossbario.com CBREALM=dvl1 python backend/backend.py
2020-03-30T17:21:40+0200 Client joined 
2020-03-30T17:21:40+0200 SessionDetails(realm="dvl1",
2020-03-30T17:21:40+0200                session=6739968003453020,
2020-03-30T17:21:40+0200                authid=None,
2020-03-30T17:21:40+0200                authrole="anonymous",
2020-03-30T17:21:40+0200                authmethod=None,
2020-03-30T17:21:40+0200                authprovider="anonymous",
2020-03-30T17:21:40+0200                authextra=None,
2020-03-30T17:21:40+0200                serializer="cbor",
2020-03-30T17:21:40+0200                transport="rawsocket.twisted",
2020-03-30T17:21:40+0200                resumed=None,
2020-03-30T17:21:40+0200                resumable=None,
2020-03-30T17:21:40+0200                resume_token=None)
^C2020-03-30T17:22:02+0200 Received SIGINT, shutting down.
2020-03-30T17:22:02+0200 WampRawSocketClientProtocol.stringReceived: WAMP ProtocolError - aborting connection!
Unexpected message <class 'autobahn.wamp.message.Abort'>
2020-03-30T17:22:02+0200 session closed with reason wamp.close.transport_lost [WAMP transport was lost without closing the session 6739968003453020 before]
2020-03-30T17:22:02+0200 Scheduling retry 1 to connect <twisted.internet.endpoints.SSL4ClientEndpoint object at 0x7f9f739fe1c0> in 1.8171652654340815 seconds.
2020-03-30T17:22:02+0200 Main loop terminated.
(cpy381_3) oberstet@thinkpad-x1:~/scm/crossbario/<REDACTED>$ CBURL=rs://<REDACTED>1.crossbario.com CBREALM=dvl1 python backend/backend.py
2020-03-30T17:22:09+0200 Client joined 
2020-03-30T17:22:09+0200 SessionDetails(realm="dvl1",
2020-03-30T17:22:09+0200                session=4901737823255013,
2020-03-30T17:22:09+0200                authid=None,
2020-03-30T17:22:09+0200                authrole="anonymous",
2020-03-30T17:22:09+0200                authmethod=None,
2020-03-30T17:22:09+0200                authprovider="anonymous",
2020-03-30T17:22:09+0200                authextra=None,
2020-03-30T17:22:09+0200                serializer="cbor",
2020-03-30T17:22:09+0200                transport="rawsocket.twisted",
2020-03-30T17:22:09+0200                resumed=None,
2020-03-30T17:22:09+0200                resumable=None,
2020-03-30T17:22:09+0200                resume_token=None)
^C2020-03-30T17:22:10+0200 Received SIGINT, shutting down.
2020-03-30T17:22:11+0200 WampRawSocketClientProtocol.stringReceived: WAMP ProtocolError - aborting connection!
Unexpected message <class 'autobahn.wamp.message.Abort'>
2020-03-30T17:22:11+0200 session closed with reason wamp.close.transport_lost [WAMP transport was lost without closing the session 4901737823255013 before]
2020-03-30T17:22:11+0200 Scheduling retry 1 to connect <twisted.internet.endpoints.TCP4ClientEndpoint object at 0x7f6798d237c0> in 2.113455556584111 seconds.
2020-03-30T17:22:11+0200 Main loop terminated.
(cpy381_3) oberstet@thinkpad-x1:~/scm/crossbario/<REDACTED>$ CBURL=wss://<REDACTED>1.crossbario.com/ws CBREALM=dvl1 python backend/backend.py
2020-03-30T17:22:21+0200 Client joined 
2020-03-30T17:22:21+0200 SessionDetails(realm="dvl1",
2020-03-30T17:22:21+0200                session=8114542305887311,
2020-03-30T17:22:21+0200                authid=None,
2020-03-30T17:22:21+0200                authrole="anonymous",
2020-03-30T17:22:21+0200                authmethod=None,
2020-03-30T17:22:21+0200                authprovider="anonymous",
2020-03-30T17:22:21+0200                authextra=None,
2020-03-30T17:22:21+0200                serializer="cbor",
2020-03-30T17:22:21+0200                transport="websocket.twisted",
2020-03-30T17:22:21+0200                resumed=None,
2020-03-30T17:22:21+0200                resumable=None,
2020-03-30T17:22:21+0200                resume_token=None)
^C2020-03-30T17:22:22+0200 Received SIGINT, shutting down.
2020-03-30T17:22:22+0200 Traceback (most recent call last):
  File "/home/oberstet/scm/crossbario/autobahn-python/autobahn/wamp/websocket.py", line 95, in onMessage
    self._session.onMessage(msg)
  File "/home/oberstet/scm/crossbario/autobahn-python/autobahn/wamp/protocol.py", line 1234, in onMessage
    raise ProtocolError("Unexpected message {0}".format(msg.__class__))
autobahn.wamp.exception.ProtocolError: Unexpected message <class 'autobahn.wamp.message.Abort'>

2020-03-30T17:22:22+0200 failing WebSocket connection (code=1002): "WAMP Protocol Error (Unexpected message <class 'autobahn.wamp.message.Abort'>)"
2020-03-30T17:22:22+0200 session closed with reason wamp.close.transport_lost [WAMP transport was lost without closing the session 8114542305887311 before]
2020-03-30T17:22:22+0200 Scheduling retry 1 to connect <twisted.internet.endpoints.SSL4ClientEndpoint object at 0x7f9fafe5fc40> in 1.856302010088619 seconds.
2020-03-30T17:22:22+0200 Main loop terminated.
(cpy381_3) oberstet@thinkpad-x1:~/scm/crossbario/<REDACTED>$ CBURL=ws://<REDACTED>1.crossbario.com/ws CBREALM=dvl1 python backend/backend.py
2020-03-30T17:22:29+0200 Client joined 
2020-03-30T17:22:29+0200 SessionDetails(realm="dvl1",
2020-03-30T17:22:29+0200                session=7131859943102440,
2020-03-30T17:22:29+0200                authid=None,
2020-03-30T17:22:29+0200                authrole="anonymous",
2020-03-30T17:22:29+0200                authmethod=None,
2020-03-30T17:22:29+0200                authprovider="anonymous",
2020-03-30T17:22:29+0200                authextra=None,
2020-03-30T17:22:29+0200                serializer="cbor",
2020-03-30T17:22:29+0200                transport="websocket.twisted",
2020-03-30T17:22:29+0200                resumed=None,
2020-03-30T17:22:29+0200                resumable=None,
2020-03-30T17:22:29+0200                resume_token=None)
^C2020-03-30T17:22:31+0200 Received SIGINT, shutting down.
2020-03-30T17:22:31+0200 Traceback (most recent call last):
  File "/home/oberstet/scm/crossbario/autobahn-python/autobahn/wamp/websocket.py", line 95, in onMessage
    self._session.onMessage(msg)
  File "/home/oberstet/scm/crossbario/autobahn-python/autobahn/wamp/protocol.py", line 1234, in onMessage
    raise ProtocolError("Unexpected message {0}".format(msg.__class__))
autobahn.wamp.exception.ProtocolError: Unexpected message <class 'autobahn.wamp.message.Abort'>

2020-03-30T17:22:31+0200 failing WebSocket connection (code=1002): "WAMP Protocol Error (Unexpected message <class 'autobahn.wamp.message.Abort'>)"
2020-03-30T17:22:31+0200 session closed with reason wamp.close.transport_lost [WAMP transport was lost without closing the session 7131859943102440 before]
2020-03-30T17:22:31+0200 Scheduling retry 1 to connect <twisted.internet.endpoints.TCP4ClientEndpoint object at 0x7ff2fdb99eb0> in 1.9764097954114188 seconds.
2020-03-30T17:22:31+0200 Main loop terminated.
(cpy381_3) oberstet@thinkpad-x1:~/scm/crossbario/<REDACTED>$ 
```

**Comment by oberstet** [comment]
fixed via https://github.com/crossbario/crossbar/pull/1741
