### ISSUE TITLE
proxy workers: traceback

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#1801]
```
node1     | 2020-07-31T18:28:46+0000 [Proxy          18] Unhandled error in Deferred:
node1     | 2020-07-31T18:28:46+0000 [Proxy          18] 
node1     | Traceback (most recent call last):
node1     |   File "/usr/local/site-packages/twisted/internet/base.py", line 1163, in connectionFailed
node1     |     self.factory.clientConnectionFailed(self, reason)
node1     |   File "/usr/local/site-packages/twisted/internet/endpoints.py", line 270, in clientConnectionFailed
node1     |     self._onConnection.errback(reason)
node1     |   File "/usr/local/site-packages/twisted/internet/defer.py", line 501, in errback
node1     |     self._startRunCallbacks(fail)
node1     |   File "/usr/local/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
node1     |     self._runCallbacks()
node1     | --- <exception caught here> ---
node1     |   File "/usr/local/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
node1     |     current.result = callback(current.result, *args, **kw)
node1     |   File "/usr/local/site-packages/crossbar/worker/proxy.py", line 761, in _connected
node1     |     proto._proxy_other_side = frontend_session
node1     | builtins.AttributeError: 'NoneType' object has no attribute '_proxy_other_side'
node1     | 
```

**Comment by oberstet** [comment]
this is fixed
