### ISSUE TITLE
Cannot install crossbar because lmdb upgrade to v1.0.0

### ISSUE THREAD

**Issue by duybinh0208** [crossbario/crossbar#1818]
```
Collecting lmdb>=0.92
  Downloading lmdb-1.0.0.tar.gz (876 kB)
    ERROR: Command errored out with exit status 1:
     command: /app/Python-3.7.5/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-wnix0zhx/lmdb/setup.py'"'"'; __file__='"'"'/tmp/pip-install-wnix0zhx/lmdb/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-c_utmq6p
         cwd: /tmp/pip-install-wnix0zhx/lmdb/
    Complete output (7 lines):
    sh: /usr/bin/patch: No such file or directory
    py-lmdb: Using bundled liblmdb with py-lmdb patches; override with LMDB_FORCE_SYSTEM=1 or LMDB_PURE=1.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-wnix0zhx/lmdb/setup.py", line 119, in <module>
        raise Exception('Applying patch failed')
    Exception: Applying patch failed
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
The command '/bin/bash -o pipefail -c pip install crossbar==20.4.2' returned a non-zero code: 1
```

If I install the previous version: `pip install lmdb==0.99` then I can install crossbar: `pip install crossbar`

**Comment by oberstet** [comment]
I tried, works for me:

```
oberstet@intel-nuci7:~$ source ~/cpy382_1/bin/activate
(cpy382_1) oberstet@intel-nuci7:~$ pip show lmdb
Name: lmdb
Version: 0.98
Summary: Universal Python binding for the LMDB 'Lightning' Database
Home-page: http://github.com/jnwatson/py-lmdb/
Author: David Wilson
Author-email: None
License: OpenLDAP BSD
Location: /home/oberstet/cpy382_1/lib/python3.8/site-packages
Requires: 
Required-by: pynndb, crossbar, zlmdb
(cpy382_1) oberstet@intel-nuci7:~$ pip install -U lmdb
Collecting lmdb
Installing collected packages: lmdb
  Found existing installation: lmdb 0.98
    Uninstalling lmdb-0.98:
      Successfully uninstalled lmdb-0.98
Successfully installed lmdb-1.0.0
WARNING: You are using pip version 19.2.3, however version 20.2.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(cpy382_1) oberstet@intel-nuci7:~$ pip show lmdb
Name: lmdb
Version: 1.0.0
Summary: Universal Python binding for the LMDB 'Lightning' Database
Home-page: http://github.com/jnwatson/py-lmdb/
Author: David Wilson
Author-email: None
License: OpenLDAP BSD
Location: /home/oberstet/cpy382_1/lib/python3.8/site-packages
Requires: 
Required-by: pynndb, crossbar, zlmdb
(cpy382_1) oberstet@intel-nuci7:~$ 
(cpy382_1) oberstet@intel-nuci7:~$ python -V
Python 3.8.2
(cpy382_1) oberstet@intel-nuci7:~$ crossbar version


    :::::::::::::::::
          :::::          _____                      __
    :::::   :   :::::   / ___/____ ___   ___  ___  / /  ___ _ ____
    :::::::   :::::::  / /__ / __// _ \ (_-< (_-< / _ \/ _ `// __/
    :::::   :   :::::  \___//_/   \___//___//___//_.__/\_,_//_/
          :::::
    :::::::::::::::::   Crossbar v20.8.1

    Copyright (c) 2013-2020 Crossbar.io Technologies GmbH, licensed under AGPL 3.0.

 Crossbar.io        : 20.8.1
   txaio            : 20.4.1
   Autobahn         : 20.7.1
     UTF8 Validator : wsaccel-0.6.2
     XOR Masker     : wsaccel-0.6.2
     JSON Codec     : stdlib
     MsgPack Codec  : msgpack-1.0.0
     CBOR Codec     : cbor-1.0.0
     UBJSON Codec   : ubjson-0.16.1
     FlatBuffers    : flatbuffers-1.12
   Twisted          : 20.3.0-EPollReactor
   LMDB             : 1.0.0/lmdb-0.9.24
   Python           : 3.8.2/CPython
 Frozen executable  : no
 Operating system   : Linux-4.15.0-118-generic-x86_64-with-glibc2.2.5
 Host machine       : x86_64
 Release key        : RWQ4VrXXmZuEsP4YXlhRfRu+ZqVwNC1qmyJaWCXX/sv4Dqiy4SiPa0Yy

(cpy382_1) oberstet@intel-nuci7:~$ 
```

**Comment by oberstet** [comment]
this is fixed - just verified again on a fresh venv https://gist.github.com/oberstet/5cc8eb3102ac7fdde58b84379a8cfb28

```
LMDB             : 1.1.1/lmdb-0.9.26
```
