### ISSUE TITLE
msgpack not listed in requirements-min, requires separate installation

### ISSUE THREAD

**Issue by Emantor** [crossbario/crossbar#1822]
Currently crossbar does not contain `msgpack` in requirements-min.txt, but unconditionally requires it through import of the autobahn `MsgPackObjectSerializer`. Stacktrace from a CI run of labgrid without `msgpack` being explicitly added:
```
crossbar: /home/travis/virtualenv/python3.5.7/lib/python3.5/site-packages/OpenSSL/crypto.py:12: CryptographyDeprecationWarning: Python 3.5 support will be dropped in the next release of cryptography. Please upgrade your Python.
crossbar:   from cryptography import x509
crossbar: 
crossbar: Traceback (most recent call last):
crossbar:   File "/home/travis/virtualenv/python3.5.7/bin/crossbar", line 10, in <module>
crossbar:     sys.exit(run())
crossbar:   File "/home/travis/virtualenv/python3.5.7/lib/python3.5/site-packages/crossbar/__init__.py", line 175, in run
crossbar:     _personalities = personalities()
crossbar:   File "/home/travis/virtualenv/python3.5.7/lib/python3.5/site-packages/crossbar/__init__.py", line 213, in personalities
crossbar:     from crossbar import personality as standalone
crossbar:   File "/home/travis/virtualenv/python3.5.7/lib/python3.5/site-packages/crossbar/personality.py", line 41, in <module>
crossbar:     from crossbar.worker.router import RouterController
crossbar:   File "/home/travis/virtualenv/python3.5.7/lib/python3.5/site-packages/crossbar/worker/router.py", line 30, in <module>
crossbar:     from crossbar.worker.transport import TransportController
crossbar:   File "/home/travis/virtualenv/python3.5.7/lib/python3.5/site-packages/crossbar/worker/transport.py", line 49, in <module>
crossbar:     from crossbar.bridge.mqtt.wamp import WampMQTTServerFactory
crossbar:   File "/home/travis/virtualenv/python3.5.7/lib/python3.5/site-packages/crossbar/bridge/mqtt/wamp.py", line 52, in <module>
crossbar:     from autobahn.wamp.serializer import JsonObjectSerializer, MsgPackObjectSerializer, CBORObjectSerializer, UBJSONObjectSerializer
crossbar: ImportError: cannot import name 'MsgPackObjectSerializer'
crossbar startup failed with b'/home/travis/virtualenv/python3.5.7/lib/python3.5/site-packages/OpenSSL/crypto.py:12: CryptographyDeprecationWarning: Python 3.5 support will be dropped in the next release of cryptography. Please upgrade your Python.\r\n  from cryptography import x509\r\n\r\nTraceback (most recent call last):\r\n  File "/home/travis/virtualenv/python3.5.7/bin/crossbar", line 10, in <module>\r\n    sys.exit(run())\r\n  File "/home/travis/virtualenv/python3.5.7/lib/python3.5/site-packages/crossbar/__init__.py", line 175, in run\r\n    _personalities = personalities()\r\n  File "/home/travis/virtualenv/python3.5.7/lib/python3.5/site-packages/crossbar/__init__.py", line 213, in personalities\r\n    from crossbar import personality as standalone\r\n  File "/home/travis/virtualenv/python3.5.7/lib/python3.5/site-packages/crossbar/personality.py", line 41, in <module>\r\n    from crossbar.worker.router import RouterController\r\n  File "/home/travis/virtualenv/python3.5.7/lib/python3.5/site-packages/crossbar/worker/router.py", line 30, in <module>\r\n    from crossbar.worker.transport import TransportController\r\n  File "/home/travis/virtualenv/python3.5.7/lib/python3.5/site-packages/crossbar/worker/transport.py", line 49, in <module>\r\n    from crossbar.bridge.mqtt.wamp import WampMQTTServerFactory\r\n  File "/home/travis/virtualenv/python3.5.7/lib/python3.5/site-packages/crossbar/bridge/mqtt/wamp.py", line 52, in <module>\r\n    from autobahn.wamp.serializer import JsonObjectSerializer, MsgPackObjectSerializer, CBORObjectSerializer, UBJSONObjectSerializer\r\nImportError: cannot import name \'MsgPackObjectSerializer\'\r\n'
```

Is this an upstream issues or do I need to keep the downstream requirement which includes `msgpack`?

**Comment by oberstet** [comment]
msgpack does come in indirectly, via `autobahn[compression]`:

* https://github.com/crossbario/crossbar/blob/20540f11af6f3e965b2da9425babbe5ed50d6136/requirements-min.txt#L2
* https://github.com/crossbario/crossbar/blob/20540f11af6f3e965b2da9425babbe5ed50d6136/requirements-latest.txt#L2
* https://github.com/crossbario/crossbar/blob/20540f11af6f3e965b2da9425babbe5ed50d6136/requirements-pinned.txt#L28

and

* https://github.com/crossbario/autobahn-python/blob/3ea4fdae9814641f6dcc03a2deb4e555b2f9a776/setup.py#L68

the best file to use (if you can't do a simple pip install) is probably `requirements-pinned.txt`, and the installation should be into a dedicated virtualenv, container or snap

**Comment by oberstet** [comment]
another option would be to depend on `autobahn[compression]` or `autobahn[all]`
