### ISSUE TITLE
remove broken vmprof

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#1874]
(cpy392_4) oberstet@intel-nuci7:~/scm/crossbario/crossbar$ crossbar version

Traceback (most recent call last):
  File "/home/oberstet/cpy392/bin/crossbar", line 33, in <module>
    sys.exit(load_entry_point('crossbar', 'console_scripts', 'crossbar')())
  File "/home/oberstet/cpy392/bin/crossbar", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/oberstet/cpy392/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/home/oberstet/cpy392/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/oberstet/scm/crossbario/crossbar/crossbar/__init__.py", line 22, in <module>
    import humanize  # noqa
  File "/home/oberstet/cpy392/lib/python3.9/site-packages/humanize/__init__.py", line 2, in <module>
    import pkg_resources
  File "/home/oberstet/cpy392/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3257, in <module>
    def _initialize_master_working_set():
  File "/home/oberstet/cpy392/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3240, in _call_aside
    f(*args, **kwargs)
  File "/home/oberstet/cpy392/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3269, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/oberstet/cpy392/lib/python3.9/site-packages/pkg_resources/__init__.py", line 582, in _build_master
    ws.require(__requires__)
  File "/home/oberstet/cpy392/lib/python3.9/site-packages/pkg_resources/__init__.py", line 899, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/oberstet/cpy392/lib/python3.9/site-packages/pkg_resources/__init__.py", line 785, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'vmprof>=0.4.15' distribution was not found and is required by crossbar

**Comment by om26er** [comment]
The version of vmprof published on pypi cannot be installed on Ubuntu 21.04, which means installing crossbar from source does not work either.

Shall we remove it all together ?

**Comment by oberstet** [comment]
ok, just retried: works for me now (vmprof 0.4.14 https://pypi.org/project/vmprof/0.4.15/ on ubuntu 20.04):

```
oberstet@intel-nuci7:~$ source ~/cpy39_1/bin/activate
(cpy39_1) oberstet@intel-nuci7:~$ pip show vmprof
Name: vmprof
Version: 0.4.15
Summary: Python's vmprof client
Home-page: https://github.com/vmprof/vmprof-python
Author: vmprof team
Author-email: fijal@baroquesoftware.com
License: UNKNOWN
Location: /home/oberstet/cpy39_1/lib/python3.9/site-packages
Requires: pytz, colorama, six, requests
Required-by: crossbar
(cpy39_1) oberstet@intel-nuci7:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
(cpy39_1) oberstet@intel-nuci7:~$ crossbar version


    :::::::::::::::::
          :::::          _____                 __              _____  __
    :::::   :   :::::   / ___/______  ___ ___ / /  ___ _____  / __/ |/_/
    :::::::   :::::::  / /__/ __/ _ \(_-<(_-</ _ \/ _ `/ __/ / _/_>  <
    :::::   :   :::::  \___/_/  \___/___/___/_.__/\_,_/_/   /_/ /_/|_|
          :::::
    :::::::::::::::::   Crossbar.io FX v21.6.1.dev1 [19000101-0000000]

    Copyright (c) 2013-2021 Crossbar.io Technologies GmbH. All rights reserved.

 Crossbar.io        : 21.6.1.dev1
   txaio            : 21.2.1
   Autobahn         : 21.3.1
     UTF8 Validator : wsaccel-0.6.2
     XOR Masker     : wsaccel-0.6.2
     JSON Codec     : stdlib
     MsgPack Codec  : msgpack-1.0.2
     CBOR Codec     : cbor-1.0.0
     UBJSON Codec   : ubjson-0.16.1
     FlatBuffers    : flatbuffers-1.12
   Twisted          : 21.2.0-EPollReactor
   LMDB             : 1.2.1/lmdb-0.9.29
   Python           : 3.9.4/CPython
   PIP              : 19.3.1
   NumPy            : 1.20.2
   zLMDB            : 21.2.1
   CFXDB            : 21.2.1
   XBR              : 21.2.1
 Frozen executable  : no
 Operating system   : Linux-5.4.0-80-generic-x86_64-with-glibc2.31
 Host machine       : x86_64
 Release key        : RWQAuKCmh07GueDGPDEe/SwEbGXicGlJj+kDpjA9kVAPwQ6pmPDsCA7/

(cpy39_1) oberstet@intel-nuci7:~$ 
```

ubuntu  21.04: not sure .. with the distro python? I don't care about that. it works on 20.04 with a vanilla python ..

**Comment by om26er** [comment]
> ubuntu 21.04: not sure .. with the distro python? I don't care about that. it works on 20.04 with a vanilla python ..

I investigated a bit more into it and the issue started with GCC 10 (https://gcc.gnu.org/gcc-10/porting_to.html). The vmprof upstream fixed it with this commit https://github.com/vmprof/vmprof-python/commit/0aa7ad29fc08759dfa878b4d276367e7e09b2457

My workaround is to set the below environment variable before installation
```
export CFLAGS=-fcommon
```

So my issue is resolved now, since I have a workaround.

**Comment by oberstet** [comment]
good to hear, thanks for the note on gcc!

**Comment by oberstet** [comment]
it is almost unbroken;) https://github.com/crossbario/crossbar/issues/1896
