### ISSUE TITLE
Problems moving to Python3

### ISSUE THREAD

**Issue by megastallman** [crossbario/crossbar#1889]
Hi guys!
I'm trying to move a big project from Python2 to 3, and had an issue with Crossbar. Of cource it works now on Python2 with older dependencies versions.

Environment:
- python:3.8.11-slim-buster container
- crossbar-19.5.1, also tried crossbar==20.2.1. Newer ones don't fit the dependencies.
- Twisted-21.7.0
- autobahn-21.3.1

In short - Crossbar starts well, catches an error inside itself and correctly terminates:
```
2021-08-04T11:09:43+0000 [Controller      1 crossbar.node.native.NativeWorkerClientProtocol] Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/autobahn/wamp/websocket.py", line 60, in onOpen
    self._session.onOpen(self)
  File "/usr/local/lib/python3.8/site-packages/crossbar/router/session.py", line 353, in onOpen
    self._transport._transport_info[u'channel_id'] = binascii.b2a_hex(channel_id).decode('ascii')
TypeError: 'NoneType' object does not support item assignment
```

**Comment by om26er** [comment]
Old versions of Crossbar are not supported. Only the very latest version is supported, so you'd have to figure out a way to run things with latest Crossbar.
