### ISSUE TITLE
CI: snap build misses package

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#1947]
```
(base) oberstet@intel-nuci7:~$ sudo snap install crossbar
crossbar 22.2.1-20220223-cc862e53 aus Crossbar.io GmbH (crossbario) installiert
(base) oberstet@intel-nuci7:~$ which crossbar
/snap/bin/crossbar
(base) oberstet@intel-nuci7:~$ /snap/bin/crossbar version

  File "/root/parts/crossbar/install/lib/python3.8/site-packages/autobahn/xbr/__init__.py", line 38, in <module>
No module named 'mnemonic'Traceback (most recent call last):
  File "/snap/crossbar/1370/bin/crossbar", line 8, in <module>
    sys.exit(run())
  File "/root/parts/crossbar/install/lib/python3.8/site-packages/crossbar/__init__.py", line 291, in run
  File "/root/parts/crossbar/install/lib/python3.8/site-packages/crossbar/master/__init__.py", line 14, in <module>
  File "/root/parts/crossbar/install/lib/python3.8/site-packages/crossbar/master/personality.py", line 18, in <module>
  File "/root/parts/crossbar/install/lib/python3.8/site-packages/crossbar/personality.py", line 19, in <module>
  File "/root/parts/crossbar/install/lib/python3.8/site-packages/crossbar/worker/router.py", line 7, in <module>
  File "/root/parts/crossbar/install/lib/python3.8/site-packages/crossbar/worker/transport.py", line 25, in <module>
  File "/root/parts/crossbar/install/lib/python3.8/site-packages/crossbar/bridge/mqtt/wamp.py", line 29, in <module>
ImportError: cannot import name 'MsgPackObjectSerializer' from 'autobahn.wamp.serializer' (/snap/crossbar/1370/lib/python3.8/site-packages/autobahn/wamp/serializer.pyc)
(base) oberstet@intel-nuci7:~$ 
```

**Comment by om26er** [comment]
issue is fixed

**Comment by oberstet** [comment]
yep, fixed:

```
(cpy39_1) (base) oberstet@intel-nuci7:~/scm/crossbario/crossbar-binaries$ snapcraft upload crossbar_22.2.1-20220223-cc862e53_amd64.snap --release stable
Preparing to upload 'crossbar_22.2.1-20220223-cc862e53_amd64.snap'.
After uploading, the resulting snap revision will be released to 'stable' when it passes the Snap Store review.
Install the review-tools from the Snap Store for enhanced checks before uploading this snap.
Generating delta for 'crossbar_22.2.1-20220223-cc862e53_amd64.snap'.
Pushing 'crossbar_22.2.1-20220223-cc862e53_amd64.snap.xdelta3' [===================================================================] 100%
Processing...|                                                                                                                           
released
Revision 1371 of 'crossbar' created.
Track    Arch    Channel    Version                   Revision
latest   amd64   stable     22.2.1-20220223-cc862e53  1371
                 candidate  ↑                         ↑
                 beta       ↑                         ↑
                 edge       21.3.1+git2.gb4172870     1368
```
