### ISSUE TITLE
Cannot make install

### ISSUE THREAD

**Issue by malibu1966** [crossbario/crossbar#2107]
Hi there, when I try to make install crossbar I get the following error:

ERROR: Cannot install autobahn[compress,encryption,scram,serialization,twisted,xbr]==24.4.2, crossbar and crossbar==23.1.2 because these package versions have conflicting dependencies.

The conflict is caused by:
    crossbar 23.1.2 depends on eth-abi 4.0.0b2 (from git+https://github.com/ethereum/eth-abi.git@v4.0.0-beta.2#egg=eth-abi)
    py-eth-sig-utils 0.4.0 depends on eth-abi>=1.1.1
    autobahn[compress,encryption,scram,serialization,twisted,xbr] 24.4.2 depends on eth-abi>=4.0.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by Skully17** [comment]
See #2091 
unfortunately, I believe the change is being blocked by the automated tests not working.

**Comment by malibu1966** [comment]
Thanks for the response.  Do you happen to know what was the last working version?  I only need wampcra, not doing any of this bitcoin stuff.

I tried 23.1.1 as well and that had the same problem.

Also I tried 22.6.1 which is the next version down and also in pypi.  The pip install worked but I get this error on a config.json that works on the crossbar docker image:```


Traceback (most recent call last):
  File "/opt/venv/bin/crossbar", line 5, in <module>
    from crossbar import run
  File "/opt/venv/lib/pypy3.9/site-packages/crossbar/__init__.py", line 15, in <module>
    from crossbar._util import hl
  File "/opt/venv/lib/pypy3.9/site-packages/crossbar/_util.py", line 22, in <module>
    from crossbar.common.checkconfig import InvalidConfigException
  File "/opt/venv/lib/pypy3.9/site-packages/crossbar/common/checkconfig.py", line 22, in <module>
    from autobahn.wamp.message import _URI_PAT_STRICT_NON_EMPTY, _URI_PAT_STRICT_LAST_EMPTY, \
ImportError: cannot import name 'identity_realm_name_category' from 'autobahn.wamp.message' (/opt/venv/lib/pypy3.9/site-packages/autobahn/wamp/message.py)
```

I guess I will keep trying lower versions.

**Comment by malibu1966** [comment]
In case anyone needs a database back end for their workers, if you use mysql proper and the mysql-connector-python package which is pure python and works on pypy.  Unfortunately the standard and recommended mysqlclient and pstcopg2 (for postgres) won't work on the crossbar container because it is built with pypy and drivers with C extensions need to be completely recompiled for pypy as far as I understand.

**Comment by malibu1966** [comment]
So I install crossbar and then I do this?

**Comment by malibu1966** [comment]
Thank you very much for your help.  This is what I got:

root@b56f8af996e6:/code# pip install git@github.com:oberstet/crossbar.git@updating_dependencies
WARNING: Ignoring invalid distribution -rossbar (/opt/venv/lib/python3.9/site-packages)
Collecting git@ github.com:oberstet/crossbar.git@updating_dependencies
ERROR: Could not install packages due to an OSError: No connection adapters were found for 'github.com:oberstet/crossbar.git@updating_dependencies'

**Comment by oberstet** [comment]
Just a quick note seeing this flying by: I hope the Ethereum world - dependencies and all that - is finally stabilizing=) It's not quite yet perfect in Crossbar.io, I mean all the build integration and test automation .. but it is on the right track and making progress over time. In my eyes.

> psycopg2 (for postgresql) won't work on the crossbar container because it is built with pypy and modules with C extensions need to be completely recompiled for pypy 

I've had success in the past using https://pypi.org/project/psycopg2cffi/ This is a proper library for PG which uses CFFI and thus works great on PyPy. I am not currently using PG together with Python a lot, but there also is https://www.psycopg.org/psycopg3/ and of course the general question has been asked before;) https://stackoverflow.com/questions/9350422/how-do-you-get-pypy-django-and-postgresql-to-work-together

**Comment by Skully17** [comment]
> Thank you very much for your help. This is what I got:

Sorry, got the command wrong. Try this:
```
pip install git+https://github.com/oberstet/crossbar.git@updating_dependencies
```
I've actually run it myself this time (like I should have done before :slightly_smiling_face: ) and it installs

**Comment by malibu1966** [comment]
First of all, thanks everyone for providing input and being so helpful.

About psycopg2cffi, thanks for the recommendation.  I do remember seeing some stuff on that and I will try it, but it doesn't seem to be very popular and there wasn't a lot on it that I found.  Even the link you gave questions in a comment how well supported psycopg2 is.

**Comment by malibu1966** [comment]
So I tried the pip install and it seems to install fine but when I enter crossbar start I get the following error:

```
Traceback (most recent call last):
  File "/opt/venv/bin/crossbar", line 5, in <module>
    from crossbar import run
  File "/opt/venv/lib/python3.9/site-packages/crossbar/__init__.py", line 19, in <module>
    import eth_abi
  File "/opt/venv/lib/python3.9/site-packages/eth_abi/__init__.py", line 5, in <module>
    from eth_abi.abi import (
  File "/opt/venv/lib/python3.9/site-packages/eth_abi/abi.py", line 1, in <module>
    from eth_abi.codec import (
  File "/opt/venv/lib/python3.9/site-packages/eth_abi/codec.py", line 13, in <module>
    from eth_abi.decoding import (
  File "/opt/venv/lib/python3.9/site-packages/eth_abi/decoding.py", line 9, in <module>
    from eth_utils import (
  File "/opt/venv/lib/python3.9/site-packages/eth_utils/__init__.py", line 86, in <module>
    from .network import (
  File "/opt/venv/lib/python3.9/site-packages/eth_utils/network.py", line 7, in <module>
    from eth_typing import ChainId
ImportError: cannot import name 'ChainId' from 'eth_typing' (/opt/venv/lib/python3.9/site-packages/eth_typing/__init__.py)

```

**Comment by oberstet** [comment]
I don't know .. I am usually using CPython built from raw vanilla upstream sources .. which works

```
(.venv) oberstet@intel-nuci7:~/scm/typedefint/rfminer$ python
Python 3.12.1 (main, Dec 23 2023, 01:01:09) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from eth_typing import ChainId
>>> 
(.venv) oberstet@intel-nuci7:~/scm/typedefint/rfminer$ pip show eth_typing
Name: eth-typing
Version: 3.5.2
Summary: eth-typing: Common type annotations for ethereum python packages
Home-page: https://github.com/ethereum/eth-typing
Author: The Ethereum Foundation
Author-email: snakecharmers@ethereum.org
License: MIT
Location: /home/oberstet/scm/typedefint/rfminer/.venv/lib/python3.12/site-packages
Requires: typing-extensions
Required-by: eth-abi, eth-keys, eth-utils, py-ecc, web3
(.venv) oberstet@intel-nuci7:~/scm/typedefint/rfminer$ python -V
Python 3.12.1
```

**Comment by malibu1966** [comment]
I did pip install psycopg2cffi but it still doesn't work.  I think I would need to recompile it.

**Comment by oberstet** [comment]
whether it is worth the work getting PyPy and PostgreSQL, plus your own Python code work, of course is sth for you to decide! but what I will say is: I have used Autobahn/Crossbario on PyPy and PostgreSQL before - and it is a perfect choice and very hard to beat in various dimensions. At least my experience in real world "big enterprise applications" ...

**Comment by oberstet** [comment]
> how to get it to work. I did setup.py install for psycopg2cffi and that didn't work either.

so one way to approach seems like: reuse the official Docker image for PyPy3.9

```
docker pull pypy:3.9-7.3.16
```

and then `pip install psycopg2cffi` within the installed Python there.

one you have that, you might archive your build image as a Docker file that derives from above PyPy image, and then may or may not also bundle your actual application code ... just my 2cts.

**Comment by malibu1966** [comment]
I tried this.  Did pip install Django and pip install psycopg2cffi.  Still get the same error:

```
  File "/opt/pypy/lib/pypy3.9/site-packages/django/db/backends/postgresql/base.py", line 29, in <module>
    raise ImproperlyConfigured("Error loading psycopg2 or psycopg module")
django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 or psycopg module
```

**Comment by malibu1966** [comment]
Thanks for sticking with this.  I haven't had a lot of time in the last bit.

Note that I wasn't doing pip install with the Dockerfile but rather I was signing into the container and running it manually for the sake of investigation, but it should be all the same.

Here is my Dockerfile:

```
FROM pypy:3.9-7.3.16
EXPOSE 8000
EXPOSE 9000

apt-get -y update && apt-get -y install libpq-dev python3-dev
RUN pip install --upgrade pip
RUN pip install django
```

**Comment by samspade0069** [comment]
In install version 22.6.1 2 files hava a error in imports. 

site-packages/crossbar/common/checkconfig.py and site-packages/crossbar/router/auth/cryptosign.py have identity_realm_name_category change to identify_realm_name_category and run correct crossbar

**Comment by oberstet** [comment]
> Here is my Dockerfile (paraphrased a bit):

fwiw, I was checking to see if I might be able to actually look at what you do, or even docker-build try it;) so, nope. anyways, doesn't matter.  also, a complete docker file for building has sth more like 140 lines ..

![grafik](https://github.com/user-attachments/assets/c4cea314-27af-4b7d-8f63-2ac66f5019e1)

**Comment by samspade0069** [comment]
Not install in docker image. Install in debian 11 with command pip install crossbar. I had to change the two files to get it to start. 

The crossbar.io website is no longer accessible. Is the project stopped?

**Comment by malibu1966** [comment]
With all due respect, why all the manual pip install lines?  Shouldn't that be handled through dependencies?

**Comment by malibu1966** [comment]
I just noticed that there is some of the dockerfile missing in that screenshot.  I tried to look for the dockerfile in 'crossbar-binaries/docker' but I could not find it.  Please, where do I find the dockerfile?

**Comment by malibu1966** [comment]
I tried to use this Dockerfile but I couldn't get it to work either.  Specifically, 

curl --proto '=https' --tls1.2 -sSf https://sh.rustup.rs | sh -s -- -y

did not create rustc so the rustc command fails.  I'm also not sure what rust has to do with crossbar or autobahn.  I don't use it at all.
