### ISSUE TITLE
tls has been made mandatory in master

### ISSUE THREAD

**Issue by tardyp** [crossbario/crossbar#248]
I got this error when running master on fresh virtualenv:
```
2015-02-16T21:37:05.39+0100 [App/0]      ERR 2015-02-16 20:37:05+0000 [Controller     31] ==================== Crossbar.io ====================
2015-02-16T21:37:05.39+0100 [App/0]      ERR
2015-02-16T21:37:05.39+0100 [App/0]      ERR 2015-02-16 20:37:05+0000 [Controller     31] Crossbar.io 0.10.2 starting
2015-02-16T21:37:05.39+0100 [App/0]      ERR 2015-02-16 20:37:05+0000 [Controller     31] Running on CPython using EPollReactor reactor
2015-02-16T21:37:05.39+0100 [App/0]      ERR 2015-02-16 20:37:05+0000 [Controller     31] Starting from node directory /home/vcap/app/conf
2015-02-16T21:37:05.49+0100 [App/0]      ERR 2015-02-16 20:37:05+0000 [Controller     31] Traceback (most recent call last):
2015-02-16T21:37:05.49+0100 [App/0]      ERR 2015-02-16 20:37:05+0000 [Controller     31]   File "/home/vcap/app/.heroku/python/bin/crossbar", line 11, in <module>
2015-02-16T21:37:05.49+0100 [App/0]      ERR 2015-02-16 20:37:05+0000 [Controller     31]     sys.exit(run())
2015-02-16T21:37:05.49+0100 [App/0]      ERR 2015-02-16 20:37:05+0000 [Controller     31]   File "/app/.heroku/python/lib/python2.7/site-packages/crossbar/controller/cli.py", line 653, in run
2015-02-16T21:37:05.49+0100 [App/0]      ERR 2015-02-16 20:37:05+0000 [Controller     31]     options.func(options)
2015-02-16T21:37:05.49+0100 [App/0]      ERR 2015-02-16 20:37:05+0000 [Controller     31]   File "/app/.heroku/python/lib/python2.7/site-packages/crossbar/controller/cli.py", line 390, in run_command_start
2015-02-16T21:37:05.49+0100 [App/0]      ERR 2015-02-16 20:37:05+0000 [Controller     31]     from crossbar.controller.node import Node
2015-02-16T21:37:05.49+0100 [App/0]      ERR 2015-02-16 20:37:05+0000 [Controller     31]   File "/app/.heroku/python/lib/python2.7/site-packages/crossbar/controller/node.py", line 51, in <module>
2015-02-16T21:37:05.49+0100 [App/0]      ERR 2015-02-16 20:37:05+0000 [Controller     31]     from crossbar.controller.process import NodeControllerSession
2015-02-16T21:37:05.49+0100 [App/0]      ERR 2015-02-16 20:37:05+0000 [Controller     31]   File "/app/.heroku/python/lib/python2.7/site-packages/crossbar/controller/process.py", line 61, in <module>
2015-02-16T21:37:05.49+0100 [App/0]      ERR 2015-02-16 20:37:05+0000 [Controller     31]     from crossbar.common.process import NativeProcessSession
2015-02-16T21:37:05.49+0100 [App/0]      ERR 2015-02-16 20:37:05+0000 [Controller     31]   File "/app/.heroku/python/lib/python2.7/site-packages/crossbar/common/process.py", line 73, in <module>
2015-02-16T21:37:05.49+0100 [App/0]      ERR 2015-02-16 20:37:05+0000 [Controller     31]     from crossbar.twisted.endpoint import create_listening_port_from_config
2015-02-16T21:37:05.49+0100 [App/0]      ERR 2015-02-16 20:37:05+0000 [Controller     31]   File "/app/.heroku/python/lib/python2.7/site-packages/crossbar/twisted/endpoint.py", line 50, in <module>
2015-02-16T21:37:05.49+0100 [App/0]      ERR 2015-02-16 20:37:05+0000 [Controller     31]     from crossbar.twisted.tlsctx import TlsServerContextFactory, \
2015-02-16T21:37:05.49+0100 [App/0]      ERR 2015-02-16 20:37:05+0000 [Controller     31]   File "/app/.heroku/python/lib/python2.7/site-packages/crossbar/twisted/tlsctx.py", line 33, in <module>
2015-02-16T21:37:05.49+0100 [App/0]      ERR 2015-02-16 20:37:05+0000 [Controller     31]     from OpenSSL import crypto, SSL
2015-02-16T21:37:05.49+0100 [App/0]      ERR 2015-02-16 20:37:05+0000 [Controller     31] ImportError: No module named OpenSSL
```

**Comment by tardyp** [comment]
This patch fixed the issue for me:
```
diff --git a/crossbar/crossbar/twisted/endpoint.py b/crossbar/crossbar/twisted/endpoint.py
index 6e67628..16ce6c1 100644
--- a/crossbar/crossbar/twisted/endpoint.py
+++ b/crossbar/crossbar/twisted/endpoint.py
@@ -43,12 +43,12 @@ from twisted.internet.endpoints import TCP4ServerEndpoint, \
 try:
     from twisted.internet.endpoints import SSL4ServerEndpoint, \
         SSL4ClientEndpoint
+    from crossbar.twisted.tlsctx import TlsServerContextFactory, \
+        TlsClientContextFactory
 except ImportError:
     _HAS_TLS = False
 else:
     _HAS_TLS = True
-    from crossbar.twisted.tlsctx import TlsServerContextFactory, \
-        TlsClientContextFactory
```
