### ISSUE TITLE
crossbar fails to start a new, empty node with an AssertionError

### ISSUE THREAD

**Issue by minneyar** [crossbario/crossbar#275]
I'm running 64-bit Ubuntu 14.04.2 LTS, otherwise nothing special about it.  I've got a fresh install of crossbar.io, and when I try to start a node, it fails with an AssertionError, and there's nothing listening on port 8080.

I installed crossbar with:
`sudo pip install crossbar[tls,msgpack,manhole,system]`

Then I create a new node and try to start it, and I get the following output:
```
$ mkdir crossbar_demo
$ cd crossbar_demo/
$ crossbar init
Initializing application template 'default' in directory '/home/preed/src/crossbar_demo'
Using template from '/usr/local/lib/python2.7/dist-packages/crossbar/templates/default'
Creating directory /home/preed/src/crossbar_demo/.crossbar
Creating file      /home/preed/src/crossbar_demo/.crossbar/config.json
Application template initialized

To start your node, run 'crossbar start --cbdir /home/preed/src/crossbar_demo/.crossbar'
$ crossbar start
2015-03-19 19:58:57-0500 [Controller  13803] Log opened.
2015-03-19 19:58:57-0500 [Controller  13803] ==================== Crossbar.io ====================

2015-03-19 19:58:57-0500 [Controller  13803] Crossbar.io 0.10.2 starting
2015-03-19 19:58:57-0500 [Controller  13803] Running on CPython using EPollReactor reactor
2015-03-19 19:58:57-0500 [Controller  13803] Starting from node directory /home/preed/src/crossbar_demo/.crossbar
2015-03-19 19:58:57-0500 [Controller  13803] Starting from local configuration '/home/preed/src/crossbar_demo/.crossbar/config.json'
2015-03-19 19:58:57-0500 [Controller  13803] Warning, could not set process title (setproctitle not installed)
2015-03-19 19:58:57-0500 [Controller  13803] Router created for realm 'crossbar'
2015-03-19 19:58:57-0500 [Controller  13803] No WAMPlets detected in enviroment.
2015-03-19 19:58:57-0500 [Controller  13803] Starting Router with ID 'worker1' ..
2015-03-19 19:58:57-0500 [Controller  13803] Entering reactor event loop ...
2015-03-19 19:58:57-0500 [Router      13812] Log opened.
2015-03-19 19:58:57-0500 [Router      13812] Warning: could not set worker process title (setproctitle not installed)
2015-03-19 19:58:58-0500 [Router      13812] Running under CPython using EPollReactor reactor
2015-03-19 19:58:58-0500 [Router      13812] Entering event loop ..
2015-03-19 19:58:58-0500 [Controller  13803] Unhandled error in Deferred:
2015-03-19 19:58:58-0500 [Controller  13803] Unhandled Error
        Traceback (most recent call last):
          File "/usr/local/lib/python2.7/dist-packages/autobahn/wamp/websocket.py", line 95, in onMessage
            self._session.onMessage(msg)
          File "/usr/local/lib/python2.7/dist-packages/crossbar/router/session.py", line 303, in onMessage
            self._add_future_callbacks(d, success, self._onError)
          File "/usr/local/lib/python2.7/dist-packages/autobahn/twisted/wamp.py", line 93, in _add_future_callbacks
            future.addCallbacks(callback, errback)
          File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 296, in addCallbacks
            self._runCallbacks()
        --- <exception caught here> ---
          File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 578, in _runCallbacks
            current.result = callback(current.result, *args, **kw)
          File "/usr/local/lib/python2.7/dist-packages/crossbar/router/session.py", line 289, in success
            welcome(self._realm, res.authid, res.authrole, res.authmethod, res.authprovider)
          File "/usr/local/lib/python2.7/dist-packages/crossbar/router/session.py", line 271, in welcome
            msg = message.Welcome(self._session_id, roles, authid=authid, authrole=authrole, authmethod=authmethod, authprovider=authprovider)
          File "/usr/local/lib/python2.7/dist-packages/autobahn/wamp/message.py", line 370, in __init__
            assert(type(roles) == dict)
        exceptions.AssertionError:
```

I'm not sure what could be going wrong.  I've also tried creating nodes based on a few of the templates, and they behave the same way.  Here's some version information:

```
$ crossbar version

Crossbar.io package versions and platform information:

Crossbar.io                  : 0.10.2

  Autobahn|Python            : 0.10.2
    WebSocket UTF8 Validator : ?
    WebSocket XOR Masker     : ?
    WAMP JSON Codec          : stdlib
    WAMP MsgPack Codec       : msgpack-python-0.4.6
  Twisted                    : 15.0.0-EPollReactor
  Python                     : 2.7.6-CPython

OS                           : Linux-3.13.0-46-generic-x86_64-with-Ubuntu-14.04-trusty
Machine                      : x86_64
```

**Comment by Mulkave** [comment]
Same issue on Centos 7 and Fedora 21

**Comment by oberstet** [comment]
I have just pushed Crossbar.io 0.10.3 to PyPI which should work with the recent new AutobahnPython (that triggers the issue). Could you do a

pip install --upgrade crossbar

and let me know if it works for you?

**Comment by minneyar** [comment]
That fixed it.  Thanks!
