### ISSUE TITLE
raspberry pi - failed to start native worker

### ISSUE THREAD

**Issue by dimddev** [crossbario/crossbar#286]
Hello I read that crossbar works well with raspberry pi, but seems does not working on my side

here is the results from pip freeze:

(env)pi@tarpi /home/core/hello $ pip freeze
Jinja2==2.7.3
MarkupSafe==0.23
PyTrie==0.2
PyYAML==3.11
Pygments==2.0.2
Twisted==15.0.0
argparse==1.2.1
autobahn==0.10.2
cffi==0.9.2
characteristic==14.3.0
crossbar==0.10.3
cryptography==0.8.1
distribute==0.6.24
enum34==1.0.4
mistune==0.5.1
netaddr==0.7.13
pyOpenSSL==0.14
pyasn1==0.1.7
pyasn1-modules==0.0.5
pycparser==2.10
requests==2.6.0
service-identity==14.0.0
shutilwhich==1.0.1
six==1.9.0
treq==15.0.0
wsgiref==0.1.2
zope.interface==4.1.2

the log file from crossbar

(env)pi@tarpi /home/core/hello $ crossbar start
2015-03-31 11:51:37+0000 [Controller   2332] Log opened.
2015-03-31 11:51:37+0000 [Controller   2332] ==================== Crossbar.io ====================
	
2015-03-31 11:51:37+0000 [Controller   2332] Crossbar.io 0.10.3 starting
2015-03-31 11:51:37+0000 [Controller   2332] Running on CPython using EPollReactor reactor
2015-03-31 11:51:37+0000 [Controller   2332] Starting from node directory /home/core/hello/.crossbar
2015-03-31 11:51:38+0000 [Controller   2332] Starting from local configuration '/home/core/hello/.crossbar/config.json'
2015-03-31 11:51:38+0000 [Controller   2332] Warning, could not set process title (setproctitle not installed)
2015-03-31 11:51:38+0000 [Controller   2332] Warning: process utilities not available
2015-03-31 11:51:39+0000 [Controller   2332] Router created for realm 'crossbar'
2015-03-31 11:51:39+0000 [Controller   2332] No WAMPlets detected in enviroment.
2015-03-31 11:51:39+0000 [Controller   2332] Starting Router with ID 'worker1' ..
2015-03-31 11:51:39+0000 [Controller   2332] Entering reactor event loop ...
2015-03-31 11:51:41+0000 [Router       2335] Log opened.
2015-03-31 11:51:41+0000 [Router       2335] Warning: could not set worker process title (setproctitle not installed)

2015-03-31 11:52:05+0000 [Router       2335] Running under CPython using EPollReactor reactor
2015-03-31 11:52:10+0000 [Controller   2332] Worker 2335: Process connection gone (A process has ended with a probable error condition: process ended with exit code 1.)
2015-03-31 11:52:10+0000 [Controller   2332] ERROR: failed to start native worker - A process has ended with a probable error condition: process ended with exit code 1.
2015-03-31 11:52:10+0000 [Controller   2332] Traceback (most recent call last):
2015-03-31 11:52:10+0000 [Controller   2332]   File "/home/core/env/local/lib/python2.7/site-packages/crossbar/controller/node.py", line 183, in run_node_config
2015-03-31 11:52:10+0000 [Controller   2332]     yield self._run_node_config(config)
2015-03-31 11:52:10+0000 [Controller   2332]   File "/home/core/env/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1105, in _inlineCallbacks
2015-03-31 11:52:10+0000 [Controller   2332]     result = result.throwExceptionIntoGenerator(g)
2015-03-31 11:52:10+0000 [Controller   2332]   File "/home/core/env/local/lib/python2.7/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
2015-03-31 11:52:10+0000 [Controller   2332]     return g.throw(self.type, self.value, self.tb)
2015-03-31 11:52:10+0000 [Controller   2332]   File "/home/core/env/local/lib/python2.7/site-packages/crossbar/controller/node.py", line 249, in _run_node_config
2015-03-31 11:52:10+0000 [Controller   2332]     yield self._controller.start_router(worker_id, worker_options, details=call_details)
2015-03-31 11:52:10+0000 [Controller   2332]   File "/home/core/env/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 578, in _runCallbacks
2015-03-31 11:52:10+0000 [Controller   2332]     current.result = callback(current.result, *args, **kw)
2015-03-31 11:52:10+0000 [Controller   2332]   File "/home/core/env/local/lib/python2.7/site-packages/crossbar/controller/process.py", line 534, in on_ready_error
2015-03-31 11:52:10+0000 [Controller   2332]     raise ApplicationError("crossbar.error.cannot_start", emsg, worker.getlog())
2015-03-31 11:52:10+0000 [Controller   2332] ApplicationError: ApplicationError('crossbar.error.cannot_start', args = ('ERROR: failed to start native worker - A process has ended with a probable error condition: process ended with exit code 1.', []), kwargs = {})
2015-03-31 11:52:10+0000 [Controller   2332] Main loop terminated.

and the OS information:

Linux tarpi 3.18.7+ #755 PREEMPT Thu Feb 12 17:14:31 GMT 2015 armv6l GNU/Linux
Raspbian GNU/Linux 7

python version:

Python 2.7.3 (default, Mar 18 2014, 05:13:23)
GCC - 4.6.3

So maybe I miss something or maybe it's a bug

**Comment by dimddev** [comment]
I forgot to say, that this test is performed with the template comes from crossbar command:

crossbar init --template hello:python --appdir hello

**Comment by dimddev** [comment]
It's strange, sometimes get crashing, sometimes works well.
may be it's not comes from crossbar

**Comment by kashifpk** [comment]
I also get the same bug however for me it always crashes. Crossbar on normal Linux system seems to run fine, just get this on Raspberry Pi with the latest Raspbian distribution.

**Comment by kashifpk** [comment]
@dimddev I'd say this is still an open issue. Is anyone on the crossbar team able to test it?

**Comment by kashifpk** [comment]
On my Linux machine I had twisted 14.0.2 so thinking that may be the newer twisted version broke something I installed twisted 14.0.2 on RPi but still the error remains. Tried using the default twisted (version 12.0.0) via apt-get but crossbar requires a minimum twisted version of 12.1

**Comment by kashifpk** [comment]
Got it resolved by creating a blank new virtualenv and installing crossbar in it and it worked.

**Comment by S613420** [comment]
I'm getting the same error on my RPi. pip install -U crossbar has help fix the issue in the past but everything is up to date and it still is not working...

**Comment by goeddea** [comment]
@S613420 - just installed Crossbar on an up-to-date Raspberry Pi 2 under Raspbian, and it works for me. So without further details, there's nothing I can do for you.

**Comment by dimddev** [comment]
So I want to excuse to Simeon because everything works as expected

there are the latest version of my debug files

run index.html into your browser, open JS console for observing and then
start

development:/srv/www/htdocs/django/ChargeMaster # ./test_emls.py

and will see how the graphware send to us it's messages

that' it Cheers ) and have a nice weekend from my



On Fri, Jul 10, 2015 at 1:29 PM, Alexander Goedde <notifications@github.com>
wrote:

> @S613420 <https://github.com/S613420> - just installed Crossbar on an
> up-to-date Raspberry Pi 2 under Raspbian, and it works for me. So without
> further details, there's nothing I can do for you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/crossbario/crossbar/issues/286#issuecomment-120363684>
> .
>



-- 
Dimitar Dimitrov
Hard Music And Sounds United
http://www.hmsu.org
+128kbps online radio

**Comment by dimddev** [comment]
sorry wrong emai l:X

On Fri, Jul 10, 2015 at 2:36 PM, Dimitar Dimitrov <targolini@gmail.com>
wrote:

> So I want to excuse to Simeon because everything works as expected
>
> there are the latest version of my debug files
>
> run index.html into your browser, open JS console for observing and then
> start
>
> development:/srv/www/htdocs/django/ChargeMaster # ./test_emls.py
>
> and will see how the graphware send to us it's messages
>
> that' it Cheers ) and have a nice weekend from my
>
>
>
> On Fri, Jul 10, 2015 at 1:29 PM, Alexander Goedde <
> notifications@github.com> wrote:
>
>> @S613420 <https://github.com/S613420> - just installed Crossbar on an
>> up-to-date Raspberry Pi 2 under Raspbian, and it works for me. So without
>> further details, there's nothing I can do for you.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/crossbario/crossbar/issues/286#issuecomment-120363684>
>> .
>>
>
>
>
> --
> Dimitar Dimitrov
> Hard Music And Sounds United
> http://www.hmsu.org
> +128kbps online radio
>



-- 
Dimitar Dimitrov
Hard Music And Sounds United
http://www.hmsu.org
+128kbps online radio
