### ISSUE TITLE
crossbar 'check' & 'start' fail on Python 3.4.3 (Debian)

### ISSUE THREAD

**Issue by petri** [crossbario/crossbar#307]
This is in a Python3 virtualenv, where everything is installed with pip.

1) upon running "crossbar check" I get: ```Error: the JSON object must be str, not 'bytes' ```
2) upon trying "crossbar start", it tries to import stuff from Twisted and fails with:

```
Traceback (most recent call last):
  File "./bin/crossbar", line 9, in <module>
    load_entry_point('crossbar==0.10.4', 'console_scripts', 'crossbar')()
  File "/opt/cloudengine/lib/python3.4/site-packages/crossbar/controller/cli.py", line 665, in run
    options.func(options)
  File "/opt/cloudengine/lib/python3.4/site-packages/crossbar/controller/cli.py", line 387, in run_command_start
    from crossbar.twisted.processutil import DefaultSystemFileLogObserver
  File "/opt/cloudengine/lib/python3.4/site-packages/crossbar/twisted/processutil.py", line 38, in <module>
    from twisted.internet.endpoints import _WrapIProtocol, ProcessEndpoint
ImportError: cannot import name 'ProcessEndpoint'
```

Is there something specific to know when installing and running crossbar via Python3? Why does crossbar even install Twisted when installing on Python3???

**Comment by oberstet** [comment]
Python 3 is not supported right now for Crossbar.io, because Crossbar.io depends on Twisted, and the latter isn't yet fully Python 3. See https://github.com/crossbario/crossbar/blob/master/setup.py#L100
