### ISSUE TITLE
SIGINT results in unclean exit

### ISSUE THREAD

**Issue by Paranaix** [crossbario/crossbar#328]
This is fatal, as this effectively prevents one from restarting nodes (without restarting the router):

```
^C2015-05-16 16:18:42+0200 [Controller   7038] Received SIGINT, shutting down.
2015-05-16 16:18:42+0200 [Controller   7038] sending TERM to subprocess 7047
2015-05-16 16:18:42+0200 [Controller   7038] waiting for 7047 to exit...
2015-05-16 16:18:42+0200 [Container    7047] Ignoring SIGINT in worker.
2015-05-16 16:18:42+0200 [Container    7047] Received SIGTERM, shutting down.
2015-05-16 16:18:42+0200 [Container    7047] Connection to node controller lost.
2015-05-16 16:18:42+0200 [Container    7047] Unhandled Error
2015-05-16 16:18:42+0200 [Container    7047] Traceback (most recent call last):
2015-05-16 16:18:42+0200 [Container    7047] File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 295, in addCallbacks
2015-05-16 16:18:42+0200 [Container    7047] self._runCallbacks()
2015-05-16 16:18:42+0200 [Container    7047] File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
2015-05-16 16:18:42+0200 [Container    7047] current.result = callback(current.result, *args, **kw)
2015-05-16 16:18:42+0200 [Container    7047] File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 429, in _continueFiring
2015-05-16 16:18:42+0200 [Container    7047] callable(*args, **kwargs)
2015-05-16 16:18:42+0200 [Container    7047] File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 624, in disconnectAll
2015-05-16 16:18:42+0200 [Container    7047] failure.Failure(main.CONNECTION_LOST))
2015-05-16 16:18:42+0200 [Container    7047] --- <exception caught here> ---
2015-05-16 16:18:42+0200 [Container    7047] File "/usr/lib/python2.7/dist-packages/twisted/python/log.py", line 88, in callWithLogger
2015-05-16 16:18:42+0200 [Container    7047] return callWithContext({"system": lp}, func, *args, **kw)
2015-05-16 16:18:42+0200 [Container    7047] File "/usr/lib/python2.7/dist-packages/twisted/python/log.py", line 73, in callWithContext
2015-05-16 16:18:42+0200 [Container    7047] return context.call({ILogContext: newCtx}, func, *args, **kw)
2015-05-16 16:18:42+0200 [Container    7047] File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
2015-05-16 16:18:42+0200 [Container    7047] return self.currentContext().callWithContext(ctx, func, *args, **kw)
2015-05-16 16:18:42+0200 [Container    7047] File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
2015-05-16 16:18:42+0200 [Container    7047] return func(*args,**kw)
2015-05-16 16:18:42+0200 [Container    7047] File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 485, in connectionLost
2015-05-16 16:18:42+0200 [Container    7047] self._commonConnection.connectionLost(self, reason)
2015-05-16 16:18:42+0200 [Container    7047] File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 299, in connectionLost
2015-05-16 16:18:42+0200 [Container    7047] protocol.connectionLost(reason)
2015-05-16 16:18:42+0200 [Container    7047] File "/usr/lib/python2.7/dist-packages/twisted/internet/endpoints.py", line 126, in connectionLost
2015-05-16 16:18:42+0200 [Container    7047] return self._wrappedProtocol.connectionLost(reason)
2015-05-16 16:18:42+0200 [Container    7047] File "/usr/local/lib/python2.7/dist-packages/autobahn-0.10.4-py2.7.egg/autobahn/twisted/websocket.py", line 98, in connectionLost
2015-05-16 16:18:42+0200 [Container    7047] self._connectionLost(reason)
2015-05-16 16:18:42+0200 [Container    7047] File "/usr/local/lib/python2.7/dist-packages/autobahn-0.10.4-py2.7.egg/autobahn/websocket/protocol.py", line 3752, in _connectionLost
2015-05-16 16:18:42+0200 [Container    7047] WebSocketProtocol._connectionLost(self, reason)
2015-05-16 16:18:42+0200 [Container    7047] File "/usr/local/lib/python2.7/dist-packages/autobahn-0.10.4-py2.7.egg/autobahn/websocket/protocol.py", line 1229, in _connectionLost
2015-05-16 16:18:42+0200 [Container    7047] self._onClose(self.wasClean, WebSocketProtocol.CLOSE_STATUS_CODE_ABNORMAL_CLOSE, "connection was closed uncleanly (%s)" % self.wasNotCleanReason)
2015-05-16 16:18:42+0200 [Container    7047] File "/usr/local/lib/python2.7/dist-packages/autobahn-0.10.4-py2.7.egg/autobahn/twisted/websocket.py", line 141, in _onClose
2015-05-16 16:18:42+0200 [Container    7047] self.onClose(wasClean, code, reason)
2015-05-16 16:18:42+0200 [Container    7047] File "/usr/local/lib/python2.7/dist-packages/crossbar-0.10.4-py2.7.egg/crossbar/worker/container.py", line 293, in close_wrapper
2015-05-16 16:18:42+0200 [Container    7047] self._publish_component_stop(component)
2015-05-16 16:18:42+0200 [Container    7047] File "/usr/local/lib/python2.7/dist-packages/crossbar-0.10.4-py2.7.egg/crossbar/worker/container.py", line 330, in _publish_component_stop
2015-05-16 16:18:42+0200 [Container    7047] self.publish(topic, event, **kw)
2015-05-16 16:18:42+0200 [Container    7047] File "/usr/local/lib/python2.7/dist-packages/autobahn-0.10.4-py2.7.egg/autobahn/wamp/protocol.py", line 995, in publish
2015-05-16 16:18:42+0200 [Container    7047] raise exception.TransportLost()
2015-05-16 16:18:42+0200 [Container    7047] autobahn.wamp.exception.TransportLost:
2015-05-16 16:18:42+0200 [Container    7047] Main loop terminated.
2015-05-16 16:18:42+0200 [Controller   7038] Worker 7047: Process connection gone (Connection was closed cleanly.)
2015-05-16 16:18:42+0200 [Controller   7038] Main loop terminated.
```

Once started again, the hosted component is unable to register its callees again as the URIs are still in use (which indicates that the worker is running).

**Comment by meejah** [comment]
Can you describe what you're doing?

It looks like the controller is getting a SIGINT in the above logs. Of course, even if a component exits uncleanly, you should still be able to start it again -- but above it looks like the router is exiting because it received a SIGINT itself?

One thing is certainly a bug in the above log: the publish should handle the case when the transport is already gone...

**Comment by Paranaix** [comment]
Thats how our configuration looks like:

```
{
    "controller": {
    },
    "workers": [
        {
            "type": "container",
            "options": {
                "pythonpath": ["../../../"]
            },
            "components": [
                {
                    "type": "class",
                    "classname": "MyClass",
                    "realm": "main",
                    "transport": {
                        "type": "websocket",
                        "endpoint": {
                            "type": "tcp",
                            "host": "127.0.0.1",
                            "port": 9090
                        },
                        "url": "ws://localhost:9090",
                        "debug_wamp": true
                    }
                }
            ]
        }
    ]
}
```

The worker is running fine, until I fire a SIGINT in order to shut it down. In that case the behaviour described above occurs and I'm unable to start the node again as the WAMP connection is obviously not dropped.

**Comment by meejah** [comment]
Have you tried with SIGTERM?

**Comment by Paranaix** [comment]
Good point, will try that tommorow. However SIGINT always worked fine for me till I upgraded. Im pretty sure that this bug was introduced by the process termination refactoring.

**Comment by meejah** [comment]
Hmm, okay. Usually you'd send TERM to a process to tell it "please shut down".

From the above logs, though, it looks like the controller is getting SIGINT (as well); perhaps you sent the signal to the process-group?

I'll try again in any case, but so what you're doing is "kill -INT <pid of worker>"? And then presumably you want crossbar to re-start that process after it dies...?

**Comment by oberstet** [comment]
it's the _publish_component_stop which can't work when the transport to the controller was lost already .. but I'm not sure that's what the issue was mainly about

**Comment by oberstet** [comment]
the particular publish that triggered that traceback is now guarded for loss of transport https://github.com/crossbario/crossbar/blob/master/crossbar/worker/container.py#L344
