### ISSUE TITLE
lmdb on FreeBSD doesnt build

### ISSUE THREAD

**Issue by goeddea** [crossbario/crossbar#345]
```console
root@ip-172-31-1-97:/usr/home/ec2-user # pip install -U "crossbar[db]"
Requirement already up-to-date: crossbar[db] in /usr/local/lib/pypy-2.4/site-packages
Requirement already up-to-date: setuptools>=2.2 in /usr/local/lib/pypy-2.4/site-packages (from crossbar[db])
Requirement already up-to-date: zope.interface>=3.6.0 in /usr/local/lib/pypy-2.4/site-packages (from crossbar[db])
Requirement already up-to-date: twisted>=twisted-13.2 in /usr/local/lib/pypy-2.4/site-packages (from crossbar[db])
Requirement already up-to-date: autobahn[twisted]>=0.10.3 in /usr/local/lib/pypy-2.4/site-packages (from crossbar[db])
Requirement already up-to-date: netaddr>=0.7.11 in /usr/local/lib/pypy-2.4/site-packages (from crossbar[db])
Requirement already up-to-date: pytrie>=0.2 in /usr/local/lib/pypy-2.4/site-packages (from crossbar[db])
Requirement already up-to-date: jinja2>=2.7.2 in /usr/local/lib/pypy-2.4/site-packages (from crossbar[db])
Requirement already up-to-date: mistune>=0.3.0 in /usr/local/lib/pypy-2.4/site-packages (from crossbar[db])
Requirement already up-to-date: pygments>=1.6 in /usr/local/lib/pypy-2.4/site-packages (from crossbar[db])
Requirement already up-to-date: pyyaml>=3.11 in /usr/local/lib/pypy-2.4/site-packages (from crossbar[db])
Requirement already up-to-date: shutilwhich>=1.0.1 in /usr/local/lib/pypy-2.4/site-packages (from crossbar[db])
Requirement already up-to-date: treq>=15.0.0 in /usr/local/lib/pypy-2.4/site-packages (from crossbar[db])
Collecting lmdb>=0.84 (from crossbar[db])
  Using cached lmdb-0.84.tar.gz
    Complete output from command python setup.py egg_info:
    lib/mdb.c:4501:39: error: use of undeclared identifier 'O_DSYNC'
                            env->me_mfd = open(dpath, oflags | MDB_DSYNC, mode);
                                                               ^
    lib/mdb.c:327:20: note: expanded from macro 'MDB_DSYNC'
    # define MDB_DSYNC      O_DSYNC
                            ^
    1 error generated.
    py-lmdb: Using bundled liblmdb; override with LMDB_FORCE_SYSTEM=1.
    Using cffi extension.
    Traceback (most recent call last):
      File "app_main.py", line 75, in run_toplevel
      File "app_main.py", line 581, in run_it
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-TFWI9A/lmdb/setup.py", line 140, in <module>
        import lmdb.cffi
      File "lmdb/__init__.py", line 40, in <module>
        from lmdb.cffi import *
      File "lmdb/cffi.py", line 328, in <module>
        library_dirs=_config_vars['extra_library_dirs'])
      File "/usr/local/lib/pypy-2.4/lib_pypy/cffi/api.py", line 340, in verify
        lib = self.verifier.load_library()
      File "/usr/local/lib/pypy-2.4/lib_pypy/cffi/verifier.py", line 74, in load_library
        self._compile_module()
      File "/usr/local/lib/pypy-2.4/lib_pypy/cffi/verifier.py", line 139, in _compile_module
        outputfilename = ffiplatform.compile(tmpdir, self.get_extension())
      File "/usr/local/lib/pypy-2.4/lib_pypy/cffi/ffiplatform.py", line 25, in compile
        outputfilename = _build(tmpdir, ext)
      File "/usr/local/lib/pypy-2.4/lib_pypy/cffi/ffiplatform.py", line 51, in _build
        raise VerificationError('%s: %s' % (e.__class__.__name__, e))
    VerificationError: CompileError: command 'cc' failed with exit status 1

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-TFWI9A/lmdb
root@ip-172-31-1-97:/usr/home/ec2-user #
```

**Comment by oberstet** [comment]
`O_DSYNC` isn't a valid option on FreeBSD.

The FreeBSD port of lmdb [corrects](https://svnweb.freebsd.org/ports/head/databases/lmdb/Makefile?view=markup) that: `CFLAGS+= -DMDB_DSYNC=O_SYNC -Dfdatasync=fsync`.

The FreeBSD port also has a newer lmdb than the one bundled with py-lmdb.

To make py-lmdb use the system lmdb:

```console
bash
cd /tmp
git clone git@github.com:dw/py-lmdb.git
cd py-lmdb
export LMDB_FORCE_SYSTEM=1
export LMDB_INCLUDEDIR=/usr/local/include
export LMDB_LIBDIR=/usr/local/lib
pypy setup.py install
```

**Comment by oberstet** [comment]
For self-contained packaging of CB, we should bundle lmdb ourselves: https://github.com/LMDB/lmdb

**Comment by oberstet** [comment]
@hawkowl can we close this? the binary package of CB on FBSD does include LMDB, right?

**Comment by oberstet** [comment]
migrated to  packaging
