### ISSUE TITLE
Logging breaks with non-ASCII chars in log messages

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#371]
```
2015-07-04T14:10:36+0200 [Router       3119] Unable to format event {'log_system': 'connection', 'message': (), 'system': 'connection', 'why': None, 'failure': <twisted.python.failure.Failure <class 'psycopg2.OperationalError'>>, 'time': 1436011836.40986, 'log_text': 'Unhandled Error\nTraceback (most recent call last):\n  File "/home/oberstet/tmp/cpy2710_1/lib/python2.7/site-packages/twisted/python/log.py", line 101, in callWithLogger\n    return callWithContext({"system": lp}, func, *args, **kw)\n  File "/home/oberstet/tmp/cpy2710_1/lib/python2.7/site-packages/twisted/python/log.py", line 84, in callWithContext\n    return context.call({ILogContext: newCtx}, func, *args, **kw)\n  File "/home/oberstet/tmp/cpy2710_1/lib/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext\n    return self.currentContext().callWithContext(ctx, func, *args, **kw)\n  File "/home/oberstet/tmp/cpy2710_1/lib/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext\n    return func(*args,**kw)\n--- <exception caught here> ---\n  File "/home/oberstet/tmp/cpy2710_1/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 611, in _doReadOrWrite\n    why = selectable.doRead()\n  File "/home/oberstet/tmp/cpy2710_1/lib/python2.7/site-packages/txpostgres/txpostgres.py", line 671, in doRead\n    _PollingMixin.doRead(self)\n  File "/home/oberstet/tmp/cpy2710_1/lib/python2.7/site-packages/txpostgres/txpostgres.py", line 193, in doRead\n    self.continuePolling()\n  File "/home/oberstet/tmp/cpy2710_1/lib/python2.7/site-packages/txpostgres/txpostgres.py", line 164, in continuePolling\n    state = self.pollable().poll()\npsycopg2.OperationalError: FATAL:  Passwort-Authentifizierung f\xc3\xbcr Benutzer \xe2\x80\x9ecdc_backend\xe2\x80\x9c fehlgeschlagen\nFATAL:  Passwort-Authentifizierung f\xc3\xbcr Benutzer \xe2\x80\x9ecdc_backend\xe2\x80\x9c fehlgeschlagen\n\n', 'log_format': u'{log_text}', 'log_time': 1436011836.40986, 'isError': 1}: 'ascii' codec can't decode byte 0xc3 in position 1445: ordinal not in range(128)
```

**Comment by oberstet** [comment]
@hawkowl

**Comment by oberstet** [comment]
here is another one:

```
2015-07-05T04:51:01+0200 [Router      26154 crossbar._logging] Unable to format event {'log_namespace': 'crossbar.controller.processtypes.WorkerProcess', 'log_level': <LogLevel=error>, 'cb_namespace': u'crossbar._logging', 'log_system': 'Router      26154', 'log_source': None, 'log_logger': <Logger 'crossbar.controller.processtypes.WorkerProcess'>, 'log_time': 1436064661.316099, 'log_format': u"Error writing: <crossbar.router.service.RouterServiceSession object at 0x7ff3bb678dd0> is not JSON serializable {'session': <crossbar.router.service.RouterServiceSession object at 0x7ff3bb678dd0>, 'level': 'debug', 'text': u'attaching non-client session <crossbar.router.service.RouterServiceSession object at 0x7ff3bb678dd0>', 'namespace': 'crossbar.router.router.Router', 'log_time': 1436064661.315892}"}: u"'session'"
```

**Comment by hawkowl** [comment]
@oberstet I think these should be fixed. I'll try and get test cases for them, so I can be sure.

**Comment by hawkowl** [comment]
This should be fixed now, in the branch you merged earlier today.
