### ISSUE TITLE
Crossbar.io on Windows doesn't stop using CRT+C

### ISSUE THREAD

**Issue by goeddea** [crossbario/crossbar#373]
2015-07-09T15:14:50+0200 [Controller  14148] Unexpected error in main loop.
2015-07-09T15:14:50+0200 [Controller  14148] Unhandled Error
Traceback (most recent call last):
  File "C:\Python27\Scripts\crossbar-script.py", line 9, in <module>
    load_entry_point('crossbar==0.11.0', 'console_scripts', 'crossbar')()
  File "c:\Python27\lib\site-packages\crossbar-0.11.0-py2.7.egg\crossbar\controller\cli.py", line 760, in run
    options.func(options)
  File "c:\Python27\lib\site-packages\crossbar-0.11.0-py2.7.egg\crossbar\controller\cli.py", line 497, in run_command_start
    reactor.run()
  File "c:\Python27\lib\site-packages\twisted-15.2.1-py2.7-win32.egg\twisted\internet\base.py", line 1194, in run
    self.mainLoop()
--- <exception caught here> ---
  File "c:\Python27\lib\site-packages\twisted-15.2.1-py2.7-win32.egg\twisted\internet\base.py", line 1206, in mainLoop
    self.doIteration(t)
  File "c:\Python27\lib\site-packages\twisted-15.2.1-py2.7-win32.egg\twisted\internet\iocpreactor\reactor.py", line 100, in doIteration
    rc, bytes, key, evt = self.port.getEvent(timeout)
exceptions.KeyboardInterrupt:

(stopping using `crossbar stop` works fine afterwards)

**Comment by goeddea** [comment]
Cannot replicate anymore on most current trunk.
