### ISSUE TITLE
Source build on FreeBSD fails

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#414]
running `pip install --upgrade -e .[all]` produces:

```
Collecting lmdb>=0.87 (from crossbar==0.11.0)
  Using cached lmdb-0.87.tar.gz
    Complete output from command python setup.py egg_info:
    lib/mdb.c:4611:39: error: use of undeclared identifier 'O_DSYNC'
                            env->me_mfd = open(dpath, oflags | MDB_DSYNC, mode);
                                                               ^
    lib/mdb.c:335:20: note: expanded from macro 'MDB_DSYNC'
    # define MDB_DSYNC      O_DSYNC
                            ^
    1 error generated.
    py-lmdb: Using bundled liblmdb; override with LMDB_FORCE_SYSTEM=1.
    Using cffi extension.
    Traceback (most recent call last):
      File "app_main.py", line 75, in run_toplevel
      File "app_main.py", line 581, in run_it
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-nnbmBn/lmdb/setup.py", line 142, in <module>
        import lmdb.cffi
      File "lmdb/__init__.py", line 40, in <module>
        from lmdb.cffi import *
      File "lmdb/cffi.py", line 333, in <module>
        library_dirs=_config_vars['extra_library_dirs'])
      File "/usr/local/lib/pypy-2.4/lib_pypy/cffi/api.py", line 340, in verify
        lib = self.verifier.load_library()
      File "/usr/local/lib/pypy-2.4/lib_pypy/cffi/verifier.py", line 74, in load_library
        self._compile_module()
      File "/usr/local/lib/pypy-2.4/lib_pypy/cffi/verifier.py", line 139, in _compile_module
        outputfilename = ffiplatform.compile(tmpdir, self.get_extension())
      File "/usr/local/lib/pypy-2.4/lib_pypy/cffi/ffiplatform.py", line 25, in compile
        outputfilename = _build(tmpdir, ext)
      File "/usr/local/lib/pypy-2.4/lib_pypy/cffi/ffiplatform.py", line 51, in _build
        raise VerificationError('%s: %s' % (e.__class__.__name__, e))
    VerificationError: CompileError: command 'cc' failed with exit status 1
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-nnbmBn/lmdb
*** Error code 1

Stop.
make: stopped in /usr/home/ec2-user/scm/crossbar
```

the used `lmdb-0.87.tar.gz` is probably too old. not sure. but it doesn't build.

**Comment by oberstet** [comment]
or we might do similar to AutobahnPython, if there is a way to fix https://github.com/tavendo/AutobahnPython/issues/467

**Comment by oberstet** [comment]
the FreeBSD problem with LMDB can be solved like this:

```
sudo pkg install lmdb
export LMDB_FORCE_CFFI=1
export LMDB_FORCE_SYSTEM=1
export LMDB_INCLUDEDIR=/usr/local/include
export LMDB_LIBDIR=/usr/local/lib
pip install lmdb
```

After that, LMDB is available:

```console
(pypy260)[oberstet@brummer2 ~]$ python
Python 2.7.9 (295ee98b69288471b0fcf2e0ede82ce5209eb90b, Jun 15 2015, 07:53:48)
[PyPy 2.6.0 with GCC 4.2.1 Compatible FreeBSD Clang 3.4.1 (tags/RELEASE_34/dot1-final 208032)] on freebsd10
Type "help", "copyright", "credits" or "license" for more information.
>>>> import lmdb
>>>> lmdb.version
<function version at 0x000000080809f628>
>>>> lmdb.version()
(0, 9, 16)
>>>> 
```

To build LMDB from source on FreeBSD, easiest is to get the mirror from GitHub [here](https://github.com/LMDB/lmdb/).

You then need to tweak the [Makefile](https://github.com/LMDB/lmdb/blob/mdb.master/libraries/liblmdb/Makefile#L20) to use clang instead of gcc, plus add these flags:

* `-DMDB_DSYNC=O_SYNC -Dfdatasync=fsync`

See the FreeBSD port [here](https://svnweb.freebsd.org/ports/head/databases/lmdb/Makefile?revision=394991&view=markup#l18)

**Comment by oberstet** [comment]
migrated to CB packaging repo
