### ISSUE TITLE
DirWatcher unavailable causes python3 guest to fail?

### ISSUE THREAD

**Issue by singlecheeze** [crossbario/crossbar#416]
Just making a guess here but I installed crossbar on a brand new Ubuntu 14.04.3 server today and cannot run a project that was running fine on 10.4 under python2 with python3 guest workers.

I am getting:
``` text
feature DirWatcher unavailable
```
On the python3 guest workers and after this happens I'm hypothesizing this is making crossbar try to load the python3 files with python2... like it is not honoring the:
``` text
Using guest worker executable '/usr/bin/python3' (executable path detected from environment)
``` 

Crossbar version:
``` bash
     __  __  __  __  __  __      __     __
    /  `|__)/  \/__`/__`|__) /\ |__)  |/  \
    \__,|  \\__/.__/.__/|__)/~~\|  \. |\__/
                                        
 Crossbar.io        : 0.11.0
   Autobahn         : 0.10.5.post2
     UTF8 Validator : wsaccel-0.6.2
     XOR Masker     : wsaccel-0.6.2
     JSON Codec     : stdlib
     MsgPack Codec  : -
   Twisted          : 15.3.0-EPollReactor
   Python           : 2.7.6/CPython
 OS                 : Linux-3.19.0-26-generic-x86_64-with-Ubuntu-14.04-trusty
 Machine            : x86_64
```
``` json
{
   "controller": {
   },
   "workers": [
      {
         "id": "wamprouter",
         "type": "router",
         "options": {
            "title": "WAMP Router"
         },
         "realms": [
            {
               "name": "realm1",
               "roles": [
                  {
                     "name": "authenticator",
                     "permissions": [
                        {
                           "uri": "com.aurora.authenticate",
                           "register": true
                        }
                     ]
                  },
                  {
                     "name": "authorizer",
                     "permissions": [
                        {
                           "uri": "com.aurora.authorize",
                           "register": true
                        }
                     ]
                  },
                  {
                     "name": "backend",
                     "authorizer": "com.aurora.authorize"
                  },
                  {
                     "name": "frontend",
                     "authorizer": "com.aurora.authorize"
                  }
               ]
            }
         ],
         "transports": [
            {
               "id": "loopback",
               "type": "websocket",
               "endpoint": {
                  "type": "tcp",
                  "port": 9090,
                  "interface": "127.0.0.1"
               },
               "auth": {
                  "wampcra": {
                     "type": "static",
                     "users": {
                        "authenUser": {
                           "secret": "prq7+YkJ1/KlW1X0YczMHw==",
                           "role": "authenticator",
                           "salt": "salt123",
                           "iterations": 100,
                           "keylen": 16
                        }
                     }
                  }
               },
               "debug": false,
               "options": {
                  "compression": {
                     "deflate": {
                        "request_no_context_takeover": false,
                        "request_max_window_bits": 11,
                        "no_context_takeover": false,
                        "max_window_bits": 11,
                        "memory_level": 4
                     }
                  },
                  "auto_ping_interval": 10000,
                  "auto_ping_timeout": 5000,
                  "auto_ping_size": 4
               }
            },
            {
               "id": "web",
               "type": "web",
               "endpoint": {
                  "type": "tcp",
                  "port": 8081
               },
               "paths": {
                  "/": {
                     "type": "static",
                     "directory": "../frontend"
                  },
                  "ws": {
                     "type": "websocket",
                     "url": "ws://localhost:8080/ws",
                     "auth": {
                        "wampcra": {
                           "type": "dynamic",
                           "authenticator": "com.aurora.authenticate"
                        }
                     },
                     "debug": false,
                     "options": {
                        "compression": {
                           "deflate": {
                              "request_no_context_takeover": false,
                              "request_max_window_bits": 11,
                              "no_context_takeover": false,
                              "max_window_bits": 11,
                              "memory_level": 4
                           }
                        },
                        "auto_ping_interval": 10000,
                        "auto_ping_timeout": 5000,
                        "auto_ping_size": 4
                     }
                  }
               }
            }
         ]
      },
      {
         "id": "authenticator",
         "type": "guest",
         "executable": "python3",
         "arguments": ["authentication.py"],
         "options": {
           "env": {
               "vars": {
                  "PYTHONUNBUFFERED": "1"
               }
            },
            "workdir": "../backend",
            "stdout": "log",
            "stderr": "log",
            "watch": {
               "directories": ["../backend"],
               "action": "restart"
            }
         }
      },
      {
         "id": "authorizer",
         "type": "guest",
         "executable": "python3",
         "arguments": ["authorization.py"],
         "options": {
            "env": {
               "vars": {
                  "PYTHONUNBUFFERED": "1"
               }
            },
            "workdir": "../backend",
            "stdout": "log",
            "stderr": "log",
            "watch": {
               "directories": ["../backend"],
               "action": "restart"
            }
         }
      },
      {
         "id": "backend",
         "type": "guest",
         "executable": "python3",
         "arguments": ["backend.py"],
         "options": {
            "env": {
               "vars": {
                  "PYTHONUNBUFFERED": "1"
               }
            },
            "workdir": "../backend",
            "stdout": "log",
            "stderr": "log",
            "watch": {
               "directories": ["../backend"],
               "action": "restart"
            }
         }
      }
   ]
}
```

Output:
``` bash
2015-08-27T23:32:10-0400 [Controller  11575]      __  __  __  __  __  __      __     __
2015-08-27T23:32:10-0400 [Controller  11575]     /  `|__)/  \/__`/__`|__) /\ |__)  |/  \
2015-08-27T23:32:10-0400 [Controller  11575]     \__,|  \\__/.__/.__/|__)/~~\|  \. |\__/
2015-08-27T23:32:10-0400 [Controller  11575]                                         
2015-08-27T23:32:10-0400 [Controller  11575]     Version: 0.11.0     
2015-08-27T23:32:10-0400 [Controller  11575]     Started: 2015-08-28T03:32:10.550Z
2015-08-27T23:32:10-0400 [Controller  11575] 
2015-08-27T23:32:10-0400 [Controller  11575] Starting from node directory /home/dave/xbar/.crossbar
2015-08-27T23:32:10-0400 [Controller  11575] Loading node configuration file '/home/dave/xbar/.crossbar/config.json'
2015-08-27T23:32:10-0400 [Controller  11575] Entering reactor event loop...
2015-08-27T23:32:10-0400 [Controller  11575] Process utilities not available
2015-08-27T23:32:10-0400 [Controller  11575] Joined realm 'crossbar' on node management router
2015-08-27T23:32:10-0400 [Controller  11575] No WAMPlets detected in enviroment.
2015-08-27T23:32:10-0400 [Controller  11575] Starting Router with ID 'wamprouter'...
2015-08-27T23:32:10-0400 [Router      11580] Running under CPython using EPollReactor reactor
2015-08-27T23:32:11-0400 [Router      11580] Entering event loop...
2015-08-27T23:32:11-0400 [Router      11580] Process utilities not available
2015-08-27T23:32:11-0400 [Controller  11575] Router with ID 'wamprouter' and PID 11580 started
2015-08-27T23:32:11-0400 [Router      11580] Worker ready to roll!
2015-08-27T23:32:11-0400 [Controller  11575] Router 'wamprouter': realm 'realm1' (named 'realm1') started
2015-08-27T23:32:11-0400 [Controller  11575] Router 'wamprouter': role 'role1' (named 'authenticator') started on realm 'realm1'
2015-08-27T23:32:11-0400 [Controller  11575] Router 'wamprouter': role 'role2' (named 'authorizer') started on realm 'realm1'
2015-08-27T23:32:11-0400 [Controller  11575] Router 'wamprouter': role 'role3' (named 'backend') started on realm 'realm1'
2015-08-27T23:32:11-0400 [Controller  11575] Router 'wamprouter': role 'role4' (named 'frontend') started on realm 'realm1'
2015-08-27T23:32:11-0400 [Router      11580] WampWebSocketServerFactory starting on 9090
2015-08-27T23:32:11-0400 [Controller  11575] Router 'wamprouter': transport 'loopback' started
2015-08-27T23:32:11-0400 [Router      11580] Site starting on 8081
2015-08-27T23:32:11-0400 [Controller  11575] Router 'wamprouter': transport 'web' started
2015-08-27T23:32:11-0400 [Controller  11575] Using guest worker executable '/usr/bin/python3' (executable path detected from environment)
2015-08-27T23:32:11-0400 [Controller  11575] Starting Guest with ID 'authenticator'...
2015-08-27T23:32:11-0400 [Controller  11575] Guest with ID 'authenticator' and PID 11585 started
2015-08-27T23:32:11-0400 [Controller  11575] Warning: cannot watch directory for changes - feature DirWatcher unavailable
2015-08-27T23:32:11-0400 [Controller  11575] Guest 'authenticator': started
2015-08-27T23:32:11-0400 [Controller  11575] Using guest worker executable '/usr/bin/python3' (executable path detected from environment)
2015-08-27T23:32:11-0400 [Controller  11575] Starting Guest with ID 'authorizer'...
2015-08-27T23:32:11-0400 [Controller  11575] Guest with ID 'authorizer' and PID 11586 started
2015-08-27T23:32:11-0400 [Controller  11575] Warning: cannot watch directory for changes - feature DirWatcher unavailable
2015-08-27T23:32:11-0400 [Controller  11575] Guest 'authorizer': started
2015-08-27T23:32:11-0400 [Controller  11575] Using guest worker executable '/usr/bin/python3' (executable path detected from environment)
2015-08-27T23:32:11-0400 [Controller  11575] Starting Guest with ID 'backend'...
2015-08-27T23:32:11-0400 [Controller  11575] Guest with ID 'backend' and PID 11587 started
2015-08-27T23:32:11-0400 [Controller  11575] Warning: cannot watch directory for changes - feature DirWatcher unavailable
2015-08-27T23:32:11-0400 [Controller  11575] Guest 'backend': started
2015-08-27T23:32:11-0400 [Guest       11585] Fatal Python error: Py_Initialize: Unable to get the locale encoding
2015-08-27T23:32:11-0400 [Guest       11585] File "/usr/lib/python2.7/encodings/__init__.py", line 123
2015-08-27T23:32:11-0400 [Guest       11585] raise CodecRegistryError,\
2015-08-27T23:32:11-0400 [Guest       11585] ^
2015-08-27T23:32:11-0400 [Guest       11585] SyntaxError: invalid syntax
2015-08-27T23:32:11-0400 [Guest       11586] Fatal Python error: Py_Initialize: Unable to get the locale encoding
2015-08-27T23:32:11-0400 [Guest       11586] File "/usr/lib/python2.7/encodings/__init__.py", line 123
2015-08-27T23:32:11-0400 [Guest       11586] raise CodecRegistryError,\
2015-08-27T23:32:11-0400 [Guest       11586] ^
2015-08-27T23:32:11-0400 [Guest       11586] SyntaxError: invalid syntax
2015-08-27T23:32:11-0400 [Guest       11587] Fatal Python error: Py_Initialize: Unable to get the locale encoding
2015-08-27T23:32:11-0400 [Guest       11587] File "/usr/lib/python2.7/encodings/__init__.py", line 123
2015-08-27T23:32:11-0400 [Guest       11587] raise CodecRegistryError,\
2015-08-27T23:32:11-0400 [Guest       11587] ^
2015-08-27T23:32:11-0400 [Guest       11587] SyntaxError: invalid syntax
2015-08-27T23:32:11-0400 [Controller  11575] Guest authenticator exited with error A process has ended with a probable error condition: process ended by signal 6.
2015-08-27T23:32:11-0400 [Controller  11575] Guest authorizer exited with error A process has ended with a probable error condition: process ended by signal 6.
2015-08-27T23:32:11-0400 [Controller  11575] Guest backend exited with error A process has ended with a probable error condition: process ended by signal 6.
^C2015-08-27T23:37:02-0400 [Controller  11575] Received SIGINT, shutting down.
2015-08-27T23:37:02-0400 [Controller  11575] sending TERM to subprocess 11580
2015-08-27T23:37:02-0400 [Controller  11575] waiting for 11580 to exit...
2015-08-27T23:37:02-0400 [Controller  11575] sending TERM to subprocess 11585
2015-08-27T23:37:02-0400 [Controller  11575] sending TERM to subprocess 11586
2015-08-27T23:37:02-0400 [Controller  11575] sending TERM to subprocess 11587
2015-08-27T23:37:02-0400 [Router      11580] Received SIGTERM, shutting down.
2015-08-27T23:37:02-0400 [Router      11580] Connection to node controller lost.
2015-08-27T23:37:02-0400 [Router      11580] (TCP Port 8081 Closed)
2015-08-27T23:37:02-0400 [Router      11580] (TCP Port 9090 Closed)
2015-08-27T23:37:02-0400 [Router      11580] Main loop terminated.
2015-08-27T23:37:02-0400 [Controller  11575] Main loop terminated.

```

**Comment by oberstet** [comment]
you have to actually read the log.

```
2015-08-27T23:32:11-0400 [Controller  11575] Warning: cannot watch directory for changes - feature DirWatcher unavailable
2015-08-27T23:32:11-0400 [Controller  11575] Guest 'backend': started
2015-08-27T23:32:11-0400 [Guest       11585] Fatal Python error: Py_Initialize: Unable to get the locale encoding
2015-08-27T23:32:11-0400 [Guest       11585] File "/usr/lib/python2.7/encodings/__init__.py", line 123
2015-08-27T23:32:11-0400 [Guest       11585] raise CodecRegistryError,\
2015-08-27T23:32:11-0400 [Guest       11585] ^
2015-08-27T23:32:11-0400 [Guest       11585] SyntaxError: invalid syntax
```

**Comment by singlecheeze** [comment]
Ok I tried removing:

``` json
           "watch": {
               "directories": ["../backend"],
               "action": "restart"
            }
```

Still same error...

``` text
2015-08-27T23:32:11-0400 [Guest       11585] Fatal Python error: Py_Initialize: Unable to get the locale encoding
2015-08-27T23:32:11-0400 [Guest       11585] File "/usr/lib/python2.7/encodings/__init__.py", line 123
2015-08-27T23:32:11-0400 [Guest       11585] raise CodecRegistryError,\
2015-08-27T23:32:11-0400 [Guest       11585] ^
2015-08-27T23:32:11-0400 [Guest       11585] SyntaxError: invalid syntax
```

Any help you can provide other than, "read the log" would be helpful. We are not all amazing python programmers! ;)

**Comment by meejah** [comment]
That's...weird. Getting a syntax error out of the builtin libraries does make me think it's running the "wrong" interpreter against the py2.7 libraries...I can try a little later on but all I can think to attempt is maybe an explicit PYTHONPATH option to point it at /usr/lib/python3.4 or whatever.

**Comment by singlecheeze** [comment]
Thank you @meejah 

I'll be in IRC all day if you want to tackle this together...

**Comment by singlecheeze** [comment]
Setting guest worker python path to an absolute path vs. relative solved one issue with encodings (thank you for the suggestion @meejah !, I think this should be listed as a bug as the interface does give false positive saying it is getting python3 from environment variables):

``` json
{
         "id": "backend",
         "type": "guest",
         "executable": "/usr/bin/python3",
         "arguments": ["backend.py"],
         "options": {
            "env": {
               "vars": {
                  "PYTHONUNBUFFERED": "1"
               }
            },
            "workdir": "../backend",
            "stdout": "log",
            "stderr": "log"
         }
      }
```

Still getting an assertion error on CRA:
``` text
2015-08-31T10:22:45-0400 [Controller   1546] Using guest worker executable '/usr/bin/python3' (executable path taken from configuration)
2015-08-31T10:22:45-0400 [Controller   1546] Starting Guest with ID 'backend'...
2015-08-31T10:22:45-0400 [Controller   1546] Guest with ID 'backend' and PID 1556 started
2015-08-31T10:22:45-0400 [Controller   1546] Guest 'backend': started
2015-08-31T10:22:45-0400 [Guest        1555] b'Connected. Joining realm realm1 as user authorUser ...\n'
2015-08-31T10:22:45-0400 [Guest        1554] b'Connected. Joining realm realm1 as user authenUser ...\n'
2015-08-31T10:22:45-0400 [Router       1550] Traceback (most recent call last):
2015-08-31T10:22:45-0400 [Router       1550]   File "/usr/local/lib/python3.4/dist-packages/crossbar/router/session.py", line 601, in onHello
2015-08-31T10:22:45-0400 [Router       1550]     user['secret'].encode('utf8'))
2015-08-31T10:22:45-0400 [Router       1550]   File "/usr/local/lib/python3.4/dist-packages/crossbar/router/auth.py", line 104, in __init__
2015-08-31T10:22:45-0400 [Router       1550]     self.signature = auth.compute_wcs(secret, self.challenge)
2015-08-31T10:22:45-0400 [Router       1550]   File "/usr/local/lib/python3.4/dist-packages/autobahn/wamp/auth.py", line 234, in compute_wcs
2015-08-31T10:22:45-0400 [Router       1550]     assert(type(challenge) == bytes)
2015-08-31T10:22:45-0400 [Router       1550] AssertionError

```

**Comment by singlecheeze** [comment]
Just to be clear this is with the latest master branch:

``` text
 Crossbar.io        : 0.11.0
   Autobahn         : 0.10.5.post2
     UTF8 Validator : autobahn
     XOR Masker     : autobahn
     JSON Codec     : stdlib
     MsgPack Codec  : -
   Twisted          : 15.3.0-EPollReactor
   Python           : 3.4.0/CPython
 OS                 : Linux-3.19.0-26-generic-x86_64-with-Ubuntu-14.04-trusty
 Machine            : x86_64
```

**Comment by meejah** [comment]
That's even more-weird; examining the code (``crossbar/controller/process.py`` at 643) it would seem the only difference between putting "/usr/bin/python3" in the config and "python3" is that it runs ``which`` against the latter -- in both cases it should be "really" using the full path ``/usr/bin/python3``.

I can't explain what's going on there :/ nor why it seems to be finding python2.7 libraries. One thing that's a little weird is that I see ``/usr/local/...`` in your last log (which is actually issue #412 I believe) but the python you're using is at ``/usr/bin/python3`` (not ``/usr/local/bin/python3``).

Can you explain how you installed Python2 and 3 on this machine?

**Comment by singlecheeze** [comment]
Its a stock install of ubuntu 14.04.03 I have not installed any extra
python versions...

**Comment by meejah** [comment]
@singlecheeze regarding the ``CodecRegistryError`` thing, see: https://github.com/crossbario/crossbar/pull/428

**Comment by singlecheeze** [comment]
Thank you!
