### ISSUE TITLE
Python 3 User authentication failure

### ISSUE THREAD

**Issue by milverton** [crossbario/crossbar#468]
## Issue
I get an exception when I try to run an authentication module in python 3 (see authenticaion.py below). In python 2 it works fine. In python 3 it chokes (see traceback below). Now, if I decode the secret key myself with this code then the code runs:

``return {'role' : 'client', 'secret' : key.decode('ascii'), 'salt' : salt}``

except that I end up with this from javscript console (authobahn)

``connection closed Object {reason: "wamp.error.not_authorized", message: "signature is invalid", retry_delay: null, retry_count: null, will_retry: false}``

In essence, the only line of code to change is key.decode('ascii') to stop crossbar throwing an exception.

## OS Details
Linux version 3.13.0-61-generic (buildd@lgw01-50) (gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) ) #100-Ubuntu SMP Wed Jul 29 11:21:34 UTC 2015
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty

## config.json
```
{
  "controller": {},
  "workers": [
    {
      "components": [
        {
          "classname": "authenticate.Hippies",
          "realm": "milvos",
          "role": "client",
          "type": "class"
        }
      ],
      "options": {
        "pythonpath": [
          ".."
        ]
      },
      "realms": [
        {
          "name": "milvos",
          "roles": [
            {
              "name": "client",
              "permissions": [
                {
                  "call": true,
                  "publish": true,
                  "register": true,
                  "subscribe": true,
                  "uri": "*"
                }
              ]
            }
          ]
        }
      ],
      "transports": [
        {
          "auth": {
            "wampcra": {
              "authenticator": "rpc.authenticate",
              "type": "dynamic"
            }
          },
          "endpoint": {
            "port": 8216,
            "type": "tcp"
          },
          "type": "websocket",
          "url": "ws://127.0.0.1:8216/ws"
        }
      ],
      "type": "router"
    }
  ]
}
```

## Console log
```
2015-09-21T20:27:31+0800 [Router       1533] Worker running under CPython-EPollReactor
2015-09-21T20:27:32+0800 [Controller   1477] Router with ID 'worker1' and PID 1533 started
2015-09-21T20:27:32+0800 [Controller   1477] Router 'worker1': realm 'realm1' (named 'milvos') started
2015-09-21T20:27:32+0800 [Controller   1477] Router 'worker1': role 'role1' (named 'client') started on realm 'realm1'
2015-09-21T20:27:32+0800 [Controller   1477] Router 'worker1': component 'component1' started
2015-09-21T20:27:32+0800 [Router       1533] WampWebSocketServerFactory starting on 8216
2015-09-21T20:27:32+0800 [Controller   1477] Router 'worker1': transport 'transport1' started
2015-09-21T20:27:33+0800 [Router       1533] Internal error (2): 'bytes' object has no attribute 'encode'
```
## Traceback
```
Traceback (most recent call last):
  File "/home/ubuntu/p3/lib/python3.4/site-packages/txaio/tx.py", line 324, in as_future
    return maybeDeferred(fun, *args, **kwargs)
  File "/home/ubuntu/p3/lib/python3.4/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/home/ubuntu/p3/lib/python3.4/site-packages/crossbar/router/session.py", line 700, in onHello
    d.addCallbacks(on_authenticate_ok, on_authenticate_error)
  File "/home/ubuntu/p3/lib/python3.4/site-packages/twisted/internet/defer.py", line 306, in addCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/home/ubuntu/p3/lib/python3.4/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/ubuntu/p3/lib/python3.4/site-packages/crossbar/router/session.py", line 670, in on_authenticate_ok
    user['secret'].encode('utf8'))
builtins.AttributeError: 'bytes' object has no attribute 'encode'
```
## authentication.py
```
 from twisted.internet.defer import inlineCallbacks
 from autobahn.twisted.wamp import ApplicationSession
 from autobahn.wamp.exception import ApplicationError
 from autobahn.wamp import auth

 import appdirs
 import os
 import glob
 import binascii
 import yaml

 def getAuth(length):
     a = os.urandom(length)
     return binascii.hexlify(a).decode('utf-8')

 def getAuthKey(secret, challenge):
     return auth.derive_key(str(secret).encode('utf-8'), salt=challenge.encode('utf-8'))

 def getSignature(key, challenge):
     return auth.compute_wcs(key, challenge=challenge.encode('utf-8'))

 def loadYAML(path):
     if os.path.exists(path):
         with open(path, 'r') as f:
             data = yaml.load(f)
             if data:
                 return data
     return {}

 def loadKeys():
     KEYS = {}
     cfg_dir = appdirs.user_config_dir('milvos', 'milvos')
     realms = glob.glob(os.path.join(cfg_dir, 'realms/*.yaml'))        

     for f in realms:
         data = loadYAML(f)
         if data:
             #REALM_KEYS[data.get('realmKey')] = data.get('realm')
             #DEPLOYMENT_CONFIG[data.get('realm')] = data
             KEYS[data.get('realm')] = data.get('orgid')
     return KEYS

  class Hippies(ApplicationSession):


     @inlineCallbacks
     def onJoin(self, details):
         keys = loadKeys()

         def authenticate(realm, authid, details):
             try:
                 _authid, _salt = authid.split('|')
                 orgid = keys.get(_authid)            
                 if orgid:
                     salt = getAuth(6)
                     key = getAuthKey(orgid, _salt)
                     #print('KEY', key)
                     return {'role' : 'client', 'secret' : key, 'salt' : salt}
                 else:
                     raise ApplicationError('unauthorised realm')
             except Exception as e:
                 raise ApplicationError(str(e))
                           
         yield self.register(authenticate, 'rpc.authenticate')

```

**Comment by KrYpTeD974** [comment]
I have exactly the same problem. It seems that Twisted isn't compatible with python 3. 
I tried to change twisted for asyncio but without success. I'm a beginner with asyncio and twisted so maybe you can give a try.

**Comment by hawkowl** [comment]
Yeah, this is a Crossbar on Py3 bug. Tagging accordingly.

**Comment by oberstet** [comment]
@hawkowl does that still persist?

**Comment by merrellb** [comment]
@oberstet @hawkowl 
I still have a similar problem when running the crossbar example:

crossbarexamples/authentication/wampcra/static/client.py on Python 3.5.1 (Debian 8.2).

I get the following error and traceback:

```
  File "/home/brian/venv/python35/lib/python3.5/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "client.py", line 64, in onChallenge
    challenge.extra['keylen'])
  File "/home/brian/venv/python35/lib/python3.5/site-packages/autobahn/wamp/auth.py", line 186, in derive_key
    assert(type(secret) == bytes)
builtins.AssertionError:  
```
I've tried fixing this and a few similar exceptions with:
```
--- a/authentication/wampcra/static/client.py
+++ b/authentication/wampcra/static/client.py
@@ -58,8 +58,8 @@ class ClientSession(ApplicationSession):
 
          if u'salt' in challenge.extra:
             # salted secret
-            key = auth.derive_key(USER_SECRET,
-                                  challenge.extra['salt'],
+            key = auth.derive_key(USER_SECRET.encode('utf8'),
+                                  challenge.extra['salt'].encode('utf8'),
                                   challenge.extra['iterations'],
                                   challenge.extra['keylen'])
          else:
@@ -67,7 +67,7 @@ class ClientSession(ApplicationSession):
             key = USER_SECRET
 
          # compute signature for challenge, using the key
-         signature = auth.compute_wcs(key, challenge.extra['challenge'])
+         signature = auth.compute_wcs(key, challenge.extra['challenge'].encode('utf8'))
 
          # return the signature to the router for verification
          return signature
```
but eventually run into this issue which I have not been able to fix:
```
  File "/home/brian/venv/python35/lib/python3.5/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/brian/venv/python35/lib/python3.5/site-packages/autobahn/wamp/protocol.py", line 376, in success
    raise Exception('signature must be unicode')
builtins.Exception: signature must be unicode
```

**Comment by meejah** [comment]
This is because crossbar is expecting a ``str`` (not ``bytes``) for the ``secret``. We could fairly easily just make crossbar accept either -- or throw an exception earlier complaining about the wrong type for ``secret`` instead of just blindly calling .encode('utf8') (https://github.com/crossbario/crossbar/blob/master/crossbar/router/auth/wampcra.py#L78)

**Comment by oberstet** [comment]
This is fixed now (on trunk) .. the WAMP-CRA examples here https://github.com/crossbario/crossbarexamples/tree/master/authentication/wampcra work for both Python 2 and Python 3
