### ISSUE TITLE
AutobahnCPP fails to connect to Crossbar under Python3

### ISSUE THREAD

**Issue by brianbirke** [crossbario/crossbar#475]
## Description:

Connect with 2 clients to Crossbar ( not neccesary simultanious ). 
* Client 1) AutobahnPython  ( cfg port 9090 see below )
* Client 2) AutobahnCpp  ( cfg port 9091 see below )

Running Crossbar under python 2 all works, but running Crossbar in python3 ( 3.4.3 ), the AutobahnCPP client fails to connect. The AutobahnPython works fine though. 

## Configuration is the same in the 2 cases : 
```
         "transports": [
            {
               "type": "web",
               "endpoint": {
                  "type": "tcp",
                  "port": 9090 
               },
               "paths": {
                  "/": {
                     "type": "static",
                     "directory": "../static"
                  },
                  "ws": {
                     "type": "websocket"
                  }
               }
            },
            {
               "type": "rawsocket",
               "endpoint": {
                  "type": "tcp",
                  "port": 9091
               },
               "debug": true 
            }
         ]
```

## The failing traceback:
```
2015-10-01T14:12:45+0000 [Router         25 log_legacy] Unhandled Error
Traceback (most recent call last):
  File "/develop/eggs/Twisted-15.4.0-py3.4.egg/twisted/python/log.py", line 101, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/develop/eggs/Twisted-15.4.0-py3.4.egg/twisted/python/log.py", line 84, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/develop/eggs/Twisted-15.4.0-py3.4.egg/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/develop/eggs/Twisted-15.4.0-py3.4.egg/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/develop/eggs/Twisted-15.4.0-py3.4.egg/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
    why = selectable.doRead()
  File "/develop/eggs/Twisted-15.4.0-py3.4.egg/twisted/internet/tcp.py", line 209, in doRead
    return self._dataReceived(data)
  File "/develop/eggs/Twisted-15.4.0-py3.4.egg/twisted/internet/tcp.py", line 215, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/develop/eggs/autobahn-0.10.9-py3.4.egg/autobahn/twisted/rawsocket.py", line 199, in dataReceived
    if ord(self._handshake_bytes[0]) != 0x7f:
builtins.TypeError: ord() expected string of length 1, but int found
```
```
2015-10-01T14:12:45+0000 [Controller     21 crossbar.router.router.Router] Router.process: WAMP PUBLISH Message (request = 439, topic = crossbar.node.cc6ec3216253.worker.worker1.on_log, args = ('Unhandled Error\nTraceback (most recent call last):\n  File "/develop/eggs/Twisted-15.4.0-py3.4.egg/twisted/python/log.py", line 101, in callWithLogger\n    return callWithContext({{"system": lp}}, func, *args, **kw)\n  File "/develop/eggs/Twisted-15.4.0-py3.4.egg/twisted/python/log.py", line 84, in callWithContext\n    return context.call({{ILogContext: newCtx}}, func, *args, **kw)\n  File "/develop/eggs/Twisted-15.4.0-py3.4.egg/twisted/python/context.py", line 118, in callWithContext\n    return self.currentContext().callWithContext(ctx, func, *args, **kw)\n  File "/develop/eggs/Twisted-15.4.0-py3.4.egg/twisted/python/context.py", line 81, in callWithContext\n    return func(*args,**kw)\n--- <exception caught here> ---\n  File "/develop/eggs/Twisted-15.4.0-py3.4.egg/twisted/internet/posixbase.py", line 597, in _doReadOrWrite\n    why = selectable.doRead()\n  File "/develop/eggs/Twisted-15.4.0-py3.4.egg/twisted/internet/tcp.py", line 209, in doRead\n    return self._dataReceived(data)\n  File "/develop/eggs/Twisted-15.4.0-py3.4.egg/twisted/internet/tcp.py", line 215, in _dataReceived\n    rval = self.protocol.dataReceived(data)\n  File "/develop/eggs/autobahn-0.10.9-py3.4.egg/autobahn/twisted/rawsocket.py", line 199, in dataReceived\n    if ord(self._handshake_bytes[0]) != 0x7f:\nbuiltins.TypeError: ord() expected string of length 1, but int found\n',), kwargs = {}, acknowledge = None, exclude_me = None, exclude = None, eligible = None, disclose_me = None)
```

##  The more exact version descriptions:

```
Crossbar.io        : 0.11.1
   Autobahn         : 0.10.9
     UTF8 Validator : autobahn
     XOR Masker     : autobahn
     JSON Codec     : stdlib
     MsgPack Codec  : msgpack-python-0.4.6
   Twisted          : 15.4.0-EPollReactor
   Python           : 2.7.6/CPython
 OS                 : Linux-3.13.0-49-generic-x86_64-with-Ubuntu-14.04-trusty
 Machine            : x86_64


 Crossbar.io        : 0.11.1
   Autobahn         : 0.10.9
     UTF8 Validator : autobahn
     XOR Masker     : autobahn
     JSON Codec     : stdlib
     MsgPack Codec  : msgpack-python-0.4.6
   Twisted          : 15.4.0-EPollReactor
   Python           : 3.4.3/CPython
 OS                 : Linux-3.13.0-49-generic-x86_64-with-Ubuntu-14.04-trusty
 Machine            : x86_64
```

**Comment by hawkowl** [comment]
Thanks for the bug report.

This seems to be a Python 3 bug in ``RawSocket``, which is what AutobahnCPP uses, while AutobahnPython uses ``WebSocket`` by default.

I'll have a fix for this soon.

**Comment by hawkowl** [comment]
Hi @brianbirke, this was an issue in Autobahn -- it's been fixed in master. Since this should fix it, I'll close this issue.

If running with a trunk Autobahn (`pip install https://github.com/crossbario/autobahn-python/archive/master.zip` in a virtualenv should work) has further issues with Rawsocket, please file another issue and I'll get on fixing it :)
