### ISSUE TITLE
Exception `...object has no attribute '_session_details'` in dynamic authorizer

### ISSUE THREAD

**Issue by schoonc** [crossbario/crossbar#483]
config.json:
```
{
  "controller": {
  },
  "workers": [
    {
      "type": "router",
      "options": {
        "pythonpath": [".."]
      },
      "realms": [
        {
          "name": "realm1",
          "roles": [
            {
               "name": "authorizer",
               "permissions": [
                  {
                     "uri": "com.example.auth",
                     "register": true
                  }
               ]
            },
            {
              "name": "app",
              "authorizer": "com.example.auth"
            }
          ]
        }
      ],
      "transports": [
        {
          "type": "websocket",
          "endpoint": {
            "type": "tcp",
            "port": 8080
          }
        }
      ],
      "components": [
        {
             "type": "class",
             "classname": "component.MyAuthorizer",
             "realm": "realm1",
             "role": "authorizer"
          },
          {
             "type": "class",
             "classname": "component.App",
             "realm": "realm1",
             "role": "app"
          }
      ]
    }
  ]
}
```
component.py:
```
from autobahn.twisted.wamp import ApplicationSession
from twisted.internet.defer import inlineCallbacks


class App(ApplicationSession):
    def test(self):
        return True

    @inlineCallbacks
    def onJoin(self, details):
        yield self.register(self.test, u'test')


class MyAuthorizer(ApplicationSession):
    @inlineCallbacks
    def onJoin(self, details):
        yield self.register(self.authorize, u'com.example.auth')

    def authorize(self, session, uri, action):
        return True
```
After `crossbar start` exception raised:
```
Traceback (most recent call last):
  File "/home/alexander/dev/crossbar/crossbar/router/router.py", line 158, in process
    self._dealer.processRegister(session, msg)
  File "/home/alexander/dev/crossbar/crossbar/router/dealer.py", line 259, in processRegister
    txaio.add_callbacks(d, on_authorize_success, on_authorize_error)
  File "/home/alexander/.virtualenvs/pro-crm-core/local/lib/python2.7/site-packages/txaio/tx.py", line 386, in add_callbacks
    future.addCallbacks(callback, errback)
  File "/home/alexander/.virtualenvs/pro-crm-core/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 306, in addCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/home/alexander/.virtualenvs/pro-crm-core/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/alexander/dev/crossbar/crossbar/router/dealer.py", line 250, in on_authorize_error
    self.log.failure(err)
  File "/home/alexander/dev/crossbar/crossbar/_logging.py", line 362, in failure
    return self.logger.failure(*args, **kwargs)
  File "/home/alexander/.virtualenvs/pro-crm-core/local/lib/python2.7/site-packages/twisted/logger/_logger.py", line 176, in failure
    failure = Failure()
  File "/home/alexander/.virtualenvs/pro-crm-core/local/lib/python2.7/site-packages/twisted/python/failure.py", line 214, in __init__
    raise NoCurrentExceptionError()
twisted.python.failure.NoCurrentExceptionError
```
This message is not very clear, but after inserting `print err` before `self.log.failure(err)` in `on_authorize_error` callback in crossbar.router.dealer.py:Dealer.processRegister I saw in crossbar log:
```
2015-10-18T16:17:19+0300 [Router      15028] [Failure instance: Traceback: <type 'exceptions.AttributeError'>: 'App' object has no attribute '_session_details'
2015-10-18T16:17:19+0300 [Router      15028] /home/alexander/dev/crossbar/crossbar/router/session.py:185:send
2015-10-18T16:17:19+0300 [Router      15028] /home/alexander/dev/crossbar/crossbar/router/router.py:158:process
2015-10-18T16:17:19+0300 [Router      15028] /home/alexander/dev/crossbar/crossbar/router/dealer.py:199:processRegister
2015-10-18T16:17:19+0300 [Router      15028] /home/alexander/.virtualenvs/pro-crm-core/local/lib/python2.7/site-packages/txaio/tx.py:336:as_future
2015-10-18T16:17:19+0300 [Router      15028] --- <exception caught here> ---
2015-10-18T16:17:19+0300 [Router      15028] /home/alexander/.virtualenvs/pro-crm-core/local/lib/python2.7/site-packages/twisted/internet/defer.py:150:maybeDeferred
2015-10-18T16:17:19+0300 [Router      15028] /home/alexander/dev/crossbar/crossbar/router/router.py:237:authorize
2015-10-18T16:17:19+0300 [Router      15028] /home/alexander/dev/crossbar/crossbar/router/role.py:203:authorize
2015-10-18T16:17:19+0300 [Router      15028] ]
```
As a workaround I added `self._session_details = details` in my class App.onJoin, but I'm not sure it's right.

P.S. Sorry for my english and long description.

**Comment by oberstet** [comment]
I can reproduce this issue when the authorizer runs embedded in a router worker: https://github.com/crossbario/crossbarexamples/tree/master/authorization/dynamic/embedded

```console
(cpy2710_1)oberstet@corei7ub1310:~/scm/crossbario/crossbarexamples/authorization/dynamic/embedded$ crossbar start
2016-04-08T15:10:15+0200 [Controller  25205]      __  __  __  __  __  __      __     __
2016-04-08T15:10:15+0200 [Controller  25205]     /  `|__)/  \/__`/__`|__) /\ |__)  |/  \
2016-04-08T15:10:15+0200 [Controller  25205]     \__,|  \\__/.__/.__/|__)/~~\|  \. |\__/
2016-04-08T15:10:15+0200 [Controller  25205]                                         
2016-04-08T15:10:15+0200 [Controller  25205]     Crossbar.io Version: 0.13.1
2016-04-08T15:10:15+0200 [Controller  25205]     Node Public Key: 9527f0b495b5f503003f541e733fbaef8e0852a46834d50168bad651c26ea224
2016-04-08T15:10:15+0200 [Controller  25205] 
2016-04-08T15:10:15+0200 [Controller  25205] Running from node directory '/home/oberstet/scm/crossbario/crossbarexamples/authorization/dynamic/embedded/.crossbar'
2016-04-08T15:10:15+0200 [Controller  25205] Controller process starting (CPython-EPollReactor) ..
2016-04-08T15:10:15+0200 [Controller  25205] Node configuration loaded from 'config.json'
2016-04-08T15:10:15+0200 [Controller  25205] Node ID 'corei7ub1310' set from hostname
2016-04-08T15:10:15+0200 [Controller  25205] Using default node shutdown triggers [u'shutdown_on_worker_exit']
2016-04-08T15:10:15+0200 [Controller  25205] Joined realm 'crossbar' on node management router
2016-04-08T15:10:15+0200 [Controller  25205] Starting Router with ID 'worker-001'...
2016-04-08T15:10:15+0200 [Router      25210] Worker process starting (CPython-EPollReactor) ..
2016-04-08T15:10:16+0200 [Controller  25205] Router with ID 'worker-001' and PID 25210 started
2016-04-08T15:10:16+0200 [Router      25210] Realm 'realm1' started
2016-04-08T15:10:16+0200 [Controller  25205] Router 'worker-001': realm 'realm-001' (named 'realm1') started
2016-04-08T15:10:16+0200 [Controller  25205] Router 'worker-001': role 'role-001' (named 'authorizer') started on realm 'realm-001'
2016-04-08T15:10:16+0200 [Controller  25205] Router 'worker-001': role 'role-002' (named 'app') started on realm 'realm-001'
2016-04-08T15:10:16+0200 [Router      25210] started component: authorizer.Authorizer id=7027844609597631
2016-04-08T15:10:16+0200 [Controller  25205] Router 'worker-001': component 'component-001' started
2016-04-08T15:10:16+0200 [Router      25210] started component: app.App id=6494418350480579
2016-04-08T15:10:16+0200 [Router      25210] Authorization failed
Traceback (most recent call last):
  File "/home/oberstet/scm/crossbario/crossbar/crossbar/router/router.py", line 182, in process
    self._dealer.processRegister(session, msg)
  File "/home/oberstet/scm/crossbario/crossbar/crossbar/router/dealer.py", line 216, in processRegister
    d = self._router.authorize(session, register.procedure, u'register')
  File "/home/oberstet/scm/crossbario/crossbar/crossbar/router/router.py", line 266, in authorize
    d = txaio.as_future(authorize, session, uri, action)
  File "/home/oberstet/scm/crossbario/txaio/txaio/tx.py", line 407, in as_future
    return maybeDeferred(fun, *args, **kwargs)
--- <exception caught here> ---
  File "/home/oberstet/cpy2710_1/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/home/oberstet/scm/crossbario/crossbar/crossbar/router/role.py", line 351, in authorize
    return self._session.call(self._authorizer, session._session_details,
exceptions.AttributeError: 'App' object has no attribute '_session_details'
...
```

When run in a container worker, this doesn't happen:

```console
(cpy2710_1)oberstet@corei7ub1310:~/scm/crossbario/crossbarexamples/authorization/dynamic/container$ crossbar start
2016-04-08T15:11:08+0200 [Controller  25217]      __  __  __  __  __  __      __     __
2016-04-08T15:11:08+0200 [Controller  25217]     /  `|__)/  \/__`/__`|__) /\ |__)  |/  \
2016-04-08T15:11:08+0200 [Controller  25217]     \__,|  \\__/.__/.__/|__)/~~\|  \. |\__/
2016-04-08T15:11:08+0200 [Controller  25217]                                         
2016-04-08T15:11:08+0200 [Controller  25217]     Crossbar.io Version: 0.13.1
2016-04-08T15:11:08+0200 [Controller  25217]     Node Public Key: 9527f0b495b5f503003f541e733fbaef8e0852a46834d50168bad651c26ea224
2016-04-08T15:11:08+0200 [Controller  25217] 
2016-04-08T15:11:08+0200 [Controller  25217] Running from node directory '/home/oberstet/scm/crossbario/crossbarexamples/authorization/dynamic/container/.crossbar'
2016-04-08T15:11:08+0200 [Controller  25217] Controller process starting (CPython-EPollReactor) ..
2016-04-08T15:11:08+0200 [Controller  25217] Node configuration loaded from 'config.json'
2016-04-08T15:11:08+0200 [Controller  25217] Node ID 'corei7ub1310' set from hostname
2016-04-08T15:11:08+0200 [Controller  25217] Using default node shutdown triggers [u'shutdown_on_worker_exit']
2016-04-08T15:11:08+0200 [Controller  25217] Joined realm 'crossbar' on node management router
2016-04-08T15:11:08+0200 [Controller  25217] Starting Router with ID 'worker-001'...
2016-04-08T15:11:08+0200 [Router      25222] Worker process starting (CPython-EPollReactor) ..
2016-04-08T15:11:08+0200 [Controller  25217] Router with ID 'worker-001' and PID 25222 started
2016-04-08T15:11:08+0200 [Router      25222] Realm 'realm1' started
2016-04-08T15:11:08+0200 [Controller  25217] Router 'worker-001': realm 'realm-001' (named 'realm1') started
2016-04-08T15:11:08+0200 [Controller  25217] Router 'worker-001': role 'role-001' (named 'authorizer') started on realm 'realm-001'
2016-04-08T15:11:08+0200 [Controller  25217] Router 'worker-001': role 'role-002' (named 'app') started on realm 'realm-001'
2016-04-08T15:11:08+0200 [Router      25222] Site starting on 8080
2016-04-08T15:11:08+0200 [Controller  25217] Router 'worker-001': transport 'transport-001' started
2016-04-08T15:11:08+0200 [Controller  25217] Starting Container with ID 'worker-002'...
2016-04-08T15:11:09+0200 [Container   25227] Worker process starting (CPython-EPollReactor) ..
2016-04-08T15:11:09+0200 [Controller  25217] Container with ID 'worker-002' and PID 25227 started
2016-04-08T15:11:09+0200 [Controller  25217] Container 'worker-002': component 'component-001' started
2016-04-08T15:11:09+0200 [Controller  25217] Container 'worker-002': component 'component-002' started
2016-04-08T15:11:09+0200 [Container   25227] authorize: session={u'authprovider': u'static', u'authid': u'app', u'authrole': u'app', u'authmethod': u'ticket', u'session': 6801636195823395L, u'transport': {u'cbtid': None, u'protocol': 'wamp.2.cbor.batched', u'http_headers_received': {u'upgrade': u'WebSocket', u'sec-websocket-version': u'13', u'sec-websocket-protocol': u'wamp.2.cbor.batched,wamp.2.cbor,wamp.2.msgpack.batched,wamp.2.msgpack,wamp.2.json.batched,wamp.2.json', u'connection': u'Upgrade', u'sec-websocket-key': u'sGyZTHJu3WhPV1hVSK8N0Q==', u'user-agent': u'AutobahnPython/0.13.0', u'host': u'127.0.0.1:8080', u'pragma': u'no-cache', u'cache-control': u'no-cache'}, u'peer': u'tcp4:127.0.0.1:44760', u'http_headers_sent': {}, u'type': 'websocket'}}, uri=com.example.test, action=register
2016-04-08T15:11:09+0200 [Container   25227] procedure successfully registered!
...
```

**Comment by meejah** [comment]
I have re-tested both the original test-case (and thanks to @schoonc for a great bug-report, BTW!) and the crossbarexample that @oberstet pointed to, and both work now. From code inspection, we don't just blindly access `._session_details` anymore either (e.g. see https://github.com/crossbario/crossbar/blob/master/crossbar/router/role.py#L364).

So, I'm convinced this is fixed at least in master; please re-open if I'm wrong.
