### ISSUE TITLE
Guest watcher starts new guest before old guest shuts down

### ISSUE THREAD

**Issue by Kostronor** [crossbario/crossbar#490]
I am using a java guest application with crossbar.io 0.11.1:

```
Automatically choosing optimal Twisted reactor
Running on Linux and optimal reactor (epoll) was installed.
     __  __  __  __  __  __      __     __
    /  `|__)/  \/__`/__`|__) /\ |__)  |/  \
    \__,|  \\__/.__/.__/|__)/~~\|  \. |\__/

 Crossbar.io        : 0.11.1
   Autobahn         : 0.10.9
     UTF8 Validator : autobahn
     XOR Masker     : autobahn
     JSON Codec     : stdlib
     MsgPack Codec  : msgpack-python-0.4.6
   Twisted          : 15.4.0-EPollReactor
   Python           : 2.7.10/PyPy-2.6.1
 OS                 : Linux-3.13.0-042stab111.12-x86_64-with-debian-jessie-sid
 Machine            : x86_64
```

My guest worker is similar to the hello template and the issue can be reproduced with it. My config.json:

```
{
      "type": "guest",
      "executable": "java",
      "arguments": [
        "-Djava.util.logging.config.file=./.crossbar/logging.properties",
        "-jar",
        "./bin/hello.jar",
        "ws://127.0.0.1:7777/ws",
        "realm"
      ],
      "options": {
        "workdir": "..",
        "watch": {
          "directories": [
            "../bin",
            "../sync/client"
          ],
          "action": "restart"
        },
        "stdout": "log",
        "stderr": "log"
      }
    }
```

Because the file watcher only gets notified when there is a new file, I have added this code in my build script to trigger a restart:

```
#all moved, pinging restart now
##first the client
touch ./sync/client/RESTART
##cleanup
rm ./sync/client/RESTART
```

My log looks like this:

```
2015-10-24T09:11:46+0200 [Controller  22560] Using guest worker executable '/usr/bin/java' (executable path detected from environment)
2015-10-24T09:11:46+0200 [Controller  22560] Starting Guest with ID 'worker2'...
2015-10-24T09:11:46+0200 [Controller  22560] Guest with ID 'worker2' and PID 22570 started
2015-10-24T09:11:46+0200 [Controller  22560] Guest 'worker2': started
2015-10-24T09:11:46+0200 [Guest       22570] INFORMATION: Session status changed to Disconnected
2015-10-24T09:11:46+0200 [Guest       22570] INFORMATION: Session status changed to Connecting
2015-10-24T09:11:47+0200 [Guest       22570] INFORMATION: Session status changed to Connected
2015-10-24T09:12:56+0200 [Controller  22560] Restarting guest ..
2015-10-24T09:12:56+0200 [Controller  22560] Could not start worker: a worker with ID 'worker2' is already running (or starting)
2015-10-24T09:12:56+0200 [Controller  22560] Unhandled Error
Traceback (most recent call last):
  File "/opt/crossbar/site-packages/crossbar/controller/cli.py", line 834, in run
    options.func(options, reactor=reactor)
  File "/opt/crossbar/site-packages/crossbar/controller/cli.py", line 551, in run_command_start
    reactor.run()
  File "/opt/crossbar/site-packages/twisted/internet/base.py", line 1194, in run
    self.mainLoop()
  File "/opt/crossbar/site-packages/twisted/internet/base.py", line 1203, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/opt/crossbar/site-packages/twisted/internet/base.py", line 825, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/opt/crossbar/site-packages/crossbar/controller/process.py", line 660, in start_guest
    raise ApplicationError(u'crossbar.error.worker_already_running', emsg)
autobahn.wamp.exception.ApplicationError: ApplicationError('crossbar.error.worker_already_running', args = ("Could not start worker: a worker with ID 'worker2' is already running (or starting)",), kwargs = {})

2015-10-24T09:12:56+0200 [Controller  22560] Guest worker2 exited with error A process has ended with a probable error condition: process ended with exit code 143.
```

After that error, both the old and the new worker are terminated. 

If you need anything else, please say.

**Comment by oberstet** [comment]
I believe the PR https://github.com/crossbario/crossbar/pull/491 at least added a stopgap solution for this
