### ISSUE TITLE
Can't login with cyrillic authid

### ISSUE THREAD

**Issue by morfair** [crossbario/crossbar#493]
I use WAMPCRA with Dynamic Authorization and PostgreSQL backend. It work good with latin authid, but do not work with cyrillic authid:

<pre><code>
Traceback (most recent call last):
  File "lib/python2.7/site-packages/autobahn-0.11.0-py2.7.egg/autobahn/wamp/protocol.py", line 544, in onMessage
    txaio.resolve(on_reply, msg.args[0])
  File "lib/python2.7/site-packages/txaio-2.0.4-py2.7.egg/txaio/tx.py", line 348, in resolve
    future.callback(result)
  File "lib/python2.7/site-packages/Twisted-15.4.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 393, in callback
    self._startRunCallbacks(result)
  File "lib/python2.7/site-packages/Twisted-15.4.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 501, in _startRunCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "lib/python2.7/site-packages/Twisted-15.4.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "lib/python2.7/site-packages/crossbar-0.11.1-py2.7.egg/crossbar/router/session.py", line 324, in success
    self._transport.send(msg)
  File "lib/python2.7/site-packages/autobahn-0.11.0-py2.7.egg/autobahn/wamp/websocket.py", line 120, in send
    raise SerializationError("WAMP serialization error ({0})".format(e))
autobahn.wamp.exception.SerializationError: WAMP serialization error ('ascii' codec can't decode byte 0xd0 in position 80: ordinal not in range(128))
</code></pre>

It callee stdout, caller do not get some errback.

**Comment by oberstet** [comment]
fixed on trunk
