### ISSUE TITLE
File Upload Service Python 3 - twisted makedirs

### ISSUE THREAD

**Issue by singlecheeze** [crossbario/crossbar#504]
@goeddea @hawkowl please ref #481 I think this might be related, same router config and index/script used there.

```text
2015-11-02T20:41:53-0500 [Controller   8066] Entering reactor event loop...
2015-11-02T20:41:53-0500 [Controller   8066] Warning, could not set process title (setproctitle not installed)
2015-11-02T20:41:53-0500 [Controller   8066] Process utilities not available
2015-11-02T20:41:53-0500 [Controller   8066] Joined realm 'crossbar' on node management router
2015-11-02T20:41:53-0500 [Controller   8066] No WAMPlets detected in enviroment.
2015-11-02T20:41:53-0500 [Controller   8066] Starting Router with ID 'wamprouter'...
2015-11-02T20:41:54-0500 [Router       8070] Worker running under CPython-EPollReactor
2015-11-02T20:41:54-0500 [Router       8070] Process utilities not available
2015-11-02T20:41:54-0500 [Controller   8066] Router with ID 'wamprouter' and PID 8070 started
2015-11-02T20:41:54-0500 [Controller   8066] Router 'wamprouter': realm 'realm1' (named 'realm1') started
2015-11-02T20:41:54-0500 [Controller   8066] Router 'wamprouter': role 'role1' (named 'anonymous') started on realm 'realm1'
2015-11-02T20:41:54-0500 [Controller   8066] Router 'wamprouter': role 'role2' (named 'backend') started on realm 'realm1'
2015-11-02T20:41:54-0500 [Controller   8066] Router 'wamprouter': role 'role3' (named 'frontend') started on realm 'realm1'
2015-11-02T20:41:54-0500 [Router       8070] Site starting on 80
2015-11-02T20:41:54-0500 [Controller   8066] Router 'wamprouter': transport 'web' started
2015-11-02T20:43:32-0500 [Router       8070] Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/twisted/web/http.py", line 1445, in dataReceived
    finishCallback(data[contentLength:])
  File "/usr/local/lib/python3.5/site-packages/twisted/web/http.py", line 1703, in _finishRequestBody
    self.allContentReceived()
  File "/usr/local/lib/python3.5/site-packages/twisted/web/http.py", line 1766, in allContentReceived
    req.requestReceived(command, path, version)
  File "/usr/local/lib/python3.5/site-packages/twisted/web/http.py", line 832, in requestReceived
    self.process()
--- <exception caught here> ---
  File "/usr/local/lib/python3.5/site-packages/twisted/web/server.py", line 183, in process
    self.render(resrc)
  File "/usr/local/lib/python3.5/site-packages/twisted/web/server.py", line 234, in render
    body = resrc.render(self)
  File "/usr/local/lib/python3.5/site-packages/twisted/web/resource.py", line 250, in render
    return m(request)
  File "/usr/local/lib/python3.5/site-packages/crossbar/twisted/resource.py", line 344, in render_POST
    fileTempDir.makedirs()
  File "/usr/local/lib/python3.5/site-packages/twisted/python/filepath.py", line 1421, in makedirs
    return os.makedirs(self.path)
  File "/usr/local/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
builtins.FileExistsError: [Errno 17] File exists: '/home/dave/monocle/frontend/temp/a5UA0000000L1rvMAC~1~WestervilleXIO-vbxbcl02psdu_2015_10_23_1029.tar.gz'

```

Javascript console output:
```text
500 (Internal Server Error)$.send @ resumable.js:758$.test.testHandler @ resumable.js:611
upload.html:72 fileError ResumableFile {opts: Object, _prevProgress: 0, resumableObj: Resumable, file: File, fileName: "a5UA0000000L1rvMAC~1~WestervilleXIO-vbxbcl02psdu_2015_10_23_1029.tar.gz"…} <html><head><title>Processing Failed</title></head><body><b>Processing Failed</b></body></html>
upload.html:25 Object {total: 620475626, status: "started", remaining: 620475626, chunk: 3, name: "a5UA0000000L1rvMAC~1~WestervilleXIO-vbxbcl02psdu_2015_10_23_1029.tar.gz"…}
upload.html:25 Object {total: 620475626, status: "progress", remaining: 615514112, chunk: 1, name: "a5UA0000000L1rvMAC~1~WestervilleXIO-vbxbcl02psdu_2015_10_23_1029.tar.gz"…}
upload.html:25 Object {total: 620475626, status: "progress", remaining: 614465536, chunk: 2, name: "a5UA0000000L1rvMAC~1~WestervilleXIO-vbxbcl02psdu_2015_10_23_1029.tar.gz"…}
upload.html:25 Object {total: 620475626, status: "progress", remaining: 613416960, chunk: 4, name: "a5UA0000000L1rvMAC~1~WestervilleXIO-vbxbcl02psdu_2015_10_23_1029.tar.gz"…}
```

**Comment by singlecheeze** [comment]
Just got a few more errors when trying to drag 2 ~600 MB files into the dropzone on the example upload page... I'm wondering if the issue is related to a non-async open/write it looks like the router is doing (I wish python had builtin libs for async file read/write)?

```text
2015-11-02T21:04:39-0500 [Router       8402] Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/twisted/web/http.py", line 1445, in dataReceived
    finishCallback(data[contentLength:])
  File "/usr/local/lib/python3.5/site-packages/twisted/web/http.py", line 1703, in _finishRequestBody
    self.allContentReceived()
  File "/usr/local/lib/python3.5/site-packages/twisted/web/http.py", line 1766, in allContentReceived
    req.requestReceived(command, path, version)
  File "/usr/local/lib/python3.5/site-packages/twisted/web/http.py", line 832, in requestReceived
    self.process()
--- <exception caught here> ---
  File "/usr/local/lib/python3.5/site-packages/twisted/web/server.py", line 183, in process
    self.render(resrc)
  File "/usr/local/lib/python3.5/site-packages/twisted/web/server.py", line 234, in render
    body = resrc.render(self)
  File "/usr/local/lib/python3.5/site-packages/twisted/web/resource.py", line 250, in render
    return m(request)
  File "/usr/local/lib/python3.5/site-packages/crossbar/twisted/resource.py", line 365, in render_POST
    with open(_chunkName.path, 'wb') as chunk:
builtins.FileNotFoundError: [Errno 2] No such file or directory: '/home/dave/monocle/frontend/temp/a5UA0000000L1sFMAS~1~DublinXIO-vbxbcl01psdu_2015_10_23_1039.tar.gz/#kfhfkzuru578e38viokbjhfvz4w__chunk_4'

2015-11-02T21:06:29-0500 [Router       8402] Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/twisted/web/http.py", line 1445, in dataReceived
    finishCallback(data[contentLength:])
  File "/usr/local/lib/python3.5/site-packages/twisted/web/http.py", line 1703, in _finishRequestBody
    self.allContentReceived()
  File "/usr/local/lib/python3.5/site-packages/twisted/web/http.py", line 1766, in allContentReceived
    req.requestReceived(command, path, version)
  File "/usr/local/lib/python3.5/site-packages/twisted/web/http.py", line 832, in requestReceived
    self.process()
--- <exception caught here> ---
  File "/usr/local/lib/python3.5/site-packages/twisted/web/server.py", line 183, in process
    self.render(resrc)
  File "/usr/local/lib/python3.5/site-packages/twisted/web/server.py", line 234, in render
    body = resrc.render(self)
  File "/usr/local/lib/python3.5/site-packages/twisted/web/resource.py", line 250, in render
    return m(request)
  File "/usr/local/lib/python3.5/site-packages/crossbar/twisted/resource.py", line 365, in render_POST
    with open(_chunkName.path, 'wb') as chunk:
builtins.FileNotFoundError: [Errno 2] No such file or directory: '/home/dave/monocle/frontend/temp/a5UA0000000L1sFMAS~1~DublinXIO-vbxbcl01psdu_2015_10_23_1039.tar.gz/#kfhfkzuru578e38viokbjhfvz4w__chunk_4'

2015-11-02T21:06:29-0500 [Router       8402] Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/twisted/web/http.py", line 1445, in dataReceived
    finishCallback(data[contentLength:])
  File "/usr/local/lib/python3.5/site-packages/twisted/web/http.py", line 1703, in _finishRequestBody
    self.allContentReceived()
  File "/usr/local/lib/python3.5/site-packages/twisted/web/http.py", line 1766, in allContentReceived
    req.requestReceived(command, path, version)
  File "/usr/local/lib/python3.5/site-packages/twisted/web/http.py", line 832, in requestReceived
    self.process()
--- <exception caught here> ---
  File "/usr/local/lib/python3.5/site-packages/twisted/web/server.py", line 183, in process
    self.render(resrc)
  File "/usr/local/lib/python3.5/site-packages/twisted/web/server.py", line 234, in render
    body = resrc.render(self)
  File "/usr/local/lib/python3.5/site-packages/twisted/web/resource.py", line 250, in render
    return m(request)
  File "/usr/local/lib/python3.5/site-packages/crossbar/twisted/resource.py", line 365, in render_POST
    with open(_chunkName.path, 'wb') as chunk:
builtins.FileNotFoundError: [Errno 2] No such file or directory: '/home/dave/monocle/frontend/temp/a5UA0000000L1sFMAS~1~DublinXIO-vbxbcl01psdu_2015_10_23_1039.tar.gz/#kfhfkzuru578e38viokbjhfvz4w__chunk_5'

2015-11-02T21:06:29-0500 [Router       8402] Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/twisted/web/http.py", line 1445, in dataReceived
    finishCallback(data[contentLength:])
  File "/usr/local/lib/python3.5/site-packages/twisted/web/http.py", line 1703, in _finishRequestBody
    self.allContentReceived()
  File "/usr/local/lib/python3.5/site-packages/twisted/web/http.py", line 1766, in allContentReceived
    req.requestReceived(command, path, version)
  File "/usr/local/lib/python3.5/site-packages/twisted/web/http.py", line 832, in requestReceived
    self.process()
--- <exception caught here> ---
  File "/usr/local/lib/python3.5/site-packages/twisted/web/server.py", line 183, in process
    self.render(resrc)
  File "/usr/local/lib/python3.5/site-packages/twisted/web/server.py", line 234, in render
    body = resrc.render(self)
  File "/usr/local/lib/python3.5/site-packages/twisted/web/resource.py", line 250, in render
    return m(request)
  File "/usr/local/lib/python3.5/site-packages/crossbar/twisted/resource.py", line 365, in render_POST
    with open(_chunkName.path, 'wb') as chunk:
builtins.FileNotFoundError: [Errno 2] No such file or directory: '/home/dave/monocle/frontend/temp/a5UA0000000L1sFMAS~1~DublinXIO-vbxbcl01psdu_2015_10_23_1039.tar.gz/#kfhfkzuru578e38viokbjhfvz4w__chunk_6'
```

**Comment by hawkowl** [comment]
Unfortunately, not even UNIX has usable asynchronous file I/O, so we might just need to get it to do smaller chunks... It works okay for smaller files, though?

I'm at Django Under The Hood (or at least about to get on a plane with it), so I will look at it when available :)

**Comment by singlecheeze** [comment]
Smaller files seem to be OK. I'll set my chunk size to a smaller value and
check stability. Currently set to resumable's default 1 MB. Any chance we
could do some better error handling so the error doesn't crash the router?

Have fun!

**Comment by singlecheeze** [comment]
So I've done some more research today. Looks like smaller file chunks work better, at least for the implementation on crossbar. Went to 1024 * 512 for chunk size and things are more smooth. Though I have discovered another error... If I upload certain tar.gz files that open fine in Ubuntu/Mint, post upload they no longer open correctly in the OS (with the image below) and additionally can not be read with stdlib tarfile:
```text
tar = tarfile.open(path_to_file)
      for member in tar.getmembers():
              print(member.name)
```
```text
file could not be opened successfully
```

**Comment by singlecheeze** [comment]
Could the issue revolve around use of dict vs. needed OrderedDict to track chunks?

**Comment by meejah** [comment]
I haven't looked very closely, but it does seem to indicate some kind of race-condition in deleting the tempdir, or collisions in chunk filenames, "or something"...

**Comment by singlecheeze** [comment]
Thanks meejah. Working on a big project and this is an integral piece. I think you are on the right path. The temp dir code in python might be returning before the dir is actually acknoldged erased by the file system.... or something....

**Comment by singlecheeze** [comment]
See https://pypi.python.org/pypi/django-admin-resumable-js/1.1

>Django silently truncates incomplete chunks, due to the way the multipart parser works: https://github.com/django/django/blob/master/django/http/multipartparser.py This could result in a file being unable to be uploaded, or a corrupt file, depending on the situation.

**Comment by gregkeys** [comment]
+1 

there does seem to be a bug here, currently I cant upload any files larger than the chunk size if I want to upload a 100MB file my chunks look like this 100*1024*1024

if I try uploading a 100MB file with chunksize set to 1*1024*1024 the reconstructed file is always less than 2kb, I have tried smaller chunk sizes and its basically the same results.

this is an integral part of our project as well, we can get by with fudging the chunk size but as you can imagine its not ideal

**Comment by singlecheeze** [comment]
Bumping this. Hope you had a nice trip @hawkowl !

**Comment by markope** [comment]
sorry guys. I'll definitely fix the issue in the near future. I'm just so busy right now....

**Comment by singlecheeze** [comment]
Marko,

Many thanks! This is very important to me so if you would like help or to
discuss something just keep this thread going and I will monitor.

Great work!

Dave

**Comment by oberstet** [comment]
Unrelated to the issue, but related to the upload service in general: the multi-core support that's on trunk should work with the upload service and should make it easy to sustain even full rate 10 GbE HTTP upload traffic .. if that is the kind of upload bandwidth needed by an app anyway;) 

https://github.com/crossbario/crossbarexamples/tree/master/benchmark/web

But if anyone wants to test that, this would also be welcome. You can just slightly adjust above benchmark, which is using a JSON value Web resource and replace that with a File Upload Web resource. And then use a HTTP file upload load generator ..

**Comment by markope** [comment]
I made a fix that should fix your issues. It's already merged into master. Please test with your setup.

**Comment by singlecheeze** [comment]
Thank you very much Marko!

**Comment by singlecheeze** [comment]
@markope I just hit this exception in CB.... do I need to be using a special build of twisted until your changes are merged to master?

File "/usr/local/lib/python3.5/site-packages/twisted/web/server.py", line 183, in process
    self.render(resrc)
  File "/usr/local/lib/python3.5/site-packages/twisted/web/server.py", line 234, in render
    body = resrc.render(self)
  File "/usr/local/lib/python3.5/site-packages/twisted/web/resource.py", line 250, in render
    return m(request)
  File "/usr/local/lib/python3.5/site-packages/crossbar/twisted/resource.py", line 405, in render_POST
    with open(_chunkName.path, 'wb') as chunk:
builtins.FileNotFoundError: [Errno 2] No such file or directory: '/home/dave/temp/a5UA0000000L1sFMAS~1~DublinXIO-vbxbcl01psdu_2015_10_23_1039.tar.gz/#kfhf3kz412uru578e38viokbjhfvz4w__chunk_1150'

**Comment by markope** [comment]
This has nothing to do with twisted, i think. I have an idea how this can happen. When the first chunk arrives some setup is performed in the backend that might take a small while. In particular at some point the folders are created. In the meantime the second chunk can arrive expecting the folders to exist. If the second chunk arrives too early then the folder is not yet created. 
I'll make a fix which always creates the folder before writing to disk. It is somehow hard to recreate your error scenario to test that this solves the issue. Could you give me your resumable.js settings? How fast is the connection from browser to the crossbar web server? Do you test on a local scenario i.e. browser on the same machine as the web server?

**Comment by singlecheeze** [comment]
Hey @markope the connection is somewhat slow as I am over vpn today. My internet is 50/50 mbps upload/download but with vpn at my company I know I'm not getting anywhere near that as I know it is throttled too. I don't test on a browser on the same machine. 
```js
r = new Resumable({
            target: 'upload',
            chunkSize: 1024 * 512, // Deault 1MB 1024 * 1024
            forceChunkSize: true, // https://github.com/23/resumable.js/issues/51
            simultaneousUploads: 4,
            testChunks: true,
            query: {
                on_progress: 'mono.upload.on_progress',
                session: sess.id //,
                //chunk_extra: JSON.stringify({
                //    SR: currentSR,
                //    extra_info2: "blah"
                //}),
                //finish_extra: JSON.stringify({
                //    SR: currentSR,
                //    extra_info2: "blah"
                //})
            }
        });
```
