### ISSUE TITLE
SyntaxError while running crossbar

### ISSUE THREAD

**Issue by grikdotnet** [crossbario/crossbar#508]
Hi, I get an error after installation on CentOS 6.7 according to docs http://crossbar.io/docs/Installation-on-CentOS/
```
$ crossbar version
Traceback (most recent call last):
  File "/usr/bin/crossbar", line 9, in <module>
    load_entry_point('crossbar==0.11.1', 'console_scripts', 'crossbar')()
  File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 2697, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 2370, in load
    return self.resolve()
  File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 2376, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.6/site-packages/crossbar/controller/cli.py", line 487
    'options': {x: y for x, y in options_dump.items()
                       ^
SyntaxError: invalid syntax

```
$ python -V
Python 2.6.6

It runs fine with python 3.4.3 on another machine, though.

Is there a minimum version requirement?

**Comment by oberstet** [comment]
Crossbar.io does not support Py 2.6, but only 2.7+ and 3.3+

**Comment by grikdotnet** [comment]
needs a check and mention in docs

**Comment by oberstet** [comment]
@grikdotnet yep, we should document that https://github.com/crossbario/crossbardocs/issues/47
