### ISSUE TITLE
Cannot start crossbar with Python 3.5 on Windows

### ISSUE THREAD

**Issue by s-trooper** [crossbario/crossbar#557]
Hi, crossbar run with python 2.7 but not with python 3.5.1
```
crossbar==0.11.2
pypiwin32==219
```

```
: crossbar start
Running on Windows, but cannot install IOCP Twisted reactor
2015-12-15T14:49:30+0100 [Controller   6432] Running on Windows, but cannot install IOCP Twisted reactor
2015-12-15T14:49:30+0100 [Controller   6432] Traceback (most recent call last):
  File "c:\dev\local\src\clone\prod\server\.py-venv\win\lib\site-packages\autobahn\twisted\choosereactor.py", line 83, in install_optimal_reactor
    from twisted.internet.iocpreactor import reactor as iocpreactor
ImportError: No module named 'twisted.internet.iocpreactor'

2015-12-15T14:49:31+0100 [Controller   6432] Stale Crossbar.io PID file (pointing to non-existing process with PID 816) C:\Dev\Local\src\Clone\prod\server\.crossbar\node.pid removed
2015-12-15T14:49:31+0100 [Controller   6432]      __  __  __  __  __  __      __     __
2015-12-15T14:49:31+0100 [Controller   6432]     /  `|__)/  \/__`/__`|__) /\ |__)  |/  \
2015-12-15T14:49:31+0100 [Controller   6432]     \__,|  \\__/.__/.__/|__)/~~\|  \. |\__/
2015-12-15T14:49:31+0100 [Controller   6432]
2015-12-15T14:49:31+0100 [Controller   6432]     Version: 0.11.2
2015-12-15T14:49:31+0100 [Controller   6432]
2015-12-15T14:49:31+0100 [Controller   6432] Starting from node directory C:\Dev\Local\src\Clone\prod\server\.crossbar
2015-12-15T14:49:32+0100 [Controller   6432] Traceback (most recent call last):
2015-12-15T14:49:32+0100 [Controller   6432]   File "C:\Dev\Local\src\Clone\prod\server\.py-venv\win\Scripts\crossbar-script.py", line 9, in <module>
2015-12-15T14:49:32+0100 [Controller   6432]     load_entry_point('crossbar==0.11.2', 'console_scripts', 'crossbar')()
2015-12-15T14:49:32+0100 [Controller   6432]   File "c:\dev\local\src\clone\prod\server\.py-venv\win\lib\site-packages\crossbar\controller\cli.py", line 848, in run
2015-12-15T14:49:32+0100 [Controller   6432]     options.func(options, reactor=reactor)
2015-12-15T14:49:32+0100 [Controller   6432]   File "c:\dev\local\src\clone\prod\server\.py-venv\win\lib\site-packages\crossbar\controller\cli.py", line 536, in run_command_start
2015-12-15T14:49:32+0100 [Controller   6432]     from crossbar.controller.node import Node
2015-12-15T14:49:32+0100 [Controller   6432]   File "c:\dev\local\src\clone\prod\server\.py-venv\win\lib\site-packages\crossbar\controller\node.py", line 49, in <module>
2015-12-15T14:49:32+0100 [Controller   6432]     from crossbar.worker.router import RouterRealm
2015-12-15T14:49:32+0100 [Controller   6432]   File "c:\dev\local\src\clone\prod\server\.py-venv\win\lib\site-packages\crossbar\worker\router.py", line 60, in <module>
2015-12-15T14:49:32+0100 [Controller   6432]     from crossbar.worker.testee import WebSocketTesteeServerFactory, \
2015-12-15T14:49:32+0100 [Controller   6432]   File "c:\dev\local\src\clone\prod\server\.py-venv\win\lib\site-packages\crossbar\worker\testee.py", line 43, in <module>
2015-12-15T14:49:32+0100 [Controller   6432]     from crossbar.worker.worker import NativeWorkerSession
2015-12-15T14:49:32+0100 [Controller   6432]   File "c:\dev\local\src\clone\prod\server\.py-venv\win\lib\site-packages\crossbar\worker\worker.py", line 45, in <module>
2015-12-15T14:49:32+0100 [Controller   6432]     from crossbar.common.process import NativeProcessSession
2015-12-15T14:49:32+0100 [Controller   6432]   File "c:\dev\local\src\clone\prod\server\.py-venv\win\lib\site-packages\crossbar\common\process.py", line 69, in <module>
2015-12-15T14:49:32+0100 [Controller   6432]     from crossbar.twisted.endpoint import create_listening_port_from_config
2015-12-15T14:49:32+0100 [Controller   6432]   File "c:\dev\local\src\clone\prod\server\.py-venv\win\lib\site-packages\crossbar\twisted\endpoint.py", line 42, in <module>
2015-12-15T14:49:32+0100 [Controller   6432]     from twisted.internet.endpoints import TCP4ServerEndpoint, \
2015-12-15T14:49:32+0100 [Controller   6432]   File "c:\dev\local\src\clone\prod\server\.py-venv\win\lib\site-packages\twisted\internet\endpoints.py", line 34, in <module>
2015-12-15T14:49:32+0100 [Controller   6432]     from twisted.internet.stdio import StandardIO, PipeAddress
2015-12-15T14:49:32+0100 [Controller   6432]   File "c:\dev\local\src\clone\prod\server\.py-venv\win\lib\site-packages\twisted\internet\stdio.py", line 30, in <module>
2015-12-15T14:49:32+0100 [Controller   6432]     from twisted.internet import _win32stdio
2015-12-15T14:49:32+0100 [Controller   6432] ImportError: cannot import name '_win32stdio'
```

P.S: btw i can't install crossbar[all] on windows please please please  add wheel support i can't install multiple VS on every Windows crossbar server ...

**Comment by agronholm** [comment]
It's not the fault of crossbar developers if the dependencies aren't available as wheels.

**Comment by hawkowl** [comment]
Hi, Twisted does not yet support Python 3 on Windows, so we can't do much quite yet. I'm working on that, you can follow the progress here -- https://twistedmatrix.com/trac/ticket/8025#ticket -- but there's still a bit of work to do, as a lot requires changing.

The availability of wheels on Windows is unfortunate, but there's little we can do (since it's up to the upstream dependencies to publish them). Python 3 should make this easier, with the Universal CRT and available for free VS 2015 -- building wheels for your dependencies should be simpler, and then you can just use your privately compiled wheels.

**Comment by oberstet** [comment]
Closing, because it needs to be fixed upstream.
