### ISSUE TITLE
Traceback event handler

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#578]
When an even handler was subscribed that can't consume the event args/kwargs, this throws an error. Check that in general, but in particular with component running embedded:

```
2016-01-04T00:11:08+0100 [Router       5358] Fatal error in component: While firing <function onhello at 0x7ff61ebabb18> subscribed under 5174327938517943. - onhello() takes exactly 1 argument (0 given)
2016-01-04T00:11:08+0100 [Router       5358] Unhandled error in Deferred:
2016-01-04T00:11:08+0100 [Router       5358] 
Traceback (most recent call last):
  File "/home/oberstet/scm/crossbario/crossbar/crossbar/router/router.py", line 170, in process
    self._broker.processPublish(session, msg)
  File "/home/oberstet/scm/crossbario/crossbar/crossbar/router/broker.py", line 337, in processPublish
    txaio.add_callbacks(d, on_authorize_success, on_authorize_error)
  File "/home/oberstet/scm/crossbario/txaio/txaio/tx.py", line 392, in add_callbacks
    future.addCallbacks(callback, errback)
  File "/home/oberstet/python279_1/lib/python2.7/site-packages/twisted/internet/defer.py", line 306, in addCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/home/oberstet/python279_1/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/oberstet/scm/crossbario/crossbar/crossbar/router/broker.py", line 313, in on_authorize_success
    for receiver in receivers:
exceptions.RuntimeError: Set changed size during iteration
```

**Comment by meejah** [comment]
Okay, so what's happening here is that the Broker works out the list of subscription receivers and then loops over these, send()ing the publish messages. Upon an error, the connecting is failed.

In the embedded-router case, the ``send()`` is actually synchronous as ``RouterApplicationSession`` is behaving as the ITransport -- and so when the connection fails, it ``detach()``es from the Broker and hence drops all observations, changing the "receivers" set-size.

I think the safest approach is to copy the initial "receivers" ``set`` (here: https://github.com/crossbario/crossbar/blob/master/crossbar/router/broker.py#L261) but it *should* also work if we instead ensure the ``send()`` calls all have to "take a trip through the reactor" by ``callLater(0, send, ...)``. OR maybe just make sure the detach (https://github.com/crossbario/crossbar/blob/master/crossbar/router/session.py#L133) takes such a trip...

**Comment by oberstet** [comment]
this has been fixed
