### ISSUE TITLE
Do not require pynacl

### ISSUE THREAD

**Issue by singlecheeze** [crossbario/crossbar#579]
```text
2016-01-06T10:26:59-0500 [Controller   1268] Traceback (most recent call last):
2016-01-06T10:26:59-0500 [Controller   1268]   File "/usr/local/bin/crossbar", line 9, in <module>
2016-01-06T10:26:59-0500 [Controller   1268]     load_entry_point('crossbar==0.11.2', 'console_scripts', 'crossbar')()
2016-01-06T10:26:59-0500 [Controller   1268]   File "/usr/local/lib/python3.5/dist-packages/crossbar/controller/cli.py", line 907, in run
2016-01-06T10:26:59-0500 [Controller   1268]     options.func(options, reactor=reactor)
2016-01-06T10:26:59-0500 [Controller   1268]   File "/usr/local/lib/python3.5/dist-packages/crossbar/controller/cli.py", line 533, in run_command_start
2016-01-06T10:26:59-0500 [Controller   1268]     from crossbar.controller.node import maybe_generate_key
2016-01-06T10:26:59-0500 [Controller   1268]   File "/usr/local/lib/python3.5/dist-packages/crossbar/controller/node.py", line 50, in <module>
2016-01-06T10:26:59-0500 [Controller   1268]     from crossbar.router.session import RouterSessionFactory
2016-01-06T10:26:59-0500 [Controller   1268]   File "/usr/local/lib/python3.5/dist-packages/crossbar/router/session.py", line 54, in <module>
2016-01-06T10:26:59-0500 [Controller   1268]     from crossbar.router.auth import AUTHMETHODS, AUTHMETHOD_MAP, PendingAuthCryptosign
2016-01-06T10:26:59-0500 [Controller   1268] ImportError: cannot import name 'PendingAuthCryptosign'
```

```text
 Crossbar.io        : 0.11.2
   Autobahn         : 0.11.0
     UTF8 Validator : autobahn
     XOR Masker     : autobahn
     JSON Codec     : stdlib
     MsgPack Codec  : -
     CBOR Codec     : -
   Twisted          : 15.5.0-EPollReactor
   Python           : 3.5.1/CPython
 OS                 : Linux-3.19.0-41-generic-x86_64-with-Ubuntu-14.04-trusty
 Machine            : x86_64
```

**Comment by oberstet** [comment]
you need AutobahnPython trunk

**Comment by singlecheeze** [comment]
Tried sudo pip3 install -U  https://github.com/crossbario/autobahn-python/zipball/master

No dice, same error

**Comment by oberstet** [comment]
ah, right!

 `pip install pynacl` should do.

the bug we have is: don't _require_ pynacl.

**Comment by singlecheeze** [comment]
Thank you Tobias for monitoring Github so closely!

**Comment by singlecheeze** [comment]
Ok got over that hump, now this:
```text
2016-01-06T13:27:40-0500 [Controller  24615] Traceback (most recent call last):
2016-01-06T13:27:40-0500 [Controller  24615]   File "/usr/local/bin/crossbar", line 9, in <module>
2016-01-06T13:27:40-0500 [Controller  24615]     load_entry_point('crossbar==0.11.2', 'console_scripts', 'crossbar')()
2016-01-06T13:27:40-0500 [Controller  24615]   File "/usr/local/lib/python3.5/dist-packages/crossbar/controller/cli.py", line 907, in run
2016-01-06T13:27:40-0500 [Controller  24615]     options.func(options, reactor=reactor)
2016-01-06T13:27:40-0500 [Controller  24615]   File "/usr/local/lib/python3.5/dist-packages/crossbar/controller/cli.py", line 543, in run_command_start
2016-01-06T13:27:40-0500 [Controller  24615]     log.info(bannerFormat.format("Node Public Key:", click.style(pubkey, fg='yellow', bold=True)))
2016-01-06T13:27:40-0500 [Controller  24615]   File "/usr/local/lib/python3.5/dist-packages/click/termui.py", line 393, in style
2016-01-06T13:27:40-0500 [Controller  24615]     return ''.join(bits)
2016-01-06T13:27:40-0500 [Controller  24615] TypeError: sequence item 2: expected str instance, bytes found
```

**Comment by oberstet** [comment]
@singlecheeze awesome, py3 again;) I will fix it. thanks for reporting!

**Comment by oberstet** [comment]
@singlecheeze alright, I've committed some changes to both CB and AB, and tested WAMP-cryptosign authentication (if that is what you wanted to check out) using this [example](https://github.com/crossbario/crossbarexamples/tree/master/authentication/cryptosign/static) in these 4 variants:

- CB on CPy 3.5.0 and CPy 2.7.9
- AB on CPy 3.5.0 and CPy 2.7.9

All 4 work for me now.

Note: I have also "simplified" the setup.py .. now most of the stuff (incl. TLS and NaCl) are required https://github.com/crossbario/crossbar/commit/a73e662f9c3fe8d5f583cd876b13fe06447b4867

In essence: could you please pull and install trunk for both AB and CB and retest if it works for you also?

**Comment by singlecheeze** [comment]
I installed crossbar and autobahn in this order:
```text
Crossbar latest git:
sudo pip3 install -U https://github.com/crossbario/crossbar/zipball/master
Autobahn latest git:
sudo pip3 install -U https://github.com/crossbario/autobahn-python/zipball/master
```

And get this traceback upon starting crossbar:
```text
2016-01-07T10:54:57-0500 [Controller   1891] Traceback (most recent call last):
2016-01-07T10:54:57-0500 [Controller   1891]   File "/usr/local/bin/crossbar", line 9, in <module>
2016-01-07T10:54:57-0500 [Controller   1891]     load_entry_point('crossbar==0.11.2', 'console_scripts', 'crossbar')()
2016-01-07T10:54:57-0500 [Controller   1891]   File "/usr/local/lib/python3.5/dist-packages/crossbar/controller/cli.py", line 907, in run
2016-01-07T10:54:57-0500 [Controller   1891]     options.func(options, reactor=reactor)
2016-01-07T10:54:57-0500 [Controller   1891]   File "/usr/local/lib/python3.5/dist-packages/crossbar/controller/cli.py", line 534, in run_command_start
2016-01-07T10:54:57-0500 [Controller   1891]     pubkey = maybe_generate_key(log, options.cbdir)
2016-01-07T10:54:57-0500 [Controller   1891]   File "/usr/local/lib/python3.5/dist-packages/crossbar/controller/node.py", line 105, in maybe_generate_key
2016-01-07T10:54:57-0500 [Controller   1891]     privkey_obj = SigningKey(privkey, encoder=HexEncoder)
2016-01-07T10:54:57-0500 [Controller   1891]   File "/usr/local/lib/python3.5/dist-packages/nacl/signing.py", line 124, in __init__
2016-01-07T10:54:57-0500 [Controller   1891]     seed = encoder.decode(seed)
2016-01-07T10:54:57-0500 [Controller   1891]   File "/usr/local/lib/python3.5/dist-packages/nacl/encoding.py", line 40, in decode
2016-01-07T10:54:57-0500 [Controller   1891]     return binascii.unhexlify(data)
2016-01-07T10:54:57-0500 [Controller   1891] binascii.Error: Odd-length string
```

**Comment by oberstet** [comment]
Seems like the `.crossbar/node.key` is broken. Could you please remove that file and restart Crossbar.io?

**Comment by singlecheeze** [comment]
That did the trick thank you Tobias!

**Comment by oberstet** [comment]
Perfect! Thanks for your patience;)
