### ISSUE TITLE
Non-Twisted FilePath: Unicode issues

### ISSUE THREAD

**Issue by singlecheeze** [crossbario/crossbar#591]
#584 #585 
@hawkowl @meejah @markope Py3 error on router, just installed latest master a few minutes ago.

```text
2016-01-13T19:16:31-0500 [Router       3048] Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/twisted/web/http.py", line 1478, in dataReceived
    finishCallback(data[contentLength:])
  File "/usr/local/lib/python3.5/dist-packages/twisted/web/http.py", line 1736, in _finishRequestBody
    self.allContentReceived()
  File "/usr/local/lib/python3.5/dist-packages/twisted/web/http.py", line 1799, in allContentReceived
    req.requestReceived(command, path, version)
  File "/usr/local/lib/python3.5/dist-packages/twisted/web/http.py", line 832, in requestReceived
    self.process()
--- <exception caught here> ---
  File "/usr/local/lib/python3.5/dist-packages/twisted/web/server.py", line 183, in process
    self.render(resrc)
  File "/usr/local/lib/python3.5/dist-packages/twisted/web/server.py", line 234, in render
    body = resrc.render(self)
  File "/usr/local/lib/python3.5/dist-packages/twisted/web/resource.py", line 250, in render
    return m(request)
  File "/usr/local/lib/python3.5/dist-packages/crossbar/twisted/resource.py", line 320, in render_POST
    fileTempDir = os.path.join(self._tempDirRoot, fileId)
  File "/usr/lib/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.5/genericpath.py", line 145, in _check_arg_types
    raise TypeError("Can't mix strings and bytes in path components") from None
builtins.TypeError: Can't mix strings and bytes in path components

2016-01-13T19:16:31-0500 [Router       3048] Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/twisted/web/http.py", line 1478, in dataReceived
    finishCallback(data[contentLength:])
  File "/usr/local/lib/python3.5/dist-packages/twisted/web/http.py", line 1736, in _finishRequestBody
    self.allContentReceived()
  File "/usr/local/lib/python3.5/dist-packages/twisted/web/http.py", line 1799, in allContentReceived
    req.requestReceived(command, path, version)
  File "/usr/local/lib/python3.5/dist-packages/twisted/web/http.py", line 832, in requestReceived
    self.process()
--- <exception caught here> ---
  File "/usr/local/lib/python3.5/dist-packages/twisted/web/server.py", line 183, in process
    self.render(resrc)
  File "/usr/local/lib/python3.5/dist-packages/twisted/web/server.py", line 234, in render
    body = resrc.render(self)
  File "/usr/local/lib/python3.5/dist-packages/twisted/web/resource.py", line 250, in render
    return m(request)
  File "/usr/local/lib/python3.5/dist-packages/crossbar/twisted/resource.py", line 320, in render_POST
    fileTempDir = os.path.join(self._tempDirRoot, fileId)
  File "/usr/lib/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.5/genericpath.py", line 145, in _check_arg_types
    raise TypeError("Can't mix strings and bytes in path components") from None
builtins.TypeError: Can't mix strings and bytes in path components

2016-01-13T19:16:31-0500 [Router       3048] Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/twisted/web/http.py", line 1478, in dataReceived
    finishCallback(data[contentLength:])
  File "/usr/local/lib/python3.5/dist-packages/twisted/web/http.py", line 1736, in _finishRequestBody
    self.allContentReceived()
  File "/usr/local/lib/python3.5/dist-packages/twisted/web/http.py", line 1799, in allContentReceived
    req.requestReceived(command, path, version)
  File "/usr/local/lib/python3.5/dist-packages/twisted/web/http.py", line 832, in requestReceived
    self.process()
--- <exception caught here> ---
  File "/usr/local/lib/python3.5/dist-packages/twisted/web/server.py", line 183, in process
    self.render(resrc)
  File "/usr/local/lib/python3.5/dist-packages/twisted/web/server.py", line 234, in render
    body = resrc.render(self)
  File "/usr/local/lib/python3.5/dist-packages/twisted/web/resource.py", line 250, in render
    return m(request)
  File "/usr/local/lib/python3.5/dist-packages/crossbar/twisted/resource.py", line 320, in render_POST
    fileTempDir = os.path.join(self._tempDirRoot, fileId)
  File "/usr/lib/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.5/genericpath.py", line 145, in _check_arg_types
    raise TypeError("Can't mix strings and bytes in path components") from None
builtins.TypeError: Can't mix strings and bytes in path components

2016-01-13T19:16:31-0500 [Router       3048] Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/twisted/web/http.py", line 1478, in dataReceived
    finishCallback(data[contentLength:])
  File "/usr/local/lib/python3.5/dist-packages/twisted/web/http.py", line 1736, in _finishRequestBody
    self.allContentReceived()
  File "/usr/local/lib/python3.5/dist-packages/twisted/web/http.py", line 1799, in allContentReceived
    req.requestReceived(command, path, version)
  File "/usr/local/lib/python3.5/dist-packages/twisted/web/http.py", line 832, in requestReceived
    self.process()
--- <exception caught here> ---
  File "/usr/local/lib/python3.5/dist-packages/twisted/web/server.py", line 183, in process
    self.render(resrc)
  File "/usr/local/lib/python3.5/dist-packages/twisted/web/server.py", line 234, in render
    body = resrc.render(self)
  File "/usr/local/lib/python3.5/dist-packages/twisted/web/resource.py", line 250, in render
    return m(request)
  File "/usr/local/lib/python3.5/dist-packages/crossbar/twisted/resource.py", line 320, in render_POST
    fileTempDir = os.path.join(self._tempDirRoot, fileId)
  File "/usr/lib/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.5/genericpath.py", line 145, in _check_arg_types
    raise TypeError("Can't mix strings and bytes in path components") from None
builtins.TypeError: Can't mix strings and bytes in path components
```

**Comment by singlecheeze** [comment]
@hawkowl Any chance you have an estimate on when you will be able to take a look at this? I'm looking forward to getting file uploads stable.

**Comment by oberstet** [comment]
@hawkowl is working on different thing with higher priority (she is paid by us) pls stop nagging.    I am closing this now. If you continue, I will remove the whole code. Thanks for understanding

**Comment by singlecheeze** [comment]
@oberstet I'm not trying to nag and apologize.
@hawkowl asked me to open this to keep track of it, if you see her comment on #585.

I have been a big promoter of both Crossbar and Autobahn (you have even tweeted one of my blog posts)... please know I am just excited :relaxed: about getting this functionality working as I have been working with @markope offline via email for over a month now. If I was more familiar with the crossbar code I would attempt to fix it myself.
