### ISSUE TITLE
Crossbar startup failure with python 3.5 on Raspberry Pi B Model 2 

### ISSUE THREAD

**Issue by kashifpk** [crossbario/crossbar#597]
I have crossbar 0.11.2 running successfully with python 3.5 and twisted 15.5.0 on an standard Linux system. However the same configuration does not seem to work on a raspberry pi model 2. I previously had issues with pi model 1 but those were fixed when I switched to model 2. Probably related to timing of stuff during crossbar startup.

New project initializes okay:

    pi@raspberrypi /tmp $ crossbar init
    Initializing application template 'default' in directory '/tmp'
    Using template from '/usr/local/lib/python3.5/site-packages/crossbar/templates/default'
    Creating directory /tmp/.crossbar
    Creating file      /tmp/.crossbar/config.json
    Application template initialized

    To start your node, run 'crossbar start --cbdir /tmp/.crossbar'

But when I try to start it, it gives me this error log:

    pi@raspberrypi /tmp $ crossbar start --cbdir /tmp/.crossbar 
    2016-01-18T01:20:09+0000 [Controller   5739]      __  __  __  __  __  __      __     __
    2016-01-18T01:20:09+0000 [Controller   5739]     /  `|__)/  \/__`/__`|__) /\ |__)  |/  \
    2016-01-18T01:20:09+0000 [Controller   5739]     \__,|  \\__/.__/.__/|__)/~~\|  \. |\__/
    2016-01-18T01:20:09+0000 [Controller   5739]                                         
    2016-01-18T01:20:09+0000 [Controller   5739]     Version: 0.11.2     
    2016-01-18T01:20:09+0000 [Controller   5739] 
    2016-01-18T01:20:09+0000 [Controller   5739] Starting from node directory /tmp/.crossbar
    2016-01-18T01:20:13+0000 [Controller   5739] Traceback (most recent call last):
    2016-01-18T01:20:13+0000 [Controller   5739]   File "/usr/local/bin/crossbar", line 9, in <module>
    2016-01-18T01:20:13+0000 [Controller   5739]     load_entry_point('crossbar==0.11.2', 'console_scripts', 'crossbar')()
    2016-01-18T01:20:13+0000 [Controller   5739]   File "/usr/local/lib/python3.5/site-packages/crossbar/controller/cli.py", line 848, in run
    2016-01-18T01:20:13+0000 [Controller   5739]     options.func(options, reactor=reactor)
    2016-01-18T01:20:13+0000 [Controller   5739]   File "/usr/local/lib/python3.5/site-packages/crossbar/controller/cli.py", line 536, in run_command_start
    2016-01-18T01:20:13+0000 [Controller   5739]     from crossbar.controller.node import Node
    2016-01-18T01:20:13+0000 [Controller   5739]   File "/usr/local/lib/python3.5/site-packages/crossbar/controller/node.py", line 49, in <module>
    2016-01-18T01:20:13+0000 [Controller   5739]     from crossbar.worker.router import RouterRealm
    2016-01-18T01:20:13+0000 [Controller   5739]   File "/usr/local/lib/python3.5/site-packages/crossbar/worker/router.py", line 60, in <module>
    2016-01-18T01:20:13+0000 [Controller   5739]     from crossbar.worker.testee import WebSocketTesteeServerFactory, \
    2016-01-18T01:20:13+0000 [Controller   5739]   File "/usr/local/lib/python3.5/site-packages/crossbar/worker/testee.py", line 43, in <module>
    2016-01-18T01:20:13+0000 [Controller   5739]     from crossbar.worker.worker import NativeWorkerSession
    2016-01-18T01:20:13+0000 [Controller   5739]   File "/usr/local/lib/python3.5/site-packages/crossbar/worker/worker.py", line 45, in <module>
    2016-01-18T01:20:13+0000 [Controller   5739]     from crossbar.common.process import NativeProcessSession
    2016-01-18T01:20:13+0000 [Controller   5739]   File "/usr/local/lib/python3.5/site-packages/crossbar/common/process.py", line 77, in <module>
    2016-01-18T01:20:13+0000 [Controller   5739]     from txpostgres import txpostgres
    2016-01-18T01:20:13+0000 [Controller   5739]   File "/usr/local/lib/python3.5/site-packages/txpostgres/txpostgres.py", line 89, in <module>
    2016-01-18T01:20:13+0000 [Controller   5739]     class _PollingMixin(object):
    2016-01-18T01:20:13+0000 [Controller   5739]   File "/usr/local/lib/python3.5/site-packages/txpostgres/txpostgres.py", line 107, in _PollingMixin
    2016-01-18T01:20:13+0000 [Controller   5739]     implements(interfaces.IReadWriteDescriptor)
    2016-01-18T01:20:13+0000 [Controller   5739]   File "/usr/local/lib/python3.5/site-packages/zope/interface/declarations.py", line 412, in implements
    2016-01-18T01:20:13+0000 [Controller   5739]     raise TypeError(_ADVICE_ERROR % 'implementer')
    2016-01-18T01:20:13+0000 [Controller   5739] TypeError: Class advice impossible in Python3.  Use the @implementer class decorator instead.

Though this does not look like a race condition. If it were a python 3 compatibility issue, I should have faced the same error on a normal Linux machine. Any ideas to what might be causing this?

**Comment by kashifpk** [comment]
Just tested crossbar with python 2.7 on RPi 2 and it starts fine, so this seems to be a python 3.x issue.

**Comment by meejah** [comment]
It looks like an exception coming out of txpostgres -- are you getting a different txpostgres version on the Pi for some reason? Or not using it on the "real" linux system?

**Comment by kashifpk** [comment]
I'm using the same txpostgres version (1, 5, 0) on both the pi and on the normal Linux machine.

**Comment by oberstet** [comment]
Could you try starting python and do `import txpostgres`?

Also: which version of zope.inerface?

**Comment by kashifpk** [comment]
txpostgres imports without any issues.

    >>> import txpostgres
    >>> txpostgres.__version__
    (1, 5, 0)

zope.interface version is 4.1.3

**Comment by oberstet** [comment]
To be honest, I have no clue. This is strange. If you don't need PostgreSQL client (and Crossbar.io doesn't .. yet), I'd uninstall `txpostgres`.

**Comment by hawkowl** [comment]
txpostgres is not ported to Python 3, so, uninstall it.

**Comment by oberstet** [comment]
@hawkowl huh, ah. ok. I've filed https://github.com/wulczer/txpostgres/issues/40

**Comment by oberstet** [comment]
@kashifpk could you pls do what @hawkowl suggest (uninstall `txpostgres`), retry and if it works, close this issue?

**Comment by kashifpk** [comment]
Yes confirmed, uninstalling txpostres started crossbar on python3.5 without any issues.

**Comment by oberstet** [comment]
@kashifpk thanks for reporting back!

**Comment by kashifpk** [comment]
@oberstet My pleasure :-)
