### ISSUE TITLE
REST Callee and Subscriber don't work on Py3

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#603]
The reason is: these two REST bridge components use treq, and that hasn't been ported (completely) to Python 3. See: https://github.com/twisted/treq/issues/63

We are currently requiring Twisted 15.5 in CB - so everything that's there can be used.

Callee (https://github.com/crossbario/crossbarexamples/tree/master/rest/callee):

```
2016-01-23T18:54:49+0100 [Container    4539] AttributeError: 'bytes' object has no attribute 'encode': Traceback (most recent call last):
  File "/home/oberstet/scm/crossbario/autobahn-python/autobahn/wamp/protocol.py", line 755, in onMessage
    on_reply = txaio.as_future(endpoint.fn, *invoke_args, **invoke_kwargs)
  File "/home/oberstet/cpy351_1/lib/python3.5/site-packages/txaio/tx.py", line 339, in as_future
    return maybeDeferred(fun, *args, **kwargs)
  File "/home/oberstet/cpy351_1/lib/python3.5/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/home/oberstet/cpy351_1/lib/python3.5/site-packages/twisted/internet/defer.py", line 1274, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/home/oberstet/cpy351_1/lib/python3.5/site-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)
  File "/home/oberstet/scm/crossbario/crossbar/crossbar/adapter/rest/callee.py", line 67, in on_call
    params=params
  File "/home/oberstet/cpy351_1/lib/python3.5/site-packages/treq/api.py", line 103, in request
    return _client(**kwargs).request(method, url, **kwargs)
  File "/home/oberstet/cpy351_1/lib/python3.5/site-packages/treq/client.py", line 128, in request
    method = method.encode('ascii').upper()
builtins.AttributeError: 'bytes' object has no attribute 'encode'
```

> Sidenote: different from the Subscriber example below, CB will NOT bail out (stop), but make the HTTP request just hang. Neither is optimal: CB should log the error, and return the HTTP request with "internal error"

Subscriber (https://github.com/crossbario/crossbarexamples/tree/master/rest/subscriber):

```
2016-01-23T18:58:31+0100 [Container    4621] Fatal error in component: While firing functools.partial(<function MessageForwarder.onJoin.<locals>.on_event at 0x2ac6ed61f400>, 'https://httpbin.org/post') subscribed under 4866605160678539. - 'bytes' object has no attribute 'encode'
Traceback (most recent call last):
  File "/home/oberstet/scm/crossbario/autobahn-python/autobahn/wamp/protocol.py", line 533, in onMessage
    future = txaio.as_future(handler.fn, *invoke_args, **invoke_kwargs)
  File "/home/oberstet/cpy351_1/lib/python3.5/site-packages/txaio/tx.py", line 339, in as_future
    return maybeDeferred(fun, *args, **kwargs)
  File "/home/oberstet/cpy351_1/lib/python3.5/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/home/oberstet/cpy351_1/lib/python3.5/site-packages/twisted/internet/defer.py", line 1274, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/home/oberstet/cpy351_1/lib/python3.5/site-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)
  File "/home/oberstet/scm/crossbario/crossbar/crossbar/adapter/rest/subscriber.py", line 84, in on_event
    headers=headers
  File "/home/oberstet/cpy351_1/lib/python3.5/site-packages/treq/api.py", line 103, in request
    return _client(**kwargs).request(method, url, **kwargs)
  File "/home/oberstet/cpy351_1/lib/python3.5/site-packages/treq/client.py", line 128, in request
    method = method.encode('ascii').upper()
builtins.AttributeError: 'bytes' object has no attribute 'encode'
```

**Comment by oberstet** [comment]
@hawkowl As usual, since this is affecting CB users (and I really won't to get rid of the Py3 issues once and for all now;) - please feel free to work on this on Tavendo work time - be it in Twisted or in treq.

**Comment by hawkowl** [comment]
Whoops, that Treq ticket should be closed :)

I'll look into this, make sure it works -- it ought to!

**Comment by oberstet** [comment]
@hawkowl Could you pls check where we are on this?
