### ISSUE TITLE
REST Caller broken

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar#604]
Consider https://github.com/crossbario/crossbarexamples/tree/master/rest/caller

Start CB in a first terminal, and then do any of the curl requests shown in the example readme. All work, both on Py2 and 3.

However, now (instead of curl), use the https://github.com/crossbario/crossbarexamples/blob/master/rest/caller/test.py client

It bails out with (on both Py2 and 3):

```
2016-01-23T19:23:19+0100 [Router       4977] Unhandled error in Deferred:
2016-01-23T19:23:19+0100 [Router       4977] 
Traceback (most recent call last):
  File "/home/oberstet/scm/crossbario/crossbar/crossbar/adapter/rest/common.py", line 173, in render
    return self._render_request(request)
  File "/home/oberstet/scm/crossbario/crossbar/crossbar/adapter/rest/common.py", line 435, in _render_request
    d = self._process(request, event)
  File "/home/oberstet/scm/crossbario/crossbar/crossbar/adapter/rest/caller.py", line 107, in _process
    return d.addCallbacks(on_call_ok, on_call_error)
  File "/home/oberstet/cpy2710_1/lib/python2.7/site-packages/twisted/internet/defer.py", line 306, in addCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/home/oberstet/cpy2710_1/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/oberstet/scm/crossbario/crossbar/crossbar/adapter/rest/caller.py", line 105, in on_call_error
    log_category="AR458")
  File "/home/oberstet/scm/crossbario/crossbar/crossbar/adapter/rest/common.py", line 116, in _fail_request
    self.log.failure(None, log_failure=kwargs["log_failure"])
exceptions.KeyError: 'log_failure'
```
CB will just hang the HTTP request instead of returning with "internal error" or the like.

Also: what is wrong with the Py client (test.py)?

**Comment by samunda** [comment]
Encountered the same issue.

**Comment by hawkowl** [comment]
Fixed by https://github.com/crossbario/crossbar/pull/725 and the docs in https://github.com/crossbario/crossbarexamples/pull/71
