### ISSUE TITLE
SessionDetails & CloseDetails don't have a `caller` attribute

### ISSUE THREAD

**Issue by touilleMan** [crossbario/crossbar#645]
Hi,

Trying to play with crossbar from the master, I encounter something strange:

```
(py27-twtrunk-abtrunk)$ crossbar start
2016-02-11T15:09:11+0100 [Controller   2676] Automatically choosing optimal Twisted reactor
2016-02-11T15:09:11+0100 [Controller   2676] Running on Linux and optimal reactor (epoll) was installed.
2016-02-11T15:09:12+0100 [Controller   2676]      __  __  __  __  __  __      __     __
2016-02-11T15:09:12+0100 [Controller   2676]     /  `|__)/  \/__`/__`|__) /\ |__)  |/  \
2016-02-11T15:09:12+0100 [Controller   2676]     \__,|  \\__/.__/.__/|__)/~~\|  \. |\__/
2016-02-11T15:09:12+0100 [Controller   2676]                                         
2016-02-11T15:09:12+0100 [Controller   2676]     Crossbar.io Version: 0.13.0
2016-02-11T15:09:12+0100 [Controller   2676]     Node Public Key: a8a2f08583e53b6d0baaf3e0a186357d34934f285ad303497167e051d7c09e32
2016-02-11T15:09:12+0100 [Controller   2676] 
2016-02-11T15:09:12+0100 [Controller   2676] Running from node directory '/home/emmanuel/projects/flask-socketio-test/dummy_test/.crossbar'
2016-02-11T15:09:12+0100 [Controller   2676] Controller process starting (CPython-EPollReactor) ..
2016-02-11T15:09:12+0100 [Controller   2676] Node configuration loaded from 'config.json'
2016-02-11T15:09:12+0100 [Controller   2676] Node ID 'megaforce' set from hostname
2016-02-11T15:09:12+0100 [Controller   2676] Using default node shutdown triggers [u'shutdown_on_worker_exit']
2016-02-11T15:09:12+0100 [Controller   2676] Joined realm 'crossbar' on node management router
2016-02-11T15:09:12+0100 [Controller   2676] Starting Router with ID 'worker1'...
2016-02-11T15:09:12+0100 [Router       2694] Worker process starting (CPython-EPollReactor) ..
2016-02-11T15:09:13+0100 [Controller   2676] Router with ID 'worker1' and PID 2694 started
2016-02-11T15:09:13+0100 [Router       2694] Realm 'realm1' started
2016-02-11T15:09:13+0100 [Controller   2676] Router 'worker1': realm 'realm1' (named 'realm1') started
2016-02-11T15:09:13+0100 [Controller   2676] Router 'worker1': role 'role1' (named 'anonymous') started on realm 'realm1'
2016-02-11T15:09:13+0100 [Router       2694] Unhandled error in Deferred:
2016-02-11T15:09:13+0100 [Router       2694] 
Traceback (most recent call last):
  File "/home/emmanuel/projects/crossbar/.tox/py27-twtrunk-abtrunk/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/emmanuel/projects/crossbar/.tox/py27-twtrunk-abtrunk/local/lib/python2.7/site-packages/crossbar/router/session.py", line 170, in success
    d = self._session.fire('join', self._session, details)
  File "/home/emmanuel/projects/crossbar/.tox/py27-twtrunk-abtrunk/local/lib/python2.7/site-packages/autobahn/util.py", line 743, in fire
    future = txaio.as_future(handler, *args, **kwargs)
  File "/home/emmanuel/projects/crossbar/.tox/py27-twtrunk-abtrunk/local/lib/python2.7/site-packages/txaio/tx.py", line 339, in as_future
    return maybeDeferred(fun, *args, **kwargs)
--- <exception caught here> ---
  File "/home/emmanuel/projects/crossbar/.tox/py27-twtrunk-abtrunk/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/home/emmanuel/projects/crossbar/.tox/py27-twtrunk-abtrunk/local/lib/python2.7/site-packages/crossbar/worker/router.py", line 678, in publish_started
    session.publish(topic, event, options=PublishOptions(exclude=details.caller))
exceptions.AttributeError: 'SessionDetails' object has no attribute 'caller'

2016-02-11T15:09:13+0100 [Router       2694] Unhandled error in Deferred:
2016-02-11T15:09:13+0100 [Router       2694] 
Traceback (most recent call last):
  File "/home/emmanuel/projects/crossbar/.tox/py27-twtrunk-abtrunk/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/emmanuel/projects/crossbar/.tox/py27-twtrunk-abtrunk/local/lib/python2.7/site-packages/crossbar/router/session.py", line 170, in success
    d = self._session.fire('join', self._session, details)
  File "/home/emmanuel/projects/crossbar/.tox/py27-twtrunk-abtrunk/local/lib/python2.7/site-packages/autobahn/util.py", line 743, in fire
    future = txaio.as_future(handler, *args, **kwargs)
  File "/home/emmanuel/projects/crossbar/.tox/py27-twtrunk-abtrunk/local/lib/python2.7/site-packages/txaio/tx.py", line 339, in as_future
    return maybeDeferred(fun, *args, **kwargs)
--- <exception caught here> ---
  File "/home/emmanuel/projects/crossbar/.tox/py27-twtrunk-abtrunk/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/home/emmanuel/projects/crossbar/.tox/py27-twtrunk-abtrunk/local/lib/python2.7/site-packages/crossbar/worker/router.py", line 678, in publish_started
    session.publish(topic, event, options=PublishOptions(exclude=details.caller))
exceptions.AttributeError: 'SessionDetails' object has no attribute 'caller'

2016-02-11T15:09:13+0100 [Controller   2676] Router 'worker1': component 'component1' started
2016-02-11T15:09:13+0100 [Router       2694] WampWebSocketServerFactory starting on '/tmp/socket1'
2016-02-11T15:09:13+0100 [Controller   2676] Router 'worker1': transport 'transport1' started

```

So crossbar is complaining there is no `caller` attribute in the `autobahn.wamp.type.SessionDetails` (I get this error also for `CloseDetails`), which is true:
https://github.com/crossbario/autobahn-python/blob/master/autobahn/wamp/types.py#L301
https://github.com/crossbario/autobahn-python/blob/master/autobahn/wamp/types.py#L256

Now things start to get strange: this code still make use of `details.caller` in crossbar 0.12.1 installed via pip (the code has changed a bit due to baedbd599804298625f0ce03d02a58a37f02eef5), but there is no crash with this version !

I tried to do some introspection here https://github.com/crossbario/crossbar/blob/v0.12.1/crossbar/worker/router.py#L675

`print(details)`:
```
SessionDetails(realm=<realm1>, session=6924861671868108, authid=<None>, authrole=<authenticator>, authmethod=None, authprovider=None, authextra=None)
```

`print(dir(details))` doesn't show any `caller` attribute:
```
2016-02-11T15:15:21+0100 [Router       2878] ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'authextra', 'authid', 'authmethod', 'authprovider', 'authrole', 'realm', 'session']
```

More interesting, `print(details.caller)` doesn't print anything and the rest of the function is not executed.

I suppose an `AttributeError` is raised but twisted handled it poorly by silencing the error and forget about this coroutine...

**Comment by meejah** [comment]
There were a couple problems here that are since fixed on master: ``details`` in the listener was shadowing the ``details`` of the main function, the publish was to the wrong session (session.publish() not self.publish()) and error-logging from "listeners" (as used above) was recently improved.

So: fixed in master.
@touilleMan please re-open if you can repeat any of the above in master :)
