### ISSUE TITLE
Logging issue on node shutdown

### ISSUE THREAD

**Issue by sehoffmann** [crossbario/crossbar#653]
This must have been introduced sometime from https://github.com/crossbario/crossbar/commit/347695ce911ab3a730571aaf33fdd8eddab86edb

```
^C2016-02-15T20:50:49+0100 [Controller   3115] Received SIGINT, shutting down.
2016-02-15T20:50:49+0100 [Controller   3115] sending TERM to subprocess 3147
2016-02-15T20:50:49+0100 [Controller   3115] waiting for 3147 to exit...
2016-02-15T20:50:49+0100 [Router       3147] Native worker received SIGTERM - shutting down ..
2016-02-15T20:50:49+0100 [Router       3147] Shutdown of worker requested!
2016-02-15T20:50:49+0100 [Router       3147] stopped component: replay.authorization.Authorizer id=7519802948707010
2016-02-15T20:50:49+0100 [Router       3147] component 'authorizer' disconnected
2016-02-15T20:50:49+0100 [Controller   3115] Unable to format event {'log_namespace': 'crossbar.controller.native.NativeWorkerClientProtocol', 'log_level': <LogLevel=critical>, 'log_logger': <Logger 'crossbar.controller.native.NativeWorkerClientProtocol'>, 'log_time': 1455565849.614003, 'log_source': None, 'log_format': 'Traceback (most recent call last):\n  File "/usr/local/lib/python2.7/dist-packages/autobahn-0.13.0-py2.7.egg/autobahn/wamp/websocket.py", line 90, in onMessage\n    self._session.onMessage(msg)\n  File "/usr/local/lib/python2.7/dist-packages/crossbar-0.13.0-py2.7.egg/crossbar/router/session.py", line 430, in onMessage\n    raise ProtocolError(u"Received {0} message, and session is not yet established".format(msg.__class__))\nProtocolError: Received <class \'autobahn.wamp.message.Publish\'> message, and session is not yet established\n'}: tuple index out of range
2016-02-15T20:50:49+0100 [Controller   3115] Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Twisted-15.5.0-py2.7-linux-x86_64.egg/twisted/python/log.py", line 101, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-15.5.0-py2.7-linux-x86_64.egg/twisted/python/log.py", line 84, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-15.5.0-py2.7-linux-x86_64.egg/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-15.5.0-py2.7-linux-x86_64.egg/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/Twisted-15.5.0-py2.7-linux-x86_64.egg/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
    why = selectable.doRead()
  File "/usr/local/lib/python2.7/dist-packages/Twisted-15.5.0-py2.7-linux-x86_64.egg/twisted/internet/process.py", line 280, in doRead
    return fdesc.readFromFD(self.fd, self.dataReceived)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-15.5.0-py2.7-linux-x86_64.egg/twisted/internet/fdesc.py", line 94, in readFromFD
    callback(output)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-15.5.0-py2.7-linux-x86_64.egg/twisted/internet/process.py", line 283, in dataReceived
    self.proc.childDataReceived(self.name, data)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-15.5.0-py2.7-linux-x86_64.egg/twisted/internet/process.py", line 937, in childDataReceived
    self.proto.childDataReceived(name, data)
  File "/usr/local/lib/python2.7/dist-packages/crossbar-0.13.0-py2.7.egg/crossbar/twisted/processutil.py", line 84, in childDataReceived
    self.protocol.dataReceived(data)
  File "/usr/local/lib/python2.7/dist-packages/autobahn-0.13.0-py2.7.egg/autobahn/twisted/websocket.py", line 132, in dataReceived
    self._dataReceived(data)
  File "/usr/local/lib/python2.7/dist-packages/autobahn-0.13.0-py2.7.egg/autobahn/websocket/protocol.py", line 1174, in _dataReceived
    self.consumeData()
  File "/usr/local/lib/python2.7/dist-packages/autobahn-0.13.0-py2.7.egg/autobahn/websocket/protocol.py", line 1186, in consumeData
    while self.processData() and self.state != WebSocketProtocol.STATE_CLOSED:
  File "/usr/local/lib/python2.7/dist-packages/autobahn-0.13.0-py2.7.egg/autobahn/websocket/protocol.py", line 1552, in processData
    fr = self.onFrameEnd()
  File "/usr/local/lib/python2.7/dist-packages/autobahn-0.13.0-py2.7.egg/autobahn/websocket/protocol.py", line 1669, in onFrameEnd
    self._onMessageEnd()
  File "/usr/local/lib/python2.7/dist-packages/autobahn-0.13.0-py2.7.egg/autobahn/twisted/websocket.py", line 160, in _onMessageEnd
    self.onMessageEnd()
  File "/usr/local/lib/python2.7/dist-packages/autobahn-0.13.0-py2.7.egg/autobahn/websocket/protocol.py", line 659, in onMessageEnd
    self._onMessage(payload, self.message_is_binary)
  File "/usr/local/lib/python2.7/dist-packages/autobahn-0.13.0-py2.7.egg/autobahn/twisted/websocket.py", line 163, in _onMessage
    self.onMessage(payload, isBinary)
  File "/usr/local/lib/python2.7/dist-packages/autobahn-0.13.0-py2.7.egg/autobahn/wamp/websocket.py", line 95, in onMessage
    self._bailout(protocol.WebSocketProtocol.CLOSE_STATUS_CODE_PROTOCOL_ERROR, reason=reason)
  File "/usr/local/lib/python2.7/dist-packages/autobahn-0.13.0-py2.7.egg/autobahn/wamp/websocket.py", line 51, in _bailout
    self.failConnection(code, reason)
exceptions.AttributeError: 'NativeWorkerClientProtocol' object has no attribute 'failConnection'

2016-02-15T20:50:50+0100 [Controller   3115] waiting for 3147 to exit...
2016-02-15T20:50:51+0100 [Controller   3115] waiting for 3147 to exit...
2016-02-15T20:50:52+0100 [Controller   3115] waiting for 3147 to exit...
2016-02-15T20:50:53+0100 [Controller   3115] waiting for 3147 to exit...
2016-02-15T20:50:54+0100 [Controller   3115] waiting for 3147 to exit...
2016-02-15T20:50:55+0100 [Controller   3115] waiting for 3147 to exit...
2016-02-15T20:50:56+0100 [Controller   3115] waiting for 3147 to exit...
2016-02-15T20:50:57+0100 [Controller   3115] waiting for 3147 to exit...
2016-02-15T20:50:58+0100 [Controller   3115] waiting for 3147 to exit...
2016-02-15T20:50:59+0100 [Controller   3115] waiting for 3147 to exit...
2016-02-15T20:51:00+0100 [Controller   3115] waiting for 3147 to exit...
2016-02-15T20:51:01+0100 [Controller   3115] waiting for 3147 to exit...
2016-02-15T20:51:02+0100 [Controller   3115] waiting for 3147 to exit...
2016-02-15T20:51:03+0100 [Controller   3115] waiting for 3147 to exit...
2016-02-15T20:51:04+0100 [Controller   3115] waiting for 3147 to exit...
2016-02-15T20:51:05+0100 [Controller   3115] waiting for 3147 to exit...
2016-02-15T20:51:06+0100 [Controller   3115] waiting for 3147 to exit...
2016-02-15T20:51:07+0100 [Controller   3115] waiting for 3147 to exit...
2016-02-15T20:51:08+0100 [Controller   3115] waiting for 3147 to exit...
2016-02-15T20:51:09+0100 [Controller   3115] waiting for 3147 to exit...
2016-02-15T20:51:10+0100 [Controller   3115] waiting for 3147 to exit...
2016-02-15T20:51:10+0100 [Controller   3115] Sending SIGKILL to 3147
```

**Comment by oberstet** [comment]
This is a AutobahnPython issue introduced in https://github.com/crossbario/autobahn-python/commit/e179ef5a8587f711ce14cc6a8a12fc89f9c7a403

**Comment by oberstet** [comment]
Should be fixed with https://github.com/crossbario/autobahn-python/commit/3cbaceed60837606ee1559b2b84dc2165dbd5b9d

**Comment by Paranaix** [comment]
Can confirm that thisp articular error hasbeen fixed but now I observe:

```
^C2016-02-17T15:32:08+0100 [Controller   4918] Received SIGINT, shutting down.
2016-02-17T15:32:08+0100 [Controller   4918] sending TERM to subprocess 4923
2016-02-17T15:32:08+0100 [Controller   4918] waiting for 4923 to exit...
2016-02-17T15:32:08+0100 [Router       4923] Native worker received SIGTERM - shutting down ..
2016-02-17T15:32:08+0100 [Router       4923] Shutdown of worker requested!
2016-02-17T15:32:08+0100 [Router       4923] stopped component: replay.authorization.Authorizer id=1630832457914936
2016-02-17T15:32:08+0100 [Router       4923] component 'authorizer' disconnected
2016-02-17T15:32:08+0100 [Controller   4918] Unable to format event {'log_namespace': 'crossbar.controller.native.NativeWorkerClientProtocol', 'log_level': <LogLevel=critical>, 'log_logger': <Logger 'crossbar.controller.native.NativeWorkerClientProtocol'>, 'log_time': 1455719528.051334, 'log_source': None, 'log_format': 'Traceback (most recent call last):\n  File "/usr/local/lib/python2.7/dist-packages/autobahn-0.13.0-py2.7.egg/autobahn/wamp/websocket.py", line 90, in onMessage\n    self._session.onMessage(msg)\n  File "/usr/local/lib/python2.7/dist-packages/crossbar-0.13.0-py2.7.egg/crossbar/router/session.py", line 430, in onMessage\n    raise ProtocolError(u"Received {0} message, and session is not yet established".format(msg.__class__))\nProtocolError: Received <class \'autobahn.wamp.message.Publish\'> message, and session is not yet established\n'}: tuple index out of range
2016-02-17T15:32:08+0100 [Router       4923] Connection to node controller closed cleanly
2016-02-17T15:32:08+0100 [Router       4923] (TCP Port 9090 Closed)
2016-02-17T15:32:08+0100 [Router       4923] (TCP Port 8080 Closed)
2016-02-17T15:32:08+0100 [Router       4923] (TCP Port 8888 Closed)
2016-02-17T15:32:08+0100 [Controller   4918] Native worker connection closed cleanly.
2016-02-17T15:32:08+0100 [Controller   4918] Node worker worker1 ended successfully
2016-02-17T15:32:08+0100 [Controller   4918] Node worker ended, and trigger 'shutdown_on_worker_exit' active
2016-02-17T15:32:08+0100 [Controller   4918] Node shutting down ..
2016-02-17T15:32:08+0100 [Controller   4918] Shutting down node...
```

**Comment by oberstet** [comment]
I guess you refer to "Unable to format event  .."? This is non-critical, but should be fixed nevertheless.

**Comment by Paranaix** [comment]
Yes

**Comment by oberstet** [comment]
both the original bug has been fixed - and I haven't seen "log formatting" issues on node shutdown for long too
