### ISSUE TITLE
WSGI app not run from a thread pool ?

### ISSUE THREAD

**Issue by touilleMan** [crossbario/crossbar#654]
Hi,

I'm working on a library for using autobahn from a synchronous application thanks to crochet.

According to the [documentation](http://crossbar.io/docs/WSGI-Host-Service/), the WSGI host service should use a pool of threads to run the wsgi app.

However, running [this code](https://github.com/Scille/autobahn-sync/tree/master/examples/basic), I end up with the following crash:

```
$ AUTHOBAHN_IN_TWISTED=true crossbar start
2016-02-18T20:00:21+0100 [Controller  16358] Automatically choosing optimal Twisted reactor
2016-02-18T20:00:21+0100 [Controller  16358] Running on Linux and optimal reactor (epoll) was installed.
2016-02-18T20:00:21+0100 [Controller  16358]      __  __  __  __  __  __      __     __
2016-02-18T20:00:21+0100 [Controller  16358]     /  `|__)/  \/__`/__`|__) /\ |__)  |/  \
2016-02-18T20:00:21+0100 [Controller  16358]     \__,|  \\__/.__/.__/|__)/~~\|  \. |\__/
2016-02-18T20:00:21+0100 [Controller  16358]                                         
2016-02-18T20:00:21+0100 [Controller  16358]     Crossbar.io Version: 0.12.1
2016-02-18T20:00:21+0100 [Controller  16358]     Node Public Key: 282fe4c6650fd08e744efb18f5d378eac7c11f139d0898ddb31373269850955f
2016-02-18T20:00:21+0100 [Controller  16358] 
2016-02-18T20:00:21+0100 [Controller  16358] Running from node directory '/home/emmanuel/projects/autobahn-sync/examples/basic/.crossbar'
2016-02-18T20:00:21+0100 [Controller  16358] Controller process starting (CPython-EPollReactor) ..
2016-02-18T20:00:21+0100 [Controller  16358] Node configuration loaded from 'config.json'
2016-02-18T20:00:21+0100 [Controller  16358] Node ID 'ubuntu' set from hostname
2016-02-18T20:00:21+0100 [Controller  16358] Using default node shutdown triggers [u'shutdown_on_worker_exit']
2016-02-18T20:00:21+0100 [Controller  16358] Joined realm 'crossbar' on node management router
2016-02-18T20:00:21+0100 [Controller  16358] Starting Router with ID 'worker1'...
2016-02-18T20:00:21+0100 [Router      16363] Worker process starting (CPython-EPollReactor) ..
2016-02-18T20:00:22+0100 [Controller  16358] Router with ID 'worker1' and PID 16363 started
2016-02-18T20:00:22+0100 [Router      16363] Realm 'realm1' started
2016-02-18T20:00:22+0100 [Controller  16358] Router 'worker1': realm 'realm1' (named 'realm1') started
2016-02-18T20:00:22+0100 [Controller  16358] Router 'worker1': role 'role1' (named 'anonymous') started on realm 'realm1'
2016-02-18T20:00:22+0100 [Router      16363] Current thread: <_MainThread(MainThread, started 140072325072704)>
2016-02-18T20:00:22+0100 [Router      16363] NativeWorkerSession.onUserError
Traceback (most recent call last):
  File "/home/emmanuel/.local/share/virtualenvs/tk2/local/lib/python2.7/site-packages/autobahn/twisted/websocket.py", line 165, in _onMessage
    self.onMessage(payload, isBinary)
  File "/home/emmanuel/.local/share/virtualenvs/tk2/local/lib/python2.7/site-packages/autobahn/wamp/websocket.py", line 90, in onMessage
    self._session.onMessage(msg)
  File "/home/emmanuel/.local/share/virtualenvs/tk2/local/lib/python2.7/site-packages/autobahn/wamp/protocol.py", line 755, in onMessage
    on_reply = txaio.as_future(endpoint.fn, *invoke_args, **invoke_kwargs)
  File "/home/emmanuel/.local/share/virtualenvs/tk2/local/lib/python2.7/site-packages/txaio/tx.py", line 339, in as_future
    return maybeDeferred(fun, *args, **kwargs)
--- <exception caught here> ---
  File "/home/emmanuel/.local/share/virtualenvs/tk2/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/home/emmanuel/.local/share/virtualenvs/tk2/local/lib/python2.7/site-packages/crossbar/worker/router.py", line 795, in start_router_transport
    root = self._create_resource(root_config, nested=False)
  File "/home/emmanuel/.local/share/virtualenvs/tk2/local/lib/python2.7/site-packages/crossbar/worker/router.py", line 967, in _create_resource
    mod = importlib.import_module(mod_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/emmanuel/projects/autobahn-sync/examples/basic/app.py", line 14, in <module>
    wamp = FlaskAutobahnSync(app)
  File "/home/emmanuel/.local/share/virtualenvs/tk2/local/lib/python2.7/site-packages/autobahn_sync/extensions/flask.py", line 15, in __init__
    self.init_app(app, **config)
  File "/home/emmanuel/.local/share/virtualenvs/tk2/local/lib/python2.7/site-packages/autobahn_sync/extensions/flask.py", line 30, in init_app
    debug_app=app.debug)
  File "/home/emmanuel/.local/share/virtualenvs/tk2/local/lib/python2.7/site-packages/autobahn_sync/core.py", line 64, in start
    _starter()
  File "/home/emmanuel/.local/share/virtualenvs/tk2/local/lib/python2.7/site-packages/crochet/_eventloop.py", line 461, in wrapper
    return eventual_result.wait(timeout)
  File "/home/emmanuel/.local/share/virtualenvs/tk2/local/lib/python2.7/site-packages/crochet/_eventloop.py", line 212, in wait
    "EventualResult.wait() must not be run in the reactor thread.")
exceptions.RuntimeError: EventualResult.wait() must not be run in the reactor thread.

2016-02-18T20:00:22+0100 [Controller  16358] wamp.error.runtime_error: EventualResult.wait() must not be run in the reactor thread.
2016-02-18T20:00:22+0100 [Controller  16358] sending TERM to subprocess 16363
2016-02-18T20:00:22+0100 [Controller  16358] waiting for 16363 to exit...
2016-02-18T20:00:22+0100 [Router      16363] Native worker received SIGTERM - shutting down ..
2016-02-18T20:00:22+0100 [Router      16363] Shutdown of worker requested!
2016-02-18T20:00:22+0100 [Router      16363] Connection to node controller closed cleanly
2016-02-18T20:00:22+0100 [Controller  16358] Native worker connection closed cleanly.
2016-02-18T20:00:22+0100 [Controller  16358] Node worker worker1 ended successfully
2016-02-18T20:00:22+0100 [Controller  16358] Node worker ended, and trigger 'shutdown_on_worker_exit' active
2016-02-18T20:00:22+0100 [Controller  16358] Node shutting down ..
2016-02-18T20:00:22+0100 [Controller  16358] Shutting down node...
```

The behavior is the same on crossbar 0.12.1 and on the master branch

After some investigation, it seems the app code is run from the main thread (the one twisted reactor runs in), which make crochet send an exception when synchronous wait is asked (given it will block the  entire reactor).

**Comment by oberstet** [comment]
> the WSGI host service should use a pool of threads to run the wsgi app

No. The docs say it **does** use a worker thread pool - so you should start your own.

**Comment by touilleMan** [comment]
You're right, my problem wasn't from the thread pool but because my app was trying to use crochet when it was imported by the main thread (FYI the fix of my code https://github.com/Scille/autobahn-sync/commit/2d83e47351141b6ab8cac33c1b73b880e3bc0f03)
