### ISSUE TITLE
Exception thrown in custom authorizer => Authorization passes and uncaught exception in crossbar

### ISSUE THREAD

**Issue by Paranaix** [crossbario/crossbar#672]
E,g:

```
@register(u"com.example.authorize")
def myFunc(session, uri, action):
    raise Exception("abc")
```

=>
```

2016-03-09T12:51:41+0100 [Router       3719] Unhandled error in Deferred:
2016-03-09T12:51:41+0100 [Router       3719] 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/crossbar-0.13.0-py2.7.egg/crossbar/router/router.py", line 175, in process
    self._broker.processSubscribe(session, msg)
  File "/usr/local/lib/python2.7/dist-packages/crossbar-0.13.0-py2.7.egg/crossbar/router/broker.py", line 436, in processSubscribe
    txaio.add_callbacks(d, on_authorize_success, on_authorize_error)
  File "/usr/local/lib/python2.7/dist-packages/txaio-2.2.1-py2.7.egg/txaio/tx.py", line 393, in add_callbacks
    future.addCallbacks(callback, errback)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 306, in addCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/crossbar-0.13.0-py2.7.egg/crossbar/router/broker.py", line 427, in on_authorize_error
    self.log.failure(err)
  File "/usr/local/lib/python2.7/dist-packages/crossbar-0.13.0-py2.7.egg/crossbar/_logging.py", line 402, in failure
    return self.logger.failure(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/twisted/logger/_logger.py", line 176, in failure
    failure = Failure()
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 214, in __init__
    raise NoCurrentExceptionError()
twisted.python.failure.NoCurrentExceptionError: 
```

Exception is logged previously

**Comment by meejah** [comment]
I think PR #666 should have fixed this, from looking at the code; is this a released version or master for the above stacktrace?

**Comment by Paranaix** [comment]
Oh yes sorry, I'm still on https://github.com/crossbario/crossbar/commit/59d6f1afafe43715d4282ce1907db170fe420b97

I guess this can be closed then
