### ISSUE TITLE
Updated crossbar, now im getting "Could not start node"

### ISSUE THREAD

**Issue by Tsunami2069** [crossbario/crossbar#676]
Hello.

Been using crossbar for quite a while on a rather big project of ours with very little issues up till now (gratz n' good job, by the way).

However, when i got to work today, i ran my "pip install --upgrade crossbar" command. I noticed that the twisted updated itself to the 16.0.0 version. Not sure if any other requirement were updated or not.
After that, i ran my crossbar start and it started just fine.

Went on to my normal coding on the application we're developing which, by the way, DIDN'T involve any work on the crossbar files, only on the web application itself. This means that no file in the crossbar / wamp router was changed today or the past few days (i've even double checked with out repository).

However, later on today, i had to restart the wamp router. Upon running the "crossbar start" command, the router failed (and has failed ever since) to start, with us only getting a "Could not start node" error, as you can see on the following screenshot.

![crossbarerror](https://cloud.githubusercontent.com/assets/14236716/13786266/bd355e22-eace-11e5-85c4-4ad93b09e86c.JPG)

Can't seem to find any other errors, maybe apart from that "could not set process title" warning.

Quite coincidently, another colleague of mine also had to install a crossbar on another machine (not his own). His crossbar also won't start with the same symptoms.
I asked the same colleague to update his crossbar on his own working laptop... same thing... crossbar won't start.

Again, i would like to reiterate that no changes were made to the crossbar and the project files, all changes we've been working do not involve changes to the router.
The only real change was the upgrade of the crossbar itself (running the command "pip install --upgrade crossbar") which upgraded the Twisted to 16.0.0 and, possibly other requirements (can't remember exactly which).

I have tried to uninstall Twisted and force a re-install of the twisted 15.5.0 (using "pip install twisted==15.5.0) but the result is still the same, the node won't start.

Please, can you help us with this issue?
If so, do you need any more informations??
Without the ability to start the crossbar, we're dead in the water.

Thank you in advance.

**Comment by Tsunami2069** [comment]
OK, update on this issue...

I think we have discovered the culprit and it was autobahn.

After fiddling around with the crossbar requirements, we started to test some older versions of some requirements in hope to find another requirement that had been updated and, somehow, broken.
And, apparently, like i stated b4, the culprit was autobahn.

If we did a "pip uninstall autobahn" and then a "pip install autobahn==0.12.1 --no-cache-dir", our crossbar now runs perfectly.

Am i safe to assume this is, possibly, a Windows only issue?

Anyways, i'll be watching this issue post for ur information on this matter.

**Comment by meejah** [comment]
Thanks for the report! I won't have time to look at this in detail until tomorrow likely, but there's at least two problems here one being the lack of logging about what error/why the node can't start.

I did have a slight issue with Twisted 16 on another project.

However, yes the likely issues here is that there should be a crossbar release as well to "go along" with the new autobahn -- so downgrading your autobahn is the right thing in this case.

However! There's also a logging issue, which should be fixed in crossbar.

**Comment by Tsunami2069** [comment]
Alright, @meejah ... appreciated the feedback.
Like i said, i'll be keeping an eye on this post for updates.

Cya around and thanks once more.

**Comment by oberstet** [comment]
@Tsunami2069 I pushed a new Crossbar.io release 0.13.0. Could you please try that? (`pip install -U crossbar`  should be fine).

> Reason: I did releases of Autobahn (and txaio), and then got interrupted before pushing CB =(

**Comment by Tsunami2069** [comment]
@oberstet Thank you. I will try it tomorrow when im at the office.
As soon as i have an update, i will post it here.

Cheers.

**Comment by Tsunami2069** [comment]
@oberstet Ok, so i've tried updating the crossbar and its requirements but its failing on the pyinotify requirement:

![pyinotify](https://cloud.githubusercontent.com/assets/14236716/13810567/7e1cac6e-eb68-11e5-903d-d89a043eac7c.JPG)

Am i wrong or is this a new requirement?

Also, if i visit the pyinotify pypi page, it says its a linux only package ( https://pypi.python.org/pypi/pyinotify/0.9.6 ).
This is also corroborated by the fact that its giving a "...is not available on win32" message.

Until this is fixed, i can use and work on the previous versions.

Cheers.

**Comment by oberstet** [comment]
The reason for that latter problem is: for the new release, I not only uploaded a source dist, but also a wheel. Which was wrong, since we have dynamic dependency switches (like for pyinotify) which don't work with wheels - as a wheel will build for the platform it was build on (Linux).

I have removed the wheel, and verified on a Windows Server 2008:

```
C:\Users\toob>pip install --proxy=http://10.200.1.21:8080 --no-cache-dir --upgra
de crossbar
Requirement already up-to-date: crossbar in c:\python27\lib\site-packages
Requirement already up-to-date: click>=5.1 in c:\python27\lib\site-packages (fro
m crossbar)
Requirement already up-to-date: setuptools>=18.3.1 in c:\python27\lib\site-packa
ges (from crossbar)
Requirement already up-to-date: zope.interface>=4.1.2 in c:\python27\lib\site-pa
ckages (from crossbar)
Requirement already up-to-date: twisted>=16.0.0 in c:\python27\lib\site-packages
 (from crossbar)
Collecting autobahn[twisted]>=0.13.0 (from crossbar)
  Downloading autobahn-0.13.0.tar.gz (169kB)
    100% |################################| 172kB 2.6MB/s
Requirement already up-to-date: netaddr>=0.7.18 in c:\python27\lib\site-packages
 (from crossbar)
Requirement already up-to-date: pytrie>=0.2 in c:\python27\lib\site-packages (fr
om crossbar)
Requirement already up-to-date: jinja2>=2.8 in c:\python27\lib\site-packages (fr
om crossbar)
Requirement already up-to-date: mistune>=0.7.1 in c:\python27\lib\site-packages
(from crossbar)
Requirement already up-to-date: pygments>=2.0.2 in c:\python27\lib\site-packages
 (from crossbar)
Requirement already up-to-date: pyyaml>=3.11 in c:\python27\lib\site-packages (f
rom crossbar)
Requirement already up-to-date: shutilwhich>=1.1.0 in c:\python27\lib\site-packa
ges (from crossbar)
Requirement already up-to-date: sdnotify>=0.3.0 in c:\python27\lib\site-packages
 (from crossbar)
Requirement already up-to-date: psutil>=3.2.1 in c:\python27\lib\site-packages (
from crossbar)
Requirement already up-to-date: lmdb>=0.88 in c:\python27\lib\site-packages (fro
m crossbar)
Requirement already up-to-date: msgpack-python>=0.4.6 in c:\python27\lib\site-pa
ckages (from crossbar)
Requirement already up-to-date: cbor>=0.1.24 in c:\python27\lib\site-packages (f
rom crossbar)
Requirement already up-to-date: cryptography>=0.9.3 in c:\python27\lib\site-pack
ages (from crossbar)
Requirement already up-to-date: pyOpenSSL>=0.15.1 in c:\python27\lib\site-packag
es (from crossbar)
Requirement already up-to-date: pyasn1>=0.1.8 in c:\python27\lib\site-packages (
from crossbar)
Requirement already up-to-date: pyasn1-modules>=0.0.7 in c:\python27\lib\site-pa
ckages (from crossbar)
Requirement already up-to-date: service-identity>=14.0.0 in c:\python27\lib\site
-packages (from crossbar)
Requirement already up-to-date: pynacl>=1.0.1 in c:\python27\lib\site-packages (
from crossbar)
Requirement already up-to-date: treq>=15.1.0 in c:\python27\lib\site-packages (f
rom crossbar)
Requirement already up-to-date: pypiwin32>=219 in c:\python27\lib\site-packages
(from crossbar)
Requirement already up-to-date: six>=1.10.0 in c:\python27\lib\site-packages (fr
om autobahn[twisted]>=0.13.0->crossbar)
Collecting txaio>=2.2.2 (from autobahn[twisted]>=0.13.0->crossbar)
  Downloading txaio-2.2.2.tar.gz
Requirement already up-to-date: MarkupSafe in c:\python27\lib\site-packages (fro
m jinja2>=2.8->crossbar)
Requirement already up-to-date: enum34 in c:\python27\lib\site-packages (from cr
yptography>=0.9.3->crossbar)
Requirement already up-to-date: ipaddress in c:\python27\lib\site-packages (from
 cryptography>=0.9.3->crossbar)
Requirement already up-to-date: idna>=2.0 in c:\python27\lib\site-packages (from
 cryptography>=0.9.3->crossbar)
Requirement already up-to-date: cffi>=1.4.1 in c:\python27\lib\site-packages (fr
om cryptography>=0.9.3->crossbar)
Requirement already up-to-date: attrs in c:\python27\lib\site-packages (from ser
vice-identity>=14.0.0->crossbar)
Requirement already up-to-date: requests>=2.1.0 in c:\python27\lib\site-packages
 (from treq>=15.1.0->crossbar)
Requirement already up-to-date: pycparser in c:\python27\lib\site-packages (from
 cffi>=1.4.1->cryptography>=0.9.3->crossbar)
Installing collected packages: txaio, autobahn
  Found existing installation: txaio 2.2.1
    Uninstalling txaio-2.2.1:
      Successfully uninstalled txaio-2.2.1
  Running setup.py install for txaio ... done
  Found existing installation: autobahn 0.11.0
    Uninstalling autobahn-0.11.0:
      Successfully uninstalled autobahn-0.11.0
  Running setup.py install for autobahn ... done
Successfully installed autobahn-0.13.0 txaio-2.2.2
You are using pip version 8.0.2, however version 8.1.0 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' comm
and.

C:\Users\toob>crossbar version
Automatically choosing optimal Twisted reactor
Running on Windows and optimal reactor (ICOP) was installed.
     __  __  __  __  __  __      __     __
    /  `|__)/  \/__`/__`|__) /\ |__)  |/  \
    \__,|  \\__/.__/.__/|__)/~~\|  \. |\__/

 Crossbar.io        : 0.13.0
   Autobahn         : 0.13.0 (with JSON, MessagePack, CBOR)
   Twisted          : 16.0.0-IOCPReactor
   LMDB             : 0.89/lmdb-0.9.18
   Python           : 2.7.11/CPython
 OS                 : Windows-2012ServerR2-6.3.9600
 Machine            : AMD64


C:\Users\toob>
```

**Comment by oberstet** [comment]
Here is Crossbar.io running on Windows 2008:

```
C:\Users\toob>mkdir node2

C:\Users\toob>cd node2

C:\Users\toob\node2>crossbar init
Automatically choosing optimal Twisted reactor
Running on Windows and optimal reactor (ICOP) was installed.
Initializing application template 'default' in directory 'C:\Users\toob\node2'
Using template from 'c:/python27/lib/site-packages/crossbar/templates/default'
Creating directory C:\Users\toob\node2\.crossbar
Creating file C:\Users\toob\node2\.crossbar\config.json
Application template initialized

To start your node, run 'crossbar start --cbdir C:\Users\toob\node2\.crossbar'


C:\Users\toob\node2>crossbar start
2016-03-16T14:36:43+0100 [Controller  92732] Automatically choosing optimal Twis
ted reactor
2016-03-16T14:36:44+0100 [Controller  92732] Running on Windows and optimal reac
tor (ICOP) was installed.
2016-03-16T14:36:44+0100 [Controller  92732] New node key generated!
2016-03-16T14:36:44+0100 [Controller  92732]      __  __  __  __  __  __      __
     __
2016-03-16T14:36:44+0100 [Controller  92732]     /  `|__)/  \/__`/__`|__) /\ |__
)  |/  \
2016-03-16T14:36:44+0100 [Controller  92732]     \__,|  \\__/.__/.__/|__)/~~\|
\. |\__/
2016-03-16T14:36:44+0100 [Controller  92732]

2016-03-16T14:36:44+0100 [Controller  92732]     Crossbar.io Version: 0.13.0
2016-03-16T14:36:44+0100 [Controller  92732]     Node Public Key: 3b80054b49294c
9626c02d94b50eb6401e68e0742d020741bdc9f285bda22b17
2016-03-16T14:36:44+0100 [Controller  92732]
2016-03-16T14:36:44+0100 [Controller  92732] Running from node directory 'C:\Use
rs\toob\node2\.crossbar'
2016-03-16T14:36:44+0100 [Controller  92732] Controller process starting (CPytho
n-IOCPReactor) ..
2016-03-16T14:36:44+0100 [Controller  92732] Node configuration loaded from 'con
fig.json'
2016-03-16T14:36:44+0100 [Controller  92732] Warning, could not set process titl
e (setproctitle not installed)
2016-03-16T14:36:44+0100 [Controller  92732] Node ID 'BVR-SQL17' set from hostna
me
2016-03-16T14:36:44+0100 [Controller  92732] Using default node shutdown trigger
s [u'shutdown_on_worker_exit']
2016-03-16T14:36:44+0100 [Controller  92732] Joined realm 'crossbar' on node man
agement router
2016-03-16T14:36:44+0100 [Controller  92732] Starting Router with ID 'worker1'..
.
2016-03-16T14:36:45+0100 [Router      65524] Worker process starting (CPython-IO
CPReactor) ..
2016-03-16T14:36:46+0100 [Controller  92732] Router with ID 'worker1' and PID 65
524 started
2016-03-16T14:36:46+0100 [Controller  92732] Router 'worker1': realm 'realm1' (n
amed 'realm1') started
2016-03-16T14:36:46+0100 [Router      65524] Realm 'realm1' started
2016-03-16T14:36:46+0100 [Controller  92732] Router 'worker1': role 'role1' (nam
ed 'anonymous') started on realm 'realm1'
2016-03-16T14:36:46+0100 [Controller  92732] Router 'worker1': transport 'transp
ort1' started
2016-03-16T14:36:46+0100 [Router      65524] Site starting on 8080
```

So it does work ..

**Comment by oberstet** [comment]
ah, one more note: you like will need to `crossbar upgrade` you config .. as the realm/permissions config has slightly changed ..

``` 
C:\Users\toob\node1>crossbar start
2016-03-16T14:39:24+0100 [Controller  96540] Automatically choosing optimal Twis
ted reactor
2016-03-16T14:39:25+0100 [Controller  96540] Running on Windows and optimal reac
tor (ICOP) was installed.
2016-03-16T14:39:25+0100 [Controller  96540] Stale Crossbar.io PID file (pointin
g to non-existing process with PID 11808) C:\Users\toob\node1\.crossbar\node.pid
 removed
2016-03-16T14:39:25+0100 [Controller  96540]      __  __  __  __  __  __      __
     __
2016-03-16T14:39:25+0100 [Controller  96540]     /  `|__)/  \/__`/__`|__) /\ |__
)  |/  \
2016-03-16T14:39:25+0100 [Controller  96540]     \__,|  \\__/.__/.__/|__)/~~\|
\. |\__/
2016-03-16T14:39:25+0100 [Controller  96540]

2016-03-16T14:39:25+0100 [Controller  96540]     Crossbar.io Version: 0.13.0
2016-03-16T14:39:25+0100 [Controller  96540]     Node Public Key: d5b54651f490b5
e7e7180a9d1a043f10efc56a47baeb283d3bb13d14208d884b
2016-03-16T14:39:25+0100 [Controller  96540]
2016-03-16T14:39:25+0100 [Controller  96540] Running from node directory 'C:\Use
rs\toob\node1\.crossbar'
2016-03-16T14:39:25+0100 [Controller  96540] Controller process starting (CPytho
n-IOCPReactor) ..
2016-03-16T14:39:25+0100 [Controller  96540] Invalid node configuration
2016-03-16T14:39:25+0100 [Controller  96540] Configuration too old: version 1, w
hile current is 2 - please upgrade using 'crossbar upgrade'

C:\Users\toob\node1>crossbar upgrade
Automatically choosing optimal Twisted reactor
Running on Windows and optimal reactor (ICOP) was installed.
Upgrading local configuration file C:\Users\toob\node1\.crossbar\config.json
Upgrading configuration from version 1 to version 2

C:\Users\toob\node1>crossbar start
2016-03-16T14:39:34+0100 [Controller  35448] Automatically choosing optimal Twis
ted reactor
2016-03-16T14:39:35+0100 [Controller  35448] Running on Windows and optimal reac
tor (ICOP) was installed.
2016-03-16T14:39:35+0100 [Controller  35448] Stale Crossbar.io PID file (pointin
g to non-existing process with PID 96540) C:\Users\toob\node1\.crossbar\node.pid
 removed
2016-03-16T14:39:35+0100 [Controller  35448]      __  __  __  __  __  __      __
     __
2016-03-16T14:39:35+0100 [Controller  35448]     /  `|__)/  \/__`/__`|__) /\ |__
)  |/  \
2016-03-16T14:39:35+0100 [Controller  35448]     \__,|  \\__/.__/.__/|__)/~~\|
\. |\__/
2016-03-16T14:39:35+0100 [Controller  35448]

2016-03-16T14:39:35+0100 [Controller  35448]     Crossbar.io Version: 0.13.0
2016-03-16T14:39:35+0100 [Controller  35448]     Node Public Key: d5b54651f490b5
e7e7180a9d1a043f10efc56a47baeb283d3bb13d14208d884b
2016-03-16T14:39:35+0100 [Controller  35448]
2016-03-16T14:39:35+0100 [Controller  35448] Running from node directory 'C:\Use
rs\toob\node1\.crossbar'
2016-03-16T14:39:35+0100 [Controller  35448] Controller process starting (CPytho
n-IOCPReactor) ..
2016-03-16T14:39:35+0100 [Controller  35448] Node configuration loaded from 'con
fig.json'
2016-03-16T14:39:35+0100 [Controller  35448] Warning, could not set process titl
e (setproctitle not installed)
2016-03-16T14:39:35+0100 [Controller  35448] Node ID 'BVR-SQL17' set from hostna
me
2016-03-16T14:39:35+0100 [Controller  35448] Using default node shutdown trigger
s [u'shutdown_on_worker_exit']
2016-03-16T14:39:35+0100 [Controller  35448] Joined realm 'crossbar' on node man
agement router
2016-03-16T14:39:35+0100 [Controller  35448] Starting Router with ID 'worker1'..
.
2016-03-16T14:39:36+0100 [Router      74628] Worker process starting (CPython-IO
CPReactor) ..
2016-03-16T14:39:37+0100 [Controller  35448] Router with ID 'worker1' and PID 74
628 started
2016-03-16T14:39:37+0100 [Controller  35448] Router 'worker1': realm 'realm1' (n
amed 'realm1') started
2016-03-16T14:39:37+0100 [Router      74628] Realm 'realm1' started
2016-03-16T14:39:37+0100 [Controller  35448] Router 'worker1': role 'role1' (nam
ed 'anonymous') started on realm 'realm1'
2016-03-16T14:39:37+0100 [Controller  35448] Router 'worker1': transport 'transp
ort1' started
2016-03-16T14:39:37+0100 [Router      74628] Site starting on 8080
```

**Comment by Tsunami2069** [comment]
Just tested it, updated and running perfectly.
Thanks :)

Keep up the great work guys.

**Comment by oberstet** [comment]
@Tsunami2069 glad it works again for you;) thanks for reporting back

**Comment by singlecheeze** [comment]
```
2016-04-27T15:41:07-0400 [Controller   1503]      __  __  __  __  __  __      __     __
2016-04-27T15:41:07-0400 [Controller   1503]     /  `|__)/  \/__`/__`|__) /\ |__)  |/  \
2016-04-27T15:41:07-0400 [Controller   1503]     \__,|  \\__/.__/.__/|__)/~~\|  \. |\__/
2016-04-27T15:41:07-0400 [Controller   1503]
2016-04-27T15:41:07-0400 [Controller   1503]     Crossbar.io Version: 0.13.2
2016-04-27T15:41:07-0400 [Controller   1503]     Node Public Key: 4063e68aa1bbe803f032018da3d928469aaac16dfaa7bbb99faadbe1c58f6219
2016-04-27T15:41:07-0400 [Controller   1503]
2016-04-27T15:41:07-0400 [Controller   1503] Running from node directory '/home/dave/monocle/.crossbar'
2016-04-27T15:41:07-0400 [Controller   1503] Controller process starting (CPython-EPollReactor) ..
2016-04-27T15:41:07-0400 [Controller   1503] Invalid node configuration
2016-04-27T15:41:07-0400 [Controller   1503] Configuration too old: version 1, while current is 2 - please upgrade using 'crossbar u
pgrade'
dave@monocle:~/monocle/log$ crossbar upgrade
Traceback (most recent call last):
  File "/usr/local/bin/crossbar", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python2.7/dist-packages/crossbar/controller/cli.py", line 964, in run
    if options.cdc:
AttributeError: 'Namespace' object has no attribute 'cdc'
```

**Comment by oberstet** [comment]
@singlecheeze Are you running from a YAML or JSON config? Could you please post your config (**make sure to remove sensitive info like secrets of course**)

**Comment by singlecheeze** [comment]
JSON:
``` json
{
   "controller": {
   },
   "workers": [
      {
         "id": "wamprouter",
         "type": "router",
         "options": {
            "title": "WAMP Router"
         },
         "realms": [
            {
               "name": "realm1",
               "roles": [
                  {
                     "name": "anonymous",
                     "permissions": [
                        {
                           "uri": "*",
                           "publish": true,
                           "subscribe": true,
                           "call": true,
                           "register": true
                        }
                     ]
                  },
                  {
                     "name": "backend",
                     "permissions": [
                        {
                          "uri": "mono.backend.*",
                          "call": true,
                          "register": true,
                          "subscribe": true,
                          "publish": true
                        }
                     ]
                  },
                  {
                     "name": "frontend",
                     "permissions": [
                        {
                          "uri": "mono.frontend.*",
                          "call": true,
                          "register": false,
                          "subscribe": true,
                          "publish": false
                        }
                     ]
                  }
               ]
            }
         ],
         "transports": [
            {
               "id": "web",
               "type": "web",
               "endpoint": {
                  "type": "tcp",
                  "port": 80
               },
               "paths": {
                  "/": {
                     "type": "static",
                     "directory": "../frontend"
                  },
                  "ws": {
                     "type": "websocket",
                     "url": "ws://localhost/ws",

                     "debug": false,
                     "options": {
                        "compression": {
                           "deflate": {
                              "request_no_context_takeover": false,
                              "request_max_window_bits": 11,
                              "no_context_takeover": false,
                              "max_window_bits": 11,
                              "memory_level": 4
                           }
                        },
                        "auto_ping_interval": 30000,
                        "auto_ping_timeout": 30000,
                        "auto_ping_size": 4
                     }
                  },
                  "upload": {
                     "type": "upload",
                     "realm": "realm1",
                     "role": "anonymous",
                     "directory": "../frontend/staging",
                     "temp_directory": "../frontend/temp",
                     "form_fields": {
                        "file_name": "resumableFilename",
                        "mime_type": "resumableType",
                        "total_size": "resumableTotalSize",
                        "chunk_number": "resumableChunkNumber",
                        "chunk_size": "resumableChunkSize",
                        "total_chunks": "resumableTotalChunks",
                        "content": "file",
                        "on_progress": "on_progress",
                        "session": "session"
                     },
                     "options": {
                        "max_file_size": 20000000000,
                        "file_permissions": "0644",
                        "file_types": [
                           ".csv", ".CSV",
                           ".txt", ".TXT",
                           ".pdf", ".PDF",
                           ".img", ".IMG",
                           ".png", ".PNG",
                           ".jpg", ".JPG",
                           ".zip", ".ZIP",
                           ".tar", ".TAR",
                           ".tgz", ".TGZ",
                           ".bz2", ".BZ2",
                           ".xz", ".XZ",
                           ".gz", ".GZ",
                           ".log", ".LOG"
                        ]
                     }
                  }
               }
            }
         ]
      }
   ]
}
```

**Comment by singlecheeze** [comment]
Are there any docs on what Version 2 of the config is supposed to look like? I'll do a manual config change for now as a workaround...

**Comment by meejah** [comment]
@singlecheeze I think only the permissions lists for realm roles changed (and a "version": 2 at the top level). See e.g. https://github.com/crossbario/autobahn-python/commit/1de985ded0e7cc1bc69c432bdc0108d7ac2c7158#diff-c10480f8dd13b407d5c872e21ee60fbf

**Comment by singlecheeze** [comment]
THANK YOU @meejah

**Comment by singlecheeze** [comment]
Adjusting the config to the below brought the router online:
``` text
2016-04-28T11:55:54-0400 [Controller   1959]      __  __  __  __  __  __      __     __
2016-04-28T11:55:54-0400 [Controller   1959]     /  `|__)/  \/__`/__`|__) /\ |__)  |/  \
2016-04-28T11:55:54-0400 [Controller   1959]     \__,|  \\__/.__/.__/|__)/~~\|  \. |\__/
2016-04-28T11:55:54-0400 [Controller   1959]
2016-04-28T11:55:54-0400 [Controller   1959]     Crossbar.io Version: 0.13.2
2016-04-28T11:55:54-0400 [Controller   1959]     Node Public Key: 4063e68aa1bbe803f032018da3d928469aaac16dfaa7bbb99faadbe1c58f6219
2016-04-28T11:55:54-0400 [Controller   1959]
2016-04-28T11:55:54-0400 [Controller   1959] Running from node directory '/home/dave/monocle/.crossbar'
2016-04-28T11:55:54-0400 [Controller   1959] Controller process starting (CPython-EPollReactor) ..
2016-04-28T11:55:54-0400 [Controller   1959] Node configuration loaded from 'config.json'
2016-04-28T11:55:54-0400 [Controller   1959] Node ID 'monocle' set from hostname
2016-04-28T11:55:54-0400 [Controller   1959] Using default node shutdown triggers [u'shutdown_on_worker_exit']
2016-04-28T11:55:54-0400 [Controller   1959] Joined realm 'crossbar' on node management router
2016-04-28T11:55:54-0400 [Controller   1959] Starting Router with ID 'wamprouter'...
2016-04-28T11:55:55-0400 [Router       1964] Worker process starting (CPython-EPollReactor) ..
2016-04-28T11:55:55-0400 [Controller   1959] Router with ID 'wamprouter' and PID 1964 started
2016-04-28T11:55:55-0400 [Router       1964] Realm 'realm1' started
2016-04-28T11:55:55-0400 [Controller   1959] Router 'wamprouter': realm 'realm-001' (named 'realm1') started
2016-04-28T11:55:55-0400 [Controller   1959] Router 'wamprouter': role 'role-001' (named 'anonymous') started on realm 'realm-001'
2016-04-28T11:55:55-0400 [Controller   1959] Router 'wamprouter': role 'role-002' (named 'backend') started on realm 'realm-001'
2016-04-28T11:55:55-0400 [Controller   1959] Router 'wamprouter': role 'role-003' (named 'frontend') started on realm 'realm-001'
2016-04-28T11:55:55-0400 [Router       1964] File upload resource started. Uploads to /home/dave/monocle/frontend/staging using temp folder /home/dave/monocle/frontend/temp.
2016-04-28T11:55:55-0400 [Router       1964] Upload Resource started.
2016-04-28T11:55:55-0400 [Router       1964] Site starting on 80
2016-04-28T11:55:55-0400 [Controller   1959] Router 'wamprouter': transport 'web' started
```

Adjusted config:
``` json
{
   "version": 2,
   "workers": [
      {
         "id": "wamprouter",
         "type": "router",
         "options": {
            "title": "WAMP Router"
         },
         "realms": [
            {
               "name": "realm1",
               "roles": [
                  {
                     "name": "anonymous",
                     "permissions": [
                        {
                           "uri": "",
                           "match": "prefix",
                           "allow": {
                              "call": true,
                              "register": true,
                              "publish": true,
                              "subscribe": true
                           },
                           "disclose": {
                              "caller": false,
                              "publisher": false
                           },
                           "cache": true
                        }
                     ]
                  },
                  {
                     "name": "backend",
                     "permissions": [
                        {
                           "uri": "mono.backend.*",
                           "match": "prefix",
                           "allow": {
                              "call": true,
                              "register": true,
                              "publish": true,
                              "subscribe": true
                           },
                           "disclose": {
                              "caller": false,
                              "publisher": false
                           },
                           "cache": true
                        }
                     ]
                  },
                  {
                     "name": "frontend",
                     "permissions": [
                        {
                           "uri": "mono.frontend.*",
                           "match": "prefix",
                           "allow": {
                              "call": true,
                              "register": false,
                              "publish": false,
                              "subscribe": true
                           },
                           "disclose": {
                              "caller": false,
                              "publisher": false
                           },
                           "cache": true
                        }
                     ]
                  }
               ]
            }
         ],
         "transports": [
            {
               "id": "web",
               "type": "web",
               "endpoint": {
                  "type": "tcp",
                  "port": 80
               },
               "paths": {
                  "/": {
                     "type": "static",
                     "directory": "../frontend"
                  },
                  "ws": {
                     "type": "websocket",
                     "url": "ws://localhost/ws",
                     "debug": false,
                     "options": {
                        "compression": {
                           "deflate": {
                              "request_no_context_takeover": false,
                              "request_max_window_bits": 11,
                              "no_context_takeover": false,
                              "max_window_bits": 11,
                              "memory_level": 4
                           }
                        },
                        "auto_ping_interval": 30000,
                        "auto_ping_timeout": 30000,
                        "auto_ping_size": 4
                     }
                  },
                  "upload": {
                     "type": "upload",
                     "realm": "realm1",
                     "role": "anonymous",
                     "directory": "../frontend/staging",
                     "temp_directory": "../frontend/temp",
                     "form_fields": {
                        "file_name": "resumableFilename",
                        "mime_type": "resumableType",
                        "total_size": "resumableTotalSize",
                        "chunk_number": "resumableChunkNumber",
                        "chunk_size": "resumableChunkSize",
                        "total_chunks": "resumableTotalChunks",
                        "content": "file",
                        "on_progress": "on_progress",
                        "session": "session"
                     },
                     "options": {
                        "max_file_size": 20000000000,
                        "file_permissions": "0644",
                        "file_types": [
                           ".csv", ".CSV",
                           ".txt", ".TXT",
                           ".pdf", ".PDF",
                           ".img", ".IMG",
                           ".png", ".PNG",
                           ".jpg", ".JPG",
                           ".zip", ".ZIP",
                           ".tar", ".TAR",
                           ".tgz", ".TGZ",
                           ".bz2", ".BZ2",
                           ".xz", ".XZ",
                           ".gz", ".GZ",
                           ".log", ".LOG"
                        ]
                     }
                  }
               }
            }
         ]
      }
   ]
}
```

**Comment by goeddea** [comment]
@singlecheeze - Docs should be up to date regarding the change in the permissions format. If you find they aren't someplace, then I would be grateful if you could file an issue (or just add to this thread)
