### ISSUE TITLE
Crossbar Start Failed with error Cannot listen on transport endpoint: Couldn't listen on any:8080: [Errno 98] Address already in use.

### ISSUE THREAD

**Issue by SumeshDubey** [crossbario/crossbar#787]
I'm facing an issue while doing crossbar start. While doing it the error is returning as below:

```
2016-05-11T09:30:19+0000 [Controller   8984] Automatically choosing optimal Twisted reactor
2016-05-11T09:30:19+0000 [Controller   8984] Running on Linux and optimal reactor (epoll) was installed.
2016-05-11T09:30:19+0000 [Controller   8984]      __  __  __  __  __  __      __     __
2016-05-11T09:30:19+0000 [Controller   8984]     /  `|__)/  \/__`/__`|__) /\ |__)  |/  \
2016-05-11T09:30:19+0000 [Controller   8984]     \__,|  \\__/.__/.__/|__)/~~\|  \. |\__/
2016-05-11T09:30:19+0000 [Controller   8984]                                         
2016-05-11T09:30:19+0000 [Controller   8984]     Version: 0.11.1     
2016-05-11T09:30:19+0000 [Controller   8984] 
2016-05-11T09:30:19+0000 [Controller   8984] Starting from node directory /home/ubuntu/hello_browser/.crossbar
2016-05-11T09:30:20+0000 [Controller   8984] Loading node configuration file '/home/ubuntu/hello_browser/.crossbar/config.json'
2016-05-11T09:30:20+0000 [Controller   8984] Entering reactor event loop...
2016-05-11T09:30:20+0000 [Controller   8984] Joined realm 'crossbar' on node management router
2016-05-11T09:30:20+0000 [Controller   8984] No WAMPlets detected in enviroment.
2016-05-11T09:30:20+0000 [Controller   8984] Starting Router with ID 'worker1'...
2016-05-11T09:30:20+0000 [Router       8990] Worker running under PyPy-EPollReactor
2016-05-11T09:30:21+0000 [Controller   8984] Router with ID 'worker1' and PID 8990 started
2016-05-11T09:30:21+0000 [Controller   8984] Router 'worker1': realm 'realm1' (named 'realm1') started
2016-05-11T09:30:21+0000 [Controller   8984] Router 'worker1': role 'role1' (named 'anonymous') started on realm 'realm1'
2016-05-11T09:30:21+0000 [Router       8990] Cannot listen on transport endpoint: Couldn't listen on any:8080: [Errno 98] Address already in use.
2016-05-11T09:30:21+0000 [Controller   8984] Cannot listen on transport endpoint: Couldn't listen on any:8080: [Errno 98] Address already in use.
2016-05-11T09:30:21+0000 [Controller   8984] sending TERM to subprocess 8990
2016-05-11T09:30:21+0000 [Controller   8984] waiting for 8990 to exit...
2016-05-11T09:30:21+0000 [Router       8990] Received SIGTERM, shutting down.
2016-05-11T09:30:21+0000 [Router       8990] Connection to node controller lost.
2016-05-11T09:30:21+0000 [Router       8990] No more controller connection; shutting down.
2016-05-11T09:30:21+0000 [Controller   8984] Process connection gone: A process has ended with a probable error condition: process ended with exit code 1.
2016-05-11T09:30:21+0000 [Controller   8984] Node worker worker1 ended (0 workers left)
2016-05-11T09:30:21+0000 [Controller   8984] Node shutting down ..
2016-05-11T09:30:21+0000 [Controller   8984] Shutting down node...
2016-05-11T09:30:21+0000 [Controller   8984] Main loop terminated.
```

Even while updating crossbar with following command :
pip install -U crossbar

it is returning below error:
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1271, in prepare_files
    req_to_install)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 71, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2833, in parse
    req, = parse_requirements(s)
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2781, in parse_requirements
    yield Requirement(line)
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2790, in __init__
    raise RequirementParseError(str(e))
RequirementParseError: Invalid requirement, parse error at "'; linux '"

Storing debug log for failure in /home/ubuntu/.pip/pip.log
 
Please help me with this as I'm new to crossbar.

**Comment by DZabavchik** [comment]
The error clearly says that port is already used by some other app.
Use netstat to find out which application is listening on port `8080`

`sudo netstat -anp | grep 8080`

As an alternative change the port for Crossbar endpoint

**Comment by meejah** [comment]
The ``pip`` problem is probably "pip is too old because Debian". So run ``pip install -U pip setuptools`` in any new virtualenv on Debian/ubuntu and then the install should work properly.

In future, asking questions like this is best done on the mailing list or IRC please.

**Comment by lucasvieirawerner** [comment]
i'm running crossbar on amazon ec2, followed the tutorial (http://crossbar.io/docs/Setup-on-Amazon-EC2/), but now i'm have this same problem

**Comment by meejah** [comment]
@lucasvieirawerner did you try my solution above? If that works, we should fix the tutorial...

**Comment by RobinByte** [comment]
Hello, exact same issue here. 
I am new to crossbar and did just spin up an AMI image on AWS.

"[Errno 98] Address already in use."
 (http://crossbar.io/docs/Setup-on-Amazon-EC2/) 

Could not find easy docu to change Port in Crossbar (getting confused within docu for different listening port types..)

Help would be nice.

**Comment by RobinByte** [comment]
Hi,

just for completeness, I worked around it by identifying and killing the process followed by imediately starting crossbar.

Identifiy the process PID number 

sudo netstat -lntp   

tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      1463/crossbar-worke

"Suprise" a crossbar worker, let's kill him and start crossbar

sudo kill 1463
crossbar start
