### ISSUE TITLE
upload fail on python 3.5.1 - Can't mix strings and bytes in path components

### ISSUE THREAD

**Issue by WebDevelopNemanja** [crossbario/crossbar#804]
Hello, 
I saw #481, but I'm stil receiving this error, it seems that is not fixed completely...
When I want to upload a file, I'm receiving this error for every chunk.

**Versions:
Crossbar.io : 0.13.2
Autobahn : 0.14.0 (with JSON, MessagePack, CBOR, UBJSON)
Twisted : 16.1.1-EPollReactor
LMDB : 0.89/lmdb-0.9.18
Python : 3.5.1/CPython
OS : Linux-3.19.0-59-generic-x86_64-with-elementary_OS-0.3.2-freya
Machine : x86_64**

2016-05-22T15:41:52+0200 [Router 13911] Unhandled Error
Traceback (most recent call last):
File "/usr/local/lib/python3.5/dist-packages/twisted/web/http.py", line 1439, in dataReceived
finishCallback(data[contentLength:])
File "/usr/local/lib/python3.5/dist-packages/twisted/web/http.py", line 1704, in _finishRequestBody
self.allContentReceived()
File "/usr/local/lib/python3.5/dist-packages/twisted/web/http.py", line 1767, in allContentReceived
req.requestReceived(command, path, version)
File "/usr/local/lib/python3.5/dist-packages/twisted/web/http.py", line 768, in requestReceived
self.process()
--- ---
File "/usr/local/lib/python3.5/dist-packages/twisted/web/server.py", line 183, in process
self.render(resrc)
File "/usr/local/lib/python3.5/dist-packages/twisted/web/server.py", line 234, in render
body = resrc.render(self)
File "/usr/local/lib/python3.5/dist-packages/twisted/web/resource.py", line 250, in render
return m(request)
File "/opt/crossbar-repo/crossbar/twisted/fileupload.py", line 242, in render_POST
fileTempDir = os.path.join(self._tempDirRoot, fileId)
File "/usr/lib/python3.5/posixpath.py", line 89, in join
genericpath._check_arg_types('join', a, *p)
File "/usr/lib/python3.5/genericpath.py", line 145, in _check_arg_types
raise TypeError("Can't mix strings and bytes in path components") from None
builtins.TypeError: Can't mix strings and bytes in path components

**Comment by oberstet** [comment]
Please see: https://github.com/crossbario/crossbar/issues/805
