### ISSUE TITLE
exception in docker image

### ISSUE THREAD

**Issue by KrishnaPG** [crossbario/crossbar#809]
While running the latest docker image, getting the below exception:

```
2016-05-23T14:36:34+0000 [Router         12] Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/twisted/python/log.py", line 101, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/local/lib/python3.5/site-packages/twisted/python/log.py", line 84, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/local/lib/python3.5/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python3.5/site-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/local/lib/python3.5/site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
    why = selectable.doRead()
  File "/usr/local/lib/python3.5/site-packages/twisted/internet/tcp.py", line 209, in doRead
    return self._dataReceived(data)
  File "/usr/local/lib/python3.5/site-packages/twisted/internet/tcp.py", line 215, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/usr/local/lib/python3.5/site-packages/autobahn/twisted/rawsocket.py", line 190, in dataReceived
    self.log.debug("WampRawSocketProtocol: invalid magic byte (octet 1) in opening handshake: was 0x{0}, but expected 0x7f".format(binascii.b2a_hex(self._handshake_bytes[0])))
builtins.TypeError: a bytes-like object is required, not 'int'
2016-05-23T14:36:34+0000 [Router         12] WampRawSocketProtocol: connection lost: reason = '[Failure instance: Traceback: <class 'TypeError'>: a bytes-like object is required, not 'int'
/usr/local/lib/python3.5/site-packages/twisted/python/log.py:84:callWithContext
/usr/local/lib/python3.5/site-packages/twisted/python/context.py:118:callWithContext
/usr/local/lib/python3.5/site-packages/twisted/python/context.py:81:callWithContext
/usr/local/lib/python3.5/site-packages/twisted/internet/posixbase.py:610:_doReadOrWrite
--- <exception caught here> ---
/usr/local/lib/python3.5/site-packages/twisted/internet/posixbase.py:597:_doReadOrWrite
/usr/local/lib/python3.5/site-packages/twisted/internet/tcp.py:209:doRead
/usr/local/lib/python3.5/site-packages/twisted/internet/tcp.py:215:_dataReceived
/usr/local/lib/python3.5/site-packages/autobahn/twisted/rawsocket.py:190:dataReceived
]'
```

**Comment by oberstet** [comment]
cannot reproduce
