### ISSUE TITLE
TypeError with Hello World application

### ISSUE THREAD

**Issue by zrneely** [crossbario/crossbar#840]
I created a simple Crossbar server with `crossbar init`. I modified the configuration by removing the "web" transport (since I won't need it) and changing the port and realm name.

I have a simple application component in Python which joins the realm and prints a debugging message (I'm trying to get a Hello World program to work). When I start the crossbar server with `crossbar start` and then start my Python application, I get the following error from the server and the `onJoin` method of the component is never called.

```
2016-07-24T12:29:39-0700 [Router      20988] Unhandled Error
Traceback (most recent call last):
  File "/home/zrneely/python/project/venv/lib/python3.5/site-packages/twisted/python/log.py", line 101, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/home/zrneely/python/project/venv/lib/python3.5/site-packages/twisted/python/log.py", line 84, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/zrneely/python/project/venv/lib/python3.5/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/zrneely/python/project/venv/lib/python3.5/site-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/home/zrneely/python/project/venv/lib/python3.5/site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
    why = selectable.doRead()
  File "/home/zrneely/python/project/venv/lib/python3.5/site-packages/twisted/internet/tcp.py", line 209, in doRead
    return self._dataReceived(data)
  File "/home/zrneely/python/project/venv/lib/python3.5/site-packages/twisted/internet/tcp.py", line 215, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/home/zrneely/python/project/venv/lib/python3.5/site-packages/crossbar/router/unisocket.py", line 96, in dataReceived
    request_uri_first_component = filter(lambda x: x.strip() != "", request_uri.split('/'))
builtins.TypeError: a bytes-like object is required, not 'str'
```

This is happening in a Python 3.5 venv under Ubuntu 16.04 (Linux 4.4.0-31). Crossbar was installed with `pip install crossbar`. This occurs both when Twisted 16.3.0 is installed, and when 16.2.0 is installed.

**Comment by Yamakaky** [comment]
Same error on Arch. Steps to reproduce:
```
pyvenv fail
cd fail
. bin/activate
pip install 'crossbar[all]'
bin/crossbar init
bin/crossbar start
<go to localhost:8080>
```

**Comment by conradoplg** [comment]
I had the same issue. It seems the problem is related to the configuration: when following the tutorial and running "crossbar init" with no params, the .crossbar/config.json file uses the "universal" transport. If you change it to a "websocket" transport, it works.

I tried fixing the obvious issues in unisocket.py line 96 (changing '/' to b'/', and putting the filter result in a list), but then another error comes up. I didn't investigate it any further.

**Comment by adrienemery** [comment]
this configuration worked for me with:
python `3.5.2`
crossbar `0.15.0`

```json
{
    "version": 2,
    "controller": {},
    "workers": [
        {
            "type": "router",
            "realms": [
                {
                    "name": "realm1",
                    "roles": [
                        {
                            "name": "anonymous",
                            "permissions": [
                                {
                                    "uri": "",
                                    "match": "prefix",
                                    "allow": {
                                        "call": true,
                                        "register": true,
                                        "publish": true,
                                        "subscribe": true
                                    },
                                    "disclose": {
                                        "caller": false,
                                        "publisher": false
                                    },
                                    "cache": true
                                }
                            ]
                        }
                    ]
                }
            ],
            "transports": [
                {
                    "type": "web",
                    "endpoint": {
                       "type": "tcp",
                       "port": 8080
                    },
                    "paths": {
                       "ws": {
                          "type": "websocket"
                       }
                    }
                }
            ]
        }
    ]
}
```

**Comment by hawkowl** [comment]
I believe this isn't an issue in latest Crossbar; there was a fix + release since this, and I've written some tests to verify that this is the case currently and that it won't regress: https://github.com/crossbario/crossbar/pull/859

Please try on the latest version.

**Comment by adrienemery** [comment]
With a fresh install of crossbar `0.15.0` and python `3.5.2` when I run the following I get the error described by @zrneely and I have been using my modified "default" config file above to get it working.

```bash
$ crossbar init
Initializing application template 'default' in directory '/Users/adrienemery/Code/crossbartest'
Using template from '/Users/adrienemery/miniconda3/lib/python3.5/site-packages/crossbar/templates/default'
Creating directory /Users/adrienemery/Code/crossbartest/.crossbar
Creating file /Users/adrienemery/Code/crossbartest/.crossbar/config.json
Application template initialized

To start your node, run 'crossbar start --cbdir /Users/adrienemery/Code/crossbartest/.crossbar'

$ crossbar start
2016-08-21T11:53:51-0700 [Controller  45091] New node key generated!
2016-08-21T11:53:51-0700 [Controller  45091]      __  __  __  __  __  __      __     __
2016-08-21T11:53:51-0700 [Controller  45091]     /  `|__)/  \/__`/__`|__) /\ |__)  |/  \
2016-08-21T11:53:51-0700 [Controller  45091]     \__,|  \\__/.__/.__/|__)/~~\|  \. |\__/
2016-08-21T11:53:51-0700 [Controller  45091]
2016-08-21T11:53:51-0700 [Controller  45091]     Crossbar.io Version: 0.15.0
2016-08-21T11:53:51-0700 [Controller  45091]     Node Public Key: 7aea633c04dd13376d240153caa076aff5ce1158e4fa6d93144fe2b9943fbe9a
2016-08-21T11:53:51-0700 [Controller  45091]
2016-08-21T11:53:51-0700 [Controller  45091] Running from node directory '/Users/adrienemery/Code/crossbartest/.crossbar'
2016-08-21T11:53:51-0700 [Controller  45091] Controller process starting (CPython-KQueueReactor) ..
2016-08-21T11:53:51-0700 [Controller  45091] Node configuration loaded from 'config.json'
2016-08-21T11:53:51-0700 [Controller  45091] Node ID 'mpb.local' set from hostname
2016-08-21T11:53:51-0700 [Controller  45091] Using default node shutdown triggers ['shutdown_on_worker_exit']
2016-08-21T11:53:51-0700 [Controller  45091] Joined realm 'crossbar' on node management router
2016-08-21T11:53:51-0700 [Controller  45091] Starting Router with ID 'worker-001'...
2016-08-21T11:53:51-0700 [Router      45092] Worker process starting (CPython-KQueueReactor) ..
2016-08-21T11:53:52-0700 [Controller  45091] Router with ID 'worker-001' and PID 45092 started
2016-08-21T11:53:52-0700 [Router      45092] Realm 'realm1' started
2016-08-21T11:53:52-0700 [Controller  45091] Router 'worker-001': realm 'realm-001' (named 'realm1') started
2016-08-21T11:53:52-0700 [Controller  45091] Router 'worker-001': role 'role-001' (named 'anonymous') started on realm 'realm-001'
2016-08-21T11:53:52-0700 [Router      45092] UniSocketServerFactory starting on 8080
2016-08-21T11:53:52-0700 [Controller  45091] Router 'worker-001': transport 'transport-001' started
2016-08-21T11:54:12-0700 [Router      45092] An exception was raised from application code while processing a reactor selectable
Traceback (most recent call last):
  File "/Users/adrienemery/miniconda3/lib/python3.5/site-packages/twisted/python/log.py", line 101, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/Users/adrienemery/miniconda3/lib/python3.5/site-packages/twisted/python/log.py", line 84, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/Users/adrienemery/miniconda3/lib/python3.5/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/Users/adrienemery/miniconda3/lib/python3.5/site-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/Users/adrienemery/miniconda3/lib/python3.5/site-packages/twisted/internet/kqreactor.py", line 293, in _doWriteOrRead
    why = selectable.doRead()
  File "/Users/adrienemery/miniconda3/lib/python3.5/site-packages/twisted/internet/tcp.py", line 209, in doRead
    return self._dataReceived(data)
  File "/Users/adrienemery/miniconda3/lib/python3.5/site-packages/twisted/internet/tcp.py", line 215, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/Users/adrienemery/miniconda3/lib/python3.5/site-packages/crossbar/router/unisocket.py", line 96, in dataReceived
    request_uri_first_component = filter(lambda x: x.strip() != "", request_uri.split('/'))
builtins.TypeError: a bytes-like object is required, not 'str'

**Comment by hawkowl** [comment]
@adrienemery ah! Okay, it seems that the version bump was for the development version, not the official release... so, it'll be in the next release, then. Sorry about that!

**Comment by adrienemery** [comment]
@hawkowl no problem thanks for the update and the great work on this project. Really enjoying using crossbar!

**Comment by totetmatt** [comment]
Same error on python 3.5.2 / crossbar 0.15.0 / windows 10 after a `pip install crossbar` and `crossbar init`.
But even using the configuration file from @adrienemery doesn't make it works.
```
> crossbar start
2016-08-30T22:41:24+0200 [Controller   7268]      __  __  __  __  __  __      __     __
2016-08-30T22:41:24+0200 [Controller   7268]     /  `|__)/  \/__`/__`|__) /\ |__)  |/  \
2016-08-30T22:41:24+0200 [Controller   7268]     \__,|  \\__/.__/.__/|__)/~~\|  \. |\__/
2016-08-30T22:41:24+0200 [Controller   7268]
2016-08-30T22:41:24+0200 [Controller   7268]     Crossbar.io Version: 0.15.0
2016-08-30T22:41:24+0200 [Controller   7268] Running from node directory '\.crossbar'
2016-08-30T22:41:24+0200 [Controller   7268] Controller process starting (CPython-IOCPReactor) ..
2016-08-30T22:41:24+0200 [Controller   7268] Node configuration loaded from 'config.json'
2016-08-30T22:41:24+0200 [Controller   7268] Using default node shutdown triggers ['shutdown_on_worker_exit']
2016-08-30T22:41:24+0200 [Controller   7268] Joined realm 'crossbar' on node management router
2016-08-30T22:41:24+0200 [Controller   7268] Starting Router with ID 'worker-001'...
2016-08-30T22:41:24+0200 [Controller   7268] Interal error: connection to forked native worker failed ([Failure instance: Traceback: <class 'TypeError'>: a bytes-like object is required, not 'str'
site-packages\twisted\internet\defer.py:1185:_inlineCallbacks
site-packages\crossbar\controller\node.py:653:_startup
site-packages\crossbar\controller\process.py:320:start_router
site-packages\crossbar\controller\process.py:606:_start_native_worker
--- <exception caught here> ---
site-packages\crossbar\twisted\processutil.py:117:connect
site-packages\twisted\internet\iocpreactor\reactor.py:258:spawnProcess
site-packages\twisted\internet\_dumbwin32proc.py:174:__init__
site-packages\twisted\python\win32.py:103:quoteArguments
site-packages\twisted\python\win32.py:103:<listcomp>
site-packages\twisted\python\win32.py:90:cmdLineQuote
])
2016-08-30T22:41:24+0200 [Controller   7268] Failed to start native worker: a bytes-like object is required, not 'str'
2016-08-30T22:41:24+0200 [Controller   7268] crossbar.error.cannot_start: Failed to start native worker: a bytes-like object is required, not 'str' []
```
Any official patch / config to apply to make it works until release ? And if not, what is the target date for the next release then ?

**Comment by hawkowl** [comment]
@totetmatt Hi, that seems to be another problem, related to Twisted on Python 3 on Windows, which isn't currently supported -- Twisted will have support in the next release (which is maybe mid-late next month), and then CB will gain support for Win+Py3 after that's released.

**Comment by pathakchirag7** [comment]
crossbar gives me following exception when I tried to start it in windows 10 with python 3.5 installed.
**crossbar.error.cannot_start: Failed to start native worker: a bytes-like object is required, not 'str' []**
```
C:\Windows\system32>crossbar start
2016-09-13T11:20:41+0530 [Controller   6336]      __  __  __  __  __  __      __     __
2016-09-13T11:20:41+0530 [Controller   6336]     /  `|__)/  \/__`/__`|__) /\ |__)  |/  \
2016-09-13T11:20:41+0530 [Controller   6336]     \__,|  \\__/.__/.__/|__)/~~\|  \. |\__/
2016-09-13T11:20:41+0530 [Controller   6336]
2016-09-13T11:20:41+0530 [Controller   6336]     Crossbar.io Version: 0.15.0
2016-09-13T11:20:41+0530 [Controller   6336]     Node Public Key: 4d1dfe29b8dd51ccec3d8284426576349e8664337a983d80bcf9c3bf54fdfae8
2016-09-13T11:20:41+0530 [Controller   6336]
2016-09-13T11:20:41+0530 [Controller   6336] Running from node directory 'C:\Windows\system32\.crossbar'
2016-09-13T11:20:41+0530 [Controller   6336] Controller process starting (CPython-IOCPReactor) ..
2016-09-13T11:20:41+0530 [Controller   6336] Node configuration loaded from 'config.json'
2016-09-13T11:20:41+0530 [Controller   6336] Node ID 'DESKTOP-FRH5Q37' set from hostname
2016-09-13T11:20:41+0530 [Controller   6336] Using default node shutdown triggers ['shutdown_on_worker_exit']
2016-09-13T11:20:41+0530 [Controller   6336] Joined realm 'crossbar' on node management router
2016-09-13T11:20:41+0530 [Controller   6336] Starting Router with ID 'worker-001'...
2016-09-13T11:20:41+0530 [Controller   6336] Interal error: connection to forked native worker failed ([Failure instance: Traceback: <class 'TypeError'>: a bytes-like object is required, not 'str'
c:\users\chirag\appdata\local\programs\python\python35-32\lib\site-packages\twisted\internet\defer.py:1185:_inlineCallbacks
c:\users\chirag\appdata\local\programs\python\python35-32\lib\site-packages\crossbar\controller\node.py:653:_startup
c:\users\chirag\appdata\local\programs\python\python35-32\lib\site-packages\crossbar\controller\process.py:320:start_router
c:\users\chirag\appdata\local\programs\python\python35-32\lib\site-packages\crossbar\controller\process.py:606:_start_native_worker
--- <exception caught here> ---
c:\users\chirag\appdata\local\programs\python\python35-32\lib\site-packages\crossbar\twisted\processutil.py:117:connect
c:\users\chirag\appdata\local\programs\python\python35-32\lib\site-packages\twisted\internet\iocpreactor\reactor.py:258:spawnProcess
c:\users\chirag\appdata\local\programs\python\python35-32\lib\site-packages\twisted\internet\_dumbwin32proc.py:174:__init__
c:\users\chirag\appdata\local\programs\python\python35-32\lib\site-packages\twisted\python\win32.py:103:quoteArguments
c:\users\chirag\appdata\local\programs\python\python35-32\lib\site-packages\twisted\python\win32.py:103:<listcomp>
c:\users\chirag\appdata\local\programs\python\python35-32\lib\site-packages\twisted\python\win32.py:90:cmdLineQuote
])
2016-09-13T11:20:41+0530 [Controller   6336] Failed to start native worker: a bytes-like object is required, not 'str'
2016-09-13T11:20:41+0530 [Controller   6336] crossbar.error.cannot_start: Failed to start native worker: a bytes-like object is required, not 'str' []
```
