### ISSUE TITLE
Missing machine id on mac

### ISSUE THREAD

**Issue by markope** [crossbario/crossbar#870]
```
2016-09-06T23:33:55+0200 [Controller  84758] Traceback (most recent call last):
2016-09-06T23:33:55+0200 [Controller  84758]   File "/usr/local/bin/crossbar", line 11, in <module>
2016-09-06T23:33:55+0200 [Controller  84758]     load_entry_point('crossbar', 'console_scripts', 'crossbar')()
2016-09-06T23:33:55+0200 [Controller  84758]   File "/Users/marko/git/crossbar/crossbar/controller/cli.py", line 1023, in run
2016-09-06T23:33:55+0200 [Controller  84758]     options.func(options, reactor=reactor)
2016-09-06T23:33:55+0200 [Controller  84758]   File "/Users/marko/git/crossbar/crossbar/controller/cli.py", line 598, in run_command_start
2016-09-06T23:33:55+0200 [Controller  84758]     pubkey = node.maybe_generate_key(options.cbdir)
2016-09-06T23:33:55+0200 [Controller  84758]   File "/Users/marko/git/crossbar/crossbar/controller/node.py", line 279, in maybe_generate_key
2016-09-06T23:33:55+0200 [Controller  84758]     raise Exception("Corrupt node private key file {} - {} tag not found".format(privkey_path, tag))
2016-09-06T23:33:55+0200 [Controller  84758] Exception: Corrupt node private key file /Users/marko/git/REone/re_crossbar/.crossbar/key.priv - machine-id tag not
```

The issue is this line: 
https://github.com/crossbario/crossbar/blame/master/crossbar/controller/node.py#L191

When the machine id is not present there should be a key "machine-id" with value None.

**Comment by oberstet** [comment]
@markope could pls you post the complete output of the commands

* `which ioreg`
* `ioreg -rd1 -c IOPlatformExpertDevice` 

here? I lack a OSX box ..

Getting a unique machineID on OSX: http://stackoverflow.com/questions/933460/unique-hardware-id-in-mac-os-x

**Comment by markope** [comment]
```console
Markos-MacBook-Pro:RA marko$ which ioreg
/usr/sbin/ioreg
Markos-MacBook-Pro:RA marko$ ioreg -rd1 -c IOPlatformExpertDevice
+-o MacBookPro11,4  <class IOPlatformExpertDevice, id 0x100000112, registered, matched, active, busy 0 (209390 ms), retain 42>
    {
      "compatible" = <"MacBookPro11,4">
      "version" = <"1.0">
      "board-id" = <"Mac-06F11FD93F0323C5">
      "IOInterruptSpecifiers" = (<0900000005000000>)
      "platform-feature" = <0200000000000000>
      "serial-number" = <4738574e00000000000000000043303250503144374738574e000000000000000000000000000000000000>
      "IOInterruptControllers" = ("io-apic-0")
      "IOPlatformUUID" = "4843D00A-D828-5850-B15A-4C06E56EC05F"
      "clock-frequency" = <00e1f505>
      "IOPolledInterface" = "SMCPolledInterface is not serializable"
      "manufacturer" = <"Apple Inc.">
      "IOPlatformSystemSleepPolicy" = <534c505402001200841e120004000000001400000004000006000000000000000f25000000000000841e120004000000001800000008000005000000000000000f25000000000000841$
      "IOPlatformSerialNumber" = "C02PP1D7G8WN"
      "system-type" = <02>
      "product-name" = <"MacBookPro11,4">
      "model" = <"MacBookPro11,4">
      "name" = <"/">
      "IOBusyInterest" = "IOCommand is not serializable"
    }
    ```

**Comment by oberstet** [comment]
So we need to call `ioreg` and parse out one of

* `IOPlatformUUID`
* `IOPlatformSerialNumber`

Which one?

> You could also parse out "IOPlatformSerialNumber" instead of the "IOPlatformUUID" if you want something human readable and that someone can find on the main dialog of "About This Mac" for tech support calls...

So `IOPlatformSerialNumber` seems the way to go.
