### ISSUE TITLE
dynamic ticket authenticater not works 

### ISSUE THREAD

**Issue by alexey2baranov** [crossbario/crossbar#928]
Hello!

I try to write dynamic authentication and get this error. Looks like python can't get psycopg2 module, but module have correctly installed on my OS. 

Can you help me with this. Thanks!

```
2016-11-21T10:46:36+0500 [Router      35293] {"log_time": 1479707196.555607, "level": "error", "namespace": "crossbar.worker.worker.NativeWorkerSession", "text": "NativeWorkerSession.onUserError"}
2016-11-21T10:46:36+0500 [Controller  35286] crossbar.error.class_import_failed: Failed to import class 'authenticator.AuthenticatorSession'
Traceback (most recent call last):
  File "/opt/crossbar/site-packages/autobahn/wamp/protocol.py", line 809, in onMessage
    on_reply = txaio.as_future(endpoint.fn, *invoke_args, **invoke_kwargs)
  File "/opt/crossbar/site-packages/txaio/tx.py", line 407, in as_future
    return maybeDeferred(fun, *args, **kwargs)
  File "/opt/crossbar/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/opt/crossbar/site-packages/crossbar/worker/router.py", line 643, in start_router_component
    create_component = _appsession_loader(config)
--- <exception caught here> ---
  File "/opt/crossbar/site-packages/crossbar/worker/__init__.py", line 58, in _appsession_loader
    module = importlib.import_module(module_name)
  File "/opt/crossbar/lib-python/2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/alexey2baranov/htdocs/kp-sequelizejs/.crossbar/authenticator.py", line 64, in <module>
    import psycopg2
exceptions.ImportError: No module named psycopg2
```

```python
import os
from pprint import pprint

import six

from twisted.internet.defer import inlineCallbacks

from autobahn.twisted.wamp import ApplicationSession
from autobahn.wamp.exception import ApplicationError

import psycopg2
import os
import json

CFG_FILENAME='../cfg/config.json'

class AuthenticatorSession(ApplicationSession):

   @inlineCallbacks
   def onJoin(self, details):

      def authenticate(realm, authid, details):
         ticket = details['ticket']
         print("WAMP-Ticket dynamic authenticator invoked: realm='{}', authid='{}', ticket='{}'".format(realm, authid, ticket))
         pprint(details)

         db_conn = None
         conf_name = os.environ.get('NODE_ENV', 'development')
         if not os.path.exists(CFG_FILENAME):
             raise Exception('File config not found')
         data = open(CFG_FILENAME, 'r').read()
         params = json.loads(data).get(conf_name)
         if params is None:
             raise Exception('Config section %s not found' % conf_name)
         try:
             db_conn = psycopg2.connect(
                 host=params.get('host'),
                 database=params.get('database'),
                 user=params.get('username'),
                 password=params.get('password')
             )
         except:
             raise Exception('Database connection error')

         cursor = db_conn.cursor()
         cursor.execute('SELECT * FROM "Kopnik" WHERE email=\'%s\' and password=\'%s\';' % (authid, ticket))
         rowcount = cursor.rowcount
         db_conn.commit()
         if rowcount == 0:
             raise ApplicationError("com.example.no_such_user", "could not authenticate session - no such principal {}".format(authid))
         return 'kopnik'

      try:
         yield self.register(authenticate, 'com.example.authenticate')
         print("WAMP-Ticket dynamic authenticator registered!")
      except Exception as e:
         print("Failed to register dynamic authenticator: {0}".format(e))

```

**Comment by meejah** [comment]
Looks more like a general python / installation problem. Whatever python environment you're running the authenticator-worker under can't import `psycopg2`.

**Comment by oberstet** [comment]
That, plus the code has a serious, classical security issue: SQL injection. The code is constructing the SQL using naive string concatenation, instead of using proper bind variables. This is asking for trouble ...

Another issue: the code is using psycopg2 directly - a blocking database library. Eg when you run this authenticator as a component embedded in the router, it will block Crossbar.io completely (serialize everything). If you run it as a worker, it'll serialize that (only one auth request can be processed at a time). Checkout this http://crossbar.io/docs/Database-Programming-with-PostgreSQL/ for a starter.

**Comment by alexey2baranov** [comment]
@oberstet you are wright of cource. this is very basic authenticator. It will be refactored later if i could start psycopg2 under Crossbar.io

I can't understand what is wrong with it. In other programs psycopg2 works well

**Comment by oberstet** [comment]
As @meejah said, the problem is that the Python that Crossbar.io is running from cannot find the psycopg2 module. You have to configure your search path: https://github.com/crossbario/crossbarexamples/blob/master/hello/python/.crossbar/config.json#L52

The search path here is configured relative to the directory where the `config.json` lives.
