### ISSUE TITLE
Heroku - Missing Machine ID (assuming Linux)

### ISSUE THREAD

**Issue by ericchapman** [crossbario/crossbar#955]
I tried running on Heroku and got the machine-id error that is described in these issues

https://github.com/crossbario/crossbar/issues/870
https://github.com/crossbario/crossbar/issues/951

```
2017-01-22T00:02:19.735039+00:00 app[web.1]: 2017-01-22T00:02:19+0000 [Controller      4] Traceback (most recent call last):
2017-01-22T00:02:19.735193+00:00 app[web.1]: 2017-01-22T00:02:19+0000 [Controller      4]   File "/app/.heroku/python/bin/crossbar", line 11, in <module>
2017-01-22T00:02:19.735403+00:00 app[web.1]: 2017-01-22T00:02:19+0000 [Controller      4]     sys.exit(run())
2017-01-22T00:02:19.735620+00:00 app[web.1]: 2017-01-22T00:02:19+0000 [Controller      4]   File "/app/.heroku/python/lib/python2.7/site-packages/crossbar/controller/cli.py", line 1023, in run
2017-01-22T00:02:19.735977+00:00 app[web.1]: 2017-01-22T00:02:19+0000 [Controller      4]     options.func(options, reactor=reactor)
2017-01-22T00:02:19.736131+00:00 app[web.1]: 2017-01-22T00:02:19+0000 [Controller      4]   File "/app/.heroku/python/lib/python2.7/site-packages/crossbar/controller/cli.py", line 598, in run_command_start
2017-01-22T00:02:19.736574+00:00 app[web.1]: 2017-01-22T00:02:19+0000 [Controller      4]   File "/app/.heroku/python/lib/python2.7/site-packages/crossbar/controller/node.py", line 280, in maybe_generate_key
2017-01-22T00:02:19.736401+00:00 app[web.1]: 2017-01-22T00:02:19+0000 [Controller      4]     pubkey = node.maybe_generate_key(options.cbdir)
2017-01-22T00:02:19.736803+00:00 app[web.1]: 2017-01-22T00:02:19+0000 [Controller      4]     raise Exception("Corrupt node private key file {} - {} tag not found".format(privkey_path, tag))
2017-01-22T00:02:19.737024+00:00 app[web.1]: 2017-01-22T00:02:19+0000 [Controller      4] Exception: Corrupt node private key file /app/.crossbar/key.priv - machine-id tag not found
```

I have the following in my requirements.txt

```
rgh==0.26.2
attrs==16.3.0
autobahn==0.17.1
bitstring==3.1.5
cbor==1.0.0
cffi==1.9.1
click==6.7
constantly==15.1.0
crossbar==16.10.1
cryptography==1.7.1
enum34==1.1.6
idna==2.2
incremental==16.10.1
ipaddress==1.0.18
Jinja2==2.9.4
lmdb==0.92
MarkupSafe==0.23
mistune==0.7.3
netaddr==0.7.19
pathtools==0.1.2
psutil==5.0.1
py-ubjson==0.8.5
pyasn1==0.1.9
pyasn1-modules==0.0.8
pycparser==2.17
Pygments==2.1.3
PyJWT==1.4.2
PyNaCl==1.0.1
pyOpenSSL==16.2.0
PyQRCode==1.2.1
PyTrie==0.3
PyYAML==3.12
requests==2.12.5
sdnotify==0.3.1
service-identity==16.0.0
setproctitle==1.1.10
shutilwhich==1.1.0
six==1.10.0
sortedcontainers==1.5.7
treq==16.12.0
Twisted==16.6.0
txaio==2.6.0
u-msgpack-python==2.3.0
watchdog==0.8.3
zope.interface==4.3.3
```

Not sure how to fix this one

**Comment by ericchapman** [comment]
I just read the code and realized that this corruption happens when the template was generated.  Note that I am on a Mac as well so this is probably the same as the other issue.  Sorry about that.

What is interesting is I can run fine locally.  The failure only occurs when I push to Heroku...

**Comment by ericchapman** [comment]
I see.  I just needed to pull the "IOPlatformSerialNumber" and manually add it to the key files as the "machine-id".  This is a duplicate.  Closing it.

**Comment by oberstet** [comment]
@ericchapman Hi Eric, sorry for the hassles .. we should have taken more care with this platform serial thingy. Well, learning.

**Comment by ericchapman** [comment]
@oberstet No worries
