### ISSUE TITLE
autobahn.wamp.exception.ProtocolError: invalid type <class 'NoneType'> for 'signature' in AUTHENTICATE

### ISSUE THREAD

**Issue by FirefighterBlu3** [crossbario/crossbar#987]
got any ideas? it just started tonight, i'm using the same code i've been using for a week now. this error is happening about once every three seconds

```
 Crossbar.io        : 0.15.0
   Autobahn         : 0.17.2 (with JSON, MessagePack, CBOR, UBJSON)
   Twisted          : 16.6.0-EPollReactor
   LMDB             : 0.92/lmdb-0.9.18
   Python           : 3.6.0/CPython
 OS                 : Linux-4.9.11-1-ARCH-x86_64-with-arch
 Machine            : x86_64
```
```
2017-03-14T06:37:37-0400 [Router      15277 crossbar.router.protocol.WampWebSocketServerProtocol] connection accepted from peer tcp4:127.0.0.1:57230
2017-03-14T06:37:37-0400 [Router      15277 crossbar.router.protocol.WampWebSocketServerProtocol] Connection made to tcp4:127.0.0.1:57230
2017-03-14T06:37:37-0400 [Router      15277 crossbar.router.protocol.WampWebSocketServerProtocol] received HTTP request:

b'GET /ws HTTP/1.1\r\nHost: misty.blue-labs.org:8080\r\nX-Forwarded-For: 162.243.76.175\r\nUpgrade: websocket\r\nConnection: upgrade\r\nPragma: no-cache\r\nCache-Control: no-cache\r\nOrigin: https://misty.blue-labs.org\r\nSec-Websocket-Version: 13\r\nUser-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36\r\nDNT: 1\r\nAccept-Encoding: gzip, deflate, sdch, br\r\nAccept-Language: en-US,en;q=0.8\r\nCookie: gsScrollPos=; cbtid=URWC9UxgMnqh2Ma1WUSeCxYi\r\nSec-Websocket-Key: fPlvrgx7lZpUlVdMCe9msw==\r\nSec-Websocket-Extensions: permessage-deflate; client_max_window_bits\r\nSec-Websocket-Protocol: wamp.2.json, wamp.2.msgpack\r\n\r\n'


2017-03-14T06:37:37-0400 [Router      15277 crossbar.router.protocol.WampWebSocketServerProtocol] received HTTP status line in opening handshake : GET /ws HTTP/1.1
2017-03-14T06:37:37-0400 [Router      15277 crossbar.router.protocol.WampWebSocketServerProtocol] received HTTP headers in opening handshake : {'host': 'misty.blue-labs.org:8080', 'x-forwarded-for': '162.243.76.175', 'upgrade': 'websocket', 'connection': 'upgrade', 'pragma': 'no-cache', 'cache-control': 'no-cache', 'origin': 'https://misty.blue-labs.org', 'sec-websocket-version': '13', 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36', 'dnt': '1', 'accept-encoding': 'gzip, deflate, sdch, br', 'accept-language': 'en-US,en;q=0.8', 'cookie': 'gsScrollPos=; cbtid=URWC9UxgMnqh2Ma1WUSeCxYi', 'sec-websocket-key': 'fPlvrgx7lZpUlVdMCe9msw==', 'sec-websocket-extensions': 'permessage-deflate; client_max_window_bits', 'sec-websocket-protocol': 'wamp.2.json, wamp.2.msgpack'}
2017-03-14T06:37:37-0400 [Router      15277 crossbar.router.protocol.WampWebSocketServerProtocol] Hybi protocol detected
2017-03-14T06:37:37-0400 [Router      15277 crossbar.router.cookiestore.CookieStore] Parsing cookie from {'host': 'misty.blue-labs.org:8080', 'x-forwarded-for': '162.243.76.175', 'upgrade': 'websocket', 'connection': 'upgrade', 'pragma': 'no-cache', 'cache-control': 'no-cache', 'origin': 'https://misty.blue-labs.org', 'sec-websocket-version': '13', 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36', 'dnt': '1', 'accept-encoding': 'gzip, deflate, sdch, br', 'accept-language': 'en-US,en;q=0.8', 'cookie': 'gsScrollPos=; cbtid=URWC9UxgMnqh2Ma1WUSeCxYi', 'sec-websocket-key': 'fPlvrgx7lZpUlVdMCe9msw==', 'sec-websocket-extensions': 'permessage-deflate; client_max_window_bits', 'sec-websocket-protocol': 'wamp.2.json, wamp.2.msgpack'}
2017-03-14T06:37:37-0400 [Router      15277 crossbar.router.protocol.WampWebSocketServerProtocol] Cookie already set
2017-03-14T06:37:37-0400 [Router      15277 crossbar.router.cookiestore.CookieStore] Adding proto <crossbar.router.protocol.WampWebSocketServerProtocol object at 0x7facb7e76240> to cookie URWC9UxgMnqh2Ma1WUSeCxYi
2017-03-14T06:37:37-0400 [Router      15277 crossbar.router.protocol.WampWebSocketServerProtocol] Cookie tracking enabled on WebSocket connection <crossbar.router.protocol.WampWebSocketServerProtocol object at 0x7facb7e76240>
2017-03-14T06:37:37-0400 [Router      15277 crossbar.router.cookiestore.CookieStore] Cookie auth info for URWC9UxgMnqh2Ma1WUSeCxYi retrieved: (None, None, None, None)
2017-03-14T06:37:37-0400 [Router      15277 crossbar.router.protocol.WampWebSocketServerProtocol] Cookie-based authentication enabled, but cookie isn't authenticated yet
2017-03-14T06:37:37-0400 [Router      15277 crossbar.router.protocol.WampWebSocketServerProtocol] parsed WebSocket extension 'permessage-deflate' with params '{'client_max_window_bits': [True]}'
2017-03-14T06:37:37-0400 [Router      15277 crossbar.router.protocol.WampWebSocketServerProtocol] client request permessage-compress extension, but we did not accept any offer [[PerMessageDeflateOffer(acceptNoContextTakeover = True, acceptMaxWindowBits = True, requestNoContextTakeover = False, requestMaxWindowBits = 0)]]
2017-03-14T06:37:37-0400 [Router      15277 crossbar.router.protocol.WampWebSocketServerProtocol] sending HTTP response:

HTTP/1.1 101 Switching Protocols
Server: Crossbar
Upgrade: WebSocket
Connection: Upgrade
Sec-WebSocket-Protocol: wamp.2.json
Sec-WebSocket-Accept: vDUvtoHCGwXeVjvvMEff4BZUhyE=


2017-03-14T06:37:37-0400 [Router      15277 crossbar.router.session.RouterSession] Client session connected - transport: {'type': 'websocket', 'protocol': 'wamp.2.json', 'peer': 'tcp4:127.0.0.1:57230', 'http_headers_received': {'host': 'misty.blue-labs.org:8080', 'x-forwarded-for': '162.243.76.175', 'upgrade': 'websocket', 'connection': 'upgrade', 'pragma': 'no-cache', 'cache-control': 'no-cache', 'origin': 'https://misty.blue-labs.org', 'sec-websocket-version': '13', 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36', 'dnt': '1', 'accept-encoding': 'gzip, deflate, sdch, br', 'accept-language': 'en-US,en;q=0.8', 'cookie': 'gsScrollPos=; cbtid=URWC9UxgMnqh2Ma1WUSeCxYi', 'sec-websocket-key': 'fPlvrgx7lZpUlVdMCe9msw==', 'sec-websocket-extensions': 'permessage-deflate; client_max_window_bits', 'sec-websocket-protocol': 'wamp.2.json, wamp.2.msgpack'}, 'http_headers_sent': {}, 'cbtid': 'URWC9UxgMnqh2Ma1WUSeCxYi', 'channel_id': '1351bb67ee4e094b26fa5a6319b138cbb7beb0465c4c8d746db37cb44a60ab53'}
2017-03-14T06:37:37-0400 [Router      15277 crossbar.router.protocol.WampWebSocketServerProtocol] Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/autobahn/wamp/websocket.py", line 88, in onMessage
    for msg in self._serializer.unserialize(payload, isBinary):
  File "/usr/lib/python3.6/site-packages/autobahn/wamp/serializer.py", line 131, in unserialize
    msg = Klass.parse(raw_msg)
  File "/usr/lib/python3.6/site-packages/autobahn/wamp/message.py", line 887, in parse
    raise ProtocolError("invalid type {0} for 'signature' in AUTHENTICATE".format(type(signature)))
autobahn.wamp.exception.ProtocolError: invalid type <class 'NoneType'> for 'signature' in AUTHENTICATE

2017-03-14T06:37:37-0400 [Router      15277 crossbar.router.protocol.WampWebSocketServerProtocol] Failing WAMP-over-WebSocket transport: code=1002, reason="WAMP Protocol Error (invalid type <class 'NoneType'> for 'signature' in AUTHENTICATE)"
2017-03-14T06:37:37-0400 [Router      15277 crossbar.router.protocol.WampWebSocketServerProtocol] failing connection: 1002: WAMP Protocol Error (invalid type <class 'NoneType'> for 'signature' in AUTHENTICATE)
2017-03-14T06:37:37-0400 [Router      15277 crossbar.router.protocol.WampWebSocketServerProtocol] dropping connection to peer tcp4:127.0.0.1:57230 with abort=True
2017-03-14T06:37:37-0400 [Router      15277 crossbar.router.protocol.WampWebSocketServerProtocol] Connection to/from tcp4:127.0.0.1:57230 was lost in a non-clean fashion: Connection to the other side was lost in a non-clean fashion: Connection lost.
2017-03-14T06:37:37-0400 [Router      15277 crossbar.router.protocol.WampWebSocketServerProtocol] _connectionLost: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionLost'>: Connection to the other side was lost in a non-clean fashion: Connection lost.
]
2017-03-14T06:37:37-0400 [Router      15277 crossbar.router.protocol.WampWebSocketServerProtocol] Auto ping/pong: canceling autoPingPendingCall upon lost connection
2017-03-14T06:37:37-0400 [Router      15277 crossbar.router.protocol.WampWebSocketServerProtocol] WAMP-over-WebSocket transport lost: wasClean=True, code=1002, reason="WAMP Protocol Error (invalid type <class 'NoneType'> for 'signature' in AUTHENTICATE)"
2017-03-14T06:37:37-0400 [Router      15277 crossbar.router.cookiestore.CookieStore] Removing proto <crossbar.router.protocol.WampWebSocketServerProtocol object at 0x7facb7e76240> from cookie URWC9UxgMnqh2Ma1WUSeCxYi
```

**Comment by oberstet** [comment]
You are running a strange mix of very old Crossbar.io (0.15.0) on a new Autobahn (0.17.2). Could you please upgrade to the latest releases and check if the issue persists?

**Comment by FirefighterBlu3** [comment]
odd, i thought i'd updated this when i updated ab. ok, i pulled and updated but cb is now giving me an import error. i'll file another ticket and reference this one:

```
2017-03-14T22:25:18-0400 [Controller   5855] Stale Crossbar.io PID file (pointing to non-existing process with PID 32569) /etc/nginx/sites/misty.blue-labs.org/app/.crossbar/node.pid removed
2017-03-14T22:25:18-0400 [Controller   5855] New node key pair generated!
2017-03-14T22:25:18-0400 [Controller   5855] File permissions on node private key fixed!
2017-03-14T22:25:18-0400 [Controller   5855]      __  __  __  __  __  __      __     __
2017-03-14T22:25:18-0400 [Controller   5855]     /  `|__)/  \/__`/__`|__) /\ |__)  |/  \
2017-03-14T22:25:18-0400 [Controller   5855]     \__,|  \\__/.__/.__/|__)/~~\|  \. |\__/
2017-03-14T22:25:18-0400 [Controller   5855]                                         
2017-03-14T22:25:18-0400 [Controller   5855] Version:     Crossbar.io COMMUNITY 17.2.1
2017-03-14T22:25:18-0400 [Controller   5855] Public Key:  9b3128f70a8ab2e0682e35881915843b636da6ff1ba5596aaa7f925a25d133bd
2017-03-14T22:25:18-0400 [Controller   5855] 
2017-03-14T22:25:18-0400 [Controller   5855] Node created with personality "community" [crossbar.controller.node.Node]
2017-03-14T22:25:18-0400 [Controller   5855] Running from node directory "/etc/nginx/sites/misty.blue-labs.org/app/.crossbar"
2017-03-14T22:25:18-0400 [Controller   5855] Node configuration loaded from "/etc/nginx/sites/misty.blue-labs.org/app/.crossbar/config.json"
2017-03-14T22:25:18-0400 [Controller   5855] Controller process starting (CPython-EPollReactor) ..
2017-03-14T22:25:18-0400 [Controller   5855] No extra node router roles
2017-03-14T22:25:18-0400 [Controller   5855] Router service session attached [crossbar.router.service.RouterServiceSession]
2017-03-14T22:25:18-0400 [Controller   5855] Joined realm 'crossbar' on node management router
2017-03-14T22:25:18-0400 [Controller   5855] Registering management API procedure "crossbar.get_info"
2017-03-14T22:25:18-0400 [Controller   5855] Registering management API procedure "crossbar.shutdown"
2017-03-14T22:25:18-0400 [Controller   5855] Registering management API procedure "crossbar.get_workers"
2017-03-14T22:25:18-0400 [Controller   5855] Registering management API procedure "crossbar.get_worker"
2017-03-14T22:25:18-0400 [Controller   5855] Registering management API procedure "crossbar.get_worker_log"
2017-03-14T22:25:18-0400 [Controller   5855] Registering management API procedure "crossbar.start_router"
2017-03-14T22:25:18-0400 [Controller   5855] Registering management API procedure "crossbar.stop_router"
2017-03-14T22:25:18-0400 [Controller   5855] Registering management API procedure "crossbar.start_container"
2017-03-14T22:25:18-0400 [Controller   5855] Registering management API procedure "crossbar.stop_container"
2017-03-14T22:25:18-0400 [Controller   5855] Registering management API procedure "crossbar.start_guest"
2017-03-14T22:25:18-0400 [Controller   5855] Registering management API procedure "crossbar.stop_guest"
2017-03-14T22:25:18-0400 [Controller   5855] Registering management API procedure "crossbar.start_websocket_testee"
2017-03-14T22:25:18-0400 [Controller   5855] Registering management API procedure "crossbar.stop_websocket_testee"
2017-03-14T22:25:18-0400 [Controller   5855] Node controller attached [crossbar.controller.process.NodeControllerSession]
2017-03-14T22:25:18-0400 [Controller   5855] Using default node shutdown triggers ['shutdown_on_worker_exit']
2017-03-14T22:25:18-0400 [Controller   5855] Configuring node from local configuration ...
2017-03-14T22:25:18-0400 [Controller   5855] Starting 1 workers ...
2017-03-14T22:25:18-0400 [Controller   5855] Starting Router with ID 'worker-001'...
2017-03-14T22:25:18-0400 [Router       5861] Traceback (most recent call last):
2017-03-14T22:25:18-0400 [Router       5861] File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
2017-03-14T22:25:18-0400 [Router       5861] mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
2017-03-14T22:25:18-0400 [Router       5861] File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
2017-03-14T22:25:18-0400 [Router       5861] __import__(pkg_name)
2017-03-14T22:25:18-0400 [Router       5861] File "/usr/lib/python3.6/site-packages/crossbar-17.2.1-py3.6.egg/crossbar/__init__.py", line 34, in <module>
2017-03-14T22:25:18-0400 [Router       5861] txaio.use_twisted()
2017-03-14T22:25:18-0400 [Router       5861] File "/usr/lib/python3.6/site-packages/txaio/__init__.py", line 109, in use_twisted
2017-03-14T22:25:18-0400 [Router       5861] from txaio import tx
2017-03-14T22:25:18-0400 [Router       5861] File "/usr/lib/python3.6/site-packages/txaio/tx.py", line 32, in <module>
2017-03-14T22:25:18-0400 [Router       5861] import inspect
2017-03-14T22:25:18-0400 [Router       5861] File "/usr/lib/python3.6/inspect.py", line 40, in <module>
2017-03-14T22:25:18-0400 [Router       5861] import linecache
2017-03-14T22:25:18-0400 [Router       5861] File "/usr/lib/python3.6/linecache.py", line 11, in <module>
2017-03-14T22:25:18-0400 [Router       5861] import tokenize
2017-03-14T22:25:18-0400 [Router       5861] File "/usr/lib/python3.6/tokenize.py", line 33, in <module>
2017-03-14T22:25:18-0400 [Router       5861] import re
2017-03-14T22:25:18-0400 [Router       5861] File "/usr/lib/python3.6/re.py", line 142, in <module>
2017-03-14T22:25:18-0400 [Router       5861] class RegexFlag(enum.IntFlag):
2017-03-14T22:25:18-0400 [Router       5861] AttributeError: module 'enum' has no attribute 'IntFlag'
2017-03-14T22:25:18-0400 [Controller   5855] Native worker connection closed uncleanly: A process has ended with a probable error condition: process ended with exit code 1.
2017-03-14T22:25:18-0400 [Controller   5855] Failed to start native worker: A process has ended with a probable error condition: process ended with exit code 1.
2017-03-14T22:25:18-0400 [Controller   5855] crossbar.error.cannot_start: Failed to start native worker: A process has ended with a probable error condition: process ended with exit code 1. ['import inspect', 'File "/usr/lib/python3.6/inspect.py", line 40, in <module>', 'import linecache', 'File "/usr/lib/python3.6/linecache.py", line 11, in <module>', 'import tokenize', 'File "/usr/lib/python3.6/tokenize.py", line 33, in <module>', 'import re', 'File "/usr/lib/python3.6/re.py", line 142, in <module>', 'class RegexFlag(enum.IntFlag):', "AttributeError: module 'enum' has no attribute 'IntFlag'"]
```

**Comment by FirefighterBlu3** [comment]
resolved by updating to 17.2.1

**Comment by FirefighterBlu3** [comment]
ok, frustration time again.

here's the thing. your git setup.py insists on installing its own copy of things which really screws up system installed modules. why? some of your 3rd party deps are _not_ needed in python 3.x and are missing functionality that exists in the base python 3.x. the 3rd party dep therefore _breaks_ system things which other software relies on.

if you want to micromanage all installed packages, then you should also force the installation and configuration of virtualenv.

otherwise, change installation to offer 3 choices:
- simply print a list of dependencies with minimum version requirements
- detect minimum dependency version exists or not, collect and present what needs fixed
- do all the work to set up a venv with deps

your current install creates a considerable amount of work in undoing 3rd party installations of packages that already exist in system managed packages, some of which are incomplete or broken implementations of core modules.

why do i insist on letting my distribution tools do package management? because while crossbar may be security conscious, you're slower to releases than i am at updating system software. moreso, the majority of 3rd party package vendors are terrible at updating internal dependencies or keeping up to date with things they supposedly replace from core. when it comes to juggling venv deps and trying to get vendors to update vs. them using system modules which _i_ keep updated, i'm going to revert yours|theirs and manage it myself with feature-strong system tools every time. easy_install doesn't have a full set of management features. after it shotguns something into the system, it's messy.

one of those significantly broken packages is the `enum34` module. it is _not_ needed in current versions of python. moreover, it _breaks_ the core enum module which has additional functionality in it that other software requires. enum34 is a backport for versions of python _earlier_ than python 3.4. again, the `enum34` 3rd party module is an incomplete implementation of the core python `enum` module and `enum34` breaks things.

**Comment by oberstet** [comment]
pls see https://groups.google.com/forum/#!topic/crossbario/hT09ueoZEfE

**Comment by oberstet** [comment]
Looking at our docs, these should indeed go into this in more detail, and explain the reasoning, and point out that Crossbar.io is best installed into a dedicated virtualenv.

> Rgd distro packaging: there is zero chance that you will convince me on that one ..

**Comment by oberstet** [comment]
https://github.com/crossbario/crossbar/issues/1027

**Comment by belloyang** [comment]
Hi @oberstet 
I also run into this same issue: my crossbar with version 17.5.1 complains :ProtocolError: invalid type <type 'NoneType'> for 'signature' in AUTHENTICATE
I'm trying to use AutobhanJS 17.5.2 to connect with the crossbar through WAMP-ticket method.


017-12-06T16:23:48-0400 [Controller  32308]      __  __  __  __  __  __      __     __
2017-12-06T16:23:48-0400 [Controller  32308]     /  `|__)/  \/__`/__`|__) /\ |__)  |/  \
2017-12-06T16:23:48-0400 [Controller  32308]     \__,|  \\__/.__/.__/|__)/~~\|  \. |\__/
2017-12-06T16:23:48-0400 [Controller  32308]                                         
2017-12-06T16:23:48-0400 [Controller  32308] Version:     Crossbar.io COMMUNITY 17.5.1
2017-12-06T16:23:48-0400 [Controller  32308] Public Key:  5d07e541a878957558215058b7d03f7ca4a39d51ffb542bcbea1eabd1a8e2f45
2017-12-06T16:23:48-0400 [Controller  32308] 
2017-12-06T16:23:48-0400 [Controller  32308] Node starting with personality "community" [crossbar.controller.node.Node]
2017-12-06T16:23:48-0400 [Controller  32308] Running from node directory "/home/bing/Workplace/BESystem/crossbar/.crossbar"
2017-12-06T16:23:48-0400 [Controller  32308] Environment variable $MYTICKET not set - needed in configuration 'auth.ticket.principals["client2"].ticket'
2017-12-06T16:23:48-0400 [Controller  32308] Node configuration loaded from "/home/bing/Workplace/BESystem/crossbar/.crossbar/config.json"
2017-12-06T16:23:48-0400 [Controller  32308] Controller process starting [CPython-EPollReactor] ..
2017-12-06T16:23:48-0400 [Controller  32308] No extra node router roles
2017-12-06T16:23:48-0400 [Controller  32308] Using default node shutdown triggers [u'shutdown_on_worker_exit']
2017-12-06T16:23:48-0400 [Controller  32308] Configuring node from local configuration ...
2017-12-06T16:23:48-0400 [Controller  32308] Starting 1 workers ...
2017-12-06T16:23:48-0400 [Controller  32308] Router worker "worker-001" starting ..
2017-12-06T16:23:49-0400 [Router      32315] Router worker "worker-001" process 32315 starting on CPython-EPollReactor ..
2017-12-06T16:23:49-0400 [Router      32315] Router worker "worker-001" session 6455596849656159 initializing ..
2017-12-06T16:23:49-0400 [Router      32315] Router worker "worker-001" session ready
2017-12-06T16:23:49-0400 [Controller  32308] Router worker "worker-001" process 32315 started
2017-12-06T16:23:49-0400 [Router      32315] Realm 'emc.daemon' started
2017-12-06T16:23:49-0400 [Controller  32308] Router 'worker-001': realm 'realm-001' (named 'emc.daemon') started
2017-12-06T16:23:49-0400 [Router      32315] role role-001 on realm realm-001 started
2017-12-06T16:23:49-0400 [Controller  32308] Router 'worker-001': role 'role-001' (named 'frontend') started on realm 'realm-001'
2017-12-06T16:23:49-0400 [Router      32315] role role-002 on realm realm-001 started
2017-12-06T16:23:49-0400 [Controller  32308] Router 'worker-001': role 'role-002' (named 'anonymous') started on realm 'realm-001'
2017-12-06T16:23:49-0400 [Router      32315] Realm 'emc.develop' started
2017-12-06T16:23:49-0400 [Controller  32308] Router 'worker-001': realm 'realm-002' (named 'emc.develop') started
2017-12-06T16:23:49-0400 [Router      32315] role role-003 on realm realm-002 started
2017-12-06T16:23:49-0400 [Controller  32308] Router 'worker-001': role 'role-003' (named 'anonymous') started on realm 'realm-002'
2017-12-06T16:23:49-0400 [Router      32315] Realm 'emc.test' started
2017-12-06T16:23:49-0400 [Controller  32308] Router 'worker-001': realm 'realm-003' (named 'emc.test') started
2017-12-06T16:23:49-0400 [Router      32315] role role-004 on realm realm-003 started
2017-12-06T16:23:49-0400 [Controller  32308] Router 'worker-001': role 'role-004' (named 'anonymous') started on realm 'realm-003'
2017-12-06T16:23:49-0400 [Router      32315] WampRawSocketServerFactory starting on 12345
2017-12-06T16:23:49-0400 [Controller  32308] Router 'worker-001': transport 'transport-001' started
2017-12-06T16:23:49-0400 [Router      32315] Environment variable $MYTICKET not set - needed in configuration 'auth.ticket.principals["client2"].ticket'
2017-12-06T16:23:49-0400 [Router      32315] Site starting on 9000
2017-12-06T16:23:49-0400 [Controller  32308] Router 'worker-001': transport 'transport-002' started
2017-12-06T16:23:49-0400 [Controller  32308] Local node configuration applied successfully!
2017-12-06T16:23:53-0400 [Router      32315] >>>>> session 6988178625023541 JOINED "emc.daemon" >>>>>

2017-12-06T16:24:16-0400 [Router      32315] Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/autobahn/wamp/websocket.py", line 88, in onMessage
    for msg in self._serializer.unserialize(payload, isBinary):
  File "/usr/local/lib/python2.7/dist-packages/autobahn/wamp/serializer.py", line 131, in unserialize
    msg = Klass.parse(raw_msg)
  File "/usr/local/lib/python2.7/dist-packages/autobahn/wamp/message.py", line 1054, in parse
    raise ProtocolError("invalid type {0} for 'signature' in AUTHENTICATE".format(type(signature)))
ProtocolError: invalid type <type 'NoneType'> for 'signature' in AUTHENTICATE


Please help, Thanks!
